### ISSUE TITLE
Lag in arena post-8.1

### ISSUE THREAD

**Issue by Jalopyy** [ascott18/TellMeWhen#15]
v8.5.9

https://i.imgur.com/A1gFi9r.jpg

https://i.imgur.com/UpS6LuC.jpg

I (and many other people) since 8.1 have received HUGE frame drops in arena games every since the patch hit. I have no clue what causes it, and no clue if it is even related to TMW, but I'm just trying to bug check whatever I can. Addon from above screenshots is 'Addon Cpu Usage'.

What happens usually is after a handful of arena games, frames start to get choppy. Whereas I usually get a normal 80-120+, it caps out around 20 or 30. I have to relaunch the entire game to fix it. No LUA errors for TMW get thrown. From what the chart shows, it seems like (especially with ElvUI, and yes I know that's not your area) every match TMW/ElvUI accrue more and more data (maybe it's caching something purposelessly?) until it slows the game down with monitored bullshit.

Note: the LARGE spikes seem to be related to loading screens after a game.

**Comment by Jalopyy** [comment]
I have a ton of auras that track information regarding arena1-5 (cached information I guess, since I made ability trackers for arena1, arena2, and arena3. I'm not sure how TMW dumps or stores this info, so possible it could be related?

**Comment by ascott18** [comment]
I'm actually amazed that your TMW CPU usage is that low considering the number of icons you have.

TMW appears to be staying well under 5% of your overall CPU usage. With these numbers, there's no way its causing your FPS to drop that badly.

**Comment by Jalopyy** [comment]
Alright. Like I said - this is purely an issue arisen since 8.1, and I know it happens to people who don't even use TMW. I was just reporting it on the VERY slim chance it was some kind of general addon bug that arose with stuff since the patch, that maybe effects TMW too.

**Comment by ascott18** [comment]
I added a new CPU profiling feature to TMW that gives per-icon stats. /tmw cpu to open it.

I'd be curious to see what your stats look like after an arena match. Make sure to press the reset button when the match starts. Then, check "Freeze" at the end so you can select and copy the text. Or just take a screenshot.

**Comment by Jalopyy** [comment]
Sure, I'll do this later.

**Comment by Jalopyy** [comment]
https://pastebin.com/DwFpALfm
https://pastebin.com/juf3vXPU
https://pastebin.com/rvAEnP43
https://pastebin.com/RZXG4GBt

When I clicked freeze to copy the text, the lag actually seemed to get noticeably better. Not sure what that means.

**Comment by ascott18** [comment]
You saw an improvement when you froze it because continually updating all that text is kind of expensive.

Anyway, I don't see anything significant in those numbers - in fact, they're lower than I expected.
