### ISSUE TITLE
[CF 1602] Unit Alive = True triggers if Arena1-3 leaves instance 

### ISSUE THREAD

**Issue by tmw-issue-import** [ascott18/TellMeWhen#1622]
<p>Title.</p>
<p>&nbsp;</p>
<p>Haven't actually confirmed this 100%, but my aura which should only evaluate as true if A1-3 are all alive is sometimes triggering when the healer is dead and after their arena frame changes - pretty sure this is because they release spirit?</p> 
<br>

> Posted by CurseForge user <a href="https://wow.curseforge.com/members/Jalopyy">Jalopyy</a> | Imported from CurseForge issue <a href="https://wow.curseforge.com/projects/tellmewhen/issues/1602">#1602</a> | <a href="https://github.com/tmw-issue-import/dump/blob/master/html/1602.html">Raw</a>

**Comment by ascott18** [comment]
cc @Jalopyy

**Comment by Jalopyy** [comment]
My only guess on this one as that if a unit which existed (arenaX in this cast) suddenly stops existing, it somehow makes unit=alive succeed? I dunno.

**Comment by ascott18** [comment]
I forgot that the "is alive" api that Blizzard provides is actually "is dead", and TMW just negates the result. This means that for some unit that doesn't exist, `UnitIsDeadOrGhost` returns false, which TMW then flips to `true`, which then makes TMW consider the unit to be alive.

I'll add a check to the condition that the unit exists.
