### ISSUE TITLE
[CF 1613] Add a way to unit cooldown/combat event to show a 2ndary timer amount if a spell is casted while the timer is still running 

### ISSUE THREAD

**Issue by tmw-issue-import** [ascott18/TellMeWhen#1633]
<p>I think I might have already suggested this and you said no, but I don't remember.</p>
<p>&nbsp;</p>
<p>Basically a 2nd value you could put if a spell is cast while the 1st timer is still running, to more easily track the duration of things with variable cooldowns in PVP.&nbsp;</p>
<p>&nbsp;</p>
<p>IE&nbsp;</p>
<p>&nbsp;</p>
<p>Combat event watching Hammer of Justice cast successful, runs for 60 seconds, but if a 2nd hammer is cast while the 60 second timer is running, the timer value changes to 30 seconds for the remainder of the time you are in the instance (however TMW decides to reset stuff like this, at least).</p> 
<br>

> Posted by CurseForge user <a href="https://wow.curseforge.com/members/Jalopyy">Jalopyy</a> | Imported from CurseForge issue <a href="https://wow.curseforge.com/projects/tellmewhen/issues/1613">#1613</a> | <a href="https://github.com/tmw-issue-import/dump/blob/master/html/1613.html">Raw</a>

**Comment by ascott18** [comment]
cc @Jalopyy @arieh

**Comment by Jalopyy** [comment]
For reference, I 'fixed' this issue by making multiple icons for every instance of an ability of a specific cooldown (if there are multiple based on talents) with spell cast count conditionals. It's not pretty and requires a BUNCH of extra auras, but it works until something like this is cleanly implemented.

**Comment by ascott18** [comment]
Not likely to ever implement this. Another suggestion would be to just always track the shorter time.
