### ISSUE TITLE
[CF 1617] Add 'Pixel Glow' and 'Autocast Shine' to Activation Border options 

### ISSUE THREAD

**Issue by tmw-issue-import** [ascott18/TellMeWhen#1637]
<p>These are two different types of button glows that exist within the default game that WeakAuras lets you use. Would be nice to see them brought to TMW as well.</p> 
<br>

> Posted by CurseForge user <a href="https://wow.curseforge.com/members/Jalopyy">Jalopyy</a> | Imported from CurseForge issue <a href="https://wow.curseforge.com/projects/tellmewhen/issues/1617">#1617</a> | <a href="https://github.com/tmw-issue-import/dump/blob/master/html/1617.html">Raw</a>

**Comment by ascott18** [comment]
cc @Jalopyy

**Comment by ascott18** [comment]
@Jalopyy WA uses LibCustomGlow, so I'm assuming that's where these are coming from. Closing in favor of #1857.
