### ISSUE TITLE
[CF 1619] Add option to Combat Event type to only process events if icon's conditions are passing 

### ISSUE THREAD

**Issue by tmw-issue-import** [ascott18/TellMeWhen#1639]
<p>From&nbsp;<a href="" rel="nofollow">https://wow.curseforge.com/projects/tellmewhen/issues/1618&amp;nbsp;</a></p>
<p>&nbsp;</p>
<blockquote>
<p>Add an option to the combat event icon type to only process events if the icon's conditions are passing. Then you could put your bladestorm condition on the icon itself instead of as a destination condition.</p>
</blockquote> 
<br>

> Posted by CurseForge user <a href="https://wow.curseforge.com/members/Cybeloras">Cybeloras</a> | Imported from CurseForge issue <a href="https://wow.curseforge.com/projects/tellmewhen/issues/1619">#1619</a> | <a href="https://github.com/tmw-issue-import/dump/blob/master/html/1619.html">Raw</a>

**Comment by ascott18** [comment]
Technically #20 is the duplicate, but I didn't realize this one was here.
