### ISSUE TITLE
[CF 1637] Suggestion: add condition type: group size 

### ISSUE THREAD

**Issue by tmw-issue-import** [ascott18/TellMeWhen#1657]
<p>It would be really nice if TMW can add an condition type of "<strong>group size</strong>" (compatible of both party and raid).</p>
<p>&nbsp;</p>
<p>I know there is a "<strong><em>instance size</em></strong>" condition type existing.</p>
<p>But noticed that it only works based on "instance", which doesn't work for raid groups in worlds / maps outside of an "instance".</p>
<p>&nbsp;</p>
<p>For example 1, the "instance size" is still and always 0 (zero) when I'm in a raid group of <strong>world boss, </strong>like <strong>dooms-howl </strong>in "Arathi Highlands"</p>
<p>And example 2, it <em>seems</em> to be 0 (zero) when I'm in some big scenario, like <strong>Stromgarde warfront scenario</strong>.</p>
<p>&nbsp;</p> 
<br>

> Posted by CurseForge user <a href="https://wow.curseforge.com/members/doneykoo">doneykoo</a> | Imported from CurseForge issue <a href="https://wow.curseforge.com/projects/tellmewhen/issues/1637">#1637</a> | <a href="https://github.com/tmw-issue-import/dump/blob/master/html/1637.html">Raw</a>

**Comment by Jalopyy** [comment]
If you want an aura to only activate if the group size is a certain number of people, you could use unit conditions for RaidX existing.

**Comment by ascott18** [comment]
Going to go with @Jalopyy's solution as the official suggestion here. `raid` unitIDs are always sequential, so if `raidN` exists, your raid has `N` members.
