### ISSUE TITLE
[CF 1640] WoW Crashing when trying to import new string 

### ISSUE THREAD

**Issue by tmw-issue-import** [ascott18/TellMeWhen#1660]
<p>Hi,</p>
<p>&nbsp;</p>
<p>I'm trying to install a new profile for TMW, but it constantly crashes the WoW Client when I c/p into the box.&nbsp;</p>
<p>&nbsp;</p>
<p>I've tried different profiles, and I've tried reinstalling etc.</p>
<p>&nbsp;</p>
<p>Can you have a look please?</p>
<p>&nbsp;</p>
<p>Thanks</p> 
<br>

> Posted by CurseForge user <a href="https://wow.curseforge.com/members/termyy">termyy</a> | Imported from CurseForge issue <a href="https://wow.curseforge.com/projects/tellmewhen/issues/1640">#1640</a> | <a href="https://github.com/tmw-issue-import/dump/blob/master/html/1640.html">Raw</a>

**Comment by ascott18** [comment]
It seems this is no longer an issue - pasting huge string doesn't crash the client.
