### ISSUE TITLE
[Bug] The buff for Grounding Totem Effect is not listed in TMW. The spellid for it is 8178 but when you enter that spellid "Grounding Totem Effect" does not show up as a buff.

### ISSUE THREAD

**Issue by BrianShaw23** [ascott18/TellMeWhen#1681]
**What version of TellMeWhen are you using? **

**What steps will reproduce the problem?**
1.
2.
3.

**What do you expect to happen? What happens instead?**

**Screenshots and Export Strings**

**Additional Info**

**Comment by Jalopyy** [comment]
Even if it doesn't show up, it should still check as true by name.
