### ISSUE TITLE
[Bug] Lua error

### ISSUE THREAD

**Issue by cordankos** [ascott18/TellMeWhen#1682]
**What version of TellMeWhen are you using? **
8.6.0
**What steps will reproduce the problem?**
1. Received randomly when was at arena and changed spell to track casting for arena1-3
2. Then out of instance to world and got second lua error

> 
> Message: attempt to yield across metamethod/C-call boundary
> Time: Wed Mar 13 16:35:14 2019
> Count: 1
> Stack: attempt to yield across metamethod/C-call boundary
> [C]: in function `yield'
> Interface\AddOns\TellMeWhen\TellMeWhen.lua:2794: in function `func'
> Interface\AddOns\TellMeWhen\TellMeWhen.lua:2788: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2787>
> Interface\AddOns\TellMeWhen\TellMeWhen.lua:823: in function `Fire'
> Interface\AddOns\TellMeWhen\Components\Core\Icon.lua:1092: in function `Setup'
> Interface\AddOns\TellMeWhen\TellMeWhen.lua:3096: in function `?'
> ...ns\Bartender4\libs\AceConsole-3.0\AceConsole-3.0.lua:94: in function `?'
> Interface\FrameXML\ChatFrame.lua:4721: in function `ChatEdit_ParseText'
> Interface\FrameXML\ChatFrame.lua:4382: in function `ChatEdit_SendText'
> [string "TMW Snippet: Hybrid profile"]:299: in function <[string "TMW Snippet: Hybrid profile"]:290>
> [string "TMW Snippet: Hybrid profile"]:343: in function `func'
> Interface\AddOns\TellMeWhen\TellMeWhen.lua:2788: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2787>
> Interface\AddOns\TellMeWhen\TellMeWhen.lua:823: in function `Fire'
> ...ace\AddOns\TellMeWhen\Options\TellMeWhen_Options.lua:320: in function <...ace\AddOns\TellMeWhen\Options\TellMeWhen_Options.lua:234>
> (tail call): ?
> [C]: ?
> [string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
> (tail call): ?
> ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
> ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
> [C]: in function `resume'
> Interface\AddOns\TellMeWhen\TellMeWhen.lua:2837: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2798>
> 
> Locals: <none>
> 
> 
> Message: Interface\AddOns\TellMeWhen\Options\IconConfig.lua:315: SpellCache is not yet initialized
> Time: Wed Mar 13 17:14:14 2019
> Count: 1
> Stack: Interface\AddOns\TellMeWhen\Options\IconConfig.lua:315: SpellCache is not yet initialized
> [C]: in function `error'
> ...Ons\TellMeWhen\Components\Core\Spells\SpellCache.lua:154: in function `GetCache'
> Interface\AddOns\TellMeWhen\Options\IconConfig.lua:315: in function `GetRealNames'
> [string "*:OnEnter"]:6: in function <[string "*:OnEnter"]:1>
> 
> Locals: (*temporary) = "SpellCache is not yet initialized"

**Comment by ascott18** [comment]
Please attach your TMW settings file. This file can be found in WoW's installation location, under `World Of Warcraft\_retail_\WTF\Account\<your account name>\SavedVariables\TellMeWhen.lua`.
