### ISSUE TITLE
[Bug] TMW bug to refresh and update icons properly when out of memory 600mb+

### ISSUE THREAD

**Issue by cordankos** [ascott18/TellMeWhen#1683]
**What version of TellMeWhen are you using? **
8.6.0 (original, not alpha)

**What steps will reproduce the problem?**
I just have very big profile with over 800 custom icons with own lua conditions, I see that TMW totally stop working to track even buffs debuffs when out of memory over 600mb+

**What do you expect to happen? What happens instead?**
I want to see how icons will work properly but I should wait a little bit, I guess, when TMW clean little bit memory space to return back out from lag

**Screenshots and Export Strings**

**Additional Info**
Memory problem I am sure. With all addons I have 800mb+ memory usage, tried without another addons but still same problem.

**Comment by cordankos** [comment]
When open tmw at arena

> Message: attempt to yield across metamethod/C-call boundary
Time: Thu Mar 14 01:16:57 2019
Count: 1
Stack: attempt to yield across metamethod/C-call boundary
[C]: in function `yield'
Interface\AddOns\TellMeWhen\TellMeWhen.lua:2794: in function `func'
Interface\AddOns\TellMeWhen\TellMeWhen.lua:2788: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2787>
Interface\AddOns\TellMeWhen\TellMeWhen.lua:823: in function `Fire'
Interface\AddOns\TellMeWhen\Components\Core\Icon.lua:1092: in function `Setup'
Interface\AddOns\TellMeWhen\TellMeWhen.lua:3096: in function `?'
...ns\Bartender4\libs\AceConsole-3.0\AceConsole-3.0.lua:94: in function `?'
Interface\FrameXML\ChatFrame.lua:4721: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4382: in function `ChatEdit_SendText'
[string "TMW Snippet: Hybrid profile"]:293: in function <[string "TMW Snippet: Hybrid profile"]:284>
[string "TMW Snippet: Hybrid profile"]:337: in function `func'
Interface\AddOns\TellMeWhen\TellMeWhen.lua:2788: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2787>
Interface\AddOns\TellMeWhen\TellMeWhen.lua:823: in function `Fire'
...ace\AddOns\TellMeWhen\Options\TellMeWhen_Options.lua:320: in function <...ace\AddOns\TellMeWhen\Options\TellMeWhen_Options.lua:234>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `resume'
Interface\AddOns\TellMeWhen\TellMeWhen.lua:2837: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2798>

Locals: <none>

**Comment by ascott18** [comment]
Nothing I can do - 600MB usage from TMW alone is insane. You've pushed the addon way past the limits of what its intended to do.

**Comment by cordankos** [comment]
Hello. Is here some limit by itself TMW because I have enough free RAM on my pc? Maybe I can do something to clean RAM by lua somehow?

**Comment by cordankos** [comment]
I see when RAM going to very high then game or TMW dump it back to normal, same as CPU Usage feature doing, same behaivor

**Comment by ascott18** [comment]
If you have any custom Lua scripts (which you do), then I can't help you unless you respond to your other ticket and give me your settings. I suspect your scripts are poorly written and have large memory leaks that are causing you to get up to 600MB.

**Comment by cordankos** [comment]
Is it possible make in CPU Usage tracking for lua snippets / functions? Or how will possible to track place with memory leak? Might you recommend to read something about that?

**Comment by cordankos** [comment]
I seem to have found what causes this behavior. I use check buffs and many icons usually use repetitive checking. That is, I check the same buff in several icons. Each icon iterates over and over again all the auras, there is no saved value which can be taken from TMW - I didn't found it I guess because TMW uses real time check any aura for each icon every time. To prevent FPS from falling, I bring an aura that is not in the table to the table through the function and each function call returns the aura from the table if it is there, and also write to the table the time when the aura was updated or entered in the table. Each call calculates the time of the last call for this aura, and if it is less than 0.1 seconds, it returns the table, or updates the data about the aura and puts it into the table and then also returns the table. I attached parts of code and yeah it looks as heavy load but what we can do if tmw core can't prevent that issue.

`
local TMW = TMW
local CNDT = TMW.CNDT
local Env = CNDT.Env

local pairs, tostring = pairs, tostring

local UnitGUID, GetSpellInfo = UnitGUID, GetSpellInfo

local Env.MyCache = {}

local DispelList = {
    Magic = {
        118, -- Polymorph
        605, -- Mind Control                
        9484, -- Shackle Undead
        2637, -- Hibernate
        20066, -- Repentance          
        5782, -- Fear
        3355, -- Freezing Trap
        209790, -- Freezing Arrow (hunter pvp)        
        6358, -- Seduction
        82691, -- Ring of Frost                          
        198909, -- Song of Chi-ji (mistweaver monk talent)
        5484, -- Howl of Terror
        6789, -- Mortal Coil
        87204, -- Sin and Punishment
        8122, -- Psychic Scream
        31661, -- Dragon's Breath
        105421, -- Bliding light (paladin talent)
        202274, -- Incendiary brew (brewmaster monk pvp talent)
        15487, -- Silence
        25046, -- Arcane Torrent
        31935, -- Avenger's Shield
        199683, -- Last Word
        47476, -- Strangulate
        31117, -- Unstable Affliction
        853, -- Hammer of Justice
        64044, -- Psychic Horror
        30283, -- Shadowfury
        117526, -- Binding Shot
        118905, -- Static Charge
        179057, -- Chaos Nova
        205630, -- Illidan's Grasp (demon hunter)
        226943, -- Mind Bomb
        209749, -- Faerie Swarm (Moonkin Disarm) 
        204399, -- Earthfury (enhancement shaman pvp talent)
        217832, -- Imprison
        286349, -- Gladiator's Maledict
    },
}

function Env.GetUCache(indentification, elapsed)
    local CachedTime = Env.MyCache[indentification] and Env.MyCache[indentification].TIME
    if not elapsed then elapsed = 0.1 end 
    if CachedTime and TMW.time - CachedTime <= elapsed then     
        return Env.MyCache[indentification].VAL, (Env.MyCache[indentification].VAL2 or "none")
    end 
    return false 
end

function Env.GetUAura(unit, key, iSource)
	local indentification = (UnitGUID(unit) or unit or "") .. "GetUAura" .. tostring(key) .. tostring(iSource)
	local Cached, Cached2 = Env.GetUCache(indentification, refresh)   
	if Cached then 
		return Cached, Cached2 -- Prevent refresh aura by each icon at one tick of refresh interval
	end 
	local value, duration = 0, 0
	value, duration = Env.Auras(unit, ((type(key) == "string" and DispelList[key]) or key), iSource or "")        
	Env.MyCache[indentification] = { TIME = TMW.time, VAL = value, VAL2 = duration }
	return Env.MyCache[indentification].VAL, Env.MyCache[indentification].VAL2
end 

function Env.Auras(unitID, spell, source, byId)
    local filter = "HELPFUL"    
    if source == "player" then
        filter = filter .. " " .. "PLAYER"
    end    
    if type(spell)=="table" then         
        for i, v in pairs(spell) do            
            if not byId then
                found, dur = Env.AuraDURATION(unitID, GetSpellInfo(v), filter)           
            else 
                found, dur = Env.AuraDURATION(unitID, v, filter) 
            end              
            if found > 0 then
                break
            end
        end
        return found, dur
    elseif not byId then
        return Env.AuraDURATION(unitID, GetSpellInfo(spell), filter)
    else
        return Env.AuraDURATION(unitID, spell, filter)
    end   
end

function Env.AuraDURATION(unit, name, filter)    
    local buffName, _, duration, expirationTime, id 
    if type(name) == "number" then 
        for i = 1, huge do        
            buffName, _, _, _, duration, expirationTime, _, _, _, id = UnitAura(unit, i, filter)
            if not id or id == name or strlowerCache[buffName] == name then
                break
            end
        end
    else 
        buffName, _, _, _, duration, expirationTime, _, _, _, id = AuraUtil.FindAuraByName(name, unit, filter)        
    end
    
    if not buffName then
        return 0, 0, 0
    else
        return expirationTime == 0 and huge or expirationTime - TMW.time, duration, expirationTime
    end
end
`

**Comment by cordankos** [comment]
Also I use in lua conditions for each icon:
local ID = thisobj.Name
return
conditions and conditions or conditions

Might it be a trouble with "thisobj" getting Name if I use more than 500 icons with that :D ?
