### ISSUE TITLE
Masque Icons border issue

### ISSUE THREAD

**Issue by stamicvs** [ascott18/TellMeWhen#1684]
**What version of TellMeWhen are you using? **
8.6.1 r4

Since the update of Masque all of the icons are in TellMeWhen show a wrong border.
If I switch the Masque skin to show a skin without border everything seems to be ok but as soon as I switch to a skin with a special border a default border is shown instead.

I've attached two screenshot one with the correct border handled by Bartender and the other with the border in TellMeWhen.

![Masque_wrong_border](https://user-images.githubusercontent.com/48605567/54473433-c8910a00-47d7-11e9-8ab8-7b1d3a016afa.png)
![Example_Bartender_correct_border](https://user-images.githubusercontent.com/48605567/54473434-c8910a00-47d7-11e9-8bd0-1cd04a50d6d4.png)

Thank you!

**Comment by ascott18** [comment]
Unable to reproduce - what is the specific skin you're using that isn't working?

With Zoomed skin:
![image](https://user-images.githubusercontent.com/5017521/54495359-68b26600-48a0-11e9-9c64-c6dca21fe306.png)

With Renaitre: Square:
![image](https://user-images.githubusercontent.com/5017521/54495369-7b2c9f80-48a0-11e9-8ac3-970dc9af4d88.png)

**Comment by ascott18** [comment]
Oh, I guess you meant with the recent alpha of Masque.

You should report a bug for Masque (https://github.com/stormfx/masque/issues), as that's where the breaking change was made. I don't see anything in the changelog at https://www.wowace.com/projects/masque/files/2684513 that indicates that any breaking changes were made and/or what the migration path is supposed to be, so I'm sure this wasn't intended.

**Comment by ascott18** [comment]
Nevermind, I made one

**Comment by stamicvs** [comment]
Thank you very much for opening the ticket!
Seems to be an issue from Masque in the latest alpha.
Sorry, I forgot to mention this in my description.

**Comment by ascott18** [comment]
Seems working again in the latest Masque alpha
