### ISSUE TITLE
error everytime i log in

### ISSUE THREAD

**Issue by micoola** [ascott18/TellMeWhen#1689]
Date: 2019-03-22 09:40:25
ID: 1
Error occured in: Global
Count: 1
Message: TellMeWhen: [string "TMW Snippet: New Snippet"] line 1:
   unexpected symbol near '^'
Debug:
   ...Ons\TellMeWhen\Components\Core\Snippets\Snippets.lua:69: RunSnippet()
   ...Ons\TellMeWhen\Components\Core\Snippets\Snippets.lua:52:
      ...Ons\TellMeWhen\Components\Core\Snippets\Snippets.lua:38
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   TellMeWhen\TellMeWhen.lua:823: Fire()
   TellMeWhen\TellMeWhen.lua:1178: ?()
   ...ies\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...ies\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...ies\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ies\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ies\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...s\GladiatorlosSA2\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...s\GladiatorlosSA2\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  BattleGroundEnemies, vv3.1.9.9
  DBMCore, v8.1.12
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  ForwardStrafe, v0.1.1
  GladiatorlosSA2, vB7
  Gladius, v6.0.6
  MikScrollingBattleText, v5.7.149
  MouselookHandler, v1.3.9
  NameplateAuras, v80100.1-release
  Recount, vv8.1.0d
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TellMeWhen, v8.6.0
  TidyPlatesThreatPlates, v9.1.4
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=1f1)

**Comment by ascott18** [comment]
You created a Lua snippet and wrote some invalid code into it. If I had to guess, you pasted an export string into it.
