### ISSUE TITLE
[Bug] Incorrect unit spec for party members

### ISSUE THREAD

**Issue by XizhiXu** [ascott18/TellMeWhen#1693]
**What version of TellMeWhen are you using? **

v8.6.0

**What steps will reproduce the problem?**
I want to track some major cooldowns for the party. To save room, I set them to show only under some spec, especially for those multi-role classes. But it doesn't show after config.

So I did some test:
1. In a party
2. Add a spec-specific unit cooldown (say Ice Barrier for Forest Mage) watch for the 1st member
3. Add a condition to show it only under a certain spec
4. Didn't show if matched

Actually, I've tried all mage specs entirely. It didn't work.
Then I added all possible specs to that condition. Still, didn't work.
It finally appears when I stumbled on negate-selecting the condition. 
That's pretty weird. Does that effectively mean it detects a spec that doesn't belong to existing ones?

**What do you expect to happen? What happens instead?**
Show it if the spec is right

**Screenshots and Export Strings**

^1^T^SUnit^Sparty~`1 ^SType^Sunitcooldown ^SName^S11426:~`25 ^SConditions^T ^N1^T ^SType^SUNITSPEC ^SUnit^Sparty~`1 ^SBitFlags^T ^N64^B ^N63^B ^N62^B ^t^t^Sn^N1 ^t^SEnabled^B ^t^N86006^S~`~| ^Sicon^^

**Additional Info**

**Comment by XizhiXu** [comment]
https://github.com/ascott18/TellMeWhen/blob/f72187bf9f71c048c990449149fe0ec08902296f/Components/Core/Conditions/Categories/Talents.lua#L122

So that's a 0 right?

**Comment by ascott18** [comment]
Working as described:

https://github.com/ascott18/TellMeWhen/blob/master/Localization/TellMeWhen-enUS.lua#L1384-L1391
