### ISSUE TITLE
Icons not showing after loading screen.

### ISSUE THREAD

**Issue by Jumpperi** [ascott18/TellMeWhen#1695]
**What version of TellMeWhen are you using? **
v8.6.0

**What steps will reproduce the problem?**
1. Loading screens
2.
3.

**What do you expect to happen? What happens instead?**
I have set certain abilities to flash for 2 secs in the middle of the screen when they come off cooldown. I also set a sound for them, but after every loading screen i have to open and close tmw using /tmw command for them to show up. The sound is still working when they come off cooldown but the icon wont show unless i open and close tmw.

**Screenshots and Export Strings**
```
^1^T^SType^Scooldown ^SName^SFeral~`Spirit ^SEvents^T ^N1^T ^SType^SAnimations ^SDuration^N2 ^SAnimation^SICONFADE ^SEvent^SOnFinish ^t^N2^T ^SType^SAnimations ^SDuration^N1.9 ^SAnimation^SACTVTNGLOW ^SEvent^SOnFinish ^t^N3^T ^SType^SSound ^SSound^STMW~`-~`Ding~`7 ^SEvent^SOnFinish ^t^Sn^N3 ^t^SStates^T ^N1^T ^SAlpha^N0 ^t^t^SEnabled^B ^t^N86006^S~`~| ^Sicon^^
```

**Additional Info**

**Comment by ascott18** [comment]
Sorry it took so long for me to get to this. That icon seems to work for me on the first try after logging in without having toggled configuration mode.

However, I wouldn't recommend the way you have it configured. Try this instead:
```
^1^T^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SSPELLCD ^SName^SFeral~`Spirit ^t^Sn^N1 ^t^SName^SFeral~`Spirit ^SConditionDurEnabled^B ^SEvents^T ^N1^T ^SType^SAnimations ^SDuration^N1 ^SAnimation^SICONFADE ^SEvent^SOnFinish ^t^N2^T ^SType^SAnimations ^SDuration^N1.9 ^SAnimation^SACTVTNGLOW ^SEvent^SOnStart ^t^N3^T ^SType^SSound ^SSound^STMW~`-~`Ding~`7 ^SEvent^SOnStart ^t^Sn^N3 ^t^SConditionDur^N1 ^SCustomTex^S51533 ^SOnlyIfCounting^B ^SEnabled^B ^t^N86603^S~`~| ^Sicon^^
```

Note that the spell being watched is configured as a condition of the icon. When the spell becomes usable, it sets off a 1 second timer on the icon. When that 1 second is up, the icon fades out over an additional 1 second.
