### ISSUE TITLE
[Bug] 8.2 error when open /tmw

### ISSUE THREAD

**Issue by cordankos** [ascott18/TellMeWhen#1697]
Message: ...Ons\TellMeWhen\Components\Core\Conditions\Config.lua:666: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: TellMeWhen_IconEditorConditionsGroupsGroup1:SetPoint.
Time: Tue Jun 25 12:11:43 2019
Count: 1
Stack: ...Ons\TellMeWhen\Components\Core\Conditions\Config.lua:666: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: TellMeWhen_IconEditorConditionsGroupsGroup1:SetPoint.
[C]: in function SetPoint'
...Ons\TellMeWhen\Components\Core\Conditions\Config.lua:666: in function <...Ons\TellMeWhen\Components\Core\Conditions\Config.lua:662>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...erface\AddOns\TellMeWhen\Lib\LibOO-1.0\LibOO-1.0.lua:172: in function <...erface\AddOns\TellMeWhen\Lib\LibOO-1.0\LibOO-1.0.lua:128>
...erface\AddOns\TellMeWhen\Lib\LibOO-1.0\LibOO-1.0.lua:662: in functionCallFunc'
...erface\AddOns\TellMeWhen\Lib\LibOO-1.0\LibOO-1.0.lua:527: in function <...erface\AddOns\TellMeWhen\Lib\LibOO-1.0\LibOO-1.0.lua:490>
(tail call): ?
...Ons\TellMeWhen\Components\Core\Conditions\Config.lua:635: in function CreateGroups'
[string "*:OnLoad"]:4: in function <[string "*:OnLoad"]:1>
[C]: in functionresume'
Interface\AddOns\TellMeWhen\TellMeWhen.lua:2837: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2798>

Locals: <none>

**Comment by raysmith59** [comment]
I'm getting this as well when logging in, it's not unique to cordankos.
