### ISSUE TITLE
[Bug] Cannot track the Azerite Essence cooldown

### ISSUE THREAD

**Issue by StragaSevera** [ascott18/TellMeWhen#1700]
**What version of TellMeWhen are you using?**

v8.6.3

**What steps will reproduce the problem?**
1. Add the cooldown tracking with the 296208 (Azerite Essence) id.
2. Use the Azerite Essence.

**What do you expect to happen? What happens instead?**
3. Expect to see it going to cooldown, but TMW will show that it is still usable.

**Screenshots and Export Strings**

^1^T^SShowTimer^B ^SType^Scooldown ^SConditions^T ^N1^T ^SType^SCOMBAT ^t^Sn^N1 ^t^SName^S296208 ^SShowTimerText^B ^SGUID^STMW:icon:1T5f6y7VsfGv ^SStates^T ^N1^T ^SAlpha^N0.5 ^t^N2^T ^SAlpha^N0.7 ^t^t^SEnabled^B ^t^N86301^S~`~| ^Sicon^^

**Comment by ascott18** [comment]
Working as intended. Enter the actual spell you want to track, e.g. "Concentrated Flame" or 295373. 296208 isn't a "real" spell, and doesn't have any cooldown associated.
