### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by BryanMohr** [ascott18/TellMeWhen#1702]
I just installed TMW but I don't get any of the icons except for the "Dummy Icon". And the only option on the opening dialog box is to exit configuration mode. What am I missing?

**Comment by ascott18** [comment]
TellMeWhen isn't configured to do anything out of the box. You have to configure icons to do what you want them to do. Right click one of the icons that you see and follow the instructions from there.

**Comment by BryanMohr** [comment]
That's the problem. The only icon I see is the "Dummy" icon. How do I see other icons?

**Comment by ascott18** [comment]
Not sure what you mean. Perhaps a screenshot would help? Include the full game window so I can see everything you're seeing.

**Comment by BryanMohr** [comment]
Well, I just re-enabled it to take the screenshot, and now there are 4 blank icon areas. I'll work on it from here. Thanks.

**Comment by ascott18** [comment]
Great, glad to hear it!

BTW - for any future questions, you may get quicker responses for questions like this if you ask in the Discord, as they'll get seen by a lot more people - https://discord.gg/NH7RmcP
