### ISSUE TITLE
LUA error when slowly scrolling through guild news

### ISSUE THREAD

**Issue by raysmith59** [ascott18/TellMeWhen#1703]
No clue how this would have anything to do with TMW but that's the only add-on I see referenced in the error.

1x Usage: GameTooltip:SetHyperlink(link)
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetHyperlink'
Blizzard_Communities\GuildNews.lua:160: in function `CommunitiesGuildNewsButton_OnEnter'
[string "*:OnEnter"]:2: in function <[string "*:OnEnter"]:1>
[C]: in function `Enable'
Blizzard_Communities\GuildNews.lua:71: in function `CommunitiesGuildNews_Update'
Blizzard_Communities\GuildNews.lua:13: in function `update'
SharedXML\HybridScrollFrame.lua:191: in function `HybridScrollFrame_SetOffset'
SharedXML\HybridScrollFrame.lua:30: in function <SharedXML\HybridScrollFrame.lua:29>
[C]: in function `SetValue'
SharedXML\HybridScrollFrame.lua:67: in function <SharedXML\HybridScrollFrame.lua:57>

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 SetCurrencyByID = <function> defined @AllTheThings\AllTheThings.lua:3181
 ItemTooltip = <unnamed> {
 }
 SetCurrencyToken = <function> defined @Altoholic\Tooltip.lua:700
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 TMW_SetEquiv = <function> defined @TellMeWhen\Options\TellMeWhen_Options.lua:165
 comparing = false
 SetSocketGem = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 TMW_SetDogTag = <function> defined @TellMeWhen\Components\Core\Common\DogTags\config.lua:398
 SetUnitDebuff = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetLFGDungeonReward = <function> defined @AllTheThings\AllTheThings.lua:3218
 SetQuestItem = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 SetToyByItemID = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 ttIcon = <unnamed> {
 }
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetUnitBuff = <function> defined =[C]:-1
 SetLFGDungeonShortageReward = <function> defined @AllTheThings\AllTheThings.lua:3235
 SetQuestLogItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined @Altoholic\Tooltip.lua:700
 SetTradeTargetItem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 SetIconTextureAndText = <function> defined @TipTacItemRef\ttItemRef.lua:62
 SetSendMailItem = <function> defined =[C]:-1
 TMW_SetSpellByIDWithClassIcon = <function> defined @TellMeWhen\Components\Core\Spells\ClassSpellCache.lua:212
 updateTooltip = 0.086000
 SetInventoryItem = <function> defined =[C]:-1
 Show = <function> defined =[C]:-1
 ttCount = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetUnitAura = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 SetRecipeResultItem = <function> defined =[C]:-1
 TMW_SetFrameHighlight = <function> defined @TellMeWhen\Components\GroupModules\GroupModule_GroupPosition\Config.lua:193
 SetAuctionItem = <function> defined =[C]:-1
}
(*temporary) = nil

**Comment by ascott18** [comment]
You're right - totally unrelated to TMW.

TMW is mentioned because it adds methods to GameTooltip (you'll also see TipTac, Altoholic, and AllTheThings there as well). This is common for addons to do, and definitely isn't causing this.
