### ISSUE TITLE
[Bug] Class and Talents condition menu not showing

### ISSUE THREAD

**Issue by Vanteil** [ascott18/TellMeWhen#1704]
**What version of TellMeWhen are you using? **

v.8.6.5

**What steps will reproduce the problem?**
1. Trying to set up a condition from the Class and Talents section
2.
3.

**What do you expect to happen? What happens instead?**
A menu is supposed to show up but nothing happens when you mouse over the selection. All other condition selections work just fine.

**Screenshots and Export Strings**

**Additional Info**

**Comment by Alexstraszaa** [comment]
I have the same problem, The error text i get is displayed below:

Error occured in: Global
Count: 1
Message: ...en\Components\Core\Conditions\Categories\Talents.lua line 444:
   attempt to index a nil value
Debug:
   ...en\Components\Core\Conditions\Categories\Talents.lua:444:
      ...en\Components\Core\Conditions\Categories\Talents.lua:444
   (tail call): ?
   ...Ons\TellMeWhen\Components\Core\Conditions\Config.lua:217:
      ...Ons\TellMeWhen\Components\Core\Conditions\Config.lua:199
   ...Ons\TellMeWhen\Components\Core\Conditions\Config.lua:296: initFunction()
   ...face\AddOns\TellMeWhen\Options\TMWUIDropDownMenu.lua:110: Initialize()
   ...face\AddOns\TellMeWhen\Options\TMWUIDropDownMenu.lua:616: Toggle()
   [string "*:OnEnter"]:5:
      [string "*:OnEnter"]:1
Locals:
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "attempt to index a nil value"

**Comment by ascott18** [comment]
Fixed in 81700742680f74c01bb6df9191ee4b1229b6654f
