### ISSUE TITLE
[Bug] Lua errors

### ISSUE THREAD

**Issue by shocker13** [ascott18/TellMeWhen#1710]
**What version of TellMeWhen are you using?**
8.6.6

**What steps will reproduce the problem?**
Just play some arenas/skirms.

**What do you expect to happen? What happens instead?**
I expected to avoid lua errors but recently I started getting different lua errors with following huge fps drops which were captured by Bugger + Bugsack addons.

**List of errors:**
1) https://pastebin.com/9gdPUrk7
2) https://pastebin.com/75DtTnea
3) https://pastebin.com/H18x7WSg
4) https://pastebin.com/7YD9qRjm

**Attached my TMW config just in case.**
[TellMeWhen.zip](https://github.com/ascott18/TellMeWhen/files/3478033/TellMeWhen.zip)

**Comment by shocker13** [comment]
One more lua error https://pastebin.com/2XWmDevJ.

**Comment by ascott18** [comment]
Thanks for including your config. In this case, I think you've just stretched TMW way past its limit. 

My guess is that you have some huge chains of counter dependencies between conditions and notifications that are ultimately forming some sort of loop.

**Comment by shocker13** [comment]
Well everything was fine until recently. I need so many counters to track 2 charges of bop and survival instincts. I couldn't find a better solution yet but anyway it works somehow. Thank you for answer I'll take a closer look at counters.
