### ISSUE TITLE
[Bug][Classic] Merge Heroic Strike w/swing timer

### ISSUE THREAD

**Issue by Jalopyy** [ascott18/TellMeWhen#1713]
gbbd8b171

In vanilla, heroic strike overwrites the autoattack with a stronger hit. TMW obviously doesn't detect this in a swing timer aura, as it is only looking for white hits. Add a way for it to recognize that a heroic strike = white swing, as far as the addon is concerned.

Also, ElvUI currently doesn't offer their cooldown text in Classic. As such, you can remove/gray out the 'Show ElvUI Timer Text' option, at least for now. I think Azilroka is in charge of the Classic fork, so you can ask him if it is something planned to return or just being phased out.

**Comment by Jalopyy** [comment]
Also add cleave, it apparently works the same way.

**Comment by ascott18** [comment]
Will leave the ElvUI timer text option alone for now. I don't want to have to re-enable it if that functionality gets added back in.
