### ISSUE TITLE
WoW Classic Ranged Weapon Swing Time

### ISSUE THREAD

**Issue by totalschaden** [ascott18/TellMeWhen#1715]
Currently it seems that Ranged Weapons Swing time is not available for tmw classic. Without it cant make a proper Hunter Rotation.
Would be nice to see it added.

**Comment by ascott18** [comment]
Seems to be working fine. Just to be sure, the way to track the Auto Shot timer in TMW is to just track "Auto Shot" in a Spell Cooldown icon.

Let me know if there's something about this not working right.
