### ISSUE TITLE
[Bug] Classic - Combopoint-dependent auras have no/wrong durations

### ISSUE THREAD

**Issue by floomdoom** [ascott18/TellMeWhen#1721]
Just like the issue with Pounce, the same one exist for Kidney Shot.

Timer sweeper or numerals does not display.
Tried with every possible ID for Kidney Shot. 
Using the same settings for every other stun and it works just fine. (Sap, Gouge, Cheap Shot)

EDIT: To clarify, it still tracks Kidney Shot for the right duration. It is just the display of the timer sweeps that is not working.

![image](https://user-images.githubusercontent.com/54779434/64081605-cb3ed780-cd03-11e9-94b2-199e6b0cd637.png)

**Comment by ascott18** [comment]
Closing as a duplicate of #1718 - the cause here is the same, since they're both variable durations based on combo points.

**Comment by ascott18** [comment]
Turns out I'm a big dummy and they aren't the same thing at all.

**Comment by ascott18** [comment]
This may now be fixed in c99065e2 - please test and let me know.

**Comment by floomdoom** [comment]
> 
> 
> This may now be fixed in [c99065e](https://github.com/ascott18/TellMeWhen/commit/c99065e23db6ee6520bb19b4d2e61326c447c544) - please test and let me know.

Downloaded that package and extracted into my current TMW and replaced all the files that it asked to replace. 

The result is that now TMW doesnt track any of my stuns on the enemy now. But not only that,it is not tracking anything on "target". Not even my Rupture can be tracked now

It still is able to track cooldowns and buff durations on myself, or "player".


After noticing that it didnt work I first tried to remake these trackers from scratch, same result. I then turned in LUA errors and went to Cheap Shot a mob to see what happend. These are the errors I got, if they are of any help to you.
1.[https://pastebin.com/4mx8dSq1](url)
2.[https://pastebin.com/UUMRnc9J](url)
3.[https://pastebin.com/MH4ZG4XH](url)

**Comment by ascott18** [comment]
@floomdoom sorry, lets try that again. Pushed another fix in 6ada1003 - try again with the latest alpha.

FYI, you generally shouldn't download the source straight from Github, as it'll lack a number of things that the build process adds. Download the packaged versions from Curseforge (https://www.curseforge.com/wow/addons/tellmewhen/files)

**Comment by floomdoom** [comment]
Downloaded the classic on curseforge, it is now back to the original problem. 
The debuff is being tracked for the right duration, but the timer sweepers are not working. Neither the numeral one or the visual one displays. (But the other debuffs work again; Cheap Shot, Sap and Gouge.)

I will try delete my old TMW and just install it fresh when I get back to see if that solves anything (dont think it should matter? but I can try just because)

**Comment by sapandtap2** [comment]
floomdoom, try the addon nugrunning while they work on this, it works perfectly

**Comment by ascott18** [comment]
@floomdoom 	please show me a screenshot of the icon editor, which will show your current version. It seems very likely that you're using the wrong version, as other people have reported to me that the fix is working fine for them.

**Comment by floomdoom** [comment]
![image](https://user-images.githubusercontent.com/54779434/64638031-4e97b180-d405-11e9-8a5a-5aae6ae619a5.png)

**Comment by ascott18** [comment]
Nope, that's the wrong version. You'll see something like g6ada1003 in the title bar of the icon editor when you get the right one.

**Comment by floomdoom** [comment]
Yepp, ok. Updated now, figured the main-file would've been updated, but found the correct version when browsing all files.  My bad.

Cheers. Works like a charm now. 
Thanks for your work.

**Comment by ascott18** [comment]
Oh. Apparently curseforge hides alpha versions from the main files page for users that aren't signed in or aren't members of the project. That would explain why everyone I send to that page seems to download the wrong version!

Sorry about that. Curseforge doing curseforge things strikes again!

**Comment by floomdoom** [comment]
How could one know though! 
Maybe it was resolved even earlier then if I kept trying the wrong versions, haha! 

Oh well, thanks again! Been using this addon since it came, love it. Thank you!

Guess this can be closed now! 👍
