### ISSUE TITLE
[Bug] Not showing correct duration of abilities - classic

### ISSUE THREAD

**Issue by sapandtap2** [ascott18/TellMeWhen#1722]
No issues with this in retail previously

Improved gouge timer ends too early. It runs to 0s but the icon continues to display because the spell is still active. Same thing with rupture.

**Comment by ascott18** [comment]
Rupture: see #1721 
Improved Gouge: Is this your own gouge that's wrong, or someone else's gouge?

**Comment by ascott18** [comment]
Fixed in e458515
