### ISSUE TITLE
[Bug] Shadow Word: Pain

### ISSUE THREAD

**Issue by eddassex** [ascott18/TellMeWhen#1723]
**What version of TellMeWhen are you using? **

Version 8,6,9 for wow classic

**What steps will reproduce the problem?**
When i do Shadow word: Pain it doesent show correct countdown on the debuff, it shows only 21 seconds and i got improved Shadow Word: Pain and that should be 24 seconds. 

**What do you expect to happen? What happens instead?**
When i cast Shadow Word: Pain on an mob it countdown from 21 seconds insted of 24 that the tooltip says on the spell. 

![2019-09-07](https://user-images.githubusercontent.com/55006895/64467382-47785700-d118-11e9-81cc-103b6b75bf6f.png)

![2019-09-07 (1)](https://user-images.githubusercontent.com/55006895/64467416-8f977980-d118-11e9-9b6e-334628b837aa.png)

Hope to slove this issue because the addon is so great, ty.

**Comment by ascott18** [comment]
Known issue: #1716
