### ISSUE TITLE
Classic: Off hand weapon imbue lua error

### ISSUE THREAD

**Issue by JoeBeezy1** [ascott18/TellMeWhen#1725]
When monitoring the offhand for a weapon Imbue  you get the following error

Message: ...ponents\IconTypes\IconType_wpnenchant\wpnenchant.lua:181: attempt to perform arithmetic on local 'expiration' (a boolean value)
Time: Wed Sep 11 16:35:50 2019
Count: 2037
Stack: ...ponents\IconTypes\IconType_wpnenchant\wpnenchant.lua:181: attempt to perform arithmetic on local 'expiration' (a boolean value)
(tail call): ?
...ponents\IconTypes\IconType_wpnenchant\wpnenchant.lua:181: in function `UpdateFunction'
Interface\AddOns\TellMeWhen\Components\Core\Icon.lua:751: in function <Interface\AddOns\TellMeWhen\Components\Core\Icon.lua:708>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Interface\AddOns\TellMeWhen\TellMeWhen.lua:2601: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2563>

Locals: <none>

**Comment by ascott18** [comment]
This has already been fixed in the latest alphas.
