### ISSUE TITLE
[Bug] Trade accept green color  be missing

### ISSUE THREAD

**Issue by FooX-X** [ascott18/TellMeWhen#1726]
my english is bad, i add video from youtube and screenshot 
if TMW ist on and you trade for another player and acept trade (you or another player) green screen showing 1 sec and missing 
https://www.youtube.com/watch?v=QuoccD8n6d8&feature=youtu.be

i off all addons and on only TMW but bug not missing

**Comment by ascott18** [comment]
Thanks for the detailed report. This has nothing to do with TMW, though - this bug is one I've seen myself many times and seems to be totally random. You just got unlucky when enabling and disabling TMW.
