### ISSUE TITLE
add new option

### ISSUE THREAD

**Issue by AminmL7** [ascott18/TellMeWhen#1728]
plz add new option about swing timer for wand ( now we have swing timer for main hand and off hand not wand) ty for ur services

**Comment by ascott18** [comment]
You can already do this by tracking "Shoot" in a spell cooldown icon. Added instructions when the Swing Timer icon type is selected (similar to those already in place for Auto Shot) in 5d22b29f

**Comment by essweinjacob** [comment]
What is the Trigger for this event?
