### ISSUE TITLE
Version 8.6.9 doesn't work in retail

### ISSUE THREAD

**Issue by raysmith59** [ascott18/TellMeWhen#1730]
The Twitch client updated this add-on along with a bunch of others today, however when I logged into the game (retail) it told me that I had installed the "classic version"... it does appear that 8.6.9 may be classic-specific but Twitch didn't seem to be aware of that.  I'm reverting back to 8.6.8 for now but it'd be good if the separation logic either worked or if the classic add-on was separated from the retail one.

**Comment by ascott18** [comment]
Your Twitch App is probably out of date. Try updating it. If that still doesn't help, contact Twitch support. The different versions of TMW properly identify the WoW version the support. If the Twitch app can't handle this properly, Twitch needs to fix it.
