### ISSUE TITLE
Classic wow interupts & weapon imbue icons

### ISSUE THREAD

**Issue by githubcorey** [ascott18/TellMeWhen#1732]
Maybe I'm missing something but I've tried a lot of different ways to make these work. I have no problem with it on retail wow but if there is a feature to make an icon when my targeted enemy starts casting a spell to show my interrupt icon? also, how are people tracking their weapon imbues such as rogue poisons. Thanks

**Comment by ascott18** [comment]
Use the Spell Cast and Weapon Imbue icon types. respectively.

In the future, please direct questions to the discord - Github is for feature request and bug reports. Thanks!
