### ISSUE TITLE
[Bug] Classic - Combo Point tracking is broken

### ISSUE THREAD

**Issue by coolnetz** [ascott18/TellMeWhen#1733]
Since Commit https://github.com/ascott18/TellMeWhen/commit/e4585158faf24f272d85e5f1a7bed7f63d6bd04b the current value of combo points is always 0.

![WoWScrnShot_092119_045138](https://user-images.githubusercontent.com/55610540/65367196-25112e00-dc2e-11e9-8a07-5d3a69aff4e8.jpg)

**Comment by ascott18** [comment]
You're in config mode, and you're also trying to watch for combo points on yourself instead of your target.
