### ISSUE TITLE
Icon Sorting by Order of Appearance

### ISSUE THREAD

**Issue by hermannm** [ascott18/TellMeWhen#1736]
I've got a group set up to track 5 temporary buffs, with icon IDs 1, 2, 3, 4 and 5. I use icon sorting with "Shown icons first" to place the active buffs forward. However, with this sorting, if for example buff 2 is active and then buff 1 is activated, buff 1 takes the first space and buff 2 is moved backwards. I would like it to work so that new buffs take up their first available space, without moving lower icon IDs behind. In my example, buff 2 would stay in the first space, and buff 1 would take up the second space, and they would stay there until expired.

One solution to this I think would be to add a new icon sorting option by "Order of Appearance". This would place the icons that have been shown the longest forward in the group. This way, when a buff is activated it would take the first available space after the other buffs that appeared before.

Importantly, I don't want the buffs to move forward if new space becomes available forward in the group. After being shown and having taken up the first available space to them, the buff should remain in that position.

Examples of desired behavior:

Buff 2 and 3 is active:
[2] [3]
Then buff 1 is activated:
[2] [3] [1]
Then buff 3 expires:
[2] [ ] [1]
Then buff 4 is activated:
[2] [4] [1]
Then buff 3 is activated again:
[2] [4] [1] [3]

I hope this makes sense, and I hope it's possible to implement!

**Comment by ascott18** [comment]
Added a new sorting option "Timer start" in d00aba19. That's the closest i'll ever get to implementing this request - the specific request around leaving open holes to later be filled is just not easily doable without lots of weird changes to TMW's internals.
