### ISSUE TITLE
[Bug] Incompatibility with accesibility addon

### ISSUE THREAD

**Issue by UsuallyQuiet** [ascott18/TellMeWhen#1737]
**What version of TellMeWhen are you using? **
8.7.1

**What steps will reproduce the problem?**
1. Load into game with ConsolePort and TMW loaded.
2. Press any keybinding assigned to bring up the RaidCursos.
3. Be forced to Alt+F4 out of the game as the entire UI becomes unusable.

**What do you expect to happen? What happens instead?**
Both addons to work together and thus allow me to play with a controller while monitoring my cooldowns and procs with TMW!

**Additional Info**

Hi, 

Due tu a recent accident I was left with severely hindered mobility and using a keyboard for any fast motions has so far proven impossible. Due to this, thought my time with WoW was over, but the addon ConsolePort and some creativity has allowed me to play with a controller. I mostly play healers, and the issue presents itself when toggling Consoleport's RaidCursor (A UI override which allows to target healing with a controller), if this is done with TMW active, it breaks the UI functionality and effectively disables the controller.

I've reached out to ConsolePort's dev and they said it was sadly an issue on TMW's side. I understand that this is an extreme edge case but I would love it if this was solvable in any way, as TMW is by far my preferred addon for keeping an eye on just about everything in the game.

-Kara

**Comment by ascott18** [comment]
You'll have to share what the ConsolePort dev told you, and what they think the issue in TMW might be.

I also have no idea how to "Press any keybinding assigned to bring up the RaidCursos" you'll have to give me some step-by-step instructions on how to do that with a keyboard and mouse (I don't own any console systems, let alone any controllers).

Some more detail on what "the entire UI becomes unusable" means would also be helpful.
