### ISSUE TITLE
Right click for icon options produces Lua error when group is anchored to personal resource frame

### ISSUE THREAD

**Issue by mdavies123** [ascott18/TellMeWhen#1738]
I have a group of spell cooldown icons anchored to my personal resource nameplate which exhibit the intended behavior of following the nameplate as you pitch the camera about the player. 

However, attempting to configure any icon when you have a group anchored to this nameplate will produce Lua errors for each group that is anchored to this icon, preventing any icon configuration.

This issue seems to be new with 8.2.5. Perhaps the personal resource display has become protected and therefore groups anchored to it inherit the nameplate's protected status as the Lua errors are thrown when `TellMeWhen_GroupX_IconY:IsMouseOver()` or `TellMeWhen_GroupX_IconY:GetPoint()` is called. 

Edit: I have found a workaround where I either temporarily disable the groups which are anchored to the personal resource display, or change those groups' anchors to `UIParent` temporarily as I configure an icon.

Stack traces below.

[stack1.txt](https://github.com/ascott18/TellMeWhen/files/3666237/stack1.txt)
[stack2.txt](https://github.com/ascott18/TellMeWhen/files/3666238/stack2.txt)

**Comment by ascott18** [comment]
Hmm, I thought I had fixed this in 46394e967. Will take a look.
