### ISSUE TITLE
[Bug]Classic - Spell/Ability dodge detection not working

### ISSUE THREAD

**Issue by smthpickboy** [ascott18/TellMeWhen#1740]
**What version of TellMeWhen are you using? **
TellMeWhen-8.7.1-classic

**What steps will reproduce the problem?**
1. New Icon
2. What to track: Dodge
3. Combat Events: Melee/Ranged > Swing Dodge & Spell/Ability Dodge
4. Source: player, Dest: target

**What do you expect to happen? What happens instead?**
Expect: detect both swing dodge & Spell/Ability Dodge
Instead: only  swing dodge can be detected

**Screenshots and Export Strings**
^1^T^SCLEUEvents^T ^SSWING_MISSED_DODGE^B ^SSPELL_MISSED_DODGE^B ^t^SType^Scleu ^SName^SDodge ^SEnabled^B ^SCLEUNoRefresh^B ^SSourceUnit^Splayer ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^S ^t^t^t^SCustomTex^SOverpower ^SDestUnit^Starget ^t^N87101^S~`~| ^Sicon^^

**Additional Info**
Really useful for notify Overpower in berserk stance.

**Comment by smthpickboy** [comment]
Seems that deleting "What to track: Dodge" fix the problem.

Export String:

^1^T^SCLEUEvents^T ^SSPELL_MISSED_DODGE^B ^SSWING_MISSED_DODGE^B ^t^SType^Scleu ^SSourceUnit^Splayer ^SEnabled^B ^SCLEUNoRefresh^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^S ^t^t^t^SCustomTex^SOverpower ^SDestUnit^Starget ^t^N87101^S~`~| ^Sicon^^

**Comment by ascott18** [comment]
Correct - there are no abilities in the game named "Dodge". Perhaps you meant to enter "Overpower" instead?
