### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Olorun** [ascott18/TellMeWhen#1742]
**What version of TellMeWhen are you using? **

v8.7.1 Classic

**What steps will reproduce the problem?**
1. Add Icon Tracker
2. Go to What to Track
3. Type in DR-

**What do you expect to happen? What happens instead?**
Should list all the DR trackers. It shows them, but a LuA error pops up once you enter the "-" character.

**Screenshots and Export Strings**

**Additional Info**

Lua Error:
1x ...s\TellMeWhen\Components\Core\Suggester\Suggester.lua:778: malformed pattern (ends with '%')
[C]: ?
...s\TellMeWhen\Components\Core\Suggester\Suggester.lua:778: in function `GetLookup'
...s\TellMeWhen\Components\Core\Suggester\Suggester.lua:904: in function `Table_GetNormalSuggestions'
...s\TellMeWhen\Components\Core\Suggester\Suggester.lua:95: in function `DoSuggest'
...s\TellMeWhen\Components\Core\Suggester\Suggester.lua:390: in function `NameOnCursor'
...s\TellMeWhen\Components\Core\Suggester\Suggester.lua:509: in function <...s\TellMeWhen\Components\Core\Suggester\Suggester.lua:506>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = "dig rat stew"
(*temporary) = "^d.- r.- %"

**Comment by ascott18** [comment]
Thanks for the report!
