### ISSUE TITLE
[Bug] Cannot create a Druid tank group

### ISSUE THREAD

**Issue by ZioGio** [ascott18/TellMeWhen#1743]
**What version of TellMeWhen are you using? **
v8.7.1 Classic

**What steps will reproduce the problem?**
1.  Be a feral Druid (in this case, I'm level 35 with talents 8/13/5)
2.  Create a new profile group
3.  Select Tank role and Feral specialization

**What do you expect to happen? What happens instead?**
Expected:  Can create a separate Tank role and Damage role with Feral specialization selected.

Actual:  With only Tank role selected, I get a dialog that states my current configuration and/or player specialization does not allow any groups to be shown.

If I select the Damage role, regardless of whether the Tank role is also selected, the configuration error dialog goes away.

**Screenshots and Export Strings**
^1^T^SScale^N1 ^SRole^N4 ^SPoint^T ^Sy^F4916802820009411 ^f-44^Sx ^F-7502370606280461^f-49 ^SrelativeTo^STMW:group:1TRobhixHnWl ^t^SEnabledSpecs^T ^N102^b ^N105^b ^t^SGUID^STMW:group:1Tcv5bfSEMyL ^SColumns^N8 ^SName^SBear ^t^N87101^S~`~| ^Sgroup^N1 ^^

String appears the same regardless of Role configuration (Tank only, Damage only, and both Tank and Damage).  

**Additional Info**
No icons have been added yet.

**Comment by ascott18** [comment]
Don't use the role checkboxes for Feral. Add group conditions based on your current shapeshift if you want groups to respond to your current form.

In general, there is no reason to ever restrict BOTH the spec checkboxes AND the role checkboxes at the same time. Pick one or the other.
