### ISSUE TITLE
[Bug] Overpower proc in Berserker posture

### ISSUE THREAD

**Issue by Ibadez38** [ascott18/TellMeWhen#1745]
**What version of TellMeWhen are you using? **
v8.7.1

Hello, 

I don't know if it's a bug, but when I create a "reactive ability" icon for Overpower it never appears when it's usable but I'm in berserker position.

Is there a way to make the icon appear when I am in the bererker posture and overpower is ready to be used.

Sorry about my English

Thank you in advance for your help.

**Comment by ascott18** [comment]
Not a bug. Overpower is not usable in Berserker Stance, so TMW doesn't incorrectly say that ability is usable while in Berserker stance.

Feel free to ask for help in the TMW Discord server.
