### ISSUE TITLE
WoW Classic: Shadow Priest "Shadow Vulnerability" not resetting timer on 5 stacks

### ISSUE THREAD

**Issue by tffchief** [ascott18/TellMeWhen#1746]
**What version of TellMeWhen are you using? **

TMW-8.7.1-classic.zip (1.13.2) from twitch client. Always updated.

**What steps will reproduce the problem?**
1. Track Debuff or "Any Buff/Debuff"
2. With timer shown, without timer
3. With stacks shown, without stacks
4. Adding requirements like stacks or duration
5. Adding/Trying to use other IDs -> did not work at all then.
6. Checking/Unchecking boxes

Basicly I tried most of the things I could think of to "work around" (even increasing update rate), nothing changed.

**What do you expect to happen? What happens instead?**

In WoW Classic:
When going up to 5 Stacks of "Shadow Vulnerability" from Shadow Priest, every time a stack is added and the timer resets. **At** 5 stacks however, reapplying "Shadow Vulnerability" does not reset the timer. It just runs out instead of refreshing the duration. Refreshing the duration on 5 stacks works with my threadplates so I guess it's not from the game.

I tried using multiple things but I stuck with normal "track debuff -> target -> "Shadow Vulnerability" -> Show Timer + Show Stacks" approach I use with other debuffs aswell. Everything else is standard. I did not tinker with any add-on settings.

**Screenshots and Export Strings**

^1^T^SShowTimer^B ^SBuffOrDebuff^SEITHER ^SUnit^Starget ^SType^Sbuff ^SStackMin^N5 ^SName^SShadow~`Vulnerability ^SStackMax^N4 ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^S ^N2^S[Stacks:Hide(0)] ^t^t^t^SOnlyMine^B ^SStates^T ^N100^T ^SAlpha^N0.3 ^t^t^SEnabled^B ^SDurationMax^N5 ^t^N87101^S~`~| ^Sicon^^

**Additional Info**

**Comment by ascott18** [comment]
Refreshes of max-stack auras don't generate combat log events, so there's no way to fix this. From the FAQ in Discord:

**Q:** **Why doesn't my Sunder Armor (or other stackable debuff) duration refresh after reaching 5 stacks?**
**A:** The refresh of a 5-stack Sunder (and other max-stack debuffs) don't appear in the combat log, so TMW cannot detect it and refresh the timer. There is no known workaround to get a true timer.
