### ISSUE TITLE
Add Keybind feature to Notification Handler 

### ISSUE THREAD

**Issue by Sqoops** [ascott18/TellMeWhen#1748]
I have set up an Icon with Notification Handler that: 
1. On left click increases a counter by 1. 
2. On right click decreases a counter by 1.

Would it be possible to implement a keybind option to the Notification Handler so you can choose:
1. On "keybind 1 pressed" increases a counter by 1. 
2. On "keybind 2 pressed" decreases a counter by 1. 

And add a few keybind options to the ESC -> "Key Bindings" menu so it would look like this:

![Keybinds](https://user-images.githubusercontent.com/4706311/68994408-ec36b380-0882-11ea-8cb1-b7f42b8e6716.jpg)

**Comment by ascott18** [comment]
Added a new slash command `/tmw counter` in 7b1d2c68. E.g. `/tmw counter casts + 1`
