### ISSUE TITLE
Condition for "Item Usable"

### ISSUE THREAD

**Issue by 0xjc** [ascott18/TellMeWhen#1749]
For cooldown icons I like the following setup: show both when ready/not ready, but add an activation border when ready. The latter is done with a Notification with Trigger Condition being Spell/Item Cooldown == 0 sec (Usable).

I have been using this setup for a potion icon. However, the condition "Item Cooldown == 0 sec" will trigger even if the potion has been used in combat. This occurs due to the override introduced in https://github.com/ascott18/TellMeWhen/commit/49f98a99f10fda3d2f4ecdeba94c319424dd9852 which forces `duration = 0` if `enable` is 0.

To resolve this, I was thinking we should have a condition that just checks `enable`. For now I will use a custom Lua condition.

**Comment by ascott18** [comment]
The linked commit only affected the Item Cooldown icon type, not the conditions.

**Comment by ascott18** [comment]
Changed in 4fcc3e410bf84bc7ee4767c95687530b470e6b82
