### ISSUE TITLE
[Bug]Classic - Dog Tag Error 

### ISSUE THREAD

**Issue by amey1956** [ascott18/TellMeWhen#1752]
**What version of TellMeWhen are you using?  8.7.1 classic

**What steps will reproduce the problem?**
when logging into a hunter with or without a pet summoned, with no profile loaded i get this error, but not every time:
`LibDogTag-3.0-20190625235144.20190625: Error with code "[THICKOUTLINE]  [HappyText] " (Base;Stats;TMW;Unit). [string "local _G = _G;..."]:27: attempt to concatenate local 'arg2' (a nil value)
...ddOns\TellMeWhen\Lib\LibDogTag-3.0\LibDogTag-3.0-20190625235144.lua:301: in function <...ddOns\TellMeWhen\Lib\LibDogTag-3.0\LibDogTag-3.0.lua:287>
...ddOns\TellMeWhen\Lib\LibDogTag-3.0\LibDogTag-3.0-20190625235144.lua:436: in function `AddFontString'
...en\Components\IconModules\IconModule_Texts\Texts.lua:933: in function `OnKwargsUpdated'
...en\Components\IconModules\IconModule_Texts\Texts.lua:887: in function `func'
TellMeWhen\TellMeWhen-8.7.1.lua:2695: in function `safecall'
...aceTellMeWhen\Components\Core\IconModule.lua:94: in function `func'
TellMeWhen\TellMeWhen-8.7.1.lua:2695: in function `safecall'
...MeWhen\Components\Core\BaseClasses\IconComponent.lua:213: in function `ImplementIntoIcon'
...rfaceTellMeWhen\Components\Core\IconView.lua:280: in function `func'
TellMeWhen\TellMeWhen-8.7.1.lua:2695: in function `safecall'
...MeWhen\Components\Core\BaseClasses\IconComponent.lua:213: in function `ImplementIntoIcon'
TellMeWhen\Components\Core\Icon.lua:996: in function `func'
TellMeWhen\TellMeWhen-8.7.1.lua:2695: in function `safecall'
TellMeWhen\Components\Core\Group-Group.lua:497: in function `func'
TellMeWhen\TellMeWhen-8.7.1.lua:2695: in function `safecall'
TellMeWhen\TellMeWhen-8.7.1.lua:2656: in function <TellMeWhen\TellMeWhen.lua:2613>`
 

**Additional Info**
the only addon i use that utilizes dog tags is luna unit frames. in order to check if it was a conflict with the built in pet happiness indicators in luna i disabled both the coloring of the health bars and the happiness indicator and still get the error intermittently. with luna disabled completely i am still getting the above lua error.

**Comment by ascott18** [comment]
Will be fixed in the next version of LibDogTag-Unit-3.0
