### ISSUE TITLE
Constant errors _AzeriteEmpoweredItem.IsPowerSelect...

### ISSUE THREAD

**Issue by Sharfus** [ascott18/TellMeWhen#1754]
**What version of TellMeWhen are you using? **
8.7.2

**What steps will reproduce the problem?**
1.  Log in to character that is 110+ but has only one azerite trait on his single item
2. Have bugsack enabled to capture the frequent errors.
3. Open TMW options profile with /tmw  - error popup occured here 1 error
4. Have TMW profile for mage arcane selected
4. Close TMW options window - continual string of errors occurs here

**What do you expect to happen? What happens instead?**
I expect to get either no errors, or a single error that can be ignored.  I get the error below when I open the TMW options window with /tmw.  I get a continuous string of that error when I exit the options window sometimes followed by the WoW "High number of addon errors" option to disable all of my addons or ignore being slowed down.  

**Screenshots and Export Strings**
3x [string "return C_AzeriteEmpoweredItem.IsPowerSelect..."]:1: bad argument #1 to 'IsPowerSelected' (Usage: local isSelected = C_AzeriteEmpoweredItem.IsPowerSelected(azeriteEmpoweredItemLocation, powerID))
[C]: in function `IsPowerSelected'
[string "return C_AzeriteEmpoweredItem.IsPowerSelect..."]:1: in function `LF_0000021C91485918'
[string "Condition_LUA_COUNTER"]:3: in function `CheckFunction'
...eWhen\Components\Core\Conditions\ConditionObject.lua:265: in function <...eWhen\Components\Core\Conditions\ConditionObject.lua:259>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...eWhen\Components\Core\Conditions\ConditionObject.lua:234: in function `RegisterForUpdating'
...eWhen\Components\Core\Conditions\ConditionObject.lua:318: in function `DeclareExternalUpdater'
TellMeWhen\Components\Core\Icon.lua:1021: in function <TellMeWhen\Components\Core\Icon.lua:907>
(tail call): ?
...
(tail call): ?
TellMeWhen\TellMeWhen-8.7.2.lua:2763: in function `UpdateNormally'
TellMeWhen\TellMeWhen-8.7.2.lua:2904: in function `Update'
TellMeWhen\TellMeWhen-8.7.2.lua:3032: in function `LockToggle'
TellMeWhen\TellMeWhen-8.7.2.lua:3137: in function `?'
Ace3\AceConsole-3.0\AceConsole-3.0-7.lua:94: in function `?'
FrameXML\ChatFrame.lua:4839: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4502: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4538: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

**Additional Info**
If I can help narrow down the cause, please let me know what information to retrieve or what test to perform.  I do have characters 120 on down, and can make a special one if needed. 

I loaded the bugsack addon to help identify which addon was causing the Blizzard 'High number of addon errors' message.  I then ran TMW and BugGrabber/BugSack only.  When TMW gets closed I cannot close the bugsack window due to the rapid errors incoming.  I had to deselect the tmw addon to have it stop.

**Comment by ascott18** [comment]
This is an error coming from custom Lua code in one of your conditions. It is not code that is included with TMW.

**Comment by Sharfus** [comment]
Thanks.  I'll see if I can chase it down, not that I'm fluent in this at all.  Imported conditions.  Will go back to empty and try to sneak up on it and then pick on the conditions author.


Sent from Yahoo Mail for iPhone


On Friday, December 6, 2019, 11:01 PM, Andrew Scott <notifications@github.com> wrote:


This is an error coming from custom Lua code in one of your conditions. It is not code that is included with TMW.
