### ISSUE TITLE
[Bug] Retail Version 8.7.3-classic.zip Loads As Classic

### ISSUE THREAD

**Issue by JackJack58** [ascott18/TellMeWhen#1757]
**What version of TellMeWhen are you using? ** 

8.7.3-classic.zip

**What steps will reproduce the problem?**
1. Downloading 8.7.3-classic.zip Retail Version is loading as Classic and doesn't load. It begins prompting to exit the game.
2. 
3.

**What do you expect to happen? What happens instead?**
The download somehow is registering as a classic version of the addon in current retail WOW.

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
"8.7.3-classic", as the name would suggest, is indeed for classic. It is not a bug that trying to load this on the retail WoW client triggers a message telling you that it is for classic.

**Comment by JackJack58** [comment]
There is a section for classic wow addons and it is not on retail WoW. I will download an older version but my twitch will keep telling me to download this classic version.

**Comment by ascott18** [comment]
You didn't mention that you were referring to the Twitch App. You'll have to contact Twitch support if the app is not functioning correctly, or stop using it.
