### ISSUE TITLE
abilities hide for the global cd duration [Bug]

### ISSUE THREAD

**Issue by anianiani123** [ascott18/TellMeWhen#1759]
TellMeWhen v8.7.3

**What steps will reproduce the problem?**

Icon Type
Spell Cooldown
Thunder Clap
Ready 100%
Not Ready: 100%
Duration Requirements
"checkmark at" Maximum
"choosing time" 1 Second
Duration > 1: hidden

**What do you expect to happen? What happens instead?**

Now. start a fight and use any ability that causes a global cooldown. The Thunderclap icon will hide each time for the duration of the global cooldown. I don't want the icon to hide. I didn't tell the icon to hide. I have "Don't ignore GCD" NOT checked. The icon should stay visible, because it is ready. The icon should only be hidden when its cooldown is over 1 second.

I have this bug since months btw. I made a github account to report this. I love this addon so so much. Please fix this or tell me what I am doing wrong. Thank you very much.

**Screenshots and Export Strings**

^1^T^SVersion^N87302 ^SNumGroups^N14 ^SGroups^T ^N1^T ^SGUID^STMW:group:1T=KQNCJT_uk ^SPoint^T ^Sy^F4697510421463040 ^f-48^Sx ^F6094642894470589^f-54 ^Spoint^SBOTTOM ^SrelativePoint^SBOTTOM ^t^SScale^F4903592079130624 ^f-50^SEnabledSpecs ^T^N72^b ^N71^b ^t^SColumns^N3 ^SIcons^T ^N1^T ^SType^Sreactive ^SShowTimerText^B ^SName^SVictory~`Rush ^SEnabled^B ^SManaCheck^B ^SStates^T ^N2^T ^SAlpha^N0.2 ^t^N4^T ^SAlpha^N0.2 ^t^t^t^N2^T ^SType^Scooldown ^SName^STaunt ^SShowTimerText^B ^SEnabled^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N3^T ^SType^Scooldown ^SShowTimerText^B ^SName^SShield~`Block ^SEnabled^B ^SManaCheck^B ^SStackMax^N1 ^SStates^T ^N2^T ^SAlpha^N0.2 ^t^N4^T ^SAlpha^N0.2 ^t^N101^T ^SAlpha^N0.2 ^t^t^t^t^SSettingsPerView^T ^Sicon^T ^SSpacingY^N-0.5 ^SSpacingX^N-0.5 ^SBorderInset^b ^t^t^t^N2^T ^SGUID^STMW:group:1T=v0YY4r_yB ^SScale^F7808885662416896 ^f-50^SRows ^N2^SPoint ^T^Sy^F5750398011781143 ^f-51^Sx ^F-7126038667342544^f-47 ^Spoint^SRIGHT ^SrelativePoint^SRIGHT ^t^SColumns^N2 ^SIcons^T ^N2^T ^SType^Scooldown ^SConditions^T ^N1^T ^SType^SCOMBAT ^t^Sn^N1 ^t^SName^SThunder~`Clap ^SStates^T ^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^SDurationMaxEnabled^B ^SDurationMax^N1 ^t^N3^T ^SType^Sbuff ^SName^SBattle~`Shout ^SEnabled^B ^SStates^T ^N1^T ^SAlpha^N0 ^t^N2^T ^SAlpha^N1 ^t^t^t^t^SSettingsPerView^T ^Sicon^T ^SBorderInset^b ^t^t^t^N3^T ^SGUID^STMW:group:1T_CuvEKNAme ^SScale^F6530106394673152 ^f-51^SRows ^N2^SPoint ^T^Sy^F5099631566389247 ^f-52^Sx ^F-7865387688527436^f-46 ^Spoint^SBOTTOM ^SrelativePoint^SBOTTOM ^t^SColumns^N3 ^SIcons^T ^N1^T ^SType^Scooldown ^SShowTimerText^B ^SName^SRallying~`Cry ^SEnabled^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N2^T ^SType^Scooldown ^SName^SLast~`Stand ^SShowTimerText^B ^SEnabled^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N3^T ^SUnit^SÅni ^SOnlyMine^B ^SType^Scooldown ^SShowTimerText^B ^SEnabled^B ^SManaCheck^B ^SName^SAvatar ^SEvents^T ^N1^T ^SType^SSound ^SSound^SChimes ^SEvent^SOnAlphaInc ^t^Sn^N1 ^t^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N5^T ^SType^Scooldown ^SName^SShield~`Wall ^SShowTimerText^B ^SEnabled^B ^SManaCheck^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N6^T ^SType^Scooldown ^SShowTimerText^B ^SEnabled^B ^SName^SDemoralizing~`Shout ^SEvents^T ^N1^T ^SType^SSound ^SSound^SCat ^SEvent^SOnAlphaInc ^t^Sn^N1 ^t^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^t^t^N4^T ^SGUID^STMW:group:1T_bYMH7B_Wm ^SScale^F6569864906932225 ^f-51^SRows ^N3^SPoint ^T^Sy^F6194982981468159 ^f-47^Sx ^F7856236707398082^f-46 ^Spoint^SBOTTOM ^SrelativePoint^SBOTTOM ^t^SColumns^N3 ^SIcons^T ^N1^T ^SType^Scooldown ^SName^SPummel ^SShowTimerText^B ^SEnabled^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N2^T ^SType^Scooldown ^SShowTimerText^B ^SName^SSpell~`Reflection ^SEnabled^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N3^T ^SType^Scooldown ^SShowTimerText^B ^SName^SHeroic~`Leap ^SEnabled^B ^SManaCheck^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N4^T ^SType^Scooldown ^SName^SShockwave ^SShowTimerText^B ^SEnabled^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N5^T ^SType^Scooldown ^SShowTimerText^B ^SName^SStorm~`Bolt ^SEnabled^B ^SManaCheck^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^N4^T ^SAlpha^N0.3 ^t^t^t^N6^T ^SType^Scooldown ^SName^SCharge ^SEnabled^B ^SManaCheck^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^SRangeCheck^B ^SShowTimerText^B ^t^N7^T ^SType^Scooldown ^SShowTimerText^B ^SName^SIntimidating~`Shout ^SEnabled^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N8^T ^SType^Scooldown ^SShowTimerText^B ^SEnabled^B ^SManaCheck^B ^SDurationMaxEnabled^B ^SName^SRevenge ^SStates^T ^N2^T ^SAlpha^N1 ^t^N4^T ^SAlpha^N1 ^t^N100^T ^SAlpha^N0.2 ^t^t^SDurationMax^N1 ^t^N9^T ^SType^Scooldown ^SName^SBerserker~`Rage ^SShowTimerText^B ^SEnabled^B ^SManaCheck^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^N4^T ^SAlpha^N0.3 ^t^t^t^t^t^N5^T ^SGUID^STMW:group:1U05DMwGlzqP ^SScale^F4804296730214400 ^f-50^SRows ^N2^SPoint ^T^Sy^F8605825434124289 ^f-48^Sx ^F-7220309421001718^f-56 ^Spoint^SBOTTOM ^SrelativePoint^SBOTTOM ^t^SEnabledSpecs^T ^N73^b ^N71^b ^t^SColumns^N3 ^SIcons^T ^N1^T ^SType^Scooldown ^SName^SBloodthirst ^SShowTimerText^B ^SEnabled^B ^SManaCheck^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N2^T ^SType^Scooldown ^SName^SRaging~`Blow ^SShowTimerText^B ^SEnabled^B ^SManaCheck^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N3^T ^SType^Sreactive ^SShowTimerText^B ^SEnabled^B ^SManaCheck^B ^SName^SExecute ^SCooldownCheck^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^N4^T ^SAlpha^N0.3 ^t^t^t^N4^T ^SType^Sbuff ^SShowTimerText^B ^SName^SWhirlwind ^SEnabled^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N5^T ^SType^Scooldown ^SName^SRecklessness ^SShowTimerText^B ^SEnabled^B ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^N6^T ^SType^Sbuff ^SName^SVictorious ^SShowTimerText^B ^SEnabled^B ^SCustomTex^S106797 ^SStates^T ^N2^T ^SAlpha^N0.3 ^t^t^t^t^t^N6^T ^SGUID^STMW:group:1U0hHZFKhACQ ^SScale^F4983466659676160 ^f-50^SPoint ^T^Sy^F6472213456748544 ^f-47^Sx ^F-5616476860106224^f-59 ^Spoint^SBOTTOM ^SrelativePoint^SBOTTOM ^t^SEnabledSpecs^T ^N72^b ^N71^b ^t^SColumns^N3 ^SIcons^T ^N1^T ^SType^Scooldown ^SName^SShield~`Slam ^SEnabled^B ^SShowTimerText^B ^SStates^T ^N2^T ^SAlpha^N0.2 ^t^N4^T ^SColor^Sffffffff ^SAlpha^N1 ^t^N100^T ^SAlpha^N0.2 ^t^t^SDurationMax^N1 ^t^N2^T ^SType^Sbuff ^SShowTimerText^B ^SInvertTimer^B ^SName^SIgnore~`Pain ^SDurationMaxEnabled^B ^SCustomTex^S193786 ^SStates^T ^N2^T ^SAlpha^N1 ^t^N100^T ^SAlpha^N0.2 ^t^t^SEnabled^B ^SDurationMax^N2 ^t^N3^T ^SType^Scooldown ^SShowTimerText^B ^SName^SThunder~`Clap ^SStates^T ^N2^T ^SAlpha^N0.2 ^t^N4^T ^SColor^Sffffffff ^SAlpha^N0 ^t^N100^T ^SAlpha^N0.2 ^t^t^SEnabled^B ^SDurationMax^N1 ^t^t^SSettingsPerView^T ^Sicon^T ^SBorderInset^b ^SSpacingX^N-0.5 ^SSpacingY^N-0.5 ^t^t^t^N7^T ^SGUID^STMW:group:1U0n93eOgOaF ^SScale^F8436037860720641 ^f-52^SRows ^N2^SPoint ^T^Sy^F-5761415050287528 ^f-47^Sx ^F-6952888661347323^f-56 ^t^SColumns^N5 ^SIcons^T ^N1^T ^SShowTimer^B ^SType^Scooldown ^SName^SShield~`Slam ^SShowTimerText^B ^SConditions^T ^N1^T ^SType^SCOMBAT ^t^Sn^N1 ^t^SDurationMin^N1 ^SEnabled^B ^SDurationMaxEnabled^B ^SStates^T ^N2^T ^SAlpha^N1 ^t^N4^T ^SColor^Sffffffff ^SAlpha^N0 ^t^t^SDurationMax^N1 ^t^N5^T ^SShowTimer^B ^SType^Scooldown ^SConditions^T ^N1^T ^SType^SCOMBAT ^t^Sn^N1 ^t^SName^SThunder~`Clap ^SShowTimerText^B ^SEnabled^B ^SDurationMin^N1 ^SDurationMaxEnabled^B ^SStates^T ^N2^T ^SAlpha^N1 ^t^N4^T ^SColor^Sffffffff ^SAlpha^N0 ^t^t^SDurationMax^N1 ^t^N6^T ^SType^Sbuff ^SConditions^T ^N1^T ^SType^SCOMBAT ^t^Sn^N1 ^t^SShowTimerText^B ^SName^SIgnore~`Pain ^SInvertTimer^B ^SDurationMaxEnabled^B ^SCustomTex^S193786 ^SStates^T ^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^SDurationMax^N2 ^t^N10^T ^SShowTimer^B ^SType^Sbuff ^SConditions^T ^N1^T ^SType^SCOMBAT ^t^Sn^N1 ^t^SShowTimerText^B ^SName^SRevenge! ^SEnabled^B ^t^t^t^N8^T ^SGUID^STMW:group:1U0uCjdIBraD ^SScale^N1.7491694688797 ^SPoint^T ^Sy^F-7169052197119807 ^f-46^Sx ^F-5659282395268766^f-48 ^t^SColumns^N6 ^SIcons^T ^N1^T ^SType^Scooldown ^SConditions^T ^N1^T ^SType^SCASTING ^SUnit^Starget ^SLevel^N1 ^t^Sn^N1 ^t^SName^SSpell~`Reflection ^SShowTimerText^B ^SEnabled^B ^t^N2^T ^SType^Scooldown ^SConditions^T ^N1^T ^SType^SCASTING ^SUnit^Starget ^t^Sn^N1 ^t^SShowTimerText^B ^SName^SPummel ^SEnabled^B ^t^N3^T ^SType^Scooldown ^SShowTimerText^B ^SName^SStorm~`Bolt ^SEnabled^B ^SManaCheck^B ^SConditions^T ^N1^T ^SType^SCASTING ^SUnit^Starget ^SLevel^N1 ^t^Sn^N1 ^t^SStates^T ^N4^T ^SAlpha^N0.2 ^t^t^t^N4^T ^SType^Scooldown ^SConditions^T ^N1^T ^SType^SCASTING ^SUnit^Starget ^SLevel^N1 ^t^Sn^N1 ^t^SShowTimerText^B ^SName^SShockwave ^SEnabled^B ^t^N5^T ^SType^Scooldown ^SConditions^T ^N1^T ^SType^SCASTING ^SUnit^Starget ^SLevel^N1 ^t^Sn^N1 ^t^SName^SIntimidating~`Shout ^SShowTimerText^B ^SEnabled^B ^t^t^SSettingsPerView^T ^Sicon^T ^SBorderInset^b ^t^t^t^N9^T ^SPoint^T ^Sy^F-6900925688665614 ^f-46^Sx ^F-5463574027065362^f-45 ^Spoint^SRIGHT ^SrelativePoint^SRIGHT ^t^SScale^F6258551181803520 ^f-51^SEnabledSpecs ^T^N72^b ^N71^b ^t^SEnabled^b ^SGUID^STMW:group:1U0_tVZ03Sye ^SColumns^N1 ^SIcons^T ^N1^T ^SName^SShield~`Block ^SShowTimerText^B ^SEnabled^B ^SStates^T ^N2^T ^SAlpha^N0.2 ^t^N4^T ^SAlpha^N1 ^t^t^t^t^SSettingsPerView^T ^Sicon^T ^SSpacingY^N-0.5 ^SSpacingX^N-0.5 ^SBorderInset^b ^t^t^t^N10^T ^SPoint^T ^Sy^F-5998485108552948 ^f-46^Sx ^F5921377458585601^f-45 ^Spoint^SLEFT ^SrelativePoint^SLEFT ^t^SScale^F6598442545577985 ^f-51^STextureName ^SElvUI~`Blank^SEnabledSpecs ^T^N72^b ^N71^b ^t^SGUID^STMW:group:1U11VeW9auqE ^SColumns^N1 ^SIcons^T ^N1^T ^SType^Sbuff ^SShowTimerText^B ^SEnabled^B ^SName^SIgnore~`Pain ^SCustomTex^S193786 ^SStates^T ^N100^T ^SAlpha^N0.2 ^t^t^SDurationMax^N2 ^t^t^SSettingsPerView^T ^Sbarv^T ^SSpacingY^N-2 ^SSizeX^N11.3 ^SIcon^b ^t^Sicon^T ^SSpacingY^N-0.5 ^SSpacingX^N-0.5 ^SBorderInset^b ^t^Sbar^T ^SSizeY^N19 ^SIcon^b ^t^t^t^N11^T ^SGUID^STMW:group:1U12JU7HkrWu ^SScale^F4863953289084928 ^f-51^SPoint ^T^Sy^F-7779120467341891 ^f-47^Sx ^F-6401626866267566^f-46 ^t^SColumns^N1 ^SIcons^T ^N1^T ^SType^Sbuff ^SName^SSpell~`Reflection ^SShowTimerText^B ^SEnabled^B ^SCustomTex^S215785 ^t^t^SSettingsPerView^T ^Sicon^T ^SBorderInset^b ^t^t^t^N12^T ^SPoint^T ^Sy^F7698044126657595 ^f-47^Sx ^F-5597129161329570^f-50 ^t^SScale^F8843097144295424 ^f-52^SRows ^N2^SEnabled ^b^SGUID ^STMW:group:1U12x9ohFQ40^SColumns ^N5^SSettingsPerView ^T^Sicon^T ^SBorderInset^b ^t^t^t^N13^T ^SScale^F7808885662416896 ^f-50^SPoint ^T^Sy^F5044853553496066 ^f-45^SrelativePoint ^SBOTTOMLEFT^Sx ^F7242611404308479^f-45 ^t^SEnabled^b ^SGUID^STMW:group:1U12yUPIvPaG ^SColumns^N1 ^SIcons^T ^N1^T ^SType^Scooldown ^SConditions^T ^N1^T ^SType^SCOMBAT ^t^Sn^N1 ^t^SName^SThunder~`Clap ^SEnabled^B ^SDurationMaxEnabled^B ^SStates^T ^N2^T ^SAlpha^N1 ^t^t^SDurationMax^N1 ^t^t^SSettingsPerView^T ^Sicon^T ^SBorderInset^b ^t^t^t^N14^T ^SGUID^STMW:group:1U1f6XkTwt0k ^SScale^F8677495016521728 ^f-50^SPoint ^T^Sy^F-8666405047239364 ^f-48^Spoint ^STOP^SrelativePoint ^STOP^Sx ^F4579563234604696^f-51 ^t^SColumns^N1 ^SIcons^T ^N1^T ^SType^Scooldown ^SName^SThunder~`Clap ^SStates^T ^N2^T ^SAlpha^N1 ^t^N100^T ^SAlpha^N0.01 ^t^t^SEnabled^B ^SDurationMaxEnabled^B ^SDurationMax^N1 ^t^t^SSettingsPerView^T ^Sicon^T ^SBorderInset^b ^t^t^t^t^t^N87302^S~`~| ^Sprofile^SÂnî~`-~`Silvermoon ^^

**Comment by anianiani123** [comment]
![TMW](https://user-images.githubusercontent.com/59297133/71535948-ae5d8e00-290a-11ea-9fd9-8fadd61edb24.PNG)

**Comment by anianiani123** [comment]
I actually have no idea how gitup works. Will you message me here? Will you E-Mail me? Will you just do your thing and never speak to me? Should I refresh the page every hour to see if you have answered? Should I just leave and hope it works in the next iteration?

**Comment by anianiani123** [comment]
still refreshing ^.^

**Comment by ascott18** [comment]
You'll get an email when I respond.

**Comment by anianiani123** [comment]
:D you are actually working wuhu x)

**Comment by ascott18** [comment]
Pasting the response I left on Discord: 

Its actually working as intended, although perhaps not very intuitively. The duration requirements setting (and the corresponding opacity level) are not related to the "Don't ignore GCD" setting. The duration requirements are affected by GCDs, as they don't have their own version of a setting that ignores the GCD. 

The timer sweep does have a setting for that, as does the timer bar overlay, as does the main Spell Cooldown functionality ("Don't ignore GCD" affects whether its classified as Ready or Not Ready). However, the duration requirements supersede the ready/not ready states, and the duration requirements don't care about GCD.

My suggestion would be to increase your max duration requirement to just a hair over your GCD
you can enter fractional amounts there - 0:01.5 for example.

Do note that if you don't have any duration requirements configured, a spell that has a cooldown of the GCD or less, while you're on the GCD, will show as usable. that's generally the normal way of showing things that are just coming off cooldown and are available on the next GCD, rather than explicitly configuring a max duration of 1 second.

**Comment by anianiani123** [comment]
Thank you for helping me!
