### ISSUE TITLE
Totem: Multiple bugs

### ISSUE THREAD

**Issue by Jaqy** [ascott18/TellMeWhen#1761]
(WOW Classic)
**issue 1:** 
If I check water totems - It shows the earth totems 

and If I check earth totems - It shows me the water totems
I leave "What to track" Blank here (where you input the names of the totems)

**issue 2**
The **Fire Resistance Totem** is shown together with the fire totems - however, it is a water totem.

**issue 3**
If I don't check any element (Fire, Earth, Water, Air) and add all the totems to the "What to track" they just don't show

Let me know if you need more details

**Comment by ascott18** [comment]
1. Fixed.
2. Fixed.
3. Working as intended.
