### ISSUE TITLE
TellMeWhen error info below

### ISSUE THREAD

**Issue by dwj57** [ascott18/TellMeWhen#1763]
**What version of TellMeWhen are you using? 8.3 according to Twitch

**What steps will reproduce the problem?**
1. See error message when first entering into the game
2. When I close out error, TMW still works but am unable to access options
3. below is the error info seen when either 1st entering the game or attempting to access options

Message: TellMeWhen: TellMeWhen_Options could not be loaded: Out of date
Time: Fri Feb  7 14:44:06 2020
Count: 1
Stack: TellMeWhen: TellMeWhen_Options could not be loaded: Out of date
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:3256: in function `LoadOptions'
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:3252: in function `LoadOptions'
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:2891: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2888>
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:707: in function `func'
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:2808: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2807>
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:841: in function `Fire'
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:2758: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2726>

Locals: <none>

**What do you expect to happen? What happens instead?**

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
Enable loading of out-of-date addons at the character selection screen, or download the latest alpha version. 

There was a mishap where the main addon was flagged for 8.3 but the options were flagged for 8.2.

**Comment by dwj57** [comment]
HI Andrew,
As a rule, i generally will not load out of date addons due to issues in the past. I to love tellmewhen and will continue to use as long as humanly possible :) I would also like to donate so if there is a preferred link please let me know. Thanks! Dave
    On Saturday, February 8, 2020, 10:28:06 PM PST, Andrew Scott <notifications@github.com> wrote:  
 
 
Enable loading of out-of-date addons at the character selection screen, or download the latest alpha version.

There was a mishap where the main addon was flagged for 8.3 but the options were flagged for 8.2.

**Comment by ascott18** [comment]
You can donate via PayPal: https://www.paypal.com/cgi-bin/webscr?return=https://github.com/ascott18/TellMeWhen&business=ascott18%40msn.com&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted&cancel_return=https://github.com/ascott18/TellMeWhen&lc=US&item_name=In%20Support%20of%20Development%20of%20TellMeWhen&cmd=_donations&rm=1&no_shipping=1&currency_code=USD

Thank you!
