### ISSUE TITLE
Resize Config Window Problem

### ISSUE THREAD

**Issue by tazpraxis** [ascott18/TellMeWhen#1764]
8.7.2 release version is the last release version that resizing the config window works.
Please fix this... the small window is a pain when there is a long list of spells.

**Comment by ascott18** [comment]
Thanks for the report. Fixed.

**Comment by tazpraxis** [comment]
WOW that was fast!!! TY!!! The alpha works great! Cant believe you fixed it that fast!

Thanks a million!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
