### ISSUE TITLE
[Bug] UnitAttributes > UnitRace > Voldunai Race Option Missing

### ISSUE THREAD

**Issue by StreetLight777** [ascott18/TellMeWhen#1768]
**What version of TellMeWhen are you using? **

8.7.4

**What steps will reproduce the problem?**
1. Go to UnitAttributes > UnitRace > Voldunai Race Option Missing

**What do you expect to happen? What happens instead?**
When I want to set a condition where UnitRace = Voldunai, I expect this race option to be available in the options. This is one of the only (if not THE only) race missing in the list of races within the app.

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
Addressed as part of #1787
