### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Kaynautic** [ascott18/TellMeWhen#1769]
**What version of TellMeWhen are you using? **
8.7.4

Hi!
Im getting the following errors, only when i switch to Brewmaster spec.  I do NOT get these errors when in windwalker spec

*******************
****ERROR 1******
*******************
Message: Interface\AddOns\TellMeWhen\TellMeWhen.lua:2721: [string "Condition_SPELLCHARGES_STAGGER_BUFFDUR_SPEL..."]:4: attempt to perform arithmetic on a nil value
Time: Tue Mar  3 19:26:16 2020
Count: 1
Stack: Interface\AddOns\TellMeWhen\TellMeWhen.lua:2721: [string "Condition_SPELLCHARGES_STAGGER_BUFFDUR_SPEL..."]:4: attempt to perform arithmetic on a nil value
[string "=[C]"]: ?
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:2721: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2710>

Locals: (*temporary) = false
(*temporary) = "[string "Condition_SPELLCHARGES_STAGGER_BUFFDUR_SPEL..."]:4: attempt to perform arithmetic on a nil value"

************************
*******ERROR 2********
************************
Message: [string "Condition_SPELLCHARGES_STAGGER_BUFFDUR_SPEL..."]:4: attempt to perform arithmetic on a nil value
Time: Tue Mar  3 19:26:16 2020
Count: 6
Stack: [string "Condition_SPELLCHARGES_STAGGER_BUFFDUR_SPEL..."]:4: attempt to perform arithmetic on a nil value
[string "Condition_SPELLCHARGES_STAGGER_BUFFDUR_SPELLCHARGES_STAGGER_ABS_THREATSCALED"]:4: in function `CheckFunction'
[string "@Interface\AddOns\TellMeWhen\Components\Core\Conditions\ConditionObject.lua"]:265: in function `Check'
[string "@Interface\AddOns\TellMeWhen\Components\Core\Icon.lua"]:756: in function <Interface\AddOns\TellMeWhen\Components\Core\Icon.lua:727>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:2681: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2643>

Locals: <none>

If you have any idea what is causing this, it would be greatly appreciated!  Let me know if any other information required that would help
Thanks very much!!

**Comment by ascott18** [comment]
What were you doing in game when this error happened?


Additionally, please post the export string(s) of the icon you're having trouble with. 

To get an export string, open the icon editor, and click the button labeled "Import/Export/Backup". Select the "To String" option for the appropriate export type (icon, group, or profile), and then press CTRL+C to copy it to your clipboard.
