### ISSUE TITLE
TellMeWhen just stopped working 

### ISSUE THREAD

**Issue by Toeclipper** [ascott18/TellMeWhen#1773]
**What version of TellMeWhen are you using? 7.0.2 for MoP

Just logged in and noticed no TMW icons showing. /tmw does nothing.
Addon shows in character login screen and is checked.
Addon does not appear in Interface/Addons screen.

Uninstalled addon and all references to it in WTF folder and re-installed.
Still nothing.
Can you advise please?

**Comment by ascott18** [comment]
I cant help you with old game clients, sorry. You're free to use old versions of TMW with old WoW clients as you please, but I can't help you.
