### ISSUE TITLE
[Bug]Problems downloading from curseforge.com

### ISSUE THREAD

**Issue by jimkillian** [ascott18/TellMeWhen#1774]
**What version of TellMeWhen are you using? **
8.7.4

**What steps will reproduce the problem?**
1. Go to the proper page: https://www.curseforge.com/wow/addons/tellmewhen
2. Click the "Download" button and it will install the Retail version.
2. Click the "Twitch Install" button and it will install the Classic version via the Twitch app.

**What do you expect to happen? What happens instead?**
I expected to install the Retail version of the addon when I clicked on the "Twitch Install" button, but it installed the Classic version. I only found out because when I went into WoW I got the notification that I was running the wrong version.

I finally figured out what was happening and downloaded the zip file and installed it myself and it works correctly now, but Twitch keeps telling me it needs to be updated because it's not the same filename it's looking for.

**Screenshots and Export Strings**
![image](https://user-images.githubusercontent.com/34056285/77148839-969b2f00-6a4d-11ea-86ab-b60c503c3c74.png)

**Comment by ascott18** [comment]
If you're having trouble with the Twitch app, you need to contact Twitch support. I can't do anything about it.
