### ISSUE TITLE
[Bug] TellMeWhen DK Frost Empower Rune Weapons

### ISSUE THREAD

**Issue by ginal8** [ascott18/TellMeWhen#1775]
**What version of TellMeWhen are you using? **
8.7.4

**What steps will reproduce the problem?**
1. Can't disable "empower rune weapons" in Frost 
2.
3.

**What do you expect to happen? What happens instead?**
I tried to hide it, disable it, remove all its conditions etc, nothing works. The 2nd spell/ability on the single target rotation is always "empower rune weapons"

**Screenshots and Export Strings**
I copied the string from https://www.chesder.com/death-knight.html

**Additional Info**

**Comment by ascott18** [comment]
Sounds like question for Chesder. Not sure what you want me to do about it.
