### ISSUE TITLE
Begginer's Luck

### ISSUE THREAD

**Issue by Crossbow013** [ascott18/TellMeWhen#1776]
I am a complete novice trying to use TellMeWhen and having difficulty.  I'm not trying to do anything extraordinary, pretty much using the defaults, but it isn't working for me.

I clicked on the box to set up the first icon.  I selected Spell Cooldown from the main window.  I selected Apotheosis for the spell to track.  My problem is with Opacity & Color.  I want the spell to light up when it is 100% Ready, and to be Hidden when it is Not Ready.  I select these options, however the icon stays lit the entire time. 

I also tried to attach a sound notification.  I selected TMW - Ping 4, which works when I test it on the notifications page, but it doesn't make any sound when the spell is off cooldown.

I know I am a novice... but what I'm trying to do does not seem difficult with the helpful interface you have set up, so not sure why it isn't working.  Can you offer any suggestions or advice to get it to work the way I want it to?

Thank you in advance for your help!

**Comment by ascott18** [comment]
Sounds like you never left configuration mode.

In the future, please only use the GitHub issue tracker for bug reports and feature requests. The TellMeWhen community Discord server is a great place to ask questions or otherwise discuss TellMeWhen: https://discord.gg/NH7RmcP
