### ISSUE TITLE
[Bug] Auras show up on map and all windows of the game

### ISSUE THREAD

**Issue by pedromss** [ascott18/TellMeWhen#1777]
**What version of TellMeWhen are you using? **
8.7.4

**What steps will reproduce the problem?**
1. Have a group configured

**What do you expect to happen? What happens instead?**
- Expect to open map and not have the auras over the map, or auction house window
- Have auras over map
![imagem](https://user-images.githubusercontent.com/10366849/77908205-f16d2b80-7282-11ea-8bd7-4a1ca313cd63.png)

Is there a way to disable this? Or is this considered a feature?

**Comment by ascott18** [comment]
Change the frame strata setting of the group to something lower than what you have it set at now.
