### ISSUE TITLE
On Condition Set Passing in Notifications rule doesn't seem to work.[Bug]

### ISSUE THREAD

**Issue by PaulKBSR** [ascott18/TellMeWhen#1778]
**What version of TellMeWhen are you using? **      **8.7.4**

**What steps will reproduce the problem?**
1. Set Notification to flash when conditions are met.
2.
3.

**What do you expect to happen? What happens instead?**
Notification occurs expected.  Nothing happens.

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
Please post the export string(s) of the icons, groups, or profiles you're having trouble with. 

To get an export string, open the icon editor, and click the button labeled "Import/Export/Backup". Select the "To String" option for the appropriate export type (icon, group, or profile), and then press CTRL+C to copy it to your clipboard.

Additionally, if applicable, add screenshots to help explain your problem. You can paste images directly into GitHub issues, or you can upload files as well.

**Comment by jhdub23** [comment]
A simple spell cooldown check works for me.  However, a lua trigger does not work.

^1^T^SShowTimer^B ^SType^Scooldown ^SName^SRushing~`Jade~`Wind ^SEnabled^B ^SManaCheck^B ^SShowTimerTextnoOCC^B ^SClockGCD^B ^SEvents^T ^N1^T ^SType^SAnimations ^SDuration^N2 ^SAnimation^SICONSHAKE ^SEvent^SOnCondition ^SOnConditionConditions^T ^N1^T ^SType^SLUA ^SOperator^S< ^SAndOr^SOR ^SName^S1~`<~`2 ^SLevel^N2 ^t^Sn^N1 ^t^t^Sn^N1 ^t^SStates^T ^N2^T ^SColor^Sffffffffd ^SAlpha^N1 ^t^N3^T ^SColor^Sffff0000 ^t^t^SRangeCheck^B ^t^N87502^S~`~| ^Sicon^^

**Comment by ascott18** [comment]
On Condition Set Passing will trigger when the conditions transition from failing to passing. Since your Lua condition is always true, this state transition never happens. You need to use a condition that can sometimes be true and sometimes be false.

Or perhaps you meant to use While Condition Set Passing as your trigger instead?

**Comment by jhdub23** [comment]
Thank you.  Dumb user error on my part.  Maybe rename it to "On Condition Set Passing Transition", to make it clear that it is only triggered on transition?
