### ISSUE TITLE
Tell me when not working at all[Bug]

### ISSUE THREAD

**Issue by SeaTurtle257** [ascott18/TellMeWhen#1779]
**What version of TellMeWhen are you using? **

v8.7.4

When I updated the addon in the twitch app, and started playing, the game told me Tell me when was for Classic WoW and this is Retail. Addon was working prior to update.
![TME Not Working](https://user-images.githubusercontent.com/63079522/78309845-2646e000-751a-11ea-8abb-d07c143d0e45.PNG)

**What steps will reproduce the problem?**
1. Cannot reproduce problem
2.
3.

**What do you expect to happen? What happens instead?**

**Screenshots and Export Strings**

**Additional Info**

**Comment by SeaTurtle257** [comment]
FIX: If you are playing retail: On the Twitch app, look under versions and make sure the version installed is not the Classic version

**Comment by ascott18** [comment]
If the Twitch app is malfunctioning, you'll need to contact Twitch support about that. I can't help you with it.
