### ISSUE TITLE
Only detect Classic Addon ... doenst work in retail[Bug]

### ISSUE THREAD

**Issue by Bloerk** [ascott18/TellMeWhen#1783]
**What version of TellMeWhen are you using? **

TellMeWhen-8.7.4-classic.zip

**What steps will reproduce the problem?**
1. i logg in and it says only classic downloaded but before it worked well
2.
3.

**What do you expect to happen? What happens instead?**

cant open /tmw  ... it does not open

what can i do?

i downloaded it new allready
theres ONLY this TMW Version to download

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
If the Twitch app is malfunctioning, you'll need to contact Twitch support about that. I can't help you with it.

**Comment by Bloerk** [comment]
Thank you for answering - i deleted ALL ..and installed for new three Times...at third Time IT worked for no reason ...

Have a nice Weekend ;)



Von meinem Samsung Galaxy Smartphone gesendet.



-------- Ursprüngliche Nachricht --------
Von: Andrew Scott <notifications@github.com>
Datum: 25.04.20 08:54 (GMT+01:00)
An: ascott18/TellMeWhen <TellMeWhen@noreply.github.com>
Cc: Bloerk <prelo.m@hotmail.com>, Author <author@noreply.github.com>
Betreff: Re: [ascott18/TellMeWhen] Only detect Classic Addon ... doenst work in retail[Bug] (#1783)


If the Twitch app is malfunctioning, you'll need to contact Twitch support about that. I can't help you with it.
