### ISSUE TITLE
[Bug] Let OmniCC detect charge-type cooldowns

### ISSUE THREAD

**Issue by jcai1** [ascott18/TellMeWhen#1784]
**What version of TellMeWhen are you using? **

v8.7.5 r6 (gdb3d12db)

OmniCC has a separate style for cooldowns with "restoring charges", spells like Conflagrate, Fire Blast, Rune of Power. This is detected as such: https://github.com/tullamods/OmniCC/blob/e80b6f96addbf63699c7bc47277aaaf6a80e5d41/main/core/cooldown.lua#L69-L72

When TMW shows such charge-type cooldowns, OmniCC doesn't detect them as such, instead just showing them as normal cooldowns.

To fix this, one could add after this location: https://github.com/ascott18/TellMeWhen/blob/3b7136a570d87e363c47e5faaf026a29e622ac67/Components/IconModules/IconModule_CooldownSweep/CooldownSweep.lua#L168

the following line:

    icon.chargeCooldown = self.cooldown2

(Note: OmniCC previously used `cooldown:GetDrawEdge()` to detect charge-type cooldowns, which did work with TMW, but this was changed to the current `parent.chargeCooldown` method a good while back.)

**Comment by ascott18** [comment]
Thanks - added that in!
