### ISSUE TITLE
[Bug] Twitch downloads Classic tell me when for current live

### ISSUE THREAD

**Issue by Whiptail** [ascott18/TellMeWhen#1785]
**What version of TellMeWhen are you using? **

It will not start in Live wow to get the version.  it downloads "TellMeWhen-8.7.4-classic.zip"

**What steps will reproduce the problem?**
1. auto updated mod with the twitch app
2.
3.

**What do you expect to happen? What happens instead?**

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
If the Twitch app is malfunctioning, you'll need to contact Twitch support about that. I can't help you with it.

**Comment by Whiptail** [comment]
It was twitch, thank  you.  I had to "rescan for games" to get the option to download the retail addons
