### ISSUE TITLE
PetRemainingTime fail when the duration change

### ISSUE THREAD

**Issue by xXs00kyXx** [ascott18/TellMeWhen#1788]
Hey everyone :)

I'm an elemental shaman and use PetRemainingTime to track my PRIMAL fire elemental.
When you use the Primal elementalist talent as Elemental shaman, your elemental is not a totem but a PET.

In this case, you have to track your Primal Fire elemental with the Unit Condition Icon and track it.

The problem is when you have a proc vision that improve the duration of your Pet remaining time.
So :
1) You have a proc vision that gives you 10,5sec of primal fire elemental
2) After 2 sec, you use your CD Fire elemental
--> It won't update the timer of you Unit Condition  Icon with the text [PetRemainingTime:TMWFormatDuration:Short] : It will finish the first timer given by the proc vision, and after that, give you a shity timer : 
49:17:02:44 !!!

It could be nice that the PetRemainingTime update when the duration of your pet left is modified :)

Thank you a lot !

**Comment by ascott18** [comment]
The `[PetRemainingTime]` tag just directly calls Blizzard's `GetPetTimeRemaining` function. http://wowprogramming.com/docs/api/GetPetTimeRemaining.html

If it is reporting wrong data, its up to Blizzard to fix - I don't have the time to try and figure out workarounds for their mistakes/shortcomings. Sorry.
