### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Razoroth** [ascott18/TellMeWhen#1791]
**What version of TellMeWhen are you using? ** 

v8.7.4

**What steps will reproduce the problem?**
1. Create multiple sound notifications with conditions in a priority list. (I'm using roll the bones buffs and conditions are set to play different sounds for different combinations off buffs or number of buffs. see exported string for details and to crosscheck work.)
2. Uncheck "continue to lower notifications" on every notification event.
3. roll the bones to hear different effects for getting 1, 2, 3, 4, 5, or 6 buffs together. (Two buffs, "Ruthless Precision" and "Broadside" are set up to trigger by themselves with the sound trigger for getting 2 buffs.)

**What do you expect to happen? What happens instead?**
::EXPECTED::
(Numbered lines are the priority set up in the notifications list)
Roll the bones.
1.) All 6 buffs proc = play sound clip 1 (Amazing Roll)
2.) 3, 4, or 5 buffs proc together = play sound clip 2 (Great Roll)
3.) 2 buffs proc together OR Just "Ruthless Precision" OR just "Broadside" proc alone = play sound clip 3 (Good Roll)
4.) 1 buff procs (excluding "Ruthless Precision" and "Broadside") = play sound clip 4 (Bad Roll)
5.) Any buffs expire = play sound clip 5 (Buffs Expired)

::WHAT HAPPENS::
When trigger events occur, sometimes the triggered event does not stop the rest of the list from triggering.
Example: I roll 2 buffs, but those 2 buffs are "Ruthless Precision" and either "Grand Melee', "Skull and Crossbones", "Buried Treasure", or "True Bearing". Good Roll sound plays, but so does Bad Roll from the next event down, despite #3 event having the "Continue to lower notifications" box unchecked.

Also, if a trigger occurs and the same conditions are met when refreshing buffs via roll the bones, the sound is not played. Example: Roll the bones, get only 1 of the 4 bad buffs, sound plays the first time, but if I reroll and get the same buff again, or another of the 4 bad buffs by themselves, no sound is played. This behavior occurs with the other sound notifications too.

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
Please post the export string(s) of the icons, groups, or profiles you're having trouble with. 

To get an export string, open the icon editor, and click the button labeled "Import/Export/Backup". Select the "To String" option for the appropriate export type (icon, group, or profile), and then press CTRL+C to copy it to your clipboard.

Additionally, if applicable, add screenshots to help explain your problem. You can paste images directly into GitHub issues, or you can upload files as well.

**Comment by Razoroth** [comment]
I'm not sure what happened to my original post, but it appears the entire thing got cut off. My original did include a paste of the exported strings. Posting again:

^1^T^SOnlyMine^B ^SType^Sbuff ^SName^S193357;~`193356;~`193358;~`199603;~`199600;~`193359 ^SEnabled^B ^SEvents^T ^N1^T ^SType^SSound ^SSound^Sinterface/addons/metalgroove.mp3 ^SEvent^SOnCondition ^SPassThrough^b ^SOnConditionConditions^T ^N1^T ^SType^SBUFFNUMBER ^SLevel^N6 ^SName^S193357;~`193356;~`193358;~`199603;~`199600;~`193359 ^t^Sn^N1 ^t^t^N2^T ^SType^SSound ^SSound^Sinterface/addons/success2.mp3 ^SEvent^SOnCondition ^SPassThrough^b ^SOnConditionConditions^T ^N1^T ^SType^SBUFFNUMBER ^SLevel^N3 ^SName^S193357;~`193356;~`193358;~`199603;~`199600;~`193359 ^t^N2^T ^SType^SBUFFNUMBER ^SLevel^N4 ^SName^S193357;~`193356;~`193358;~`199603;~`199600;~`193359 ^SAndOr^SOR ^t^N3^T ^SType^SBUFFNUMBER ^SLevel^N5 ^SName^S193357;~`193356;~`193358;~`199603;~`199600;~`193359 ^SAndOr^SOR ^t^Sn^N3 ^t^t^N3^T ^SType^SSound ^SSound^Sinterface/addons/success1.mp3 ^SEvent^SOnCondition ^SPassThrough^b ^SOnConditionConditions^T ^N1^T ^SType^SBUFFNUMBER ^SLevel^N2 ^SName^S193357;~`193356;~`193358;~`199603;~`199600;~`193359 ^t^N2^T ^SType^SBUFFNUMBER ^SAndOr^SOR ^SName^S193357;~`193356 ^SLevel^N1 ^t^Sn^N2 ^t^t^N4^T ^SType^SSound ^SSound^Sinterface/addons/badroll1.mp3 ^SEvent^SOnCondition ^SPassThrough^b ^SOnConditionConditions^T ^N1^T ^SType^SBUFFNUMBER ^SLevel^N1 ^SName^S193358;~`199603;~`199600;~`193359 ^t^N2^T ^SType^SBUFFDUR ^SOperator^S>= ^SLevel^N12 ^SName^SGrand~`Melee ^SPrtsBefore^N2 ^t^N3^T ^SType^SBUFFDUR ^SPrtsAfter^N1 ^SOperator^S< ^SLevel^N12 ^SName^SRuthless~`Precision ^t^N4^T ^SType^SBUFFDUR ^SOperator^S>= ^SLevel^N12 ^SName^SGrand~`Melee ^SPrtsBefore^N1 ^SAndOr^SOR ^t^N5^T ^SType^SBUFFDUR ^SPrtsAfter^N1 ^SOperator^S< ^SLevel^N12 ^SName^SBroadside ^t^N6^T ^SType^SBUFFDUR ^SOperator^S>= ^SLevel^N12 ^SName^SSkull~`and~`Crossbones ^SPrtsBefore^N1 ^SAndOr^SOR ^t^N7^T ^SType^SBUFFDUR ^SPrtsAfter^N1 ^SOperator^S< ^SLevel^N12 ^SName^SRuthless~`Precision ^t^N8^T ^SType^SBUFFDUR ^SOperator^S>= ^SLevel^N12 ^SName^SSkull~`and~`Crossbones ^SPrtsBefore^N1 ^SAndOr^SOR ^t^N9^T ^SType^SBUFFDUR ^SPrtsAfter^N1 ^SOperator^S< ^SLevel^N12 ^SName^SBroadside ^t^N10^T ^SType^SBUFFDUR ^SOperator^S>= ^SLevel^N12 ^SName^SBuried~`Treasure ^SPrtsBefore^N1 ^SAndOr^SOR ^t^N11^T ^SType^SBUFFDUR ^SPrtsAfter^N1 ^SOperator^S< ^SLevel^N12 ^SName^SRuthless~`Precision ^t^N12^T ^SType^SBUFFDUR ^SOperator^S>= ^SLevel^N12 ^SName^SBuried~`Treasure ^SPrtsBefore^N1 ^SAndOr^SOR ^t^N13^T ^SType^SBUFFDUR ^SPrtsAfter^N1 ^SOperator^S< ^SLevel^N12 ^SName^SBroadside ^t^N14^T ^SType^SBUFFDUR ^SOperator^S>= ^SLevel^N12 ^SName^STrue~`Bearing ^SPrtsBefore^N1 ^SAndOr^SOR ^t^N15^T ^SType^SBUFFDUR ^SPrtsAfter^N1 ^SOperator^S< ^SLevel^N12 ^SName^SRuthless~`Precision ^t^N16^T ^SType^SBUFFDUR ^SOperator^S>= ^SLevel^N12 ^SName^STrue~`Bearing ^SPrtsBefore^N1 ^SAndOr^SOR ^t^N17^T ^SType^SBUFFDUR ^SPrtsAfter^N2 ^SOperator^S< ^SLevel^N12 ^SName^SBroadside ^t^Sn^N17 ^t^t^N5^T ^SType^SSound ^SSound^Sinterface/addons/powerdown1.mp3 ^SEvent^SOnFinish ^SPassThrough^b ^t^Sn^N5 ^t^SSettingsPerView^T ^Sicon^T ^STextLayout^STMW:textlayout:1UnZhBZ0JmiW ^STexts^T ^N1^SBuffSo ^t^t^t^SStates^T ^N2^T ^SAlpha^N0.1 ^t^t^SFakeHidden^B ^t^N87505^S~`~| ^Sicon^^

^1 ^T^N1^T ^SSkinAs^SHotKey ^SStringName^SBinding/Label ^SHeight^N1 ^SAnchors^T ^N1^T ^Sy^N-2 ^Sx^N-2 ^Spoint^STOPLEFT ^SrelativePoint^STOPLEFT ^t^N2^T ^Sy^N-2 ^Sx^N-2 ^Spoint^STOPRIGHT ^SrelativePoint^STOPRIGHT ^t^Sn^N2 ^t^SSize^N9 ^t^N2^T ^SAnchors^T ^N1^T ^Sy^N2 ^Sx^N-2 ^Spoint^SBOTTOMRIGHT ^SrelativePoint^SBOTTOMRIGHT ^t^t^SSkinAs^SCount ^SStringName^SStacks ^SDefaultText^S[Stacks:Hide(0)] ^t^SGUID^STMW:textlayout:1UnZhBZ0JmiW ^Sn^N2 ^SName^SIcon~`Layout~`2 ^t^N87505^S~`~| ^Stextlayout^STMW:textlayout:1UnZhBZ0JmiW ^^

**Comment by Razoroth** [comment]
Made a video of the issues. Tried to show work and gave a few minutes of hitting the target dummy to display what's happening. I could not get certain procs to happen to get the audio files to overlap together to prove the priority list wasn't stopping after whatever notification was played, but it does happen during gameplay periodically when those conditions arise.

**Comment by ascott18** [comment]
A few things happening here.

>  When trigger events occur, sometimes the triggered event does not stop the rest of the list from triggering.
On Condition Set Passing events don't respect the "Continue to lower notifications" setting. I can't remember why this is the case, or if there ever was an actually compelling reason for it or not. However, it doesn't matter too much as you'll see below...

> Also, if a trigger occurs and the same conditions are met when refreshing buffs via roll the bones, the sound is not played.
This is correct - if the true/false state of the condition hasn't changed, the notification won't happen. It has no idea that is now passing for a different reason - conditions are only true or false.

You might restructure this as follows:
1) Create one Combat Event icon for each sound you want to play. Set the event to spell cast success, set the spell to Roll the Bones, set the source to "player".
2) On each icon, add the appropriate conditions for that sound to the icon itself (not as a notification).
3) Add the sound to each icon as an On Combat Event notification, checking the "Only handle if icon is shown" box.
4) For the "lower tier" sound icons (e.g. Bad Roll), add an additional Icon Shown condition that checks that the next icon up in the tier is hidden. This should prevent multiple sounds at once.
