### ISSUE TITLE
Refresh Sunder Armor bug icon

### ISSUE THREAD

**Issue by Ibadez38** [ascott18/TellMeWhen#1792]
Hi,

I use TellMeWhen v8.7.5 Classic.

I created an icon that lets me see when I need to refresh Sunder Armor.

I only have two conditions:

1. The debuff Sunder Armor of my target must be under 5 seconds. (debuff - duration, target, <5s)

and

2. The target must have 5 stacks of Sunder Armor (debuff-stacks, target, == 5 piles)

The icon is displayed when the conditions are met, everything works, the problem is that when I launch a Sunder Armor, the icon does not disappear. It should disappear because the debuff of the target is again higher than 5 sec.
I don't understand, I have more than fifty icons and I've never had this kind of problem.

Translated with www.DeepL.com/Translator (free version)

**Comment by Ibadez38** [comment]
I just read the FAQ: "Why doesn't my Sunder Armor (or other stackable debuff) duration refresh after reaching 5 stacks?"

I think it answers my question. Sorry for the inconvenience.

**Comment by juggarrnaut** [comment]
Where is this FAQ? Why doesn't my Sunder Armor (or other stackable debuff) duration refresh after reaching 5 stacks

**Comment by Ibadez38** [comment]
She's on the discord

**Comment by Ibadez38** [comment]
Q: Why doesn't my Sunder Armor (or other stackable debuff) duration refresh after reaching 5 stacks?
A: The refresh of a 5-stack Sunder (and other max-stack debuffs) don't appear in the combat log, so TMW cannot detect it and refresh the timer. There is no known workaround to get a true timer.

**Comment by juggarrnaut** [comment]
Strange that it works with WA, I guess that uses a different API.  Just tried it.  I have one trigger that is less than 5 sunders another less than 11.  works as expected.  Anyway, cheers.  Thanks for the info.

**Comment by hijakke** [comment]
WA watching SPELL_CAST_SUCCESS and SPELL_DAMAGE event to refresh the timer.
