### ISSUE TITLE
Guardian icon issue

### ISSUE THREAD

**Issue by LucianDK** [ascott18/TellMeWhen#1794]
Ive set up a guardian icon for my Warlock's summon infernal spell. But I cant seem to set an activation border to flash when theres 20 or less seconds left on it.

**Comment by ascott18** [comment]
Please only use the GitHub issue tracker for bug reports and feature requests. The TellMeWhen community Discord server is a great place to ask questions or otherwise discuss TellMeWhen: https://discord.gg/NH7RmcP
