### ISSUE TITLE
delete please

### ISSUE THREAD

**Issue by LucianDK** [ascott18/TellMeWhen#1795]
Using version 8.7.5

Target something, go through portal. Pet health and energy bar is now displayed on the screen, and is removed with clicking on another target.   The exact same issue as the class specialty resources like DK runes.

**Comment by ascott18** [comment]
Please post the export string(s) of the icons, groups, or profiles you're having trouble with. 

To get an export string, open the icon editor, and click the button labeled "Import/Export/Backup". Select the "To String" option for the appropriate export type (icon, group, or profile), and then press CTRL+C to copy it to your clipboard.

Additionally, if applicable, add screenshots to help explain your problem. You can paste images directly into GitHub issues, or you can upload files as well.

**Comment by LucianDK** [comment]
I am sorry, i mixed this up with another addon. *facepalm* delete please

**Comment by LucianDK** [comment]
Ok, here is the icon that tracks the infernal guardian.^1^T^SType^Sguardian ^SShowTimerText^B ^SEnabled^B ^SGUID^STMW:icon:1V2E81cJ47Oa ^SName^SInfernal ^t^N87505^S~`~| ^Sicon^^
Followed by Dark Soul: Instability spell cooldown^1^T^SType^Scooldown ^SConditions^T ^N1^T ^SType^SALIVE ^SUnit^Starget ^SPrtsBefore^N1 ^t^N2^T ^SType^SREACT ^SPrtsAfter^N1 ^SUnit^Starget ^SLevel^N1 ^t^N3^T ^SType^SCOMBAT ^SAndOr^SOR ^SPrtsBefore^N1 ^t^N4^T ^SType^SMOUNTED ^SPrtsAfter^N1 ^SLevel^N1 ^t^Sn^N4 ^t^SShowTimerText^B ^SName^SDark~`Soul:~`Instability ^SEnabled^B ^SGUID^STMW:icon:1RU5Ol45zCqV ^SEvents^T ^N1^T ^SType^SAnimations ^SAnimation^SACTVTNGLOW ^SEvent^SWCSP ^SOnConditionConditions^T ^N1^T ^SType^SSPELLCD ^SName^SDark~`Soul:~`Instability ^t^N2^T ^SType^SSPELLCD ^SOperator^S<= ^SUnit^Starget ^SLevel^N170 ^SName^SSummon~`Infernal ^t^N3^T ^SType^SSPELLCD ^SOperator^S>= ^SLevel^N150 ^SName^SSummon~`Infernal ^t^Sn^N3 ^t^t^Sn^N1 ^t^SStates^T ^N2^T ^SAlpha^N0.5 ^t^t^t^N87505^S~`~| ^Sicon^^
The thing is that you want to press Dark Soul when theres 20 seconds left of the 30 second duration infernal. Which I were I want Dark Soul to light up with the activation border to maximize chaos bolt damage. So I am missing an option to get the duration of the infernal guardian.


    On Monday, July 13, 2020, 1:02:57 AM GMT+2, Andrew Scott <notifications@github.com> wrote:  
 
 


Please post the export string(s) of the icons, groups, or profiles you're having trouble with.

To get an export string, open the icon editor, and click the button labeled "Import/Export/Backup". Select the "To String" option for the appropriate export type (icon, group, or profile), and then press CTRL+C to copy it to your clipboard.

Additionally, if applicable, add screenshots to help explain your problem. You can paste images directly into GitHub issues, or you can upload files as well.
