### ISSUE TITLE
[Bug] Mouseover

### ISSUE THREAD

**Issue by Spydawg** [ascott18/TellMeWhen#1797]
**TellMeWhen v8.7.5**

**What steps will reproduce the problem?**
1. Condition "Unit Specialization"
2. Unit "Mouseover"
3. Choose Specs..  "any specs chosen, like Holy/Shadow Priest"

**What do you expect to happen?**
If I mouseover a Holy or Shadow Priest,  The icon I want to see shows..

**What happens instead?**
If I mouseover a Holy or Shadow Priest,  The icon I want to see does not show..

**Screenshot**
![WoWScrnShot_072920_121053](https://user-images.githubusercontent.com/1214244/88824721-b88f8580-d194-11ea-98a7-e6f34152a8d3.jpg)

 **Export String**

^1^T^SStrata^SFULLSCREEN_DIALOG ^SScale^F8481780336164864 ^f-51^SPoint ^T^Sy^F4782710761455616 ^f-50^Sx ^F-5595250559049503^f-46 ^Spoint^SBOTTOM ^SrelativePoint^SBOTTOM ^t^SLocked^B ^SLevel^N16 ^SGUID^STMW:group:1V7u3Qq=Ax4f ^SColumns^N1 ^SIcons^T ^N1^T ^SBuffOrDebuff^SHARMFUL ^SUnit^Smouseover ^SType^Scooldown ^SConditions^T ^N1^T ^SType^SSPELLCD ^SName^SImprison ^t^N2^T ^SType^SLIBRANGECHECK ^SOperator^S<= ^SUnit^Smouseover ^SLevel^N20 ^t^N3^T ^SType^SDEBUFFSTACKS ^SName^SImprison ^t^N4^T ^SType^SCLASS2 ^SChecked^B ^SUnit^Smouseover ^SBitFlags^N2477 ^t^N5^T ^SType^SPVPFLAG ^t^N6^T ^SType^SREACT ^SUnit^Smouseover ^SLevel^N1 ^t^N7^T ^SType^SUNITSPEC ^SUnit^Smouseover ^SBitFlags^T ^N258^B ^N257^B ^t^t^Sn^N7 ^t^SName^SImprison ^SEnabled^B ^SStates^T ^N3^T ^SAlpha^N0 ^t^t^t^t^t^N87505^S~`~| ^Sgroup^N13 ^^

**Additional Info**

**Comment by Spydawg** [comment]
The Unit Class works with mouseover, just not specialization

**Comment by ascott18** [comment]
If you read the tooltip, you'll find that the Unit Specialization condition only works on yourself, battleground enemies, and arena enemies.

**Comment by Spydawg** [comment]
I'm using this only in BG's, not working..

**Comment by ascott18** [comment]
I'll take a look at some point then. It could be something has changed in recent patches that has broken this.

**Comment by Spydawg** [comment]
thanks

**Comment by ascott18** [comment]
Just tested it - it works just fine.
