### ISSUE TITLE
New Condition: [@targetoftarget, player]

### ISSUE THREAD

**Issue by juggarrnaut** [ascott18/TellMeWhen#1798]
**Is your feature request related to a problem? Please describe.**
In wow classic, I would like a condition that let's me see when the target of my target is *NOT* me.  If that exists not sure how to trigger it.

**Comment by ascott18** [comment]
That's what the Unit is Unit condition is.

**Comment by juggarrnaut** [comment]
Thank you!! Got it


Sent from Yahoo Mail for iPhone


On Friday, July 31, 2020, 23:03, Andrew Scott <notifications@github.com> wrote:




That's what the Unit is Unit condition is.
