### ISSUE TITLE
losing profile on  character switch 

### ISSUE THREAD

**Issue by abaddon-2020** [ascott18/TellMeWhen#1799]
**What version of TellMeWhen are you using? **

ver 8.75 

**What steps will reproduce the problem?**
1.switching between characters world of Warcraft  have to reload the string file for each 
2.
3.

**What do you expect to happen? What happens instead?**

**Screenshots and Export Strings**

**Additional Info**

same issue  on  2 computers both  running win 10  pro 2004  both  amd rayzen 7  and 9  with  nvidia gpus   1080 and rtx  2060  both with  32gb ddr4 3200

**Comment by ascott18** [comment]
All I can think of is that you're trying to run two instances of the same wow installation at the same time, or otherwise are using the same settings files.
