### ISSUE TITLE
[Bug] totem timer

### ISSUE THREAD

**Issue by mepark12** [ascott18/TellMeWhen#1801]
**What version of TellMeWhen are you using? **

8.7.5-classic

**What steps will reproduce the problem?**
1. /tmw
2. create tracks totems and set searing totem any rank, tic timer option and done.
3. Icon shows rank 6 timer anyway. and last as same.

**What do you expect to happen? What happens instead?**

so i play shaman. when i use "searing totem rank 1" (spell id 3599) which is i put on this addons slot to tracks totem, it shows 55 sec(rank 6) timer but it should be displayed as 30 seconds because rank 1 last time is 30 sec.
also not only wrong timer number, also the "icon" of spell last longer then 30 sec. actually last same 55 sec as rank 6.

i did also with spell id(rank 1) and the result was same 55 sec (rank 6).

set other ranks example, rank 2 or 3 was same result. seems always shows highest rank regardless of whatever rank you set.

**Screenshots and Export Strings**

^1^T^SShowTimer^B ^SType^Stotem ^SShowTimerText^B ^SName^S3599 ^SEnabled^B ^t^N87505^S~`~| ^Sicon^^

![totem](https://user-images.githubusercontent.com/69491076/89848026-7288e780-dbc0-11ea-8900-7d4397b63699.jpg)

**Additional Info**

i think possibly i did something wrong at setting i hope. if so please tell me how i should do.
if not hope you can fix. thanks.
forgive my bad english

**Comment by ascott18** [comment]
I can't differentiate between ranks. The timers are configured for the max ranks as that is 99% of users care about.
