### ISSUE TITLE
[Bug] Unable to Properly Track Fire Vulnerability in Raid

### ISSUE THREAD

**Issue by hankinsohl** [ascott18/TellMeWhen#1803]
**What version of TellMeWhen are you using? **

TellMeWhen v8.7.5 Classic

**What steps will reproduce the problem?**
I've set up a debuff icon to track Fire Vulnerability (procced by Improved Scorch) buff stacks and time remaining.  When I'm alone in combat the icon works perfectly.  When in a raid, however, with other mages also contributing towards the Fire Vulnerability debuff, the icon does not work.  For example, the timer will show that Fire Vulnerability has a short duration remaining and will continue counting down even if I repeatedly cast scorch to refresh the debuff.  The icon seems to try to count my contribution towards the debuff only and is thus inaccurate.

**Screenshots and Export Strings**
^1^T^SShowTimer^B ^SBuffOrDebuff^SHARMFUL ^SUnit^Starget ^SType^Sbuff ^SName^SFire~`Vulnerability ^SShowTimerText^B ^SEnabled^B ^t^N87505^S~`~| ^Sicon^^

Thanks in advance for your help with this.

**Comment by ascott18** [comment]
Same issue as #1792
