### ISSUE TITLE
How to track timer on Demonology Dreadstalkers?

### ISSUE THREAD

**Issue by Anumet77** [ascott18/TellMeWhen#1804]
Is there a way to track the time remaining of the Dreadstalkers a demonology warlock calls? I'd like to show the icon for "Summon Demonic Tyrant" when the Dreadstalker guardians only have 6 seconds remaining.

**Comment by ascott18** [comment]
Is the Guardians icon type not working for you?

Please only use the GitHub issue tracker for bug reports and feature requests. The TellMeWhen community Discord server is a great place to ask questions or otherwise discuss TellMeWhen: https://discord.gg/NH7RmcP
