### ISSUE TITLE
[Bug] Classic Tell Me When not tracking Rain of Fire cast by other characters

### ISSUE THREAD

**Issue by nodozen** [ascott18/TellMeWhen#1805]
**What version of TellMeWhen are you using? **

version 8.7.5 Classic
Wanted to say thanks as this is a great tool.

**What steps will reproduce the problem?**
1. Setup Icon to track Spell Cast (and Channels)
2. Leave Blank to Track All
3. Under who to track put in a Warlock party member
4. On Warlock setup the above to track yourself (optional but helped me debug some)
4. Exit configuration mode
5. From Warlock cast HellFire (result: Icon shows on main character and Warlock)
6. From Warlock cast Health Funnel (result: Icon shows on main character and Warlock)
7. From Warlock cast Rain of Fire (result: Icon does NOT show on main character but does show on Warlock)

**What do you expect to happen? What happens instead?**
I was expecting to see that the Warlock was casting Rain of Fire from my main character but cannot see that.  When debugging I tried it on the Warlock and he can see his own casts but external characters cannot see them.

**Screenshots and Export Strings**

![image](https://user-images.githubusercontent.com/70788526/92297274-45033580-ef03-11ea-93b5-2116218b54e2.png)

https://i.gyazo.com/5b71bbbfcca6bfbca56d3930d7ac4acb.png 

**Additional Info**

In the above screenshot my 3 warlocks are casting 3 spells but my main can only see two (HellFire & Health Funnel) but not Rain of Fire.

**Comment by ascott18** [comment]
Rain of fire probably doesn't appear in the combat log. Nothing I can do about it. Welcome to Classic wow API limitations.
