### ISSUE TITLE
[Shadowlands] [Bug] Crash when trying to edit text icons' displays

### ISSUE THREAD

**Issue by dygyijingbeizhanyong** [ascott18/TellMeWhen#1806]
**What version of TellMeWhen are you using? **

9.0 PTR

**What steps will reproduce the problem?**
1.When the mouse moves to the box under the text display scheme, the game will exit directly
2.
3.

**What do you expect to happen? What happens instead?**

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
In the future, please include relevant screenshots and messages of the errors that you encounter when reporting a bug.

**Comment by ascott18** [comment]
This bug is on Blizzard's end - there's nothing I can do about it short of gutting functionality out of TMW. 

![image](https://user-images.githubusercontent.com/5017521/92415586-79970d00-f10e-11ea-968e-502a41253363.png)

**Comment by arieh** [comment]
I am also seeing this on Mac OSX. 
This seems to be triggred by the dogtags help menu, since it only happens after dogtags are loaded, and for eg, if I remove my local fix to DogTags backdrop it's no longer an issue.
I'll try and dive a bit deeper into it - it's possible temporarily disabling some functionality might be the best action here until blizz fix it

**Comment by arieh** [comment]
Just to elaborate on previous comment, returning early on `DogTag:OpenHelp()` (`LibDogTag-3.0/Help.lua`) and `Module:OnSuggest()` (Core/Common/DogTag/config.lua#236) completely removes the crash while still showing the list of dogtags and the help tooltip.

Obviously, this removes a chunk of important functionality, but might be best to do this temp fix until Bliz solve this

**Comment by arieh** [comment]
Ok - further investigation - basically, the single line that crashes WoW is `helpFrame:Show()` at the end of `Help.lua`

Some interesting things I've noticed while debugging this:
The game has no issues actually rendering the helpFrame - I went about this by returning early, and if you return as late as line 1217 (so - just the definition of the Show method), the entire UI of the help menu renders fine without crashing at all (another interesting tidbit - this is actually a piece of UI I've never seen before? is this new?)

I'll be happy to help investigate this further but this is about as far as I can get without knowing more details about what the `Show` function actually does and what might cause it to crash

**Comment by ascott18** [comment]
I'm not going to go bisecting through DogTag to try and track down a Blizzard bug. Furthermore, if I do add some kind of workaround or just straight up removal of functionality to work around this, it significantly reduces the number of people reporting this crash to Blizzard and therefore significantly reduces the chances they will fix it.

If you're still getting Backdrop issues on the help frame, you're using an old version of LibDogTag.

**Comment by ascott18** [comment]
They fixed this at some point.
