### ISSUE TITLE
[Shadowlands][Bug] Need to disable TMW if i am guilded on the PTR server

### ISSUE THREAD

**Issue by SveSop** [ascott18/TellMeWhen#1808]
**What version of TellMeWhen are you using?**
8.7.5-6-ge590855e

**What steps will reproduce the problem?**
1. Be in a guild on the PTR server
2. Have TMW addon enabled
3. Possibly need to have stuff set up - I have not tested this with a completely empty config with no cd's/timers/whatever configured.
4. This does not seem to happen on a character without a guild

**What do you expect to happen? What happens instead?**
It crashes a few seconds after i log in. The error counter keep counting up until i click "reload".

**Screenshots and Export Strings**

![Tmw](https://user-images.githubusercontent.com/33990277/92941279-76728880-f450-11ea-863e-29b2d5bbb341.jpg)

Seems to be something iffy with LibDogTag and 'GuildRoster' being a (nil value).

**Additional Info**

It does not seem to happen on my 2 other characters that are not in a guild.

**Comment by SveSop** [comment]
Editing `/_ptr_/Interface/Addons/TellMeWhen/Lib/LibDogTag-Unit-3.0/Categories/GuildNote.lua` and change
`if currentTime > nextGuildRosterUpdate then`
to
`if currentTime == nextGuildRosterUpdate then`

Gets rid of the error by basically never be true... But i don't know if getting "GuildNote" from the guild is important for TMW?

**Comment by ascott18** [comment]
Fixed upstream in LDT-Unit
