### ISSUE TITLE
[Bug] PTR - DogTag:Help failing to set backdrop

### ISSUE THREAD

**Issue by arieh** [ascott18/TellMeWhen#1810]
**What version of TellMeWhen are you using? **
8.7.6

**What steps will reproduce the problem?**
1. Try and edit an icon's text

**What do you expect to happen? What happens instead?**
DogTags crashes because it's trying to set backdrops. Adding BackdropTemplate as a dependency to all created frames (`helpFrame`, `treeFrame` and `mainFrame`) solves the issue, however I couldn't find out where to create a PR for it, so reporting here instead.

Also - once fixed, editing a text field will cause the game to crash (I saw an existing bug on this, but wanted to mention).

**Comment by ascott18** [comment]
I already fixed this.
