### ISSUE TITLE
Unholy Blight Ignore Runes is Bugged when tracking spell usability[Bug]

### ISSUE THREAD

**Issue by Mysterious12345** [ascott18/TellMeWhen#1813]
**What version of TellMeWhen are you using? **

9.0.1

**What steps will reproduce the problem?**
1. Track Unholy Blight Spell Cooldown
2. Click Ignore Runes Button 
3. Spend all your runes, yet the unholy blight icon still disappears when unholy blight is off cooldown and there are no runes available. 

**What do you expect to happen? What happens instead?**
Unholy Blight should be ignoring the amount of runes you have when ignore runes is checked. However, when I reach 0 runes, unholy blight disappears off the screen (even though ignore runes is checked). Unholy Blight icon should remain on the screen the whole time when off cooldown, even with no runes. 

**Screenshots and Export Strings**
```
^1^T^SIgnoreRunes^B ^SType^Scooldown ^SConditions^T ^N1^T ^SType^SSPELLCD ^SName^SUnholy~`Blight ^t^Sn^N1 ^t^SName^SUnholy~`Blight ^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^S ^t^t^t^SStates^T ^N102^T ^SAlpha^N1 ^t^t^t^N90001^S~`~| ^Sicon^^
```

**Additional Info**

Ignore runes seems to be broken as a condition

**Comment by ascott18** [comment]
Unable to reproduce. Works just fine for me.
