### ISSUE TITLE
Festering Strike not supporting "Range check" [Bug]

### ISSUE THREAD

**Issue by petersoncurvelo** [ascott18/TellMeWhen#1814]
Addon version 9.0.1

1. Creating a new icon for spell cool down
2.  Tracking Festering Strike spell
3. Marking the checkbox "Range check

Its expected to happen: the icon should show as configured on the Out of range slider (icon color, transparency etc...)
What happens instead: the icon stays the same as the original

The string for the festering strike only:
```
^1^T^SShowTimer^B ^SType^Scooldown ^SName^SFestering~`Strike ^SEnabled^B ^SManaCheck^B ^SShowTimerTextnoOCC^B ^SStates^T ^N2^T ^SColor^Sffffffffd ^SAlpha^N1 ^t^N3^T ^SColor^Sffff0000 ^SAlpha^N1 ^t^N4^T ^SAlpha^N1 ^t^t^SRangeCheck^B ^t^N90101^S~`~| ^Sicon^^
```

![image](https://user-images.githubusercontent.com/24270141/96355841-e82b9b00-10bc-11eb-9f0b-ffc366ffc29b.png)
![image](https://user-images.githubusercontent.com/24270141/96355844-fda0c500-10bc-11eb-9e52-98fb3cecd887.png)

The 1st image is the configuration used for the icon
The 2nd is an example using the same configurations on two icons, only changing the spell name

**Comment by ascott18** [comment]
Thanks, will be fixed in the next release. You can go download the latest https://www.curseforge.com/wow/addons/libspellrange-1-0 right now if you don't want to wait.
