### ISSUE TITLE
[Bug]Tracks temporary weapon imbues

### ISSUE THREAD

**Issue by tenchi-masaki** [ascott18/TellMeWhen#1815]
**What version of TellMeWhen are you using? **

TellMeWhen-9.0.1

**What steps will reproduce the problem?**
1. Tracks temporary weapon imbues
2.
3.

**What do you expect to happen? What happens instead?**
2x TellMeWhen\TellMeWhen-9.0.1.lua:2721: ...ponents\IconTypes\IconType_wpnenchant\wpnenchant.lua:181: attempt to perform arithmetic on local 'expiration' (a boolean value)

528x ...ponents\IconTypes\IconType_wpnenchant\wpnenchant.lua:181: attempt to perform arithmetic on local 'expiration' (a boolean value)

**Screenshots and Export Strings**

^1^T^SType^Swpnenchant ^SHideUnequipped^B ^SShowTimerText^B ^SEnabled^B ^SStates^T ^N2^T ^SAlpha^N0.4 ^t^t^SWpnEnchantType^SSecondaryHandSlot ^t^N90101^S~`~| ^Sicon^^

**Additional Info**

**Comment by ascott18** [comment]
Will be fixed in the next version.
