### ISSUE TITLE
Lost profiles

### ISSUE THREAD

**Issue by rubentejo** [ascott18/TellMeWhen#1816]
With the last upgrade today 19/10/2020, I've lost all my profiles of all my chars. Anyone got the same problem? Any idea of how to solve it? I'm very pissed off ngl.

**Comment by ascott18** [comment]
Loss of settings results from not exiting the game properly. They could have also been deleted by some third-party app like the Twitch app if you uninstalled TMW and failed to turn off its setting that automatically deletes addon configuration when uninstalling.

Your TMW settings file can be found in WoW's installation location, under `World Of Warcraft\_retail_\WTF\Account\<your account name>\SavedVariables\TellMeWhen.lua`.

There may be a version of your settings with `.bak` appended. If so, delete the real file (which is probably mostly empty now) and replace it with the `.bak` version. Or, you can restore you settings using copies from your backup scheme you use for your whole PC. If you don't have a backup strategy in place for your computer, you just learned the hard way about how valuable such a thing is.
