### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by brirodrigo** [ascott18/TellMeWhen#1818]
**What version of TellMeWhen are you using? **
v9.0.2

**What steps will reproduce the problem?**
1. I can't import a profile. The option "from string" is not available to me
2.
3.

**What do you expect to happen? What happens instead?**

**Screenshots and Export Strings**
![image](https://user-images.githubusercontent.com/73247235/96752564-076c4600-13a5-11eb-9328-5a6a0a45f300.png)

**Additional Info**

**Comment by ascott18** [comment]
You didn't paste in any string into the textbox.
