### ISSUE TITLE
[Feature Request] Player and Target HP Comparison

### ISSUE THREAD

**Issue by alexfg24** [ascott18/TellMeWhen#1823]
I would like to make an icon that would warn me that the selected target has a lot more HP than me. Any ideas how this could be done?

**Comment by ascott18** [comment]
Please only use the GitHub issue tracker for bug reports and feature requests. The TellMeWhen community Discord server is a great place to ask questions or otherwise discuss TellMeWhen: https://discord.gg/NH7RmcP
