### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Xpucmemo** [ascott18/TellMeWhen#1825]
**What version of TellMeWhen are you using? ** 9.0.2

**What steps will reproduce the problem?**
1. Paste an import string
2. Click the button for Import/Export/Backup
3. Hover on the from string bar

**What do you expect to happen? What happens instead?**

On my laptop it allows me to import properly, but on my father's PC it does not give him the menu where he can choose whether or not he wants to overwrite or add it as a new one. We are both on version 9.0.2, we tried multiple times to reinstall it and I even sent him my TMW and TMW_Options folders from the interface addons path.

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
Please share the exact string that isn't working on your father's PC. Most likely it got corrupted or incorrectly copied when you transferred it across computers.
