### ISSUE TITLE
[Bug] Using power bar overlay on certain spells displays wrong resource

### ISSUE THREAD

**Issue by tidyshark** [ascott18/TellMeWhen#1827]
**What version of TellMeWhen are you using? **

v9.0.2

**What steps will reproduce the problem?**
1. using power bar overlay on certain spells (starsurge, for instance).

**What do you expect to happen? What happens instead?**
it should display astral power needed, instead it is displaying mana (starsurge does not even use mana).

**Screenshots and Export Strings**

**Additional Info**

 There are issues with other spells, as well. However, I have not played in a few months and I'm not sure which ones, I know a spell on my rogue also attempts to read mana needed instead of energy needed, but, again, that was quite some time ago. Though since my druid spell is reading the wrong type of power, I assume it's still an issue that persists.

**Comment by ascott18** [comment]
Unable to reproduce. It works just fine for me. If you're still having this issue, please include the detail requested by the issue template (screenshots and export strings.

![image](https://user-images.githubusercontent.com/5017521/102004414-43e16180-3cc5-11eb-8c1a-e9480a52bd2e.png)
