### ISSUE TITLE
[Bug] Warlock Guardian Felguard Timer 

### ISSUE THREAD

**Issue by Chasty74** [ascott18/TellMeWhen#1829]
**What version of TellMeWhen are you using? **
v9.0.2

**What steps will reproduce the problem?**
1. Guardians tracking for Felguard (17252) is not on the good timer, when using Grimoire: Felguard (111898), the Felguard summoned (17252) duration is 15s and it should be **17s**
2. When using Summon Demonic Tyrant after more than 15s of Felguard, timer does not extend.
3.

**What do you expect to happen? What happens instead?**
Fix the timer

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
Blizzard added a number of guardians as totems to warlocks. For now, you can use the existing Totem icon type for them for always-accurate durations.
