### ISSUE TITLE
[Bug] Crossed Bars' Overlay Order Randomly Mess Up! 

### ISSUE THREAD

**Issue by Atlaimond** [ascott18/TellMeWhen#1830]
**TellMeWhen v9.0.2**

**What steps will reproduce the problem?**
1. Crossing two bars on each other, make the top of them with transparent background. 
2. Tick the **[✔]Only show in combat]** option under the Bar's General options, 
3. Start getting in-and-out of combat. The issue happens randomly, need a few attempt to trigger it. 
 

**What do you expect to happen?** 
I expected the overlay order remains the same, in the exact order I had set them up in the [Profile Group] / [General] options menu. 
**What happens instead?** 
The bars' overlay order randomly change when they appear, and the top bar gets under the second bar's overlay. It also randomly changes back to the expected order. 

**Screenshots and Export Strings** 
I recorded it, and uploaded to my Google Drive. [Link Here!](https://drive.google.com/file/d/1D245qhgB51UpsW8PtSlXhveIHSd0x3Sj/view?usp=sharing) 
**-- If your issue pertains to a specific icon or group, please post the relevant export string(s).** 
**Top bar's string:** 
```
^1^T^SBackdropColor^S00333333 ^STimerBar_MiddleColor^S0000ff00 ^SScale^N1.3 ^STimerBar_CompleteColor^S0000ff00 ^STextureName^SBantoBar ^STimerBar_EnableColors^B ^STimerBar_StartColor^S0000ff00 ^SEnabledSpecs^T ^N270^b ^t^SOnlyInCombat^B ^SPoint^T ^Sy^N-128 ^Sx^N-45 ^t^SColumns^N1 ^SGUID^STMW:group:1VoETuKFWle= ^SBackdropColor_Enable^B ^SName^SChis ^SSettingsPerView^T ^Sbar^T ^SSizeX^F5639294207131648 ^f-46^SBorderColor ^S00000000^SIcon ^b^t ^t^SIcons^T ^N1^T ^SType^Svalue ^SPowerType^N12 ^SSettingsPerView^T ^Sbar^T ^STexts^T ^N1^S ^N2^S([Value:Short~`"/"~`ValueMax:Short]) ^t^t^t^SCustomTex^SNONE ^SStates^T ^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^t^t^SView^Sbar ^t^N90201^S~`~| ^Sgroup^N5 ^^
```

**Second bar's string:** 
```
^1^T^SView^Sbar ^SPoint^T ^Sy^N-128 ^Sx^N-95 ^t^SScale^N1.3 ^STextureName^SMinimalist ^SGUID^STMW:group:1Vdkpejzf_Ss ^SLocked^B ^SEnabledSpecs^T ^N270^b ^t^SColumns^N1 ^SName^SEnergy ^SSettingsPerView^T ^Sbar^T ^SIcon^b ^t^t^SIcons^T ^N1^T ^SType^Svalue ^SPowerType^N3 ^SSettingsPerView^T ^Sbar^T ^STextLayout^STMW:textlayout:1Vc6XOeMyD0s ^STexts^T ^N1^S[Value:Short] ^N2^S[Value:Short~`"/"~`ValueMax:Short] ^t^t^t^SCustomTex^SNONE ^SEnabled^B ^t^t^SOnlyInCombat^B ^t^N90201^S~`~| ^Sgroup^N6 ^^

^1 ^T^SGUID^STMW:textlayout:1Vc6XOeMyD0s ^SName^SNew~`1 ^t^N90201^S~`~| ^Stextlayout^STMW:textlayout:1Vc6XOeMyD0s ^^ 
```

**Additional Info**
It also happens with my Death Knight Runes' number. I have set up those bars in this same way, and the same issue happens there as well, also randomly.

**Comment by ascott18** [comment]
Both these groups have identical strata and frame level settings. At that point, it is entirely up to the internals of the Blizzard UI framework on which one it decides to render on top.

Just set the frame level of one of the groups higher or lower than the other.

**Comment by Atlaimond** [comment]
Aaah! 🤦‍♂️ I see now. I didn't give attention on that "Frame Level" thing, because I believed that the profile order, you know the "1. 2. 3. etc." did this thing. I'm sorry, it was my fault. 😞
