### ISSUE TITLE
[Bug] WW monk abilities to track Spell CD are not working

### ISSUE THREAD

**Issue by dariobojat** [ascott18/TellMeWhen#1832]
**What version of TellMeWhen are you using? **

**What steps will reproduce the problem?**
1.WW monk abilities to track Spell CD are not working
2. Abilities like Paralysis, Leg Sweep, Ring of Peace, etc.
3. I did all correctly and been using this addon for years. It's simply not working for me now, and I dont know why - I checked all I am supposed to.

**What do you expect to happen? What happens instead?**

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
Please include export strings _and_ screenshots of the specific things that are not working for you.
