### ISSUE TITLE
[Bug] Lightning Lasso (Shaman PvP Talent) has the wrong id in the equivalency "stunned"

### ISSUE THREAD

**Issue by Rackelhardt** [ascott18/TellMeWhen#1833]
**What version of TellMeWhen are you using? **

9.03

**What steps will reproduce the problem?**
1. Lightning Lasso (PvP Talent Shaman) has the wrong id under the category "stunned"
2.
3.

**What do you expect to happen? What happens instead?**

I expect to see it when i use the category "stunned"

**Screenshots and Export Strings**

**Additional Info**

the actual (wrong) id for Lightning Lasso in the category "stunned" is 204437
I guess it should be 305483.

**Comment by ascott18** [comment]
Thanks, will be fixed in the next release.
