### ISSUE TITLE
[Bug] "Between the Eyes" (Rogue) isnt a Stun anymore and should be removed from the category "stunned"

### ISSUE THREAD

**Issue by Rackelhardt** [ascott18/TellMeWhen#1834]
**What version of TellMeWhen are you using? **

9.0.3

**What steps will reproduce the problem?**
1. "Between the Eyes" is in the category "stunned"
2.
3.

**What do you expect to happen? What happens instead?**

**Screenshots and Export Strings**

**Additional Info**

The ability changed and should be removed from the category "stunned"

**Comment by ascott18** [comment]
Thanks, will be fixed in the next release.
