### ISSUE TITLE
Direction icon for moonkin balance eclipse (last eclipse was lunar, show Wrath icon)

### ISSUE THREAD

**Issue by bomrico** [ascott18/TellMeWhen#1835]
I have my rotation in TMW, but can't figure out how to write an icon that remembers which eclipse I last had, so it can show me which icon would push it to the other eclipse.  Thanks!

**Comment by ascott18** [comment]
Please only use the GitHub issue tracker for bug reports and feature requests. The TellMeWhen community Discord server is a great place to ask questions or otherwise discuss TellMeWhen: https://discord.gg/NH7RmcP
