### ISSUE TITLE
[FERAL] Bloodtalons Trigger Abilities Tracking and NEW Abilities Used Condition Type

### ISSUE THREAD

**Issue by Necrochrist** [ascott18/TellMeWhen#1837]
**Is your feature request related to a problem? Please describe.**

Problem:  [Feral] Unable to properly track combo point-generating abilities (CPGA) **used** to meet Bloodtalons triggering requirements (4-second window).  

**Describe the solution you'd like**

Goal:  Based on CPGA already used within a 4-second timer, have **remaining** abilities required to show as icons when the Bloodtalons buff goes missing so that said abilities can be activated to re-trigger Bloodtalons.

What is needed: 

 A timer that can be triggered when an ability is USED.

A condition icon that can track specific abilities used when the timer starts and show the remaining abilities required to meet the overall condition...the activation of Bloodtalons.

As far as I can see, there is no condition that tracks when an ability is used, only the Last Ability Used, which doesn't quite work, so a **new** condition type "Abilities Used" should be added.

**Describe alternatives you've considered**

Developer adds a whole new icon type that tracks the triggering of Bloodtalons with all available CPGA's and 4-second timer baked in and will show what ability needs to be activated to make the trigger.  CPGA's would be selectable by check box in case certain CPGA's aren't use (i.e. Lunar Inspiration/Moonfire).

**Additional context**

**Comment by ascott18** [comment]
> A timer that can be triggered when an ability is USED.

This already exists. See Combat Event icons, and/or the Timer notification handler (in the Notifications tab).

> A condition icon that can track specific abilities used when the timer starts and show the remaining abilities required to meet the overall condition...the activation of Bloodtalons.

You can make this just fine with Icon Shown conditions (checking the aforementioned Combat Event icons) or Timer conditions (checking the aforementioned timers).

> As far as I can see, there is no condition that tracks when an ability is used, only the Last Ability Used, which doesn't quite work, so a new condition type "Abilities Used" should be added.

Correct, since you can do this yourself using the aforementioned techniques. Last Ability Used a unique case for abilities that must be (or must not be, e.g WW monk mastery) used in immediate succession.

**Comment by Necrochrist** [comment]
Thanks for the info.  There was still quite a bit of difficulty trying to figure out how to use Combat Event icons and Icon Shown.  A few hours later I was able to achieve my goal.  I still believe it could be simplified with an Ability Used condition, but I appreciate your response.  I'm submitting another issue regarding Meta icon conditions vs. group conditions.
