### ISSUE TITLE
Tracking effects

### ISSUE THREAD

**Issue by beresromanalex** [ascott18/TellMeWhen#1838]
Good afternoon! How to enable it "Track fragments"
![2021-01-03](https://user-images.githubusercontent.com/76909262/103481144-edf66a00-4de9-11eb-9a62-75496e703a54.png)

**Comment by beresromanalex** [comment]
I want to track effects above the life bars, how do I enable them?

**Comment by ascott18** [comment]
Please only use the GitHub issue tracker for bug reports and feature requests. The TellMeWhen community Discord server is a great place to ask questions or otherwise discuss TellMeWhen: https://discord.gg/NH7RmcP
