### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Architekt909** [ascott18/TellMeWhen#1839]
**What version of TellMeWhen are you using? **
9.0.3

**What steps will reproduce the problem?**
1. Spell cooldown enabled, add spell ID 281195 (survival of the fittest, only avail as marksman without pet i.e. with lone wolf buff)
2.also add (with a semicolon) spell name "Command Pet" for when pet is summoned as you lose the above spell and instead gain a spell based on the pet spec. You can alternatively use the spell ID for this from your spell book, it makes no difference.
3. If you don't have a pet, everything works as expected. The icon is for SOTF, and it correctly shows it cooling down when used.
4. If you DO have a pet, and SOTF is replaced with "Command Pet", notice that the icon doesn't change: It still shows the icon for SOTF. Furthermore, using the Command Pet ability doesn't change the icon nor in any way show a cooling down. 
5. Effectively this makes the icon only work for 1 spell. I have other set ups with multiple semicolon separated spells that work as I expected this one to.

**What do you expect to happen? What happens instead?**
Icon should be dependent on whether pet is summoned or not, as you lose the SOTF ability and it's replaced with Command Pet when pet is out. Icon should also reflect cooldown state.

**Screenshots and Export Strings**

^1^T^SShowTimer^B ^SType^Scooldown ^SConditions^T ^N1^T ^SType^SCOMBAT ^t^N2^T ^SType^SREACT ^SUnit^Starget ^SAndOr^SOR ^SLevel^N1 ^t^Sn^N2 ^t^SShowTimerText^B ^SName^S281195;~`Command~`Pet ^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STextLayout^STMW:textlayout:1KGUbKf6odcS ^STexts^T ^N1^SSD ^t^t^t^SStates^T ^N2^T ^SAlpha^N1 ^t^N102^T ^SAlpha^N0.35 ^t^t^t^N90301^S~`~| ^Sicon^^

^1 ^T^N1^T ^SAnchors^T ^N1^T ^Sy^N-2 ^Sx^N2 ^Spoint^STOPLEFT ^SrelativePoint^STOPLEFT ^t^N2^T ^Sy^N-2 ^Sx^N-2 ^Spoint^STOPRIGHT ^SrelativePoint^STOPRIGHT ^t^Sn^N2 ^t^SStringName^SBinding/Label ^SSkinAs^SHotKey ^SSize^N8 ^t^N2^T ^SDefaultText^S[Stacks:Hide(0)] ^SAnchors^T ^N1^T ^Sy^N2 ^Sx^N2 ^Spoint^SBOTTOMRIGHT ^SrelativePoint^SBOTTOMRIGHT ^t^t^SStringName^SStacks ^SSkinAs^SCount ^SSize^N8 ^t^SGUID^STMW:textlayout:1KGUbKf6odcS ^Sn^N2 ^SName^Ssmaller~`text~`both~`rows ^t^N90301^S~`~| ^Stextlayout^STMW:textlayout:1KGUbKf6odcS ^^

Edit: I have no idea why the formatting looks so weird but that should be the string regardless. I have also posted it on pastebin [here](https://pastebin.com/vY5ETQyu)

**Comment by ascott18** [comment]
This is correct - you entered the first spell by ID. This allows the game's API to always resolve this to an actual spell. Entering spells by name works differently - the game's API only will treat it as a valid spell (and this one that will be shown by the TMW icon) if a spell by that name is learned by your current character.

In any case, you can just enter only "Command Pet" (the actual base spell that is replaced by either SotF or a pet ability) to track and any all spells for that slot.

**Comment by Architekt909** [comment]
Awesome, thanks man. I appreciate you taking the time to explain a solution.
