### ISSUE TITLE
Meta Icon Conditions vs. Meta Group Conditions

### ISSUE THREAD

**Issue by Necrochrist** [ascott18/TellMeWhen#1841]
**Is your feature request related to a problem? Please describe.**

Created a single Meta icon with a Group Condition to show when Bloodtalons = Missing.  Works as expected.

Created a **second** Group Condition for Resource => 70 Energy.  Expected for the group to show when Bloodtalons = Missing and Energy was at least 70.  Instead, each icon in the meta priority would only show if => 70 Energy.  I put the same conditions in Icon Conditions of the meta and got the same results as expected.

**Describe the solution you'd like**

Shouldn't Group Conditions affect the group as a whole, which would be the meta icon itself rather than the icons in the meta priority?  Isn't that what Icon Conditions are for?

**Comment by ascott18** [comment]
1. This appears to be a question, not a feature request or bug report.
2. You didn't provide any export strings, or even any screenshots, of what you're talking about.

If you think you've found a bug, feel free to open an new issue, taking care to follow the instructions in the provided template.
