### ISSUE TITLE
Select legendary item for "Item is equipped" condition not working well

### ISSUE THREAD

**Issue by outlying** [ascott18/TellMeWhen#1842]
**What version of TellMeWhen are you using? **
v9.0.3

**What steps will reproduce the problem?**
* Create an icon for anything
* Go to conditions
* Add condition "Item is equipped"
* Try to type in a legendary item name - no suggestion when I type in the legendary name

**What do you expect to happen? What happens instead?**
I would expect to be able to select a legendary item for the conditional icon, or maybe have the new condition to check if the legendary of a given type is on my character.

Right now it's possible to select a base item of legendary for this condition. There is a suggestion for legendary if I start typing the base item name, but only legendary I'm wearing is suggested, the other one in my backpack is not, and still by clicking this suggestion the base item name is put into the field, not a legendary.

Also, there is one problem with that, what if I have two legendaries using the same base item? Some people have 3 by now, and it is only going to grow.

![image](https://user-images.githubusercontent.com/2069751/104119827-acf2de00-5332-11eb-8fe6-45ceee474d49.png)

![image](https://user-images.githubusercontent.com/2069751/104119848-bf6d1780-5332-11eb-8bcb-e87ac9dce9ba.png)

**Comment by outlying** [comment]
... it seems that even if I select base item and wear it condition is not true

**Comment by ascott18** [comment]
This is indeed a bug with the suggestion list, but you don't have to use the suggestion list. Just type in the name of the legendary yourself - everything still functions properly.

**Comment by outlying** [comment]
Not intuitive but correct, it works.

**Comment by ascott18** [comment]
This has been fixed.
