### ISSUE TITLE
Resource bar with data from the Lua script

### ISSUE THREAD

**Issue by outlying** [ascott18/TellMeWhen#1843]
**Is your feature request related to a problem? Please describe.**
Well you can say that my problem is that I cannot create a resource bar for anything

**Describe the solution you'd like**
Would be great to have a "Resource type" of "Lua", so I can provide my own data to the resource bar. For example, I have a trinket that stores some extra healing, I could check how much is stored but that would require to move the cursor over a buff

**Describe alternatives you've considered**
Not much, maybe use a group controller icon and show some amount of icons to represent health stored?

**Additional context**
No, I only would like to feed the resource bar with anything

**Comment by rldml** [comment]
Same here: It would be very nice to have the rest amount of "Ignore Pain" (protection warrior) as a bar. Actually you can only display the amount as a number.

**Comment by ascott18** [comment]
Added by #1908
