### ISSUE TITLE
Please add Timewalk Raid as a several loading condition

### ISSUE THREAD

**Issue by Polyhymnea** [ascott18/TellMeWhen#1846]
As i was lately in a timewalk raid i noticed that TMW loaded the Timewalk-Instance (5 man) conditioned group, which is sub-optimal. So i'd like to suggest to add a seperate condition to load when in a Timewalk Raid. Love your add-on btw :)

**Comment by Polyhymnea** [comment]
and maybe would torghast as a loading condition a good idea :)

**Comment by ascott18** [comment]
If blizzard is reporting TW raids as 5 mans then that's not something I care to fix or workaround. You can always just combine the Instance Type condition with the Group Type condition.

Torghast can already be determined with the Zone condition:
![image](https://user-images.githubusercontent.com/5017521/111920392-da06ef80-8a4b-11eb-98c7-6b0dfe93bf62.png)
