### ISSUE TITLE
Global Class Profiles

### ISSUE THREAD

**Issue by Morwo01** [ascott18/TellMeWhen#1848]
**Is your feature request related to a problem? Please describe.**
no problem. at least convenience issues

**Describe the solution you'd like**
Tagging a profile to a 'global class profile'. on each additional char with similar class could be a toggle 'use global class profile'. changes on either char to the global class profile automaticly takes effect on each same 'global class profile' chars

**Describe alternatives you've considered**
picking profiles from import feature on other chars after each and single change at any time manually.

**Additional context**
playing multiple classes with more then 1 char can be fun. right now SL being very generous playing alts then ever before.

**Comment by ascott18** [comment]
Just select the same profile on multiple characters?
![image](https://user-images.githubusercontent.com/5017521/107859618-6ee45080-6def-11eb-8885-15db0b85cba7.png)
