### ISSUE TITLE
Diminishing Returns[Bug]

### ISSUE THREAD

**Issue by usercruiser1** [ascott18/TellMeWhen#1849]
When creating tmw diminishing return icons, only the "DR-Stun" (typed in "what to track")spells seem to work.(tested DR-Disorient and DR-Incapacitate and they didnt work). Even when typing fear into the "what to track" window it doesnt work but typing shadowfury does for example.

**Comment by ascott18** [comment]
Only stuns have DR in PvE. You can't test DR against training dummies because non-player targets don't have DR (again, with the exception of stuns).
