### ISSUE TITLE
[Bug] Tracking Monk Statue

### ISSUE THREAD

**Issue by ekenberg** [ascott18/TellMeWhen#1850]
**What version of TellMeWhen are you using? **
9.0.3

**What steps will reproduce the problem?**
1. Use a brewmaster monk with talent "Summon Black Ox Statue"
2. Create an icon of type "Monk Statue". Leave everything else as default. 
3. Summon Black Ox Statue. Icon is shown.
4. When available, summon Black Ox Statue again. Icon disappears.
5. Summon again and it appears, etc. Every summon seems to toggle the icon.

**What do you expect to happen? What happens instead?**
Icon should always be shown when there is a Black Ox Statue up. 

**Screenshots and Export Strings**
````
^1^T^SType^Stotem` ^SEnabled^B ^t^N90301^S~`~| ^Sicon^^
````

**Additional Info**
"Monk Statue" is also available as a condition under "Spells/Items" -> "Monk Statue". That's where I encountered the issue first time.

**Comment by ascott18** [comment]
Blizzard yet again changed the way that totems work for some classes. I updated this in the latest version so specific slots aren't tied to specific totems. So, the totem icon type and conditions are now just generic (as they are for shamans), allowing you to use the Any Totem condition, or the Totem icon type with all slots checked.
