### ISSUE TITLE
Covenant membership as Condition

### ISSUE THREAD

**Issue by stamicvs** [ascott18/TellMeWhen#1852]
Hi,

I've set up regular icons for Covenant class abilities like "Convoke the Spirits" or "Sepsis" etc. to track cooldowns or buff/debuff duration.
I am using generic class profiles which I've set up for every class and specialization so I am getting icons in my profiles for abilities which my character does not even have learned.
e.g I have a rogue on Horde who is member of the Nightfae covenant so I set up an icon tracking the CD of Sepsis. I am currently levelling my rogue on Alliance so the character is not in a Covenant right now.
Unfortunately I have no chance to hide the icon for the CD of Sepsis because there is no condition is existing like "spell learned" or something similar.
Because I read some requests on Discord about a condition for tracking the Convenant memberships this would also not only solve my issue also allow additional possibilities like global groups based on Covenants etc.

Thank you very much in advance.

Stamic

**Comment by ascott18** [comment]
Added in f78a8a93
