### ISSUE TITLE
[Feature Request] Opacity slider for "Only show in combat" for Group?

### ISSUE THREAD

**Issue by eightflat** [ascott18/TellMeWhen#1853]
**Is your feature request related to a problem? Please describe.**
Not a problem of course, but instead of making this functionality happen icon by icon, I would really like if we could "fade out" TMW groups based on combat state. AFAIK, the group setting is all or nothing, invisible out of combat, visible during combat.

**Describe the solution you'd like**
Perhaps something similar to the icon Opacity & Color sliders? When "Only show in combat" is checked, a slider exists to control opacity for the group?

**Additional context**
Regardless, thank you for all your work on this amazing addon.

**Comment by ascott18** [comment]
"Only show in combat" and group conditions are both very deliberate in their functionality in that they "turn off" the entire group when they are not in a passing state, stopping updates of all the icons within.

That doesn't mean that a change like this _couldn't_ be made, but at this point it is very unlikely that I would do this.
