### ISSUE TITLE
[Bug] "Unit Cooldown" weird tracking bug

### ISSUE THREAD

**Issue by Betaskill** [ascott18/TellMeWhen#1854]
**What version of TellMeWhen are you using? **

v9.0.3

**What steps will reproduce the problem?**

Hi first of all. 

I´ve found by chance a bug that I would like to report. When I am tracking a spell of another unit like "target" with the unit cooldown icon and add a minimum duration to it, it will not be tracked correctly. Since my english is not the best I have made a video to it:

https://www.youtube.com/watch?v=xVSiKsf6otg&feature=youtu.be

I will still try to explain what is happening. When the minimum duration of this icon is added in the "Duration Requirements" box normally the icon should not be visible anymore when the duration of the spell is below 5 seconds. But this is not working. Instead it will only be properly working when, and now here it is where it gets weird, I am hovering with the over the top left corner where "unit cooldown", " What to track" and "Who to watch" is placed. 
It will also be working properly when I am the bar of the duration tracker in the "Opacity & Color" location or clicking in the "Prioritize" box. 

The hovering part will only work when the actual duraion is over 5 seconds not under my set 5 seconds for the minimum duration. Like you can see in second 30 to 40 in the video. From second 42 my friend is casting the spell and the icon is shown. Then I am hovering with the mouse over the mentioned part and when it reaches 5 seconds or below the icon is not visible anymore.  I do not know how this will be triggered because from second 52 we are trying this again and nothing happens. 

Sometimes it will also work by moving the bar of the duration tracker or setting the icon in the "Prioritize" box to "high duration" and then back to "normal". 

**Screenshots and Export Strings**

\^1^T^SUnit^Starget ^SDurationMin^N5 ^SType^Sunitcooldown ^SName^S48438:\~\`10 ^SDurationMinEnabled^B ^SStates^T ^N1^T ^SAlpha^N0 ^t^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^SDurationMax^N5 ^t^N90301^S~\`~| ^Sicon^^

Hope that I could express myself properly and that it can be fixed with it.

All the best

**Comment by ascott18** [comment]
Unable to reproduce
