### ISSUE TITLE
[Bug] DR-List is not up to date

### ISSUE THREAD

**Issue by wanghedi1991** [ascott18/TellMeWhen#1855]
Hey I just wanna tell you your DR-List 1.0 is not up to date. Yesterday I spend several hours to figure out why newly added sindragosa and driftglobe do not appear on diminishing return addon. I even open an issue there and it turned out to be conflicting with tmw DR-list. I simply remove the folder DR-list in tmw and it worked. Please considering either update it or remove it thanks : )

Great addon btw i have been using it for years now (from 2013)

**Comment by ascott18** [comment]
The latest version of libraries are coped in when the addon is packaged. If you'd like a more recent version of a particular library, just install that library as a standalone addon.
