### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Brightbrown** [ascott18/TellMeWhen#1856]
Got 2 updates tonight (Threat Plates,& TellMeWhen), this is what result I got (seems mixed in with other add-ons), so am reverting to previous versions:

1x TellMeWhen: TidyPlates_ThreatPlates\Init.lua:42: attempt to index local 'key' (a nil value)1x TellMeWhen: TidyPlates_ThreatPlates\Init.lua:42: attempt to index local 'key' (a nil value)[string "@TellMeWhen\TellMeWhen-9.0.4.lua"]:2861: in function <TellMeWhen\TellMeWhen.lua:2818>
20x TidyPlates_ThreatPlates\Init.lua:42: attempt to index local 'key' (a nil value)[string "@TidyPlates_ThreatPlates\Init.lua"]:42: in function <TidyPlates_ThreatPlates\Init.lua:41>[string "SetInfo unit, GUID"]:92: in function `?'[string "@TellMeWhen\Components\Core\Icon.lua"]:1438: in function `SetInfo'[string "@TellMeWhen\Components\Core\IconDataProcessors.lua"]:1082: in function <...ns\TellMeWhen\Components\Core\IconDataProcessors.lua:1081>[string "=(tail call)"]: ?[string "=[C]"]: ?[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>[string "=(tail call)"]: ?[string "@TellMeWhen\TellMeWhen-9.0.4.lua"]:841: in function `Fire'[string "@TellMeWhen\Components\Core\Icon.lua"]:896: in function `DisableIcon'[string "@TellMeWhen\Components\Core\Icon.lua"]:976: in function <TellMeWhen\Components\Core\Icon.lua:926>[string "=(tail call)"]: ?...[string "=(tail call)"]: ?[string "@TellMeWhen\Components\Core\Group-Group.lua"]:496: in function <TellMeWhen\Components\Core\Group.lua:424>[string "=(tail call)"]: ?[string "=[C]"]: ?[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>[string "=(tail call)"]: ?[string "@TellMeWhen\TellMeWhen-9.0.4.lua"]:2769: in function `UpdateNormally'[string "@TellMeWhen\TellMeWhen-9.0.4.lua"]:2918: in function `Update'[string "@TellMeWhen\TellMeWhen-9.0.4.lua"]:2926: in function `?'[string "@DataStore\libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:55: in function <DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:50>

**Comment by GreyFoxGer** [comment]
Same problem with Threat Plates...

**Comment by Brightbrown** [comment]
Posted the same LUA there... reverted both to previous versions, no errors.

**Comment by Brightbrown** [comment]
ThreatPlates fixed his issue and no longer does TMW freak...
