### ISSUE TITLE
Make special sound when a spell is being cast by NPC

### ISSUE THREAD

**Issue by Alchymysts** [ascott18/TellMeWhen#1858]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem or flaw as far as I can tell.

**Describe the solution you'd like**
I would like to have specified in a character's TMW bar a condition or warning related to the specified spell to interrupt.
As in the Paladin Rebuke.
Sometimes in the heat of a fight you don't see the NPC's pending action, the spell being cast. So you might miss the interrupt chance.
Example, in Torghast, the Empowered Mage type casts a heal spell on itself that is interruptible. But if you don't the fight gets prolonged ad nauseum.
Another example is the Fear spell some cast that can be interrupted.

**Describe alternatives you've considered**
Nothing really other than having to watch what is being cast, seeing it in time, but then not watching other stuff which can be a problem. Especially if there are more than that NPC in the fight.
I did try to add in the Paladin's Rebuke to watch for the spell and make a sound. It hasn't worked.

**Additional context**

**Comment by ascott18** [comment]
You can already do this with a Combat Event icon (to detect casts from any enemy) or a simple Spell Cast icon (to track casts from specific units).
