### ISSUE TITLE
[Bug] Import text box not showing

### ISSUE THREAD

**Issue by jims23211** [ascott18/TellMeWhen#1859]
**What version of TellMeWhen are you using? **
Downloaded via Curseforge.  Not displaying version number

**What steps will reproduce the problem?**
1. Install from Curseforge both TMW and TMW scripting tool
2. Load WoW and check addon is enabled.
3. Type /tmw 

**What do you expect to happen? What happens instead?**
The configuration mode to allow importing of strings/scripts along with other configuration options Nothing shows

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
You have to right-click an icon to show the configuration UI after unlocking TMW with `/tmw`. Or, you can use `/tmw options` to open it directly without having to click on an icon.
