### ISSUE TITLE
[Bug] Sound notification triggers after loading screen.

### ISSUE THREAD

**Issue by GreyFoxGer** [ascott18/TellMeWhen#1860]
**What version of TellMeWhen are you using? ** 9.0.4

**What steps will reproduce the problem?**
1. Create a trigger with a sound notification. Lets say it's your rogue poisons, it should be triggered if poisons buff have < 5 mins .
2. Renew the poisons buff (> 5 mins)
3. Then, use some teleport, /reload not always triggers it, but teleport!

**What do you expect to happen? What happens instead?**

I expect to hear the sound notification only if my poisons buffs have less than 5 mins on cd.

**Screenshots and Export Strings**

**Comment by GreyFoxGer** [comment]
ok... seems nobody cares...

**Comment by ascott18** [comment]
You're right, I don't. Maybe that's because you couldn't be bothered to include an export string, or maybe its because you whined about not getting a response in the middle of a week after posting this on a Sunday afternoon.

**Comment by GreyFoxGer** [comment]
Im not whining at all dude. That bug presist very long time. You told me to give you a import string... I don't know what class you are playing. It's a simple sound notification trigger if buff has less "time".

But ok, if you decide to close without a fix. Fine.
