### ISSUE TITLE
[Bug] fury warrior Rampage showing as having enough power while Bladestorm is active

### ISSUE THREAD

**Issue by CinemaCat420** [ascott18/TellMeWhen#1863]
**What version of TellMeWhen are you using? **

9.0.4

**What steps will reproduce the problem?**
1. create icon > spell cooldown > Rampage > enable "Power check"
2. cast Bladestorm while you have zero rage

**What do you expect to happen? What happens instead?**
Expected: The opacity and color of the icon does not change because I don't have enough power to use the spell.
What happens instead: The opacity and color of the icon changes to the "ready" state while I'm using Bladestorm even though I have less than the 80 rage required to use Rampage.

**Screenshots and Export Strings**

^1^T^SType^Scooldown ^SName^SRampage ^SManaCheck^B ^SStates^T ^N4^T ^SAlpha^N0.25 ^t^t^SEnabled^B ^t^N90403^S~`~| ^Sicon^^

**Additional Info**

**Comment by ascott18** [comment]
For whatever reason, the Blizzard API reports that this (and many other abilities) are no longer lacking sufficient resources when Bladestorm is active. I have no plans to put in place any fix or workaround for this. If you like, you can submit a bug to Blizzard about this, but there's a 100% chance they will ignore you.

You can switch your icon type of Reactive Ability if you wish in order for TMW to take into account the separate non-usable flag that is placed on the ability instead when Bladestorm is being used.
