### ISSUE TITLE
Copy conditons/group conditions

### ISSUE THREAD

**Issue by catthou** [ascott18/TellMeWhen#1864]
**Is your feature request related to a problem? Please describe.**
When setting up a new spec or for a new patch, or after realizing something isn't reacting the way I want, I often have to go through multiple group conditions and modify them all in the same way (such as to add combat or instance detection).

**Describe the solution you'd like**
I would like "copy" and "paste" buttons on each conditions and group conditions page, so that I can reduce the repetition of setting up multiple groups.

**Describe alternatives you've considered**
What I would like even more, but I consider quite an overhaul, would be a template systems, where I can spawn multiple groups from the same template, and each group will continue to inherit settings clusters (like "Timer Sweep" or "Spell Cooldown" or Conditions) until they're edited manually. So I could set "only combat or instance" in the template, spawn four groups, and I can simply edit the template they're inheriting from to update them all at once.

**Comment by ascott18** [comment]
This already exists in the right-click-and-drag menu.
![image](https://user-images.githubusercontent.com/5017521/109405788-f7530d00-7928-11eb-81e6-9cda915eafea.png)
