### ISSUE TITLE
Inherit action bar coloring state option

### ISSUE THREAD

**Issue by Jalopyy** [ascott18/TellMeWhen#1865]
![image](https://user-images.githubusercontent.com/15044218/109574434-bf70d480-7aa4-11eb-93f7-8f7cb883757f.png)

Would be nice if for opacity & coloring, instead of making the user hunt down the proper coloring shading which correlates to the normal action bar tinting, there could just be a checkbox would auto-filled this stuff. Useful for making auras which replace action bars (allows for more granular control of when they're shown). Plus some stuff doesn't play super well with trying to get the proper conditions for coloring which shade and when, which force you to add a bunch of conditionals and sometimes even duplicate auras of the same spell, which have separate show conditions for range/power. Would just be a whole lot neater if there's a clean way for TMW to just pull the shading from what the active tinting would be if the bar is on a keybind already.

**Comment by ascott18** [comment]
TMW is deliberately very independent of your action bars and their behavior. Different action bar addons can behave however they like and I don't intend to go crawling around trying to figure out exactly how they treat all the different states of different abilities.

So, in response to "if there's a clean way" - there isn't really a clean way. Sorry.
