### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by eightflat** [ascott18/TellMeWhen#1866]
**What version of TellMeWhen are you using?**
9.0.4

**What steps will reproduce the problem?**
1. Use the following DogTag in any label: `[StripServer(Unit:Name)]`
2. See that it returns: "Unknown tag: TMWName"

**What do you expect to happen? What happens instead?**
Usually, it shows the unit's name with the server/realm name stripped. Has been working like this for many weeks.

**Screenshots and Export Strings**
https://imgur.com/a/HvLYkIc

**Comment by eightflat** [comment]
I apologize for the lack of title, not intentional.

**Comment by ascott18** [comment]
Thanks, this was fixed in be71393.
