### ISSUE TITLE
[Bug] Lua errors with Retail 9.0.5

### ISSUE THREAD

**Issue by zjx2172** [ascott18/TellMeWhen#1868]
I'm getting Lua errors after the patch:

SetMinMaxValues(min,max) max must be finite

TellMeWhen version 9.0.4
WoW version 0.0.5 (37862)

Error text from BugSack:
```
36x ...aceTellMeWhen\Options\TellMeWhen_Options.lua:2708: <unnamed>:SetMinMaxValues(min, max) max must be finite
[string "=[C]"]: in function 'SetMinMaxValues_base'
[string "@TellMeWhen\Options\TellMeWhen_Options.lua"]:2708: in function 'UpdateRange'
[string "@TellMeWhen\Options\TellMeWhen_Options.lua"]:2368: in function 'SetValue'
[string "@TellMeWhen\Options\TellMeWhen_Options.lua"]:2742: in function <...aceTellMeWhen\Options\TellMeWhen_Options.lua:2734>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@TellMeWhen\Options\TellMeWhen_Options.lua"]:1129: in function 'CScriptCall'
[string "@TellMeWhen\Options\TellMeWhen_Options.lua"]:995: in function <...aceTellMeWhen\Options\TellMeWhen_Options.lua:987>
[string "@TellMeWhen\Options\TellMeWhen_Options.lua"]:1000: in function <...aceTellMeWhen\Options\TellMeWhen_Options.lua:987>
[string "@TellMeWhen\Options\TellMeWhen_Options.lua"]:1000: in function <...aceTellMeWhen\Options\TellMeWhen_Options.lua:987>
...
[string "@TellMeWhen\Options\TellMeWhen_Options.lua"]:1129: in function 'CScriptCall'
[string "@TellMeWhen\Options\TellMeWhen_Options.lua"]:980: in function <...aceTellMeWhen\Options\TellMeWhen_Options.lua:968>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@TellMeWhen\Options\TellMeWhen_Options.lua"]:1040: in function 'CScriptBubble'
[string "@TellMeWhen\Options\TellMeWhen_Options.lua"]:1469: in function 'OnSettingSaved'
[string "@TellMeWhen\Components\Core\Conditions\Config.lua"]:752: in function 'SelectType'
[string "@TellMeWhen\Components\Core\Conditions\Config.lua"]:197: in function 'func'
[string "@TellMeWhen\Options\TMWUIDropDownMenu.lua"]:473: in function 'Button_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
```

**Comment by fault-tt** [comment]
Im getting the same thing. just echoing and hoping this gets fixed really soon. :(

**Comment by zanth77** [comment]
I opened the TMW addon in notepad++ and replaced math.huge with 1e15 to work around the issue. I do NOT recommend anyone else try this since I did NOT study the code. I like to live dangerously, and it gets rid of the lua errors for me. (note, I did backup my wtf folder just in case)

**Comment by fault-tt** [comment]
which file/s and line/s exactly? if you don't mind/have the time, i realise you can't configure values for conditionals while ignoring the lua errors and I need this to work for my everyday gameplay :(

**Comment by zanth77** [comment]
I ransacked then notepad edited them all at once. So...lots. :slight_smile: Here was my end result. Again I do NOT recommend using my version of this addon as it likely will make your computer melt. :slight_smile: https://drive.google.com/file/d/1Uu2PKPcJbLl4mjI_Mfr-ixFjUrJvuq9U/view?usp=sharing

**Comment by fault-tt** [comment]
Thanks, you are both a gentleman and a scholar. Worked like a charm.

**Comment by ascott18** [comment]
Thanks B̷̡̜̠͆̅l̶̖̫͐́i̴̮͈̥̣̪̓́̌͘̚z̷̨̙͇͎̈͜z̵̨̧͚̣̈̇a̷̤̻̮̩̞̽́r̸͔̻̰̠͋̽ď̷̟̼̞͍̊, very cool change.
