### ISSUE TITLE
[Bug] Unknown tag TMWName

### ISSUE THREAD

**Issue by Ekyu** [ascott18/TellMeWhen#1872]
**What version of TellMeWhen are you using? **
TellMeWhen-9.0.3-classic

**What steps will reproduce the problem?**
In a custom group, having [Name] in Text Displays

**What do you expect to happen? What happens instead?**
Having target name appear on my bars.

**Screenshots and Export Strings**

![image](https://user-images.githubusercontent.com/54787443/111030501-dbf50100-8402-11eb-9f0f-8cd661a73529.png)

^1^T^SShowTimer^B ^SUnit^Starget ^SType^Sdotwatch ^SName^SRejuvenation;~`Regrowth;~`Abolish~`Poison ^SShowTimerText^B ^SOnlyMine^B ^SSettingsPerView^T ^Sbar^T ^STextLayout^Sbar1 ^STexts^T ^N1^S[Duration(gcd=true):TMWFormatDuration] ^N2^S[Name]~`[Stacks:Hide(0):Paren] ^t^t^t^SEnabled^B ^t^N87305^S~`~| ^Sicon^^

**Comment by ascott18** [comment]
The fix has been released as TMW 9.0.6.
