### ISSUE TITLE
[Bug] LibDogTag-Unit-3.0\Categories\TooltipScanning.lua:121: attempt to call field 'IterateFactions' (a nil value)

### ISSUE THREAD

**Issue by Wulfig** [ascott18/TellMeWhen#1873]
TMW v9.0.5
Hi, 
Since the new update of both WoW and TMW, TMW does not run upon logging in. I have to type /tmw to kick it into life.

Thanks

**Comment by Wulfig** [comment]
Sorry, I'm new to this bug reporting, and the template didn't ask me any questions I could answer.

The lua errors at the start are:
Message: ...bs\LibDogTag-Unit-3.0\Categories\TooltipScanning.lua:121: attempt to call field 'IterateFactions' (a nil value)
Time: Thu Mar 18 13:07:59 2021
Count: 1
Stack: ...bs\LibDogTag-Unit-3.0\Categories\TooltipScanning.lua:121: attempt to call field 'IterateFactions' (a nil value)
[string "@Interface\AddOns\TidyPlates_ThreatPlates\Libs\LibDogTag-Unit-3.0\Categories\TooltipScanning.lua"]:121: in function `func'
[string "@Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Events.lua"]:271: in function <...rface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Events.lua:264>

Locals: (*temporary) = nil
(*temporary) = "attempt to call field 'IterateFactions' (a nil value)"
in_UNIT_FACTION = true
InCombatLockdown = <function> defined =[C]:-1
should_UPDATE_FACTION = false
DogTag = <table> {
 unparse = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Parser.lua:1219
 select2 = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Helpers.lua:155
 callbackToFunction = <table> {
 }
 hasEvent = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Events.lua:159
 callbackToExtraArg = <table> {
 }
 __colors = <table> {
 }
 Tags = <table> {
 }
 CleanCode = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Parser.lua:1581
 codeToFunction = <table> {
 }
 newDict = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Helpers.lua:35
 clearCodes = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Helpers.lua:515
 TimerHandlers = <table> {
 }
 ADDON_LOADED = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\LibDogTag-3.0.lua:515
 AddCallback = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Events.lua:193
 RemoveCompilationStep = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Compiler.lua:2259
 _clearCodes = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Helpers.lua:441
 deepCompare = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Helpers.lua:335
 RemoveEventHandler = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Events.lua:730
 newSet = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Helpers.lua:51
 __mytonumber = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Compiler.lua:292
 OpenHelp = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Help.lua:25
 EventHandlers = <table> {
 }
 RemoveCallback = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Events.lua:238
 parse = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Parser.lua:1043
 frame = <unnamed> {
 }
 fixNamespaceList = <table> {
 }
 fsToFrame = <table> {
 }
 compilationSteps = <table> {
 }
 AddTag = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\LibDogTag-3.0.lua:126
 AddCompilationStep = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Compiler.lua:2232
 kwargsToKwargTypes = <table> {
 }
 sortStringList = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Helpers.lua:138
 UpdateFontString = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\LibDogTag-3.0.lua:327
 AddEventHandler = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Events.lua:700
 standardize = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Parser.lua:1063
 RemoveAllCompilationSteps = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Compiler.lua:2286
 getTagData = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Compiler.lua:247
 ColorizeCode = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Parser.lua:1656
 memoizeTable = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Helpers.lua:315
 RemoveFontString = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\LibDogTag-3.0.lua:448
 joinSet = <function> defined @Interface\AddOns\TellMeWhen\Lib\LibDogTag-3.0\Helpers.lua:162
 Remo
Message: TellMeWhen: [string "SetInfo unit, GUID"]:92: attempt to index field 'IsLegitimateUnit' (a nil value)
Time: Thu Mar 18 13:08:00 2021
Count: 1
Stack: TellMeWhen: [string "SetInfo unit, GUID"]:92: attempt to index field 'IsLegitimateUnit' (a nil value)
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:2861: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:2818>

Locals: <none>


And the TMW lua settings are:-
[TellMeWhen.lua.txt](https://github.com/ascott18/TellMeWhen/files/6164351/TellMeWhen.lua.txt)

**Comment by ascott18** [comment]
As a workaround for now, try updating Threat Plates. According to its release notes, it no longer embeds LDT, but from your error message I can tell that your installed version is doing just that.

**Comment by ascott18** [comment]
This is now fixed in the version of LDT bundled with TMW 9.0.6.
