### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by wowmacro** [ascott18/TellMeWhen#1875]
265x [string "return math.abs(select(2,LibStub("LibRangeC..."]:1: attempt to perform arithmetic on a nil value
[string "return math.abs(select(2,LibStub("LibRangeCheck-2.0-100204"):GetRange("target"))-select(2,LibStub("LibRangeCheck-2.0"):GetRange("focus")))<10"]:1: in function `LF_000000004D1506D8'
[string "Condition_EXISTS_EXISTS_LUA"]:5: in function `CheckFunction'
[string "@TellMeWhen\Components\Core\Conditions\ConditionObject.lua"]:265: in function `Check'
[string "@TellMeWhen\Components\Core\Icon.lua"]:756: in function <TellMeWhen\Components\Core\Icon.lua:727>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@TellMeWhen\TellMeWhen-9.0.5.lua"]:2681: in function <TellMeWhen\TellMeWhen.lua:2643>

**Comment by wowmacro** [comment]
4x invalid key to 'next'
[string "=[C]"]: in function `(for generator)'
[string "@TellMeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0-20210228122115.lua"]:49: in function <...MeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:46>
[string "@TellMeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0-20210228122115.lua"]:56: in function <...MeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:55>

Locals:
(*temporary) = <table> {
}
(*temporary) = "raid7target"

**Comment by wowmacro** [comment]
2x TellMeWhen\TellMeWhen-9.0.5.lua:2721: [string "return math.abs(select(2,LibStub("LibRangeC..."]:1: attempt to perform arithmetic on a nil value
[string "=[C]"]: ?
[string "@TellMeWhen\TellMeWhen-9.0.5.lua"]:2721: in function <TellMeWhen\TellMeWhen.lua:2710>

Locals:
(*temporary) = false
(*temporary) = "[string "return math.abs(select(2,LibStub("LibRangeC..."]:1: attempt to perform arithmetic on a nil value"

**Comment by ascott18** [comment]
Your first and third error are coming from custom Lua code that you have written in a Lua condition. 

The second error is an error with https://github.com/parnic/LibDogTag-Unit-3.0. It has been reported at least 8 years ago - https://www.curseforge.com/wow/addons/libdogtag-unit-3-0/issues/32

**Comment by wowmacro** [comment]
thank you :D
