### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by RvPr** [ascott18/TellMeWhen#1878]
**What version of TellMeWhen are you using?**

9.0.3-classic

**What steps will reproduce the problem?**

1. Open /tmw on any of my classic characters (not sure how to reproduce it on a different account, since I'm not sure what's causing it, and don't have a different account to test with)

**What do you expect to happen? What happens instead?**

I expect there to be no error messages. I instead see this error message:
```
Message: Couldn't find inherited node: BackdropTemplate
Time: Sun Mar 21 06:17:10 2021
Count: 5
```
Functionally, everything still seems to work fine

**Screenshots and Export Strings**

Error happens even on an alt with completely blank TMW profile

**Comment by ascott18** [comment]
Thanks, fixed in bd349fc721fce8d92345bd03180e63b3fb4c6aa2
