### ISSUE TITLE
Spell Cooldown

### ISSUE THREAD

**Issue by ananbellus** [ascott18/TellMeWhen#1880]
When i choose spell cooldown, choosing a spell and then use the Duration Requirements and set it to minimum 0:05(5 secs)
And then under opacity & Color choose Duration < 5 and set it to 100%. the icon is not shown when the cooldown is < 5 secs

**Comment by ascott18** [comment]
Please do not ignore the issue template that is provided when you create a new issue. The questions and sections within it provide me with essential information to be able to diagnose and resolve your issue. If you do not include this information, there is little I can do to help you.
