### ISSUE TITLE
Error: Demo Lock

### ISSUE THREAD

**Issue by reale411** [ascott18/TellMeWhen#1883]
Message: invalid key to 'next'
Time: Fri Mar 26 18:11:45 2021
Count: 1
Stack: invalid key to 'next'
[string "=[C]"]: in function `(for generator)'
[string "@Interface\AddOns\TellMeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua"]:59: in function <...MeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:56>
[string "@Interface\AddOns\TellMeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua"]:66: in function <...MeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:65>

Locals: (*temporary) = <table> {
 targettargettarget = true
 targettarget = true
 playerpettarget = true
 pettarget = true
 playertargettarget = true
}
(*temporary) = "playertargettargettarget"

**Comment by snotshot** [comment]
I am getting the same error but in 3 counts
only happening in pvp battlegrounds including rated ones
issue started happening on latest update

i am only tracking 3 things, -- concusive shot cd intimidation cd and the duration left on concusive shot

**Comment by NeoAnotherOne** [comment]
A fix already exists in the new version of the LibDogTag-Unit-3.0 library, but this one is not yet included in TellMeWhen 9.0.6.
You can wait for a new version of TellMeWhen, or in the meantime, try to manually replace the version of LibDogTag, included in TellMeWhen, with the latest available:
https://github.com/parnic/LibDogTag-Unit-3.0/releases/download/v90000.5/LibDogTag-Unit-3.0-v90000.5.zip

**Comment by ascott18** [comment]
Closing in favor of #1886 which has a much better title
