### ISSUE TITLE
wago.io

### ISSUE THREAD

**Issue by Kirbdawg** [ascott18/TellMeWhen#1884]
I'm a long, long, long time user.  

We need more examples.  Especially LUA code examples.

Maybe a searchable website like https://wago.io/, but for TMW.   If there is already one, please let us know.

Just say'in...

**Comment by ascott18** [comment]
The TMW Discord is searchable and has plenty of user-created export strings within. There used to be forums on Curseforge with loads of examples, but Curse shut those down across all addons and confiscated the data despite having previously expressed intent to make that data available in a read-only format.

Wago was created by member(s) of the greater WoW community, not by the WeakAuras devs. The TMW community is similarly welcome to create their own websites with a similar function, or to petition for Wago to add support for TMW. This is not an endeavor that I will ever undertake.
