### ISSUE TITLE
Allow that 'Stacks' dog tag to work with target.  For example allow an icon for sunder armor to display the stacks on the target

### ISSUE THREAD

**Issue by Zhenia1024** [ascott18/TellMeWhen#1888]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Zhenia1024** [comment]
Of course it's possible I just dont know how to do it, but I have researched and tried many approaches with no success.

**Comment by ascott18** [comment]
Please do not ignore the issue template that is provided when you create a new issue. The questions and sections within it provide me with essential information to be able to diagnose and resolve your issue. If you do not include this information, there is little I can do to help you.
