### ISSUE TITLE
[Bug] Import From String menu highlighted, but empty

### ISSUE THREAD

**Issue by morourkejr** [ascott18/TellMeWhen#1889]
**What version of TellMeWhen are you using? **

v9.0.6

**What steps will reproduce the problem?**
1. Importing the string
2. Under Import/Export/Restore --> From String pops up but no profile shows. String is updated from user
3. String

```
^1^T^SGroups^T ^N1^T ^SPoint^T ^Sy^F-6830494796742656 ^f-47^Sx ^F-5399089571168258^f-45 ^t^SGUID^STMW:group:1VjlJ8t8I5KT ^SIcons^T ^N2^T ^SShowTimer^B ^SBuffOrDebuff^SHARMFUL ^SUnit^SSamueljay ^SType^Sbuff ^SShowTimerText^B ^SName^SDevouring~Plague ^SEnabled^B ^t^N3^T ^SShowTimer^B ^SBuffOrDebuff^SHARMFUL ^SType^Sbuff ^SName^SExecution~Sentence ^SShowTimerText^B ^SEnabled^B ^t^N4^T ^SShowTimer^B ^SUnit^Sfocus ^SType^Sbuff ^SName^SImmuneToInterrupts;~ImmuneToMagicCC;~Overwatch;~Spell~Reflection ^SShowTimerText^B ^SEnabled^B ^t^t^t^N2^T ^SPoint^T ^Sy^F-6094457661292544 ^f-46^Sx ^F-8323307317231620^f-46 ^t^SGUID^STMW:group:1VmomPDmf6yY ^SIcons^T ^N1^T ^SShowTimer^B ^SBuffOrDebuff^SHARMFUL ^SType^Sbuff ^SName^SDevouring~Plague;~g ^SShowTimerText^B ^SEnabled^B ^t^N2^T ^SShowTimer^B ^SType^Sbuff ^SName^SUnfurling~Darkness ^SShowTimerText^B ^SEnabled^B ^t^N3^T ^SShowTimer^B ^SUnit^Splayer;~party1;~party2 ^SType^Sbuff ^SShowTimerText^B ^SName^SRallying~Cry ^SEnabled^B ^t^N4^T ^SShowTimer^B ^SType^Sbuff ^SName^SIntervene;~Aura~Mastery;~Blessing~of~Protection;~Cenarion~Ward ^SShowTimerText^B ^SEnabled^B ^t^t^t^N3^T ^SPoint^T ^Sy^N-8.3555908203125 ^Sx^F-4521318514950146 ^f-45^t ^SGUID^STMW:group:1VmpCIJ6BRmO ^SIcons^T ^N1^T ^SShowTimer^B ^SBuffOrDebuff^SHARMFUL ^SUnit^SHansol ^SType^Sbuff ^SName^SDevouring~Plague ^SShowTimerText^B ^SEnabled^B ^t^N3^T ^SShowTimer^B ^SType^Sbuff ^SName^SMeasured~Contemplation ^SShowTimerText^B ^SEnabled^B ^t^N4^T ^SShowTimer^B ^SUnit^Sarena~1-5 ^SType^Sbuff ^SShowTimerText^B ^SName^SDoom~Winds ^SEnabled^B ^t^t^t^N4^T ^SPoint^T ^Sy^F-6849227296604160 ^f-46^Sx ^F5942246167805952^f-46 ^t^SGUID^STMW:group:1W5ZdpGEwDSB ^SIcons^T ^N1^T ^SShowTimer^B ^SType^Sbuff ^SShowTimerText^B ^SName^SGladiator's~Emblem ^SEnabled^B ^t^t^t^t^SNumGroups^N4 ^SVersion^N90601 ^t^N90601^S~~| ^Sprofile^SStahp~-~`Mal'Ganis ^^
```

**What do you expect to happen? What happens instead?**
Be able to use a profile

**Screenshots and Export Strings**

![image](https://user-images.githubusercontent.com/82852023/115322327-d4d4b780-a153-11eb-9463-5bb5b5243bdf.png)

^1^T^SGroups^T ^N1^T ^SPoint^T ^Sy^F-6830494796742656 ^f-47^Sx ^F-5399089571168258^f-45 ^t^SGUID^STMW:group:1VjlJ8t8I5KT ^SIcons^T ^N2^T ^SShowTimer^B ^SBuffOrDebuff^SHARMFUL ^SUnit^SSamueljay ^SType^Sbuff ^SShowTimerText^B ^SName^SDevouring~Plague ^SEnabled^B ^t^N3^T ^SShowTimer^B ^SBuffOrDebuff^SHARMFUL ^SType^Sbuff ^SName^SExecution~Sentence ^SShowTimerText^B ^SEnabled^B ^t^N4^T ^SShowTimer^B ^SUnit^Sfocus ^SType^Sbuff ^SName^SImmuneToInterrupts;~ImmuneToMagicCC;~Overwatch;~Spell~Reflection ^SShowTimerText^B ^SEnabled^B ^t^t^t^N2^T ^SPoint^T ^Sy^F-6094457661292544 ^f-46^Sx ^F-8323307317231620^f-46 ^t^SGUID^STMW:group:1VmomPDmf6yY ^SIcons^T ^N1^T ^SShowTimer^B ^SBuffOrDebuff^SHARMFUL ^SType^Sbuff ^SName^SDevouring~Plague;~g ^SShowTimerText^B ^SEnabled^B ^t^N2^T ^SShowTimer^B ^SType^Sbuff ^SName^SUnfurling~Darkness ^SShowTimerText^B ^SEnabled^B ^t^N3^T ^SShowTimer^B ^SUnit^Splayer;~party1;~party2 ^SType^Sbuff ^SShowTimerText^B ^SName^SRallying~Cry ^SEnabled^B ^t^N4^T ^SShowTimer^B ^SType^Sbuff ^SName^SIntervene;~Aura~Mastery;~Blessing~of~Protection;~Cenarion~Ward ^SShowTimerText^B ^SEnabled^B ^t^t^t^N3^T ^SPoint^T ^Sy^N-8.3555908203125 ^Sx^F-4521318514950146 ^f-45^t ^SGUID^STMW:group:1VmpCIJ6BRmO ^SIcons^T ^N1^T ^SShowTimer^B ^SBuffOrDebuff^SHARMFUL ^SUnit^SHansol ^SType^Sbuff ^SName^SDevouring~Plague ^SShowTimerText^B ^SEnabled^B ^t^N3^T ^SShowTimer^B ^SType^Sbuff ^SName^SMeasured~Contemplation ^SShowTimerText^B ^SEnabled^B ^t^N4^T ^SShowTimer^B ^SUnit^Sarena~1-5 ^SType^Sbuff ^SShowTimerText^B ^SName^SDoom~Winds ^SEnabled^B ^t^t^t^N4^T ^SPoint^T ^Sy^F-6849227296604160 ^f-46^Sx ^F5942246167805952^f-46 ^t^SGUID^STMW:group:1W5ZdpGEwDSB ^SIcons^T ^N1^T ^SShowTimer^B ^SType^Sbuff ^SShowTimerText^B ^SName^SGladiator's~Emblem ^SEnabled^B ^t^t^t^t^SNumGroups^N4 ^SVersion^N90601 ^t^N90601^S~~| ^Sprofile^SStahp~-~`Mal'Ganis ^^

Additionally, if applicable, add screenshots to help explain your problem. You can paste images directly into GitHub issues, or you can upload files as well. -->

**Additional Info**

**Comment by ascott18** [comment]
Thanks for the report. The string that you got is corrupt and thus cannot be imported in TMW. There is a bug that is causing the From String option to be highlighted when it should not be.
