### ISSUE TITLE
[Bug] Can't move a locked group

### ISSUE THREAD

**Issue by gjsolerllavina** [ascott18/TellMeWhen#1892]
**What version of TellMeWhen are you using? **
v9.0.6 Classic

**What steps will reproduce the problem?**
1. Left click on an icon
2. Drag

**What do you expect to happen? What happens instead?**
Expect Icon to move, with my mouse, but it does not.

**Screenshots and Export Strings**
**String 1 [Icon: Buff/Debuff]**
```
^1^T^SType^Sbuff ^SName^SCorruption;~`Curse~`of~`Agony;~`Immolate;~`Siphon~`Life ^SEnabled^B ^t^N90601^S~`~| ^Sicon^^
```
**String 2 [Group: Dots (Group: 1)]**
```
^1^T^SGUID^STMW:group:1U6ucUgXeR8R ^SScale^F4866192577658899 ^f-52^SRows ^N4^STextureName ^SDetails~`Serenity^SOnlyInCombat ^B^SLocked ^B^SView ^Sbar^SColumns ^N1^SLayoutDirection ^N5^SName ^SDoTs^SSettingsPerView ^T^Sbar^T ^SSizeX^N135.9 ^SSizeY^N19.9 ^SPadding^N1 ^t^t^SIcons^T ^N1^T ^SType^Sbuff ^SName^SCorruption;~`Curse~`of~`Agony;~`Immolate;~`Siphon~`Life ^SEnabled^B ^t^N2^T ^SType^Scooldown ^SName^SCurse~`of~`Agony ^SEnabled^B ^t^N3^T ^SType^Scooldown ^SName^SImmolate ^SEnabled^B ^t^N4^T ^SType^Scooldown ^SName^SSiphon~`Life ^SEnabled^B ^t^t^SPoint^T ^Sy^F5266421121111656 ^f-45^Sx ^F-7403317190447788^f-46 ^Spoint^SRIGHT ^SrelativePoint^SRIGHT ^t^t^N90601^S~`~| ^Sgroup^N1 ^^
```
![SS](https://user-images.githubusercontent.com/83481640/116765882-96fa4d80-a9f5-11eb-9bde-7121bc31a844.png)

**Additional Info**
Regarding the image, the top group is the one that won't move.  The Icons below (each is its own group) can be dragged perfectly fine

**Comment by ascott18** [comment]
You can't click-and-drag to move a locked group - that's the entire purpose of locking a group. Unlock it if you want to be able to drag it.

**Comment by gjsolerllavina** [comment]
TY Andrew, for prompt reply.  I believe I had them unlocked and still had
issues (hope I'm right).
I wiped it, reinstalled, re-created Group (took like 5 minutes) and It's
all good now.
