### ISSUE TITLE
Fleshcraft Absorb not showing [Bug]

### ISSUE THREAD

**Issue by arkan8000** [ascott18/TellMeWhen#1894]
**What version of TellMeWhen are you using? **

9.0.7

**What steps will reproduce the problem?**
https://imgur.com/a/dsL2RI6
I can't see the absorb amount on the Fleshcraft icon even tho its on "aura variables"

**Comment by ascott18** [comment]
As the tooltip for the Aura Variables setting states, it is up to Blizzard's discretion which values they make available as aura variables and which ones they don't.

If you are OK with seeing the total absorbs of _all_ your shields, use the [TotalAbsorb] tag in the icon's text displays.
