### ISSUE TITLE
[Bug] Unit range does not work in some dungeons

### ISSUE THREAD

**Issue by ngmafia** [ascott18/TellMeWhen#1896]
Im using version 9.0.7

The unit range condition does not work in some dungeons.
Always appears as imprecise.

**Comment by ngmafia** [comment]
I've seen what happens in 2 dungeons so far. Spires of Ascension and Necrotic Wake. I dont know if the issue is from blizzard or not.

**Comment by ascott18** [comment]
Unable to reproduce - it works just fine.

![image](https://user-images.githubusercontent.com/5017521/117588664-c4bc5200-b0d9-11eb-8306-e31f7bd46cc6.png)

**Comment by ngmafia** [comment]
The unit to track is the target, not the player. I'll try to show you some screenshots

**Comment by ascott18** [comment]
Ok, but the unit doesn't matter at all.
