### ISSUE TITLE
[Bug] TBC Beta - SetBackdrop (a nil value)

### ISSUE THREAD

**Issue by PJai** [ascott18/TellMeWhen#1897]
**What version of TellMeWhen are you using? **
v9.0.6 TBC

**What steps will reproduce the problem?**
1. On initial load

11x [string "<unnamed>:OnLoad"]:1: attempt to call method 'SetBackdrop' (a nil value)
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[string "=[C]"]: in function `resume'
[string "@TellMeWhen\TellMeWhen-9.0.6.lua"]:2749: in function <TellMeWhen\TellMeWhen.lua:2710>

Locals:
self = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = <table> {
 edgeSize = 3
 tile = true
 edgeFile = "Tooltips\UI-Tooltip-Background"
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"

**Comment by ascott18** [comment]
Fixed, thanks.
