### ISSUE TITLE
Condition threat

### ISSUE THREAD

**Issue by Ibadez38** [ascott18/TellMeWhen#1901]
Hello,

I play Wow classic TBC and I currently have TellMeWhen version 9.0.7 TBC.

I may have searched incorrectly but I did not find a condition related to the threat.

For example display an icon when our threat exceeds a certain threshold in % for example.

If this feature does not exist, is it planned?

Thanks for your answer.

**Comment by ascott18** [comment]
Wow, the threat APIs actually exist in TBC. I... didn't expect that.
