### ISSUE TITLE
[Bug] TBC Diminishing Returns

### ISSUE THREAD

**Issue by shimo-sudo** [ascott18/TellMeWhen#1902]
**What version of TellMeWhen are you using? **
9.0.7 TBC

**What steps will reproduce the problem?**
1. Create an Icon with the Diminishing Returns type
2. The suggestions DR-* are missing. Manually entering them (for example, DR-Stun) doesn't work either.

**What do you expect to happen? What happens instead?**
The icon doesn't work. I have tried with specific spell IDs as well and they also don't work. 

**Screenshots and Export Strings**
^1^T^SGUID^STMW:group:1Woe96bo5Cyg ^SColumns^N1 ^SIcons^T ^N1^T ^SShowTimer^B ^SUnit^Starget ^SType^Sdr ^SShowTimerText^B ^SName^SDR-Root ^SCustomTex^S5211 ^SStates^T ^N1^T ^SAlpha^N0.5 ^t^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^t^t^SName^SDR ^t^N90701^S~`~| ^Sgroup^N10 ^^

**Comment by ascott18** [comment]
This was already fixed a bit ago but has not been released. Try the latest alpha versions.
