### ISSUE TITLE
[Bug] Add values Arena1-5 TBC

### ISSUE THREAD

**Issue by AbaddonMVP** [ascott18/TellMeWhen#1905]
**What version of TellMeWhen are you using? **
<9.0.8-bcc>

**What steps will reproduce the problem?**
1. Add please values Arena1-5, cos now only target and focus in TBC.

Thanks.

**Comment by Alwies** [comment]
I actually thought you forgot, so posted an issue myself. I've now removed that.
Here's the now closed link: https://github.com/ascott18/TellMeWhen/issues/1903
