### ISSUE TITLE
[Bug] Unit Specialisation not working in some situations

### ISSUE THREAD

**Issue by Nakor101** [ascott18/TellMeWhen#1911]
**What version of TellMeWhen are you using? **

**What steps will reproduce the problem?**
1. Create an icon (i tested with combat event + any spell + cast start and cast success + source unit party 2)
2. In conditions choose unit specialisation > party 2 > any spec

**What do you expect to happen? What happens instead?**

The icon will not show when all conditions pass
If you enable "negate selected" on the condition the icon shows up.
If you change "unit specialisation" to "unit class" and choose the correct class it also shows up.

**Screenshots and Export Strings**

Example icon:

^1^T^SShowTimer^B ^SCLEUEvents^T ^SSPELL_CAST_SUCCESS^B ^SSPELL_CAST_START^B ^t^SType^Scleu ^SSourceUnit^Sparty~2 ^SCLEUDur^N60 ^SName^SCapacitor~Totem ^SShowTimerText^B ^SConditions^T ^N1^T ^SType^SUNITSPEC ^SUnit^Sparty~2 ^SBitFlags^T ^N262^B ^t^t^Sn^N1 ^t^SStates^T ^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^t^N91000^S~~| ^Sicon^^

**Comment by ascott18** [comment]
From the description of the Unit Specialization condition:
```
This condition ONLY works for:
- Yourself
- Battleground enemies
- Arena enemies

It does NOT work for: 
- Group members
- Any other players
```
