### ISSUE TITLE
[Bug] Unable to differentiate between Cat and Bear form

### ISSUE THREAD

**Issue by SimonM404** [ascott18/TellMeWhen#1912]
**What version of TellMeWhen are you using? **

v9.0.8 TBC

**What steps will reproduce the problem?**
1. Create two profile groups named Cat and Bear
2. Cat profile group set to Role DPS Spec Feral, and Group Condition Shapeshift Cat Form
3. Bear profile group set to Role Tank Spec Feral and Group Condition Shapeshift Dire Bear Form; Bear Form

**What do you expect to happen? What happens instead?**
I would expect to see two different sets of TMW windows, one for Feral Cat and one for Feral Bear.  Whenever I close the config screen, it always reverts to Group: Cat (2), and I cannot get Group: Bear(1) to stay active

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
Please post the export string(s) of the icons, groups, or profiles you're having trouble with. 

To get an export string, open the icon editor, and click the button labeled "Import/Export/Backup". Select the "To String" option for the appropriate export type (icon, group, or profile), and then press CTRL+C to copy it to your clipboard.

Additionally, if applicable, add screenshots to help explain your problem. You can paste images directly into GitHub issues, or you can upload files as well.

**Comment by SimonM404** [comment]
I did export my profile and posted it in the bug report. However, it appears to be corrupted :-( and I lost my settings.

I think that it is because I created two profiles... one for bear, and one for cat. Is it possible to create a tmw that will shift the displayed icons when I'm in native, cat or bear forms?

**Comment by SimonM404** [comment]
PEBKAC... I misunderstood the profiles, and had set two up, thinking that it would switch between them, based on my conditionals.
