### ISSUE TITLE
PvP trinkets untrackable

### ISSUE THREAD

**Issue by joex12** [ascott18/TellMeWhen#1916]
You can only track pvp trinket "Gladiator's Medallion: 2:00" for party or arena enemies. You can't see if the target changes the trinket for something else. Can you support other pvp trinkets? (adaptation and relentless) so tmw can fully replace Gladius? much love <3

**Comment by ascott18** [comment]
Probably not, as the idea of replacing Gladius with TMW is a bit strange and not something I can imagine anyone ever actually doing - the two addons have radically different purposes.
