### ISSUE TITLE
[Bug] Classic TBC - Shrink Group Not Working

### ISSUE THREAD

**Issue by Starlynk1** [ascott18/TellMeWhen#1919]
**What version of TellMeWhen are you using? **

9.1.2

**What steps will reproduce the problem?**
1. Create a group with multiple icons that have conditions to hide
2. Set group to Shrink
3. Icons continue to show up where they were placed instead of moving to the left to fill the empty (hidden) icon. Not shrinking.

**What do you expect to happen? What happens instead?**
When icons are hidden, the icons to the right should shrink to fill in the empty space.

**Screenshots and Export Strings**

**Additional Info**

**Comment by ascott18** [comment]
It sounds like you may be confusing the functionality of Shrink Group with the functionality of Icon Sorting. Please have another read of the tooltip for Shrink Group to make sure this is not what's happening.

If you're certain you've used the correct setting, please revisit the issue template. The questions and sections within it provide me with essential information to be able to diagnose and resolve your issue. If you do not include this information, there is little I can do to help you.

**Comment by Starlynk1** [comment]
Yup, looks like a shrink group misunderstanding. I will play with it more, but my very basic use is centering as I was expecting now using sorting. Thanks!
