### ISSUE TITLE
Thunder Clap debuff classed under "Slowed" when it shouldn't be

### ISSUE THREAD

**Issue by Halsey1006** [ascott18/TellMeWhen#1920]
**Is your feature request related to a problem? Please describe.**
Not a huge problem but the Thunder Clap debuff is under the "Slowed" debuff grouping when it's not actually a slow as in a movement speed reduction, rather it's an attack speed reduction. Every other debuff in the category is a movement speed reduction, so it's kind of an odd man out. Some of these debuffs (Chilled, Slow, Slowing Poison) do also slow attack speed, but the main purpose of the group appears to be movement speed slows.

**Describe the solution you'd like**
I'd like to see Thunder Clap removed from the "Slowed" debuff category, and possibly a new "Attack speed slowed" debuff category created. This category would include Thunder Clap as well as the previously mentioned other attack speed slows (Chilled, Slow, Slowing Poison), some other ones not included there yet such as Soothing Kiss, and any new ones that will get added later. I'm sure TMW will be updated for WOTLK classic when it rolls around, and every tank will have one then.

**Describe alternatives you've considered**
The reason I ran into this problem was I wanted an icon to track movement speed slows specifically, but Thunder Clap frequently got in the way and made it difficult to track them. So I've already created a separate icon with all relevant movement speed snares included as individual spells, which is a functional alternative.

**Additional context**

**Comment by ascott18** [comment]
Fixed. In the future, report bugs using the bug report template rather than the feature request template. Thanks!

Also, do note this feature described in the tooltips of the "What to track" field:

```
```
