### ISSUE TITLE
Condition for Ranged Swing Timer

### ISSUE THREAD

**Issue by Speaker1264** [ascott18/TellMeWhen#1925]
There is no condition for ranged swing timers for the TBC client.  I tried using the spell cooldown condition on auto shot and that doesn't seem to work either.  Am I doing something wrong or could this possibly be added?

**Comment by Alwies** [comment]
Can duplicate.
I'll add that it is possible by using the Icon is shown condition on a spell cooldown icon tracking auto-shot.
I'll add an export for all 3 icons `^1^T^SGUID^STMW:group:1XfZZX0pX_u9 ^SIcons^T ^N1^T ^SShowTimer^B ^SType^Scooldown ^SBarDisplay_BarGCD^B ^SSwingTimerSlot^SSecondaryHandSlot ^SName^S75 ^SGUID^STMW:icon:1Xy7mWmN7k4Y ^SShowTimerText^B ^SEnabled^B ^SClockGCD^B ^SStates^T ^N1^T ^SAlpha^N0 ^t^N2^T ^SAlpha^N1 ^t^t^t^N2^T ^SShowTimer^B ^SType^Sconditionicon ^SShowTimerText^B ^SEnabled^B ^SConditions^T ^N1^T ^SType^SSPELLCD ^SChecked^B ^SOperator^S> ^SLevel^N0.1 ^SName^S75 ^t^Sn^N1 ^t^t^N3^T ^SShowTimer^B ^SType^Sconditionicon ^SShowTimerText^B ^SEnabled^B ^SConditionDur^N1.5 ^SConditions^T ^N1^T ^SType^SICON ^SChecked^B ^SOperator^S> ^SAndOr^SOR ^SName^S75 ^SIcon^STMW:icon:1Xy7mWmN7k4Y ^t^Sn^N1 ^t^t^t^t^N91200^S~`~| ^Sgroup^N1 ^^`

**Comment by ascott18** [comment]
Technically there's no condition for range swing timers in _any_ client. "Proper" hunter rotations in TBC are [very complex](https://github.com/diziet559/rotationtools) and not really something you can reasonably create a "press this next" TMW icon for using conditions. Look into something like https://www.curseforge.com/wow/addons/weaponswingtimer-sixxfix/screenshots instead.

A spell cooldown icon tracking Auto Shot won't capture any of the nuance of interactions w/ Aimed or Steady shot.
