### ISSUE TITLE
[Bug]: Debuff icon doesn't show up fast anymore

### ISSUE THREAD

**Issue by zanth77** [ascott18/TellMeWhen#1930]
### WoW Version

Retail

### TellMeWhen Version

9.2.0

### Describe the bug

I have icons to track debuffs in my 5-man groups. They're bigger and flashier than the native ones blizzard provides on unit frames. Since I upgraded to tmw 9.2 today, these debuff icons are taking a couple seconds to appear (if at all). They always used to show up fairly immediately. Here is an example of one. I first noticed the problem in a dungeon tonight and then went to proving grounds on my healer to confirm it happened there too (occasionally a debuff is cast in that scenario). Note, this may not be a bug and certainly not high priority. Tomorrow, I may check out other debuff addons like decursive or big debuffs to handle it (i still use a ton of other functionality in TMW and it all still works great as far as i've seen!)

![buff1](https://user-images.githubusercontent.com/39532168/160318635-65b3de4e-4e15-4379-a500-9f22906f2740.png)

### Export Strings

```text
^1^T^SShowTimer^B ^SBuffOrDebuff^SHARMFUL ^SUnit^Sparty2 ^SDurationMin^N1 ^SType^Sbuff ^SConditions^T ^N1^T ^SType^SSPELLCD ^SName^SPurify~`Spirit ^t^N2^T ^SType^SGROUP2 ^SBitFlags^N2 ^t^Sn^N2 ^t^SName^SMagic;~`Curse ^SShowTimerText^B ^SEnabled^B ^SEvents^T ^N1^T ^SType^SAnimations ^SOnlyShown^B ^SAnimation^SACTVTNGLOW ^SEvent^SOnShow ^SInfinite^B ^t^Sn^N1 ^t^SDurationMinEnabled^B ^SDurationMax^N2 ^t^N92000^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
> Tomorrow, I may check out other debuff addons

weird threat but ok

**Comment by zanth77** [comment]
Doh! Seriously didn't intend that as a threat but, upon re-reading, can see how it appears that way. My apologies sir! Honestly, I thought this might not be a bug. I thought blizz might've throttled aura polling recently, or perhaps I had too much other stuff slowing my processing down, or  simply user error - perhaps I was just tired and imagining things. Didn't want folks to investigate as high priority when something in back of my head told me i was just doing something wrong, which I so often do. Regardless my words conveyed the wrong connotation so I'm sorry. But thanks for the super fast fix! Love the addon!!

**Comment by zanth77** [comment]
Oh, and the fix works great btw, just tried it out! Also, I forgot to mention, the comment about decursive/big debuffs was also conversational at the time in my tired brain. On my healer I have to sort my raid frames by 'group' instead of 'role', because I need these 5 debuff icons (all like the one mentioned in this issue) to show up on each frame (party2, party3, etc) in a predictable way. I couldn't figure out a way to position the tmw debuff icons over the correct raid frame otherwise but still always wanted to find a way to sort by role eventually. So this is the stuff my brain was processing but didn't convey in my original post which might've contributed to the 'wierd' par of the threat. The fact I'm writing a book here likely only digs the hole deeper and making it even weirder, so I'll stop now. :) 

On a side note, the word weird is nearly impossible to spell correctly without spellcheck!
