### ISSUE TITLE
Venthyr Fury Warrior Condemn Cooldown not working[Bug]: 

### ISSUE THREAD

**Issue by OSabb** [ascott18/TellMeWhen#1934]
### WoW Version

Retail

### TellMeWhen Version

Shadowlands 9.2.2

### Describe the bug

Venthyr Warrior Condemn Cooldown not working[Bug]: 

Condem has 4 second cd on fury however TMW thinks it's on 0 CD, due to that being true but for ARMS, not FURY.

### Export Strings

```text
NA
```

**Comment by ascott18** [comment]
Please post the export string(s) of the icons, groups, or profiles you're having trouble with. 

To get an export string, open the icon editor, and click the button labeled "Import/Export/Backup". Select the "To String" option for the appropriate export type (icon, group, or profile), and then press CTRL+C to copy it to your clipboard.

Additionally, if applicable, add screenshots to help explain your problem. You can paste images directly into GitHub issues, or you can upload files as well.
