### ISSUE TITLE
[Feature Request] Add Tooltip info in Meta icons

### ISSUE THREAD

**Issue by gotu0902** [ascott18/TellMeWhen#1935]
**Is your feature request related to a problem? Please describe.**
Sometimes I forget which icon is which, f.ex a buff or a spell cd when setting up the order inside an meta icon.
Right clicking or going into the dropdown gives the information, though sometimes it's a bit tedious.

**Describe the solution you'd like**
Not a big thing, but would be a small QoL if this could also be reflected in the tooltips on the icons in the row themselves.

**Describe alternatives you've considered**
Make sure my hidden groups have a good setup from the start, or just go into the dropdown menu but it's not always easy to remember, for instance if icon 18 is supposed to be above icon 20 etc.

**Additional context**
![1](https://user-images.githubusercontent.com/14739966/168220179-50827726-d488-432e-81bf-54682996a139.jpg)
![2](https://user-images.githubusercontent.com/14739966/168220182-ca137a48-49ac-41c4-8d2b-9abb29027435.jpg)

**Comment by ascott18** [comment]
Great idea - will be in the next release!
