### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dpyron325** [ascott18/TellMeWhen#1936]
### WoW Version

TBC Classic

### TellMeWhen Version

2.5.2

### Describe the bug

the addon isnt loading at all as of this morning when the wowup merge occured. i downloaded curseforge to see if that would fix it and the problem is still there. i have the addon turned on in the game addons menu and have load out of date addons selected. the addon doesnt show up when u type /tmw and its not there in the interface>addons settings either. 

### Export Strings

```text
N/A
```

**Comment by dpyron325** [comment]
I also tried uninstalling and reinstalling it on curseforge and the problem still persisted

**Comment by Neekobr** [comment]
Date: 2022-05-17 15:20:50
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\TellMeWhen\TellMeWhen.lua line 22:
   attempt to perform arithmetic on a string value
Debug:
   [string "=[C]"]: ?
   [string "@TellMeWhen\TellMeWhen.lua"]:22: in main chunk
Locals:

AddOns:
  Swatter, v2.5.6773 (SwimmingSeadragon)
  AskMrRobotClassic, v7
  AtlasLootClassic, vv2.4.4-bcc
  AtlasLootClassicData, vv2.4.4-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.4.4-bcc
  Attune, v253
  AucAdvanced, v2.5.6733 (SwimmingSeadragon)
  AucFilterBasic, v2.5.6759 (SwimmingSeadragon)
  AucStatHistogram, v2.5.6761 (SwimmingSeadragon)
  AucStatiLevel, v2.5.6765 (SwimmingSeadragon)
  AucStatPurchased, v2.5.6762 (SwimmingSeadragon)
  AucStatSimple, v2.5.6763 (SwimmingSeadragon)
  AucStatStdDev, v2.5.6764 (SwimmingSeadragon)
  AucUtilFixAH, v2.5.6766 (SwimmingSeadragon)
  Auctionator, v9.2.16
  BagBrother, v
  Bagnon, v9.2.0
  Bartender4, v4.11.1
  BeanCounter, v2.5.6767 (SwimmingSeadragon)
  CEPGP, v
  CEPGPStandingsTracker, v1.1.0
  CEPGPTBC, v1.0.2
  CharacterStatsTBC, v1.2.4
  ClassicCodex, vv0.4.9
  ClassicCodexdb, vv0.4.9
  ClassicCodexdbenUS, vv0.4.9
  ClassicCodexloader, vv0.4.9
  ClassicCodexpatch, vv0.4.9
  DBMCore, v7ec2f18
  DBMStatusBarTimers, v7ec2f18
  DBMVPVEM, v9d95365
  Decursive, v2.7.8.5
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v2.5.6768 (SwimmingSeadragon)
  EnchantrixBarker, v2.5.6769 (SwimmingSeadragon)
  GTFO, v4.66.6
  LeatrixPlus, v2.5.105
  LFGBulletinBoard, v2.61
  NovaWorldBuffs, v2.28
  OmniCC, v9.2.0
  Pawn, v2.5.38
  Quartz, v3.6.9
  Questie, v6.10.2
  SlideBar, v2.5.6771 (SwimmingSeadragon)
  Stubby, v2.5.6772 (SwimmingSeadragon)
  TellMeWhen, v9.1.2
  BlizRuntimeLib_enUS v2.5.4.20504 <none>
  (ck=5c5)

**Comment by ascott18** [comment]
You installed the wrong version of TMW for the game version you're playing. Unfortunately, there was an error in the code that shows the in-game dialog that informs you of this fact.

I've released new versions for all 3 game versions that fixes this dialog.

If you're still having trouble with your addon manager, contact the support resources for that addon manager.
