### ISSUE TITLE
[Bug]: Points in Talent condition not working since latest update

### ISSUE THREAD

**Issue by Speaker1264** [ascott18/TellMeWhen#1938]
### WoW Version

TBC Classic

### TellMeWhen Version

v9.2.2

### Describe the bug

Using the "Points in talent" condition to show an icon only when Bloodthirst is talented, but the icon only shows when I set Points in Talent == 0, even though I do have 1 point into Bloodthirst.  This condition worked fine in previous versions.  I can only think the latest update somehow broke it.

### Export Strings

```text
^1^T^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SSPELLCD ^SOperator^S< ^SLevel^N1.5 ^SName^SBloodthirst ^SPrtsBefore^N2 ^t^N2^T ^SType^SSPELLCDCOMP ^SName2^SWhirlwind ^SOperator^S<= ^SName^SBloodthirst ^t^N3^T ^SType^SHEALTH ^SPrtsAfter^N1 ^SOperator^S> ^SUnit^Starget ^SLevel^N20 ^t^N4^T ^SType^SSPELLCD ^SPrtsAfter^N1 ^SAndOr^SOR ^SName^SBloodthirst ^t^N5^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbbtgEwtOV ^t^N6^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XiMz69gaEuf ^t^N7^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbQAjOr ^t^N8^T ^SType^SPTSINTAL ^SName^SBloodthirst ^t^Sn^N8 ^t^SGUID^STMW:icon:1XhbHq4fVEyd ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SF ^t^t^SLuaCode^T ^STextLayout^S ^t^t^SCustomTex^SBloodthirst ^SEnabled^B ^t^N92200^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
Works perfectly for me (when I remove the Icon Is Shown conditions that reference icons that you didn't provide).
![image](https://user-images.githubusercontent.com/5017521/170628715-643adec9-5bce-4202-b22f-ee8195e32479.png)
![image](https://user-images.githubusercontent.com/5017521/170628745-44783223-22d6-4f57-bd63-63114c59a396.png)

**Comment by Speaker1264** [comment]
Okay, this is the full string, maybe I'm just doing something wrong
^1^T^SPoint^T ^Sy^N24 ^Sx^N-20 ^t^SScale^N2.4 ^SRows^N12 ^SLocked^B ^SGUID^STMW:group:1Xhb3TammgGe ^SColumns^N1 ^SIcons^T ^N1^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SSPELLRANGE ^SUnit^Starget ^SLevel^N1 ^SName^SSunder~`Armor ^t^N2^T ^SType^SALIVE ^SUnit^Starget ^t^N3^T ^SType^SREACT ^SUnit^Starget ^SLevel^N1 ^t^Sn^N3 ^t^SGUID^STMW:icon:1XhbbtgEwtOV ^SEvents^T ^N1^T ^SType^SAnimations ^SOnlyShown^B ^SAnimation^SICONFLASH ^SEvent^SWCSP ^t^Sn^N1 ^t^SSettingsPerView^T ^Sicon^T ^STextLayout^STMW:textlayout:1XhdSVpux5aX ^STexts^T ^N1^SRange ^t^t^t^SCustomTex^S6603 ^SEnabled^B ^t^N2^T ^SShowTimer^B ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SDEBUFFSTACKS ^SOperator^S> ^SUnit^Starget ^SName^SSunder~`Armor ^t^N2^T ^SType^SDEBUFFDUR ^SOperator^S< ^SUnit^Starget ^SLevel^N5 ^SName^SSunder~`Armor ^t^N3^T ^SType^SDEBUFFDUR ^SUnit^Starget ^SName^SExpose~`Armor ^t^N4^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbbtgEwtOV ^t^Sn^N4 ^t^SShowTimerText^B ^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^ST ^t^t^t^SGUID^STMW:icon:1XiMz69gaEuf ^SCustomTex^SSunder~`Armor ^t^N3^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SBUFFDUR ^SChecked^B ^SAndOr^SOR ^SName^SBattle~`Shout ^t^N2^T ^SType^SBUFFDUR ^SChecked^B ^SName^SCommanding~`Shout ^t^N3^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbbtgEwtOV ^t^N4^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XiMz69gaEuf ^t^Sn^N4 ^t^SGUID^STMW:icon:1Xhb3TbQAjOr ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^S4 ^t^t^t^SCustomTex^SBattle~`Shout ^SEnabled^B ^t^N4^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SSPELLCD ^SOperator^S< ^SLevel^N1.5 ^SName^SBloodthirst ^SPrtsBefore^N2 ^t^N2^T ^SType^SSPELLCDCOMP ^SName2^SWhirlwind ^SOperator^S<= ^SName^SBloodthirst ^t^N3^T ^SType^SHEALTH ^SPrtsAfter^N1 ^SOperator^S> ^SUnit^Starget ^SLevel^N20 ^t^N4^T ^SType^SSPELLCD ^SPrtsAfter^N2 ^SAndOr^SOR ^SName^SBloodthirst ^SPrtsBefore^N1 ^t^N5^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbbtgEwtOV ^t^N6^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XiMz69gaEuf ^t^N7^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbQAjOr ^t^N8^T ^SType^SPTSINTAL ^SLevel^N1 ^SName^SBloodthirst ^t^Sn^N8 ^t^SGUID^STMW:icon:1XhbHq4fVEyd ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SF ^t^t^SLuaCode^T ^STextLayout^S ^t^t^SCustomTex^SBloodthirst ^SEnabled^B ^t^N5^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SSPELLCD ^SOperator^S< ^SLevel^N1.5 ^SName^SWhirlwind ^SPrtsBefore^N2 ^t^N2^T ^SType^SHEALTH ^SPrtsAfter^N1 ^SOperator^S> ^SUnit^Starget ^SLevel^N20 ^t^N3^T ^SType^SSPELLCD ^SPrtsAfter^N2 ^SAndOr^SOR ^SName^SWhirlwind ^SPrtsBefore^N1 ^t^N4^T ^SType^SSTANCE ^SName^SBerserker~`Stance ^t^N5^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbbtgEwtOV ^t^N6^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XiMz69gaEuf ^t^N7^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbQAjOr ^t^N8^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbHq4fVEyd ^t^Sn^N8 ^t^SGUID^STMW:icon:1Xhb3TbXJ24p ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SG ^t^t^SLuaCode^T ^STextLayout^S ^t^t^SCustomTex^SWhirlwind ^SEnabled^B ^t^N6^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SHEALTH ^SOperator^S<= ^SUnit^Starget ^SLevel^N20 ^t^N2^T ^SType^SSTANCE ^SName^SBattle~`Stance;~`Berserker~`Stance ^t^N3^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbbtgEwtOV ^t^N4^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XiMz69gaEuf ^t^N5^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbQAjOr ^t^N6^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbHq4fVEyd ^t^N7^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbXJ24p ^t^Sn^N7 ^t^SGUID^STMW:icon:1Xhb3TbeaV8t ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SV ^t^t^SLuaCode^T ^STextLayout^S ^t^t^SCustomTex^SExecute ^SEnabled^B ^t^N7^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SREACTIVE ^SName^SRampage ^t^N2^T ^SType^SBUFFDUR ^SOperator^S<= ^SLevel^N5 ^SName^SRampage ^t^N3^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbbtgEwtOV ^t^N4^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XiMz69gaEuf ^t^N5^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbQAjOr ^t^N6^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbHq4fVEyd ^t^N7^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbXJ24p ^t^N8^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbeaV8t ^t^Sn^N8 ^t^SGUID^STMW:icon:1Xhb=vuW5mif ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SH ^t^t^t^SCustomTex^SRampage ^SEnabled^B ^t^N8^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SREACTIVE ^SName^SVictory~`Rush ^t^N2^T ^SType^SSTANCE ^SName^SBattle~`Stance;~`Berserker~`Stance ^t^N3^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbbtgEwtOV ^t^N4^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XiMz69gaEuf ^t^N5^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbQAjOr ^t^N6^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbHq4fVEyd ^t^N7^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbXJ24p ^t^N8^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbeaV8t ^t^N9^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb=vuW5mif ^t^Sn^N9 ^t^SGUID^STMW:icon:1XiMiRbbhXeH ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SC ^t^t^t^SCustomTex^SVictory~`Rush ^SEnabled^B ^t^N9^T ^SShowTimer^B ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SDEBUFFSTACKS ^SOperator^S< ^SUnit^Starget ^SLevel^N5 ^SName^SSunder~`Armor ^t^N2^T ^SType^SDEBUFFDUR ^SUnit^Starget ^SName^SExpose~`Armor ^t^N3^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbbtgEwtOV ^t^N4^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XiMz69gaEuf ^t^N5^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbQAjOr ^t^N6^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbHq4fVEyd ^t^N7^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbXJ24p ^t^N8^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbeaV8t ^t^N9^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb=vuW5mif ^t^N10^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XiMiRbbhXeH ^t^Sn^N10 ^t^SShowTimerText^B ^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^ST ^t^t^t^SGUID^STMW:icon:1XihzzqyfIeA ^SCustomTex^SSunder~`Armor ^t^N10^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SSPELLCD ^SOperator^S>= ^SLevel^N2 ^SName^SBloodthirst ^t^N2^T ^SType^SSPELLCD ^SOperator^S>= ^SLevel^N2 ^SName^SWhirlwind ^t^N3^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XihzzqyfIeA ^t^N4^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XiMiRbbhXeH ^t^N5^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb=vuW5mif ^t^N6^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbeaV8t ^t^N7^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbXJ24p ^t^N8^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbHq4fVEyd ^t^N9^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Xhb3TbQAjOr ^t^N10^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XiMz69gaEuf ^t^N11^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1XhbbtgEwtOV ^t^Sn^N11 ^t^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SR ^t^t^t^SCustomTex^SHamstring ^SEnabled^B ^t^N11^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SRAGE_ABS ^SOperator^S>= ^SLevel^N42 ^t^Sn^N1 ^t^SEvents^T ^N1^T ^SType^SAnimations ^SOnlyShown^B ^SAnimation^SACTVTNGLOW ^SEvent^SWCSP ^SOnConditionConditions^T ^N1^T ^SType^SRAGE_ABS ^SOperator^S>= ^SLevel^N54 ^t^Sn^N1 ^t^t^N2^T ^SAnimColor^S7f00ff00 ^SType^SAnimations ^SOnlyShown^B ^SAnimation^SICONSHAKE ^SEvent^SWCSP ^SOnConditionConditions^T ^N1^T ^SType^SCURRENTSPELL ^SName^SHeroic~`Strike ^t^Sn^N1 ^t^t^Sn^N2 ^t^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SWU ^t^t^t^SCustomTex^SHeroic~`Strike ^SEnabled^B ^t^N12^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SRAGE_ABS ^SOperator^S< ^SLevel^N42 ^t^N2^T ^SType^SCURRENTSPELL ^SName^SHeroic~`Strike ^t^Sn^N2 ^t^SEvents^T ^N1^T ^SType^SAnimations ^SOnlyShown^B ^SAnimation^SICONFLASH ^SEvent^SWCSP ^t^Sn^N1 ^t^SSettingsPerView^T ^Sicon^T ^STextLayout^STMW:textlayout:1XhdSVpux5aX ^STexts^T ^N1^SCancel ^t^t^t^SCustomTex^SHeroic~`Strike ^SEnabled^B ^t^N13^T ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SH ^t^t^t^SEnabled^B ^t^t^SSortPriorities^T ^N1^T ^SMethod^Sfakehidden ^t^N2^T ^SMethod^Sshown ^SOrder^N-1 ^t^N3^T ^SMethod^Sid ^SOrder^N1 ^t^t^SLayoutDirection^N8 ^SName^SFury~`Warrior~`Single~`Target ^t^N92200^S~`~| ^Sgroup^N1 ^^

^1 ^T^N1^T ^SAnchors^T ^N1^T ^Sx^N1 ^SrelativeTo^SIconModule_SelfIcon ^t^t^SSize^N8 ^t^SGUID^STMW:textlayout:1XhdSVpux5aX ^SName^SIcon~`Layout~`2 ^t^N92200^S~`~| ^Stextlayout^STMW:textlayout:1XhdSVpux5aX ^^

**Comment by ascott18** [comment]
Thanks. The issue was indeed an unfortunate interaction with the Icon Is Shown conditions. 

While you wait for the fix to become available, if you move the talent check condition to be the first condition on the icon (before the spell CD) then it should work.

**Comment by Speaker1264** [comment]
That seems to work! I thought I was going crazy because it was working sometimes, and then I would reload and it would stop working, and sometimes after opening the tellmewhen options it would start working again, and sometimes it just wouldn't work at all.  I kept trying to change things to figure out what was causing it, but finally this seems to be the fix.  Thank you!
