### ISSUE TITLE
[Bug]: 毁灭术士守护者监控地狱火时间BUG

### ISSUE THREAD

**Issue by mmqqll2** [ascott18/TellMeWhen#1939]
### WoW Version

Retail

### TellMeWhen Version

9.2.2

### Describe the bug

您好

9.2版本   术士的天赋[混乱之雨][地狱火爪牙]
或者[4件套装效果][地狱火]持续时间是8秒,
但是守护者监控限时为30秒,时间错误

![1](https://user-images.githubusercontent.com/74142534/174126357-fb7092bf-3276-4f40-ac0d-00893b195d96.jpg)

![20220617010404](https://user-images.githubusercontent.com/74142534/174126724-040ec27f-6d40-4298-8cd8-3bbfef67c0e8.png)

### Export Strings

```text
^1^T^SType^Sguardian ^SName^S地狱火爪牙 ^SEnabled^B ^t^N92300^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
Unfortunately I can only address issues in English.
