### ISSUE TITLE
[Feature Request] Add conduit slotted & active to Conditions

### ISSUE THREAD

**Issue by Wisdawn** [ascott18/TellMeWhen#1940]
**Is your feature request related to a problem? Please describe.**
I cannot add a TMW reminder for my Hunter to cast Hunter's Mark on bosses or mini-bosses when the Marksman's Advantage conduit is slotted and active. And frankly, I found it rather strange that I can check for "Piercing Scope" Torghast Anima Power count != or > 0 to remind my Hunter to cast Hunter's Mark on any target in Torghast for the significantly increased damage, but not check for a slotted and active conduit.

**Describe the solution you'd like**
I add my vote to @Lunchie's, @goodNight's, and @Naermorth's on the Discord #hunter channel, asking you to please add the option to check for conduits being slotted and active. This will not just be used for the Hunter class or just the Hunter's Mark. There are plenty of other conduits that can go to waste if the player is not reminded to use their relevant spells at the right time(s), like the Hunter's Feign death to reduce incoming damage, even when aggro is not an issue and the hunter isn't being targeted for any big attack, and like the Warlock's ability to gain a speed boost after popping a gate, and so on.

I am aware of the "just learn your class" argument, of course, but this is easier said than done for altoholics and players returning to long-parked classes or from a hiatus. TMW makes picking up a slightly unfamiliar class much easier for its users, and a condition for conduits will enhance this ability for the rest of the SL expansion.

**Describe alternatives you've considered**
Without playing around with LUA code, the only alternative that I could think of was to add a Hunter's Mark Buff/Debuff icon, "Only cast by me," Hidden when Present, 100% showing when All Absent, and conditions: target Unit is Alive, target Unit Reaction is Hostile, and (Torghast Anima Power Count of Piercing Scope != 0 OR target Unit Level == Boss OR target Unity is a Player).

This is not ideal, of course, because this will not remind you to use Hunter's Mark against dangerous M+ mobs, for example, that cast semi-unavoidable AoE damage, and you _will_ be reminded to use it even when the Marksman's Advantage conduit is not active and/or slotted, but this is the best I could think of without playing around with LUA code.

**Comment by ascott18** [comment]
Since Shadowlands is now essentially over, I won't be adding this. Sorry that it never happened.
