### ISSUE TITLE
[Bug]: Guardian timer tracker for Warlock not working properly

### ISSUE THREAD

**Issue by Betaskill** [ascott18/TellMeWhen#1941]
### WoW Version

Retail

### TellMeWhen Version

9.2.3
( With German client)

### Describe the bug

Hello there,

I have found a little bug, at least I expect that it is a bug. 

With my warlock I am using the guardian timer for my wild imps and noticed that the timer is slightly out of touch. I was using a weakaura to see if I am not mistaking and also taking a look at the imps. 

The timer is still running around 1-2 seconds after the imps have despawned. Also the timer will keep up running if I am out of combat, but I expect that this is due to the reason that it is using an internal timer. 

The reason why this is important is because I wanna use my imp explosion on time and if the timer is out of touch some imps will "survive" I am missing some imps to blow up. ( Yeah, I hate my imps)

I have also made a little video in the case that my english and explanation is not properly:

https://youtu.be/IdFrQrIjOgM

Edit: I found out right now that if you are summoning the " Demonic Tyrant " while having a set of imps the icon will simply not be shown anymore. For me it looks like the guardian tracker is assuming that you are not having any imps up anymore. Even after the tyrant has despawned the icon will not come back to be visible. If I am spawning new imps the icon will appear with the timer of the freshly spawned new imps.

Possible to fix that?

Greetings 

Betaskill (former Mindfork)

### Export Strings

```text
^1^T^SShowTimer^B ^SSort^N-1 ^SDurationMin^N3 ^SType^Sguardian ^SShowTimerText^B ^SName^S55659 ^SEnabled^B ^SDurationMax^N10 ^t^N92300^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
Ultimately the issue is that wild imps don't work the way they used to anymore. They live for up to 5 casts of their firebolt, rather than a fixed amount of time. So, trying to show any kind of timer for them is a bit of an impedance mismatch. 

I don't have a good answer for this problem, unfortunately.

**Comment by ascott18** [comment]
Merging into #1941
