### ISSUE TITLE
[Bug]: Pet's spells

### ISSUE THREAD

**Issue by hustlerwrld** [ascott18/TellMeWhen#1942]
### WoW Version

Retail

### TellMeWhen Version

9.2.3

### Describe the bug

The condition "Spell in radius of unit" does not consider spells like devour magic of the warlock's felhunter. It cannot be done so that it is tracked like "target" or "pettarget", or something else. It is not possible to make sure that the range of use of the spell is tracked by a pet controlled by the player.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Correct - this is not possible, because there's no API for this.
