### ISSUE TITLE
[Feature Request]更多的运算

### ISSUE THREAD

**Issue by zhubinabc** [ascott18/TellMeWhen#1943]
兽王猎可能需要更复杂的数值运算过程，比如：
(最大集中值-当前集中值)/集中值恢复速度>杀戮命令冷却时间(不考虑公共CD)

**Comment by ascott18** [comment]
Unfortunately I'm not really able to assist with issues that aren't reported in English.

Best I can tell from Google Translate is that you're trying to write complex conditional logic. You can try a Lua condition for that.
