### ISSUE TITLE
[Bug]:version

### ISSUE THREAD

**Issue by krugerminer** [ascott18/TellMeWhen#1950]
### WoW Version

TBC Classic

### TellMeWhen Version

9.2.4

### Describe the bug

![9c53d2a25fe589909bc4fb0cbd1f95df](https://user-images.githubusercontent.com/112727625/188225220-a5f6776e-382a-49d6-a52f-a7837087f02f.png)

Addon isn't recognizing game version properly after the launcher update today.

Worked fine yesterday but not today with no change to addon.

Please save me I can't play without TMW, I'm bad. 

### Export Strings

```text
N/A
```

**Comment by muhshuh** [comment]
I also have this error. Temporary fix is to just delete the version check entirely.

lines 77-92 of:
C:\Program Files (x86)\World of Warcraft\_classic_\Interface\AddOns\TellMeWhen\TellMeWhen.lua

Not sure of unforeseen consequences, but if you can't play without it... worth trying.

**Comment by issa-beep** [comment]
Open TellMeWhen.lua with notepad

Find: WOW_PROJECT_BURNING_CRUSADE_CLASSIC

Replace with: WOW_PROJECT_WRATH_CLASSIC

This will fix the error.

**Comment by ascott18** [comment]
Issue was fixed by https://github.com/ascott18/TellMeWhen/releases/tag/9.2.5-wrath
