### ISSUE TITLE
[Bug]: TellMeWhen won't load/says wrong version

### ISSUE THREAD

**Issue by Geminine** [ascott18/TellMeWhen#1952]
### WoW Version

TBC Classic

### TellMeWhen Version

tellmewhen-9.2.5-wrath.zip

### Describe the bug

Upon entering wrath pre-patch game with most current version of TMW downloaded, a warning is given stating "You've installed TellMeWhen for Classic TBC/Wrath, but this is Wrath of the Lich King. Please double-check which version of TMW you downloaded." It then gives the option to Reload UI or cancel.  Reload UI does nothing and cancel just removes the warning.  In either instance TMW is not present and cannot be used in game.

### Export Strings

```text
n/a
```

**Comment by shimo-sudo** [comment]
https://github.com/ascott18/TellMeWhen/issues/1950

This was fixed yesterday, update your addon. :)

**Comment by ascott18** [comment]
If this is still happening with 9.2.5-wrath, its because your WoW client is not updated. Exit completely and check for updates in the bnet launcher. You need to be on at least build 45435.

![image](https://user-images.githubusercontent.com/5017521/188283302-9c7983fd-3fcf-4956-8008-db21ca55f23f.png)

**Comment by Geminine** [comment]
Thank you for the quick response.  Unfortunately I am on version 3.4.0.45435 and I have updated the add on as well.  All of my other add ons are working fine except for this

**Comment by ascott18** [comment]
@Geminine Please run this command and share the output:

`/dump TELLMEWHEN_VERSION, WOW_PROJECT_ID, GetBuildInfo()`

**Comment by Geminine** [comment]
Dump: value=TELLMEWHEN_VERSION, WOW_PROJECT_ID,
  GetBuildInfo()
  [1]="9.2.4",
  [2]=11,
  [3]="3.4.0",
  [4]="45435",
  [5]="Sep 1 2022",
  [6]=30400
