### ISSUE TITLE
[Bug]: Dragonflight Alpha - Troubleshooting Icon invisible

### ISSUE THREAD

**Issue by J-Gierend** [ascott18/TellMeWhen#1962]
### WoW Version

Retail

### TellMeWhen Version

v9.2.6 r12 g15b287f

### Describe the bug

<img width="445" alt="image" src="https://user-images.githubusercontent.com/39157646/193421634-e1e57f2d-8d24-4ff1-a244-c0af6e31735c.png">

"Troubleshooting Icon" is now invisible instead of solid color.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Can you help me understand what you're expecting to happen in this situation? You entered the word "Troubleshooting" as a custom texture, but I'm not aware of any spells in the game named "Troubleshooting", so it would indeed have no effect.

**Comment by J-Gierend** [comment]
<img width="439" alt="image" src="https://user-images.githubusercontent.com/39157646/193573256-beb2a73a-e36a-4627-92c9-4d268167d5cc.png">
Troubleshooting is a solid color Icon wich is defined here in the text about custom Textures.

If i use the same icon in Retail with TMW i get the following result : 
<img width="453" alt="image" src="https://user-images.githubusercontent.com/39157646/193573553-1a5012b1-babc-472c-93b3-44dab03c7dfe.png">

**Comment by J-Gierend** [comment]
Maybe i misunderstood this behaviour in retail as a way to make solid color icons (wich i prefer to normal icons). I guess i could make my own solid color icons and put them as custom textures into the wow subfolder to fix this problem. I was just used to use the "Troubleshooting" custom Texture to get this behaviour.

**Comment by ascott18** [comment]
"Troubleshooting" is the heading for that paragraph that includes instructions on what to do if your custom texture isn't working (which, when it isn't working, is usually a green square). Again. there are no textures or spells named "Troubleshooting" in the game. You could have just as well entered "asdsdlkfjladksf" into that input and gotten the same effect.

The fact that invalid textures render as green squares is entirely up to the whims of Blizzard. It seems that right now on beta, invalid textures render invisibly. Sometimes they change this behavior during betas while they're developing the UI. It may stay like that when DF goes live, or it may not. But its not something that I made a change around, and not something that I have any control over.
