### ISSUE TITLE
[Bug]: DF Beta: TMW is randomly disappearing after login/reload

### ISSUE THREAD

**Issue by Draculla-NOLIFE** [ascott18/TellMeWhen#1964]
### WoW Version

Retail

### TellMeWhen Version

9.2.3

### Describe the bug

TMW is randomly disappearing after login/reload on DF Beta. I have to type /tmw and /tmw again to show all bars again. 

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Potentially fixed in 1d4ba370, but without any error messages its hard to say.
