### ISSUE TITLE
[Bug]: Condition, Points in Talent

### ISSUE THREAD

**Issue by nogueirups** [ascott18/TellMeWhen#1966]
### WoW Version

Retail

### TellMeWhen Version

9.2.6 r17

### Describe the bug

The Rogue talent "Deeper Stratagem" have to way with add a seven point at combo points, with it we need to add a second pont in this talent! actually its work with one!

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Not sure that I follow. Could you share a screenshot indicating where the issue is?
