### ISSUE TITLE
[Bug]: Masque skins disappearing

### ISSUE THREAD

**Issue by AddonWhiner** [ascott18/TellMeWhen#1973]
### WoW Version

Retail

### TellMeWhen Version

10.0.0

### Describe the bug

Upon logging in or reloading UI, my TMW icons use the Masque Serenity appearance, as I want and as they were before the patch. I don't know all the things that make them revert to standard squares, but /tmw is one of them.

Might be this is a Masque issue, as I see nowhere in neither TMW nor Masque to actually specify that it's Serenity I want, but my ElvUI actionbars are staying Serenity without issue.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
At the time you posted this issue, Masque did not support WoW 10.0. There's now a version that does. https://www.curseforge.com/wow/addons/masque/files/4052818
