### ISSUE TITLE
[Bug]: Unrecognized XML attribute: Urgency

### ISSUE THREAD

**Issue by kdubato** [ascott18/TellMeWhen#1974]
### WoW Version

Retail

### TellMeWhen Version

10.0.0

### Describe the bug

Apologies if there is something I missed but wanted to post this in case. 

After installing the latest version of TellMeWhen yesterday 10.0.0 for Dragonflight prepatch, I'm getting 41 lua errors when I enter the game.  Instead of posting all 41, I copied a few of them to show the different files they are coming from, they have the same error, "Unrecognized XML Attribute:  Urgency", but one has Unrecognized XML: Binding.

Note, I have tried disabling all other addons except TellMeWhen, and the same 41 lua errors appear.

------------------------------------------------------------------------
Message: Interface/AddOns/TellMeWhen/Options/Bindings.xml:9 Unrecognized XML: Binding
Time: Wed Oct 26 12:39:30 2022
Count: 2

------------------------------------------------------------------------
Message: Interface/AddOns/TellMeWhen/Options/TMWUIDropDownMenuTemplates.xml:323 Unrecognized XML attribute: urgency
Time: Wed Oct 26 12:39:30 2022
Count: 2

------------------------------------------------------------------------
Message: Interface/AddOns/TellMeWhen/Options/TMWUIDropDownMenuTemplates.xml:328 Unrecognized XML attribute: urgency
Time: Wed Oct 26 12:39:30 2022
Count: 2

------------------------------------------------------------------------
Message: Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:259 Unrecognized XML attribute: urgency
Time: Wed Oct 26 12:39:30 2022
Count: 2

------------------------------------------------------------------------
Message: Interface/AddOns/TellMeWhen/Components/Core/IconEvents/config.xml:81 Unrecognized XML attribute: urgency
Time: Wed Oct 26 12:39:30 2022
Count: 2

------------------------------------------------------------------------
Message: Interface/AddOns/TellMeWhen/Components/GroupModules/GroupModule_IconPosition_Sortable/Config.xml:38 Unrecognized XML attribute: urgency
Time: Wed Oct 26 12:39:30 2022
Count: 2

------------------------------------------------------------------------
Message: Interface/AddOns/TellMeWhen/Components/IconModules/IconModule_Texts/Config.xml:1009 Unrecognized XML attribute: urgency
Time: Wed Oct 26 12:39:30 2022
Count: 2

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
These aren't errors, but rather as the title of the dialog that you saw them in states, just warnings.

**Comment by Sagan99OU812** [comment]
> These aren't errors, but rather as the title of the dialog that you saw them in states, just warnings.

Awesome, how can we get rid of the 41 warnings?

**Comment by StreetLight777** [comment]
> These aren't errors, but rather as the title of the dialog that you saw them in states, just warnings.

I don’t understand - they show as lua errors in game. So we just have to see and dismiss these lua errors every time we boot into the game from now on? Forever?

**Comment by StreetLight777** [comment]
It seems I can use the console command below to permanently disable all lua warnings and errors together, but I don’t want to do that as it seems like I’d be throwing the baby out with the bath water and not having visibility to true errors in other addons.  I’d like to actually better understand the root cause of all these warnings so I can fix it at the source. 

/console scriptErrors 0

**Comment by kdubato** [comment]
@ascott18 ... did you close the ticket because I worded it wrong?  Or are you saying because the user is only greeted with 41 "warnings" every time they login to the game (or /reloadui), you don't plan on doing anything to make them go away?

**Comment by ascott18** [comment]
I closed it because the issue has been fixed. https://www.curseforge.com/wow/addons/tellmewhen/files/4053188

**Comment by StreetLight777** [comment]
Got it thanks - this particular release (that contains the fix) didn't appear to have been published to my Curseforge client yet, so we just assumed it was being closed without being fixed. Manually installing outside of the Curseforged client did the trick... thanks!

**Comment by kdubato** [comment]
> I closed it because the issue has been fixed. https://www.curseforge.com/wow/addons/tellmewhen/files/4053188

> this particular release (that contains the fix) didn't appear to have been published to my Curseforge client yet, so we just assumed it was being closed without being fixed. 

This is what I thought as well, my apologies and I was able to find the updated version in Curseforge under the "Versions" tab after clicking on TellMeWhen.  Thanks a lot to @ascott18 and/or his team for putting the fix up so quickly.
