### ISSUE TITLE
[Bug]: 2x Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:262 Unrecognized XML attribute: urgency

### ISSUE THREAD

**Issue by Sagan99OU812** [ascott18/TellMeWhen#1976]
### WoW Version

Retail

### TellMeWhen Version

TellMeWhen-10.0.0

### Describe the bug

I'm getting 41 lua errors whenever I log into wow.
Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:262 Unrecognized XML attribute: urgency
or 3x Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.xml:836 Unrecognized XML attribute: change

Only addons enabled is Tellmewhen and Tellmewhen Options.

I have tried to rename tellmewhen folders under addons and WTF and redownloaded Tellmewhen, but still same problem.
TIA

### Export Strings

```text
N/A
```

**Comment by raysmith59** [comment]
Same.

**Comment by StreetLight777** [comment]
I too have this same error when logging in. I have the latest version, latest Windows 11 updates/build, latest NVidia drivers, etc. This is the only addon I am using.
![Snag_104661](https://user-images.githubusercontent.com/61394031/198177337-0d352454-23b8-4c2e-9c5b-123f8e6c8c62.png)

**Comment by ascott18** [comment]
Duplicate of #1974
