### ISSUE TITLE
[Bug]: A text layout issue?

### ISSUE THREAD

**Issue by WickedSeth47** [ascott18/TellMeWhen#1977]
### WoW Version

Retail

### TellMeWhen Version

10.0.0

### Describe the bug

Hi this lua error appears every time I login or change specs on a character I have tried loading only TMW and TMW options to see if there is any conflict but the same error still pops up. I also have tried loading the TMW with the "show numbers for cooldowns" ON, and got the same results. the addon seems to work alright and shows the rotations from pre-patch profiles that are already on it, other than that nothing seems to be wrong. for the time being I have installed BugSack addon to silence the pop ups.

the lua error massage:

Message: TellMeWhen: ...en/Components/IconModules/IconModule_Texts/Texts.lua:696: bad argument #1 to 'SetEndDelay' (must be a finite number - Usage: self:SetEndDelay(delaySec [, recomputeGroupDuration]))
Time: Thu Oct 27 15:25:16 2022
Count: 1
Stack: TellMeWhen: ...en/Components/IconModules/IconModule_Texts/Texts.lua:696: bad argument #1 to 'SetEndDelay' (must be a finite number - Usage: self:SetEndDelay(delaySec [, recomputeGroupDuration]))
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2875: in function <Interface/AddOns/TellMeWhen/TellMeWhen.lua:2832>

Locals: <none>

### Export Strings

```text
N/A
```

**Comment by Alwies** [comment]
Another small addition: Causes text from text displays to be invisible
