### ISSUE TITLE
[Bug]: Soul Rot (new affliction talent/old warlock covenant ability) spell cooldown not tracking if tracked by name.

### ISSUE THREAD

**Issue by Alwies** [ascott18/TellMeWhen#1978]
### WoW Version

Retail

### TellMeWhen Version

10.0.0

### Describe the bug

In the pre patch the Night Fae covenant (warlock) ability was made into a talent for affliction warlocks.
When picking this new talent and tracking it using the name in a spell cooldown icon type it'll always show as ready even when the ability is on CD(no CD swipe when checked and using the ready opacity). 
This can be fixed by tracking it as ID instead (386997 in this case). 

Just to test I unlearned the talent and went to the Shadowlands to test the covenant ability which worked as expected being trackable with either name or ID. 
When having both the talent and being in a Shadowlands zone the behavior was the same with it tracking as name depending on which the 2 Soul rot's I use from the spellbook. It's not possible to use them both as separate abilities despite only 1 showing as on cooldown in the spellbook itself.
Likely this is an issue due to blizzards (weird) implementation of them being the same spell but one being restricted to Shadowlands zones.

This comment on the TMW discord https://gyazo.com/3903bdb0f6d96fac9c59494f8d95469d suggest this may be the case for other now talent and previous covenant abilities as well. 

The export string is the group I used to test. 

Edit: To add no lua errors, suppose it could be argued whether this is a bug at all. But figured I'd leave that for you to decide.

### Export Strings

```text
^1^T^SGUID^STMW:group:1ZMh67wjz3im ^SRows^N2 ^SPoint^T ^Sy^F7012642212282368 ^f-46^Spoint ^SRIGHT^SrelativePoint ^SRIGHT^Sx ^N-206.416015625^t ^SName^Ssoul~`rot~`test ^SIcons^T ^N1^T ^SShowTimer^B ^SType^Scooldown ^SShowTimerText^B ^SName^S386997 ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SNEW~`TALENT~`WORKING~`ID ^t^t^t^SStates^T ^N2^T ^SColor^Sffffffffd ^SAlpha^N0.51 ^t^t^SEnabled^B ^t^N2^T ^SShowTimer^B ^SType^Scooldown ^SShowTimerText^B ^SName^SSoul~`Rot ^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^Sname ^t^t^t^SStates^T ^N2^T ^SColor^Sffffffffd ^SAlpha^N0.48 ^t^t^t^N3^T ^SShowTimer^B ^SType^Scooldown ^SShowTimerText^B ^SName^S325640 ^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SOLD~`ID~` ^t^t^t^SStates^T ^N2^T ^SColor^Sffffffffd ^SAlpha^N0.47 ^t^t^t^t^t^N100000^S~`~| ^Sgroup^N2 ^^
```

**Comment by ascott18** [comment]
Is this still broken, or did Blizz perhaps fix it? Just tried with Abomination Limb, both talented and untalented, and both in shadowlands and out (well, untalented + outside of SL doesn't work obviously).

**Comment by Alwies** [comment]
For the case of Soul Rot yes.

**Comment by ascott18** [comment]
Since this issue will only be a thing for another month or so, and since its a bug in Blizzard's API, and a workaround is available (tracking by ID), I won't be implementing any kind of fix for this.
