### ISSUE TITLE
Button that auto disables aura if spell not known (for dragonlands talents)

### ISSUE THREAD

**Issue by mtdagny** [ascott18/TellMeWhen#1979]
Redoing my auras for dragonlands and finding it time consuming and annoying to constantly have to create a condition where I don't see the aura if I don't have a point in the talent.  Would be so much simpler if there was a button like range check that I click to only show if spell is known.  Thanks

**Comment by ascott18** [comment]
This is already normal behavior for cooldown icons when tracking spells by name. For buff/debuff icons, this would require me maintaining a mapping between all talents and the buffs/debuffs that they apply (since quite often these are not the same names), which is just not going to happen.
