### ISSUE TITLE
[Bug]: ElvUI timer text is not visible inside the TMW Icon

### ISSUE THREAD

**Issue by Vmihai95** [ascott18/TellMeWhen#1985]
### WoW Version

Retail

### TellMeWhen Version

10.0.1

### Describe the bug

Preconditions:

1. Have ElvUI latest version installed (12.98) 
2. Disable Blizzard cooldown timers 

Steps:
1. Create aura icon in tellmewhen which should track the timer left on a buff/debuff/spell cooldown etc.
2. Check "Show timer" and "Show ElvUI timer Text" options in the "Timer Sweep" section

Expected Results:
The timer should be visible inside the icon

Actual Results:
The timer is not visible inside the Icon, only the icon progression

![71d804f469d31234036c5336fad5247a](https://user-images.githubusercontent.com/97759739/199103738-f9173ba0-adda-4377-8fef-37bfd7db4610.png)

### Export Strings

```text
N/A
```

**Comment by Vmihai95** [comment]
I seen the same issue being reported recently, but the newest Elvui update might have broken it again

**Comment by ascott18** [comment]
Works for me. Make sure you have this feature enabled in ElvUI's options too.

**Comment by Vmihai95** [comment]
It is fixed now  on  retail using ElvUI 12.99 and TMW 10.0.1

Unfortunately it is broken on wrath classic using ElvUI 12.99 and TMW 9.2.5 (9/2/2022) 
![fee7865ac65e14a1c265181420a0a3ef](https://user-images.githubusercontent.com/97759739/199282365-83620e22-0b23-461b-8350-06b137e2b0a8.png)

**Comment by amaea** [comment]
> Works for me. Make sure you have this feature enabled in ElvUI's options too.
Which feature are you referring to specifically?

The issue seems resolved on Retail, but it persists on Classic/Wrath. A prior bug report mentioned it breaking for the 12.95 release of ElvUI - this is consistent with my experience. I'm wondering if there's a current workaround whilst waiting for TMW v10 for patch 3.4.0? I've rolled back to ElvUI 12.94, but I'd like to utilize some of the additions to ElvUI in their latest release.

**Comment by ascott18** [comment]
@amaea @Vmihai95 #1986 is the tracking issue for classic/wrath. 

@amaea The feature I'm referring to is the cooldown timer feature.

**Comment by Vmihai95** [comment]
@ascott18  I mentioned in a comment 5 days ago it got fixed for me (on retail) after the newest ElvUI update (12.99) . 

The problem is currently present in wrath using ElvUI 12,99, I had to downgrade it to 12.91 in order to have it work in Wrath

**Comment by ascott18** [comment]
@Vmihai95 Yes, I must once again iterate that #1986, not this issue, is the issue for it being broken in wrath.
