### ISSUE TITLE
[Bug]: Stuttering caused when TMW plays notification sound.

### ISSUE THREAD

**Issue by zzipsa22** [ascott18/TellMeWhen#1988]
### WoW Version

Retail

### TellMeWhen Version

10.0.1

### Describe the bug

Strictly speaking, this is not a bug, and It may not be a problem caused by TMW, but if the sound channel is set to MASTER in TMW options, small stuttering is caused when every time notification sounds are played.

I'm not sure whether this is caused only in combat or not, but other addons that seems play sound to MASTER channel are OK even in combat. (ex. omen3, Nugcombobar)

Changing sound channel to other channels except MASTER solves this issue for me.

Sorry for my bad english, but I wanna report this issue for someone that having same trouble like me.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
This isn't something that TMW has any control over whatsoever and is not something that can be fixed. If you don't have an SSD, I'd recommend that as a first step.
