### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Macmooney** [ascott18/TellMeWhen#1990]
### WoW Version

Retail

### TellMeWhen Version

10.0.1

### Describe the bug

I tracked Windfury Totem through TMW on my shaman, but since prepatch I can no longer click on the Windury Totem Icon on screen when opening TMW options. The icon doesn't even disappear after disabling nor deleting the whole addon. It does still work though, and disappears whenever I drop the totem and reappears when out of range or after the 2 minuten cd window. I don't have this problem on any other character and can't access the icon, nor move it or anything else. It is just there, altough it is nowhere shown in the options.
I also can't export a string as it literally doesn't show up on the addon.

### Export Strings

```text
N/A
```

**Comment by Alwies** [comment]
If it doesn't disappear after deleting the addon it's not TMW.
Though if you're not convinced you can find out by typing /fstack in chat. 
Hover over the icon, if it's TMW it'll include "TellMeWhen_GroupX_IconX" like it does here: https://gyazo.com/6f08fe21aed98f450dc92f1bdfc7c6b0

**Comment by ascott18** [comment]
Please ensure you've enabled Lua errors (`/console scriptErrors 1`) and post any errors that you're seeing that look like they relate to TMW.
