### ISSUE TITLE
Condition for Talent Loadouts

### ISSUE THREAD

**Issue by stamicvs** [ascott18/TellMeWhen#1992]
As in Dragonfloght the TalentUI will also support different Talent Loadouts by default it would be great to be able to set up group and icon conditions based on those loadouts.
Currently we can create conditions on talent points added but the loadout condition would allow us to only show groups or icons if a specific loadout is active.

**Comment by ascott18** [comment]
Added in fd19b85b83ec0a23132b40ecbc9bfac00e6e74f2
