### ISSUE TITLE
[Bug]: Error loading PlayerCombatStats.lua

### ISSUE THREAD

**Issue by Kilmatar** [ascott18/TellMeWhen#1993]
### WoW Version

Wrath Classic

### TellMeWhen Version

10.0.2R5

### Describe the bug

Message: Error loading Interface\AddOns\TellMeWhen\Components\Core\Conditions\Categories\PlayerCombatStats.lua
Time: Mon Nov  7 21:46:27 2022
Count: 3

Addon trying to load PlayerCombatStats.lua but this file now divided to PlayerCombatStats-Retail.lua and PlayerCombatStats-Wrath.lua so addon can't find file needed

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Thanks, fixed.
