### ISSUE TITLE
[Bug]: Range check on pet abilities does not work in any icon type or conditions.

### ISSUE THREAD

**Issue by wwdes** [ascott18/TellMeWhen#1994]
### WoW Version

Retail

### TellMeWhen Version

10.0.1

### Describe the bug

Just as title says. Tested on DK.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Ultimately this is a failing of the Blizzard API. The only thing that can be done, which I have done, is use the action bar API to check the range of pet abilities that you have on your pet action bar.
