### ISSUE TITLE
[Bug]: Rune Strike is not counted as a melee swing spell

### ISSUE THREAD

**Issue by Virtual-Crow** [ascott18/TellMeWhen#1996]
### WoW Version

Wrath Classic

### TellMeWhen Version

9.2.5

### Describe the bug

I made a swing timer icon to track Rune Strike (death knight next-hit ability similar to Heroic Strike and Maul), however the sweep timer stops counting down after every time I attack with Rune Strike activated. It seems as if a Rune Strike is not counted as a melee swing so the icon thinks I haven't attacked. The next time I hit something with an auto attack, the timer starts sweeping normally again. Copying the same icon to my druid and changing Rune Strike to Maul, the icon works like it should, it recognizes Maul as an auto attack and displays the swing timer properly. It seems like TellMeWhen is just not recognizing Rune Strike as an auto attack for swing timers.

I was able to fix this by replacing the spell id for Raptor Strike in this code with that of Rune Strike (56815), in the Components/Core/Common folder. A proper fix might be to add Rune Strike as an additional swing spell but I am not a programmer and not sure how to do this correctly.

![image](https://user-images.githubusercontent.com/117695758/200447374-6fa247bf-ae16-480f-8cea-a51e0da93e69.png)

### Export Strings

```text
^1^T^SShowTimer^B ^SType^Sswingtimer ^SConditions^T ^N1^T ^SType^SREACTIVE ^SName^SRune~`Strike ^t^Sn^N1 ^t^SGUID^STMW:icon:1ZQ66KvbSC3l ^SEvents^T ^N1^T ^SType^SAnimations ^SAnimation^SACTVTNGLOW ^SEvent^SWCSP ^SOnConditionConditions^T ^N1^T ^SType^SCURRENTSPELL ^SName^SRune~`Strike ^t^Sn^N1 ^t^t^Sn^N1 ^t^SCustomTex^SRune~`Strike ^SStates^T ^N102^T ^SColor^Sff808080 ^SAlpha^N1 ^t^t^SEnabled^B ^t^N92500^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
Thanks, fixed!
