### ISSUE TITLE
[Bug]: Coalescing Shadows buff stack tracking

### ISSUE THREAD

**Issue by Morjens** [ascott18/TellMeWhen#2002]
### WoW Version

Retail

### TellMeWhen Version

V10.0.1

### Describe the bug

Tracking of Shadowpriest talent Coalescing Shadow stacks works the first time. After the stacks are consumed the first time and you again gain 3 stacks TMW notices it after a very long delay

### Export Strings

```text
^1^T^SStackMinEnabled^B ^SType^Sbuff ^SStackMin^N3 ^SName^SCoalescing~`Shadows;~`Coalescing~`Shadows ^SCustomTex^S391243 ^SEvents^T ^N1^T ^SType^SAnimations ^SAnimation^SACTVTNGLOW ^SEvent^SOnShow ^t^Sn^N1 ^t^SEnabled^B ^SGUID^STMW:icon:1ZONmY74raK7 ^t^N100100^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
There are two different buffs named Coalescing Shadows. 391243 is the one that stacks to 3. 391244 is the one you get when you consume the stacks. Since you're only tracking the effect by name (twice?), TMW might pick either one. You need to track 391243.

**Comment by Morjens** [comment]
Oh yeah! Thankyou!
