### ISSUE TITLE
Support new UNIT_AURA stuff

### ISSUE THREAD

**Issue by ascott18** [ascott18/TellMeWhen#2003]
UNIT_AURA has been reworked again. Now with mandatory memory allocations on every event for every frame!

Probably need to develop a central UNIT_AURA handler to avoid allocations for every single icon. Also obviously need to support the new payload.

**Comment by ascott18** [comment]
I already finished everything, but its in a branch because i've been playing with it for a while because its been pretty buggy (UNIT_AURA payload has really annoying bugs, like firing updates of auras that were removed, or firing removals of auras that never existed)

**Comment by ascott18** [comment]
https://github.com/ascott18/TellMeWhen/compare/master...ascott/df-auras

**Comment by arieh** [comment]
that's super nice!

Obviously much cleaner than mine, but at least I was close with my idea. Seems like `TMW_UNITSET_UPDATED` takes care of all the edge cases I was worried about.

Any idea on when this is planned to land?

**Comment by ascott18** [comment]
I'll try to get to it (and your PR) this weekend. Been trying to knock down the flood of recent bug reports tonight.

**Comment by arieh** [comment]
Looking a bit into the code - do you think it will be possible to have a simpler utility on top of it that is more closely related to the old `GetAura`? 
Tried doing something like:
```lua

function tmwGetUnitAura(unit, spell, onlyMine)
	local name, rank, icon, castTime, minRange, maxRange, spellID = GetSpellInfo(spell)

	local unitStr = ConditionObject:GenerateUnitAuraString(unit, TMW:GetSpells(spell).First, onlyMine)

	local config = GetAuras(unitStr)
	local instances = config.instances
	local lookup = config.lookup

	local spellLookup =  lookup(spell) or lookup[spellID]

	for instanceId,_ in spellLookup do 
		if (instances[instanceId]) then
			return instances[instanceId]
		end
	end
	return nil
end
```

However it's hard for me to know if I'm missing something

**Comment by ascott18** [comment]
The unit parameter to GetAuras is only valid if `TMW.COMMON.Auras:RequestUnits(TMW.UNITS:GetUnitSet(unit))` returns true. Otherwise, it'll still create a set of tables for that unit, but those tables will never again be updated. For performance reasons, GetAuras doesn't do that validation every time you call it - that part is always done ahead of time.

**Comment by ascott18** [comment]
This is now in `master`.
