### ISSUE TITLE
Ability to change Buff/Debuff icon

### ISSUE THREAD

**Issue by realmsoft** [ascott18/TellMeWhen#2005]
-Issue-
Most proc buff/debuffs have different names/icons.  For example, when Serendipity on a  priest procs it's called "Serendipity" and shows a little speed blazzing mana icon.  However, what this is telling you is your Greater Heal is now ready to be cast. 

-Solution-
An option to show a different icon when the buff/debuff occurs/is missing, rather than the icon of the actual buff/debuff being monitored. In the example above, it would be great to show the "Greater Heal" icon instead of the "Serendipity" icon.

**Comment by ascott18** [comment]
That's what the custom texture option is for, and is available for all icon types.
