### ISSUE TITLE
./tmw cpu

### ISSUE THREAD

**Issue by w0lner** [ascott18/TellMeWhen#2007]
the /tmw cpu command does not work. I tried reinstalling, LUA does not issue errors.
a window appears but no more.

![cpu](https://user-images.githubusercontent.com/98551572/202760483-af9cabce-aed0-4384-9170-a4531a710084.png)

**Comment by ascott18** [comment]
Please do not ignore the issue template that is provided when you create a new issue. The questions and sections within it provide me with essential information to be able to diagnose and resolve your issue. If you do not include this information, there is little I can do to help you.
