### ISSUE TITLE
[Feature Request] Item Variable for Item Conditions

### ISSUE THREAD

**Issue by Allnuerizym** [ascott18/TellMeWhen#2012]
I was unable to find the syntax to do this, so if I'm just blind let me know... but, please consider adding an "item variable" for items conditions that works like the custom texture field in a Conditional Icon. This will enable players to target an item slot to be evaluated instead of a specific item for that slot.

Example:

Conditional Icon
Condition: "Item has on use effect" and in the "Item to Check" box we are able to put $item.10 to evaluate hands, or $item.13 to evaluate trinket slot # 13 for an on-use effect. If the effect exists and is not on CD, then the condition returns True. If the item has an on-use effect and is on CD, then the condition returns false.

Thanks.

**Comment by Alwies** [comment]
This is a thing, though instead of $item.13 you'd enter "13". 
As for syntax it can be found in the tooltip of a what to track box of an item cooldown icon, but is indeed missing in the conditions.

**Comment by ascott18** [comment]
Its also in the suggestion list and the tooltips for the suggestion list 
![image](https://user-images.githubusercontent.com/5017521/203691172-abf8dc62-1ffc-45a7-a099-5a89b47cd7bc.png)

**Comment by Allnuerizym** [comment]
Alwies gave the correct answer by entering the slot number... @ascott18 the suggestion list lets you pick an item to watch, not a slot, but A for effort.

**Comment by ascott18** [comment]
@Allnuerizym The first 10 items in the screenshot in the suggestion list _are_ showing the item slots, my friend. See the item slot numbers along the right-hand side?
