### ISSUE TITLE
[Bug]: unknown class DRUID

### ISSUE THREAD

**Issue by rdmqwerty** [ascott18/TellMeWhen#2013]
### WoW Version

Wrath Classic

### TellMeWhen Version

10.0.2

### Describe the bug

i get this error when logging in to my druid

`1x TellMeWhen: Unknown class DRUID
[string "@TellMeWhen\Components\Core\Spells\ClassSpellCache.lua"]:276: in function <...ellMeWhen\Components\Core\Spells\ClassSpellCache.lua:228>
[string "@TellMeWhen\TellMeWhen-9.2.6.lua"]:695: in function <TellMeWhen\TellMeWhen.lua:694>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
[string "=(tail call)"]: ?
[string "@TellMeWhen\TellMeWhen-9.2.6.lua"]:827: in function `Fire'
[string "@TellMeWhen\TellMeWhen-9.2.6.lua"]:1183: in function `InitializeDatabase'
[string "@TellMeWhen\TellMeWhen-9.2.6.lua"]:1093: in function `?'
[string "@Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Bartender4\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:119>`

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Fixed in 719effbd116f78463bd152b83922d7155ceef8a4
