### ISSUE TITLE
[Bug]: Magic, Poison, Curse, Disease Equivalencies

### ISSUE THREAD

**Issue by geckzilla** [ascott18/TellMeWhen#2014]
### WoW Version

Retail

### TellMeWhen Version

10.0.2

### Describe the bug

Magic, Poison, Curse, and Disease equivalencies are not working for tracking in All-Unit Buffs/Debuffs (and presumably elsewhere)
I can get Rooted, Dazed, Slowed and Bleeding to work.

### Export Strings

```text
^1^T^SBuffOrDebuff^SHARMFUL ^SUnit^Sgroup1-5 ^SType^Sdotwatch ^SName^SMagic;~`Poison;~`Disease;~`Curse ^SSettingsPerView^T ^Sicon^T ^STextLayout^STMW:textlayout:1ZTz0ww7C9af ^STexts^T ^N1^SRight ^t^t^t^SFakeHidden^B ^SGUID^STMW:icon:1Z9JfGQg=Aik ^t^N100200^S~`~| ^Sicon^^

^1 ^T^N1^T ^SJustify^SLEFT ^SAnchors^T ^N1^T ^Sy^N-5 ^Sx^N5 ^Spoint^STOPLEFT ^SrelativePoint^STOPLEFT ^t^t^SWidth^N23 ^SStringName^SNumber ^SConstrainWidth^b ^SOutline^SOUTLINE ^SSize^N8 ^t^SGUID^STMW:textlayout:1ZTz0ww7C9af ^SName^SInfo~`Text ^t^N100200^S~`~| ^Stextlayout^STMW:textlayout:1ZTz0ww7C9af ^^
```

**Comment by ascott18** [comment]
These aren't equivalencies. They use the UnitAura API (in places where they're supported), which returns the dispel type. This icon type does not use UnitAura, but rather the combat log, so this information is not available. If you're trying to watch for dispellable effects on your group, use a normal buff/debuff icon.
