### ISSUE TITLE
[Bug]: LUA Error - Unknown class DRUID

### ISSUE THREAD

**Issue by OzDruiD** [ascott18/TellMeWhen#2016]
### WoW Version

Wrath Classic

### TellMeWhen Version

10.0.2  / updated 22/11/2022

### Describe the bug

LUA Error on mod load (login) on DruiD Character- see LUA error below.

Message: TellMeWhen: Unknown class DRUID
Time: Wed Nov 23 19:43:22 2022
Count: 1
Stack: TellMeWhen: Unknown class DRUID
[string "@Interface\AddOns\TellMeWhen\Components\Core\Utils.lua"]:445: in function `Error'
[string "@Interface\AddOns\TellMeWhen\Components\Core\Spells\ClassSpellCache.lua"]:276: in function <...ellMeWhen\Components\Core\Spells\ClassSpellCache.lua:228>
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:695: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:694>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:827: in function `Fire'
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:1183: in function `InitializeDatabase'
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:1093: in function `?'
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

### Export Strings

```text
Message: TellMeWhen: Unknown class DRUID
Time: Wed Nov 23 19:43:22 2022
Count: 1
Stack: TellMeWhen: Unknown class DRUID
[string "@Interface\AddOns\TellMeWhen\Components\Core\Utils.lua"]:445: in function `Error'
[string "@Interface\AddOns\TellMeWhen\Components\Core\Spells\ClassSpellCache.lua"]:276: in function <...ellMeWhen\Components\Core\Spells\ClassSpellCache.lua:228>
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:695: in function <Interface\AddOns\TellMeWhen\TellMeWhen.lua:694>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:827: in function `Fire'
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:1183: in function `InitializeDatabase'
[string "@Interface\AddOns\TellMeWhen\TellMeWhen.lua"]:1093: in function `?'
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>
```

**Comment by Elvara26** [comment]
I wanted to make an issue about it a few days ago then I forgot, just to explain it works fine on my mage but on my druid even after erasing and reinstalling and not configuring anything you get the error.
[https://chilledman.com/tmw/Screenshot_549.png](url)
Before erasing I also tried to reset the addon and I got an error message too, I was using the latest version 10.0.2 even if the screenshot says another version which is weird.
https://chilledman.com/tmw/Screenshot_551.png

**Comment by Alwies** [comment]
This issue has been fixed in the latest alpha build: [Curseforge link](https://www.curseforge.com/wow/addons/tellmewhen/files/4103129)

See issue #2013
