### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gozzwow** [ascott18/TellMeWhen#2018]
In the new alpha build (10.0.2-1g719effb.zp) I was unable to create condition's for a specific character. In my troubleshooting I renamed my wtf folder and then the issue was on all characters.

Opening a TMW group to edit/create icon produced this LUA error:

Message: ...Ons/TellMeWhen/Components/Core/Conditions/Config.lua:186: attempt to index local 'tab' (a nil value)
Time: Wed Nov 23 12:19:11 2022
Count: 2
Stack: ...Ons/TellMeWhen/Components/Core/Conditions/Config.lua:186: attempt to index local 'tab' (a nil value)
[string "@Interface/AddOns/TellMeWhen/Components/Core/Conditions/Config.lua"]:186: in function SetTabText'
[string "@Interface/AddOns/TellMeWhen/Components/Core/Conditions/Conditions.lua"]:1281: in function <...TellMeWhen/Components/Core/Conditions/Conditions.lua:1280>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:829: in function Fire'
[string "@Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.lua"]:3553: in function <...ace/AddOns/TellMeWhen/Options/TellMeWhen_Options.lua:3534>
[string "=[C]"]: in function Click'
[string "@Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.lua"]:3468: in function <...ace/AddOns/TellMeWhen/Options/TellMeWhen_Options.lua:3433>
[string "=[C]"]: in function Click'
[string "@Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.lua"]:3488: in function SetChildrenEnabled'
[string "@Interface/AddOns/TellMeWhen/Options/IconConfig.lua"]:121: in function LoadIcon'
[string "@Interface/AddOns/TellMeWhen/Components/IconModules/IconModule_IconEditorLoader/module.lua"]:38: in function <...s/IconModules/IconModule_IconEditorLoader/module.lua:24>
[string "@Interface/AddOns/TellMeWhen/Components/IconModules/IconModule_IconEditorLoader/module.lua"]:104: in function <...s/IconModules/IconModule_IconEditorLoader/module.lua:88>
[string "@Interface/AddOns/TellMeWhen/Components/Core/BaseClasses/ObjectModule.lua"]:42: in function <...lMeWhen/Components/Core/BaseClasses/ObjectModule.lua:39>
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals: <none>

**Comment by Alwies** [comment]
To add when I tried the same TMW Alpha version on my evoker I got 20 errors(retail), which I'd guess are likely related in some way. 
If needed I added them all in 1 text file.

[TMW alpha errors.txt](https://github.com/ascott18/TellMeWhen/files/10078569/TMW.alpha.errors.txt)

**Comment by ascott18** [comment]
Fixed in 4854fcf7b58c45761783fe85f3e091ee17bb5318
