### ISSUE TITLE
[Bug]: Group position suggestion list errors

### ISSUE THREAD

**Issue by Alwies** [ascott18/TellMeWhen#2020]
### WoW Version

Retail

### TellMeWhen Version

10.0.2

### Describe the bug

When changing the position anchor target of a group the default suggestion list is visible.
However when changing it throws errors (2 different ones) and doesn't update. 
Edit: also breaks the suggestion list for spells, reload fixes this.

The errors: 
`20x ...ts/GroupModules/GroupModule_GroupPosition/Config.lua:113: attempt to compare nil with string
[string "@TellMeWhen/Components/GroupModules/GroupModule_GroupPosition/Config.lua"]:113: in function <...ts/GroupModules/GroupModule_GroupPosition/Config.lua:111>
[string "=[C]"]: ?
[string "@TellMeWhen/Components/Core/Suggester/Suggester.lua"]:151: in function `SuggestingComplete'
[string "@TellMeWhen/Components/Core/Suggester/Suggester.lua"]:108: in function `DoSuggest'
[string "@TellMeWhen/Components/Core/Suggester/Suggester.lua"]:385: in function `NameOnCursor'
[string "@TellMeWhen/Components/Core/Suggester/Suggester.lua"]:504: in function <...s/TellMeWhen/Components/Core/Suggester/Suggester.lua:501>

Locals:
a = 369913
b = RangeDisplayMainFrame_mouseover {
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 0 = <userdata>
}
nameA = nil
nameB = "RangeDisplayMainFrame_mouseover"
(*temporary) = nil
(*temporary) = "attempt to compare nil with string"
SUG = <table> {
 1 = TellMeWhen_IconEditorSuggestItem1 {
 }
 SetDefaultModuleLibraries = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 2 = TellMeWhen_IconEditorSuggestItem2 {
 }
 8 = TellMeWhen_IconEditorSuggestItem8 {
 }
 ColorHelp = <function> defined @TellMeWhen/Components/Core/Suggester/Suggester.lua:574
 EnableModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 CancelTimer = <function> defined @AlwiesAddonMods/Libs/AceTimer-3.0/AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 UnregisterComm = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 9 = TellMeWhen_IconEditorSuggestItem9 {
 }
 10 = TellMeWhen_IconEditorSuggestItem10 {
 }
 SetDefaultModulePrototype = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 defaultModuleState = true
 IsEnabled = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 11 = TellMeWhen_IconEditorSuggestItem11 {
 }
 ScheduleTimer = <function> defined @AlwiesAddonMods/Libs/AceTimer-3.0/AceTimer-3.0.lua:94
 DisableModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 RegisterMessage = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 startpos = 0
 SendCommMessage = <function> defined @AlwiesAddonMods/Libs/AceComm-3.0/AceComm-3.0.lua:87
 13 = TellMeWhen_IconEditorSuggestItem13 {
 }
 UnregisterAllComm = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 enabledState = true
 RegisterEvent = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 GetHeightForFrames = <function> defined @TellMeWhen/Components/Core/Suggester/Suggester.lua:603
 IterateModules = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 baseName = "TellMeWhen_Options"
 GetFrame = <function> defined @TellMeWhen/Components/Core/Suggester/Suggester.lua:649
 atBeginning = "^mo"
 SuggestionList = TellMeWhen_IconEditorSuggest {
 }
 28 = TellMeWhen_IconEditorSuggestItem28 {
 }
 27 = TellMeWhen_IconEditorSuggestItem27 {
 }
 EnableEditBox = <function> defined @TellMeWhen/Comp`
 
 
 
  
 
**Error 2**

`18x ...ts/GroupModules/GroupModule_GroupPosition/Config.lua:133: attempt to index a nil value
[string "@TellMeWhen/Components/GroupModules/GroupModule_GroupPosition/Config.lua"]:133: in function `sorterBucket'
[string "@TellMeWhen/Components/Core/Suggester/Suggester.lua"]:139: in function `SuggestingComplete'
[string "@TellMeWhen/Components/Core/Suggester/Suggester.lua"]:108: in function `DoSuggest'
[string "@TellMeWhen/Components/Core/Suggester/Suggester.lua"]:385: in function `NameOnCursor'
[string "@TellMeWhen/Components/Core/Suggester/Suggester.lua"]:494: in function <...s/TellMeWhen/Components/Core/Suggester/Suggester.lua:475>

Locals:
self = <table> {
 showColorHelp = false
 noTexture = true
 NewModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 defaultModuleLibraries = <table> {
 }
 Table_Get = <function> defined @TellMeWhen/Components/GroupModules/GroupModule_GroupPosition/Config.lua:73
 helpText = "As you type, TellMeWhen will try to determine the input that you were looking for.

This list is not always exhaustive - in some cases, there may be valid input that doesn't appear. You also don't have to use the entries in the suggestion list - as long as you type the correct text into the editbox, TellMeWhen will accept it without issue.

Clicking on an entry will insert it into the editbox."
 GetName = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 Sorter_Bucket = <function> defined @TellMeWhen/Components/GroupModules/GroupModule_GroupPosition/Config.lua:115
 name = "TellMeWhen_Suggester_frameName"
 IsEnabled = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 DisableModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 Sorter_ByName = <function> defined @TellMeWhen/Components/GroupModules/GroupModule_GroupPosition/Config.lua:111
 OnSuggest = <function> defined @TellMeWhen/Components/GroupModules/GroupModule_GroupPosition/Config.lua:61
 IsModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:213
 SetDefaultModuleState = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:383
 InvalidEntries = <table> {
 }
 SetEnabledState = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Table_GetSorter = <function> defined @TellMeWhen/Components/GroupModules/GroupModule_GroupPosition/Config.lua:149
 enabledState = true
 Table = <table> {
 }
 baseName = "TellMeWhen_Options"
 OnInitialize = <function> defined @TellMeWhen/Components/GroupModules/GroupModule_GroupPosition/Config.lua:58
 defaultModuleState = true
 SetDefaultModuleLibraries = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 IterateModules = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 Table_GetNormalSuggestions = <function> defined @TellMeWhen/Components/GroupModules/GroupModule_GroupPosition/Config.lua:76
 noMin = true
 Entry_AddToList_1 = <function> defined @TellMeWhen/Components/GroupModules/GroupModule_GroupPosition/Config.lua:172
 moduleName = "frameName"
 SetDefaultModulePrototype = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 Disable = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:310
}
suggestions = <table> {
 1 = UIParentMainScrollLine6 {
 }
 2 = TellMeWhen_Group19 {
 }
 3 = UIParentScrollUpButton {
 }
 4 = UIParentHeaderLineHeaderIndex1 {
 }
 5 = UIParentScrollDownButton {
 }
 6 = UIParentMainScrollLine25 {
 }
 7 = UIParentMainScrollLine21TalentIconsRow {
 }
 8 = UIParentMainScrollLine15TalentIconsRow {
 }
 9 = UIParentMainScrollLine19 {
 }
 10 = TellMeWhen_Group18 {
 }
 11 = UIParentMainScrollLine1TalentIconsRow {
 }
 12 = UIParentMainScrollLine27 {
 }
 13 = UIParentMainScrollLine13TalentIconsRow {
 }
 14 = TellMeWhen_Group16 {
 }
 15 = UIParentMainScrollLine28TalentIconsRow {
 }
 16 = TellMeWhen_Group5 {
 }
 17 = UIParentMainScrollLine19TalentIconsRow {
 }
 18 = TellMeWhen_Group15 {
 }
 19 = UIParentMainScrollLine29 {
 }
 2`
 

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
> a = 369913
> b = RangeDisplayMainFrame_mouseover

Well at least I have confirmation of the almost decade-old bug that these weird rare suggestion list errors are caused by data from different modules from somehow getting intermingled.
