### ISSUE TITLE
Bug: Combat event icon is not working properly / at all with evoker empowered spells 

### ISSUE THREAD

**Issue by Betaskill** [ascott18/TellMeWhen#2025]
### WoW Version

Retail

### TellMeWhen Version

10.0.3 r12 (gb30b8cb)

### Describe the bug

I would like to report two problems that I am having with my german client. 

First of all thank you for adding the tracking of the empower level of the evoker spells. On that recently added function is a bug, where, if you are trying to track level 4 of any of the empowered spells, it doesnt work.  Because once you are reaching level 4 of the spell, the condition is handling it like if it was set to 0. 

I was able to create it by setting the level in the condition to 0 and : once i had reached level 0 and then level 4 both times the  icon was shown. Not sure if this is known. 

-------------------------------------------------

But I have found another bug that is concerns the "combat event"- icon in combination with the tracking of the empowered spells. 

Here are two problems happening: 

- The first one is that the selectable ID is only working with the ID "382266" (see picture). I have tried every possible ID that was suggested from the TMW-Suggestions-List with the spell "Fire Breath". Normally you would think that it would be one of the top two suggested ids (oranged marked in the picture) and not one that is nearly the end (red marked in the picture). 

- The second problem is that if you are trying to check an event, the events are not working correctly with an empowered spell. "Spell cast success" and "spell cast start" are not working at all, "spell cast failed" is working when you click the spell while it is on cooldown (guess thats intended but not sure) sometimes the "spell damage"- events are working sometimes not, sometimes they are only working when you are infight, so that the first hit out of fight will not trigger the "spell damage"-events. I have not tried all possibilitys, these are just some that I found.

Thank you for your work. 

![choices](https://user-images.githubusercontent.com/55817239/204069793-b1718a2a-12a3-4b86-9b76-9f1df064c8bd.png)

### Export Strings

```text
^1^T^SCLEUEvents^T ^SSPELL_CAST_FAILED^B ^t^SType^Scleu ^SCLEUDur^N5.2 ^SName^S382266 ^SSourceUnit^Splayer ^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STextLayout^STMW:textlayout:1TEBinvNUr4i ^STexts^T ^N1^Sany ^N2^S ^N3^S ^t^t^t^SCustomTex^S291520 ^t^N100300^S~`~| ^Sicon^^

^1 ^T^N1^T ^SAnchors^T ^N1^T ^Sy^N-5 ^Sx^N1 ^SrelativePoint^STOP ^t^t^SName^SAnonymous~`Pro~`Bold~`(U) ^SStringName^SOben ^SSize^N8 ^t^N2^T ^SName^SAnonymous~`Pro~`Bold~`(U) ^SStringName^SMitte ^SSize^N8 ^t^N3^T ^SAnchors^T ^N1^T ^Sy^N1 ^Sx^N2 ^Spoint^SBOTTOMRIGHT ^SrelativePoint^SBOTTOMRIGHT ^t^t^SJustifyV^SBOTTOM ^SName^SAnonymous~`Pro~`Bold~`(U) ^SStringName^SUnten ^SSize^N7 ^t^SGUID^STMW:textlayout:1TEBinvNUr4i ^Sn^N3 ^SName^SText ^t^N100300^S~`~| ^Stextlayout^STMW:textlayout:1TEBinvNUr4i ^^
```

**Comment by ascott18** [comment]
> The first one is that the selectable ID is only working with the ID "382266" 

This is, in a way, a manifestation of #2017 and #354. I'll manually add the other IDs to the known class spells when Font of Magic is learned.

> the events are not working correctly with an empowered spell

Empowered casts have their own combat events that I haven't added yet.
