### ISSUE TITLE
[Bug] Unit conditions always returning true

### ISSUE THREAD

**Issue by Alwies** [ascott18/TellMeWhen#2029]
### WoW Version

Retail

### TellMeWhen Version

10.0.4-3-gdd0b839

### Describe the bug

Unit conditions seem to always return true. 
To replicate(see included export string).
1. Create 2 unit condition icons tracking player
2. Set on of the icons to check if unit exists = true and the other to false
3. Both icons show 

Reported on disc, not sure of the user was gonna make a report himself but with launch close by I figured I'd do it myself. 
Original report used a spell cast icon tracking nameplate 1-40, with 2 unit conditions:
1. unittarget exists
2. unit reaction = hostile

### Export Strings

```text
^1^T^SPoint^T ^Sy^F7177732165206016 ^f-48^Sx ^F6210045968646144^f-45 ^t^SGUID^STMW:group:1ZWtbtofwjml ^SColumns^N2 ^SIcons^T ^N1^T ^SType^Sunitcondition ^SUnitConditions^T ^N1^T ^SType^SEXISTS ^SLevel^N1 ^t^Sn^N1 ^t^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^Sno~`exist ^t^t^t^SCustomTex^S768 ^SEnabled^B ^t^N2^T ^SType^Sunitcondition ^SUnitConditions^T ^N1^T ^SType^SEXISTS ^t^Sn^N1 ^t^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^Sexist ^t^t^t^SCustomTex^S768 ^t^t^t^N100500^S~`~| ^Sgroup^N1 ^^
```

**Comment by ascott18** [comment]
Funnily enough, this is actually a completely different bug. Turns out that a Unit Exists condition against "player" is always true, regardless of the true/false setting on the condition. That made figuring out the real error that was trying to be reported here... take longer than it should have.

**Comment by Alwies** [comment]
Damn I just thought of it as an easy way to test.
Was even amused by the Schrödinger's cat reference.
