### ISSUE TITLE
Errors for Swing Timer

### ISSUE THREAD

**Issue by Jeffrey-Wang98** [ascott18/TellMeWhen#2033]
### WoW Version

Wrath Classic

### TellMeWhen Version

10.0,4

### Describe the bug

When swing timer is enabled, with or without a condition, errors are generated. (Originally had a condition to only show swing timer when off-hand equipped is False.) The count on the 2nd error message increments rapidly when enabled. 
This only stops when disabling swing timer and reloading.
I have pasted the export string of the icon below.

Message: TellMeWhen: [string "Condition_MHSWING_LUA_LUA_ITEMEQUIPPED"]:6: attempt to index field '?' (a nil value)
Time: Sun Nov 27 16:28:04 2022
Count: 1
Stack: TellMeWhen: [string "Condition_MHSWING_LUA_LUA_ITEMEQUIPPED"]:6: attempt to index field '?' (a nil value)

Locals: <none>

Message: [string "Condition_MHSWING_LUA_LUA_ITEMEQUIPPED"]:6: attempt to index field '?' (a nil value)
Time: Sun Nov 27 16:28:07 2022
Count: 42
Stack: [string "Condition_MHSWING_LUA_LUA_ITEMEQUIPPED"]:6: attempt to index field '?' (a nil value)

Locals: <none>

### Export Strings

```text
^1^T^SType^Sswingtimer ^SConditions^T ^N1^T ^SType^SITEMEQUIPPED ^SLevel^N1 ^SName^S17 ^t^Sn^N1 ^t^STimerBar_StartColor^Sff000000 ^SName^S20375;~`20915;~`20918;~`20919;~`20920;~`20154;~`20287;~`20288;~`20289;~`20290;~`20291;~`20292;~`20293;~`21084;~`20166;~`20356;~`20357;~`20165;~`20347;~`20348;~`20349;~`20162;~`20305;~`20306;~`20307;~`20308;~`21082 ^STimerBar_EnableColors^B ^SBarDisplay_Invert^B ^SBarDisplay_Reverse^B ^SEvents^T ^N1^T ^SAnchorTo^SIconModule_TimerBar_BarDisplayTimerBar ^SAnimColor^Sff000000 ^SFade^b ^SType^SAnimations ^SThickness^N3 ^SPeriod^N0 ^SAnimation^SICONBORDER ^SEvent^SWCSP ^SOnConditionConditions^T ^N1^T ^SType^SCOUNTER ^SName^Sborder_toggle ^t^Sn^N1 ^t^t^N2^T ^SAnchorTo^SIconModule_TimerBar_BarDisplayTimerBar ^SAnimColor^Sffe38fff ^SFade^b ^SType^SAnimations ^SPeriod^N0 ^SAnimation^SICONFLASH ^SEvent^SWCSP ^SOnConditionConditions^T ^N1^T ^SType^SMHSWING ^SOperator^S>= ^SLevel^N1 ^SPrtsBefore^N1 ^t^N2^T ^SType^SLUA ^SPrtsAfter^N1 ^SName^Sspell~`=~`IsSpellKnown(20375)~J return~`spell ^t^N3^T ^SType^SLUA ^SAndOr^SOR ^SName^Sspell~`=~`IsSpellKnown(20375)~J ~J if~`spell~`==~`false~`then~J ~`~`~`~`~J ~`~`~`~`return~`true~J end ^t^N4^T ^SType^SITEMEQUIPPED ^SAndOr^SOR ^SName^S17 ^t^Sn^N4 ^t^t^N3^T ^SAnchorTo^SIconModule_TimerBar_BarDisplayTimerBar ^SAnimColor^Sffff3434 ^SFade^b ^SType^SAnimations ^SPeriod^N0 ^SAnimation^SICONFLASH ^SEvent^SWCSP ^SOnConditionConditions^T ^N1^T ^SType^SMHSWING ^SOperator^S< ^SLevel^N1 ^t^N2^T ^SType^SLUA ^SName^Sspell~`=~`IsSpellKnown(20375)~J return~`spell ^t^N3^T ^SType^SITEMEQUIPPED ^SLevel^N1 ^SName^S17 ^t^Sn^N3 ^t^t^Sn^N3 ^t^SSettingsPerView^T ^Sbar^T ^STexts^T ^N1^S[Duration(gcd=true):TMWFormatDuration] ^N2^SSwing ^t^t^t^SStates^T ^N2^T ^SAlpha^N1 ^t^t^STimerBar_MiddleColor^Sff000000 ^STimerBar_CompleteColor^Sff000000 ^SOnlyMine^B ^SEnabled^B ^t^N100300^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
Thanks for the report. This error is coming from the 4th condition, Item Equipped, and is the same root issue as #2026 and 2028, which was already fixed.
