### ISSUE TITLE
TMW causing 4 secs freeze

### ISSUE THREAD

**Issue by Pivker** [ascott18/TellMeWhen#2036]
### WoW Version

Retail

### TellMeWhen Version

10.0.5

### Describe the bug

Opening config freezes wow for 3-4 secs. Entering a dungeon freezes wow for 3-4 secs. Changing a talentpoint freezes wow for 3-4 secs. 

Disabling TMW resolves all these issues.

Edit: its an interaction with another addon. I will try to find the culprit later after work.

Edit 2: idTip-10.3.0 is causing the lock up. Disabling idTip resolves the issue.

### Export Strings

```text
"N/A"
```

**Comment by ascott18** [comment]
Please attach your TMW settings file. This file can be found in WoW's installation location, under `World Of Warcraft\_retail_\WTF\Account\<your account name>\SavedVariables\TellMeWhen.lua`.

**Comment by Pivker** [comment]
Lua uploaded

**Comment by ascott18** [comment]
Sorry, you didn't need to do that - I didn't see your followup that you figured out the issue since you put it as an edit rather than an additional comment.
