### ISSUE TITLE
Show Based on Talent Loadout

### ISSUE THREAD

**Issue by Chalsean** [ascott18/TellMeWhen#2037]
**Is your feature request related to a problem? Please describe.**
Currently you can only (not) show based on combat, role and spec.  But for example as a hpriest, I have multiple loadouts based on dungeon vs raid, dispels needed, etc.  Currently I can only have 1 group that gets automatically displayed, so theres lots of holes in the icon set depending on whether I got that talent or not.  

**Describe the solution you'd like**
Add Talent Loadout as a group (no) show option.

**Describe alternatives you've considered**
I have to have a lot of logic behind each icon to determine which icon to show, what conditions should be considered, etc.

**Additional context**
![image](https://user-images.githubusercontent.com/45693161/205350604-a23e9920-45bc-401b-a971-5790c5a1647d.png)
![image](https://user-images.githubusercontent.com/45693161/205350882-67e31b9d-bfe0-433d-8532-1e00f296c7c7.png)
![image](https://user-images.githubusercontent.com/45693161/205351064-bc686ebb-a613-49f9-8eba-0bd4f167d860.png)

**Comment by ascott18** [comment]
There's a Talent Loadout condition. You can set it as a group condition.

I may consider adding a group setting to make group conditions also apply while in config mode to make config mode less cluttered when using conditions in this manner. @VanHelsing05 I believe this would solve the problem you were getting at in the second half of your massive, sparsely-punctuated paragraph in #2038.
