### ISSUE TITLE
[BUG] Timer text showing up briefly whenever I cast a spell in any class (GCD?)

### ISSUE THREAD

**Issue by Architekt909** [ascott18/TellMeWhen#2040]
### WoW Version

Retail

### TellMeWhen Version

10.0.5

### Describe the bug

<img width="254" alt="image" src="https://user-images.githubusercontent.com/3301620/205672388-a54437c8-f5a1-4e7d-a07e-11dd0f15d4a0.png">

This is on my new evoker, but the exact same issue happens on all of my characters, regardless of race/alliance/class. What happens is that whenever I cast a spell, I see a timer appear briefly (it displays usually a 1 or a 2: In the screenshot above you can see a somewhat opaque 1 displaying in the center after I cast a basic spell that incurs a standard GCD) which seems to coincidentally coincide with the GCD. However, I do not have any GCD settings enabled that I know of. As for my text layout, I have the following defined for my timer value:
<img width="495" alt="image" src="https://user-images.githubusercontent.com/3301620/205673269-de3b170c-16c7-40de-a86a-2023fbf2dcac.png">

Here are the settings for one of my icons (the others are the same just different spell ID):
<img width="497" alt="image" src="https://user-images.githubusercontent.com/3301620/205673527-8fa7873d-d579-4ec7-8bd5-beaa129e309b.png">

I am not using OmniCC (don't even have it installed) or ElvUI for timer text (although I do have ElvUI installed, v13.10). Again, this happens on all characters, all specs, all classes: cast any spell that incurs a GCD, and **all** icons display a counter starting at either 1 or 2 counting down. I've tried to hide it with that "[Yellow(Duration:Ceil:Hide(0))]" and increasing the number, but that's a bandaid solution.

**Please note: This never happened to me before in Shadowlands, it seems to be new to Dragonflight**

I'm attaching the string for my group. 

### Export Strings

```text
^1^T^SScale^F5389319594311680 ^f-52^SRows ^N2^SPoint ^T^Sy^F4822319230584272 ^f-46^Sx ^F5933460182407023^f-45 ^t^SGUID^STMW:group:1ZZWEYUTARud ^SColumns^N5 ^SIcons^T ^N1^T ^SShowTimer^B ^SType^Scooldown ^SName^STail~`Swipe ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SSF ^N2^Sup ^t^t^t^SStates^T ^N1^T ^SAlpha^N0.35 ^t^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^t^N4^T ^SShowTimer^B ^SType^Scooldown ^SName^STail~`Swipe ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SSF ^N3^S[Yellow(Duration:Ceil:Hide(0))] ^t^t^t^SStates^T ^N1^T ^SAlpha^N0.35 ^t^N2^T ^SAlpha^N1 ^t^t^t^N6^T ^SShowTimer^B ^SType^Scooldown ^SName^SWing~`Buffet ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SSR ^N2^Sknock ^t^t^t^SStates^T ^N1^T ^SAlpha^N0.35 ^t^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^t^t^SName^SDevoker~`Main ^SSettingsPerView^T ^Sicon^T ^STextLayout^STMW:textlayout:1KGUbKf6odcS ^t^t^t^N100500^S~`~| ^Sgroup^N1 ^^

^1 ^T^N1^T ^SAnchors^T ^N1^T ^Sy^N-1.6 ^Sx^N2 ^Spoint^STOPLEFT ^SrelativePoint^STOPLEFT ^t^N2^T ^Sy^N-2 ^Sx^N3 ^Spoint^STOPLEFT ^SrelativePoint^STOPLEFT ^t^Sn^N2 ^t^SStringName^SBinding/Label ^SSkinAs^SHotKey ^SSize^N10 ^t^N2^T ^SDefaultText^S[Stacks:Hide(0)] ^SSkinAs^SCount ^SStringName^SStacks ^SAnchors^T ^N1^T ^Sy^N2 ^Sx^N2 ^Spoint^SBOTTOMRIGHT ^SrelativePoint^SBOTTOMRIGHT ^t^t^SSize^N8 ^t^N3^T ^SDefaultText^S[Yellow(Duration:Ceil:Hide(0))] ^SName^S2002~`Bold ^SStringName^STimer ^t^SGUID^STMW:textlayout:1KGUbKf6odcS ^Sn^N3 ^SName^Ssmaller~`text~`both~`rows ^t^N100500^S~`~| ^Stextlayout^STMW:textlayout:1KGUbKf6odcS ^^
```

**Comment by Architekt909** [comment]
Update: I reinstalled OmniCC, and enabled "Show timer text" on the icons, deleted the "Timer" text display for each text layout, and removed the "[Yellow(Duration:Ceil:Hide(0))]" text, if any, from the icons and when I use OmniCC instead of the built in TMW timer, I don't have this issue. When I cast a spell, I don't see a 1-2s counter on every icon. I'm not sure if this is intentional when using the built in TMW timer, but I assumed that by not ticking "Allow Global Cooldown" on the icons that I wouldn't see what appears to be the GCD showing up on my icons. I'd prefer not to have to install another addon and just use TMW, but this works for now. Not sure if this helps narrow anything down at all or not.

**Comment by ascott18** [comment]
The Timer Sweep option "Allow Global Cooldown" has no effect on the text displays - these are completely independent and unrelated modules. The [Duration] tag has its own gcd option - `[Duration(gcd=false)]`.
