### ISSUE TITLE
I cant import from string

### ISSUE THREAD

**Issue by Kotrall** [ascott18/TellMeWhen#2041]
### WoW Version

Retail

### TellMeWhen Version

10.0.6 r1

### Describe the bug

I copied a Tell me when profile from https://www.chesder.com/ and when i have pasted it in like i always did before it won't let me click import from string its greyed out
![Skärmbild (43)](https://user-images.githubusercontent.com/119950773/205938848-85578e2b-a862-4203-a171-4c7953d2ada2.png)

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
You can't import Weakauras into TMW.
