### ISSUE TITLE
[BUG] Counter can't track stack build on Scintillation proc

### ISSUE THREAD

**Issue by Badkruka** [ascott18/TellMeWhen#2042]
### WoW Version

Retail

### TellMeWhen Version

10.0.5

### Describe the bug

When I want to track stacks using counter for Evoker Devastation "Charged Blast" buff it fails to add +1 when Scintillation procs for each target it hits.
I have a tellmewhen for Buff/Debuff tracking "Charged Blast" (spell ID: 370454). In that I have done like this:

In notification I have "On Stacks Increased" "mycountername add 1
I also have a counter that sets it to value 0 when the buff goes away.

I works everytime except when I proc "Scintillation" using "Disintegrate". That proc cast a level 1 "Eternity Surge" and can hit up to two targets. If it hits one target my counter value is one lower then the buff stacks and if it hits two targets my counter value is two less then the buff stacks.

### Export Strings

```text
^1^T^SType^Sbuff ^SName^S370454 ^SEvents^T ^N1^T ^SType^SCounter ^SCounter^Schargedblast ^SEvent^SOnStackIncrease ^t^N2^T ^SType^SCounter ^SCounter^Schargedblast ^SCounterAmt^N0 ^SCounterOperation^S= ^SEvent^SOnCondition ^SOnConditionConditions^T ^N1^T ^SType^SBUFFDUR ^SChecked^B ^SName^S370454 ^t^Sn^N1 ^t^t^N3^T ^SType^SCounter ^SCounter^Schargedblast ^SCounterAmt^N0 ^SCounterOperation^S= ^SEvent^SOnEventsRestored ^t^Sn^N3 ^t^SSettingsPerView^T ^Sicon^T ^STextLayout^Sicon2 ^STexts^T ^N1^S[Stacks:Hide(0)] ^t^t^t^SOnlyMine^B ^SEnabled^B ^t^N100500^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
Why are you trying to do this? Why not just track the stacks of Charged Blast?

There's no bug here. When the stacks increase, it increments your counter. The stacks increase trigger does not trigger multiple times if the stacks increase by more than 1.

**Comment by Badkruka** [comment]
I want to see the stacks inside dragonrage and since dogtag string is bugging I tryed to make this workaround untill the bugfixed is realeased.
