### ISSUE TITLE
Feral Druid: Stealthed Rake failing Debuff Duration conditional between 10 and 8 sec remaining

### ISSUE THREAD

**Issue by jamesdipalma** [ascott18/TellMeWhen#2045]
### WoW Version

Retail

### TellMeWhen Version

10.0.5

### Describe the bug

Icon shows a Spell Cooldown for Rake with a condition that Rake debuff on target has a duration < 2.5

When applying Rake while Stealthed, Rake applies to target and icon disappears; after 2 sec, when debuff timer shows "9" sec duration, this Rake icon shows.  Then, after 4 sec, when debuff timer shows "7" sec duration, this icon disappears until 2.5 seconds remaining.

Expectation: Rake icon will not show while Rake is on target with Rake debuff above 8 sec
Observed: Rake icon shows shows between 10 sec and 8 sec duration.

### Export Strings

```text
^1^T^SBuffOrDebuff^SHARMFUL ^SUnit^Starget ^SType^Scooldown ^SConditions^T ^N1^T ^SType^SDEBUFFDUR ^SChecked^B ^SUnit^Starget ^SOperator^S< ^SLevel^N2.5 ^SName^SRake ^t^Sn^N1 ^t^SName^SRake ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SW ^t^t^t^SCustomTex^SRake ^SOnlyMine^B ^SEnabled^B ^t^N100500^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
There are two effects named Rake. One is a 4 second stun, one is a 15 second bleed. If you want to track one of those in particular, use the spell ID, not the name.
