### ISSUE TITLE
GetItemCooldown Errors in Wrath PTR

### ISSUE THREAD

**Issue by ornumladnar** [ascott18/TellMeWhen#2046]
### WoW Version

Wrath Classic

### TellMeWhen Version

10.0.0.6 r1

### Describe the bug

Unable to import full profile from Wrath Classic into Wrath Classic PTR

When manually recreating my profile, any icons used for tracking item CD's spew out many errors
Grenades/Sappers/Potions/Gloves/boots/cloak/trinkets

177x ...ceTellMeWhen/Components/Core/Common/Item.lua:278: attempt to call upvalue 'GetItemCooldown' (a nil value)
[string "@TellMeWhen/Components/Core/Common/Item.lua"]:278: in function `GetCooldown'
[string "@TellMeWhen/Components/IconTypes/IconType_item/item.lua"]:130: in function `UpdateFunction'
[string "@TellMeWhen/Components/Core/Icon.lua"]:784: in function `Update'
[string "@TellMeWhen/Components/IconTypes/IconType_item/item.lua"]:234: in function <...llMeWhen/Components/IconTypes/IconType_item/item.lua:216>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
[string "=(tail call)"]: ?
[string "@TellMeWhen/Components/Core/Icon.lua"]:1038: in function `Setup'
[string "@TellMeWhen/Options/IconConfig.lua"]:71: in function <TellMeWhen/Options/IconConfig.lua:65>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
...
[string "@TellMeWhen/Options/TellMeWhen_Options.lua"]:994: in function <...aceTellMeWhen/Options/TellMeWhen_Options.lua:981>
[string "@TellMeWhen/Options/TellMeWhen_Options.lua"]:994: in function <...aceTellMeWhen/Options/TellMeWhen_Options.lua:981>
[string "@TellMeWhen/Options/TellMeWhen_Options.lua"]:994: in function <...aceTellMeWhen/Options/TellMeWhen_Options.lua:981>
[string "@TellMeWhen/Options/TellMeWhen_Options.lua"]:994: in function <...aceTellMeWhen/Options/TellMeWhen_Options.lua:981>
[string "@TellMeWhen/Options/TellMeWhen_Options.lua"]:994: in function <...aceTellMeWhen/Options/TellMeWhen_Options.lua:981>
[string "@TellMeWhen/Options/TellMeWhen_Options.lua"]:1023: in function `CScriptTunnel'
[string "@TellMeWhen/Options/TellMeWhen_Options.lua"]:822: in function `SaveSettings'
[string "@TellMeWhen/Components/Core/Common/IconDragger.lua"]:397: in function `func'
[string "@TellMeWhen/Options/TMWUIDropDownMenu.lua"]:473: in function `Button_OnClick'
[string "*TMWUIDropDownMenuTemplates.xml:83_OnClick"]:1: in function <[string "*TMWUIDropDownMenuTemplates.xml:83_OnClick"]:1>

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
I can't believe they're actually just going to remove GetItemCooldown. Its not gone in retail, so it makes no sense to be gone in Wrath. WeakAuaras is also just treating this is as a blizz bug. https://github.com/WeakAuras/WeakAuras2/commit/6cff09ddca3402d3d69b0810487fda45fa569a9a

**Comment by ascott18** [comment]
Looks like its back as C_Container.GetItemCooldown

**Comment by ssateneth** [comment]
just to add, i changed line 21 of tellmewhen\components\core\common\item.lua from

  = IsEquippedItem, GetItemCount, GetItemInfo, GetItemCooldown, GetItemIcon, IsItemInRange

to

  = IsEquippedItem, GetItemCount, GetItemInfo, C_Container.GetItemCooldown, GetItemIcon, IsItemInRange

and the error went away
