### ISSUE TITLE
Buff/Debuff

### ISSUE THREAD

**Issue by BelkaPro** [ascott18/TellMeWhen#2047]
### WoW Version

Classic/Classic SoM

### TellMeWhen Version

Game Version: 10.0.5

### Describe the bug

![image](https://user-images.githubusercontent.com/120458894/207287388-1b9a1e7f-1a79-4413-bcc0-840959bf175f.png)
I'm trying to set up a Debuff to track control on teammates. But it does not work and does not track... I ask you to correct this flaw.

### Export Strings

```text
"N"
```

**Comment by BelkaPro** [comment]
why was it closed? It really doesn't work.

**Comment by ascott18** [comment]
You didn't provide an export string, and also reported the version as Classic while providing a screenshot of Valdrakken.

My guess would be that your icon isn't working because you set it to Always Hide (Всегда скрывать), so it is indeed always hiding.
