### ISSUE TITLE
Can't clear focus

### ISSUE THREAD

**Issue by khalilnajjar** [ascott18/TellMeWhen#2051]
### WoW Version

Retail

### TellMeWhen Version

10.0.5

### Describe the bug

I can't clear focus without disabling the addon. This applies to Right-Click -> Clear Focus and to the /clearfocus script (in a macro).

![image](https://user-images.githubusercontent.com/2459935/209178439-94a388f8-dc9d-4ecb-8337-8fbb4697df09.png)

Edit: Clearing focus works after /reload

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
There is no chance that TMW is causing this. See https://github.com/ascott18/TellMeWhen/issues/1991
