### ISSUE TITLE
Void Eruption transform timer broken

### ISSUE THREAD

**Issue by Breavyn** [ascott18/TellMeWhen#2053]
### WoW Version

Retail

### TellMeWhen Version

10.0.6

### Describe the bug

Void Eruption is a special ability that transforms to Void Bolt while in Void Form.

After upgrading to 10.0.6, entering Void Form changes the spell icon from Void Eruption to Void Bolt, but the timer reflects the long cooldown of Void Eruption, not the short cooldown of Void Bolt.

Downgrading to 10.0.5 does resolve the issue again.

### Export Strings

```text
^1^T^SShowTimer^B ^SType^Scooldown ^SShowTimerText^B ^SName^SVoid~`Eruption ^SEvents^T ^N1^T ^SType^SAnimations ^SAnimation^SACTVTNGLOW ^SEvent^SOnFinish ^t^Sn^N1 ^t^SSettingsPerView^T ^Sicon^T ^STexts^T ^N2^S ^t^t^t^SStates^T ^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^t^N100500^S~`~| ^Sicon^^
```
```

**Comment by ascott18** [comment]
Thanks, fixed
