### ISSUE TITLE
Execute showing when on cooldown

### ISSUE THREAD

**Issue by Krisroth** [ascott18/TellMeWhen#2054]
### WoW Version

Retail

### TellMeWhen Version

10.0.7

### Describe the bug

Hi

I've noticed problem with Warrior Execute ability on Fury Warrior.
When I take Massacre talent TellMeWhen stops reporting when ability is on cooldown. I've done some testing and it works fine without Massacre.
I've tried Execute as reactive ability with cooldown check and as cooldown ability with Spell Reactivity condition. Sam problem.
Any hotfix or advise how to set it up would be appreciated.

Thanks

Kris

![image](https://user-images.githubusercontent.com/121729785/210151738-522edf45-7f25-4de3-82fb-ac8cd65162ae.png)

### Export Strings

```text
^1^T^SShowTimer^B ^SType^Sreactive ^SName^SExecute ^SOnlyActvtnOverlay^B ^SConditions^T ^N1^T ^SType^SREACTIVE ^t^Sn^N1 ^t^SClockGCD^B ^SCooldownCheck^B ^SStates^T ^N4^T ^SAlpha^N0 ^t^t^SEnabled^B ^t^N100700^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
This is a manifestation of https://github.com/Stanzilla/WoWUIBugs/issues/354

As a workaround for now, track it by ID when you have Massacre learned - 280735
