### ISSUE TITLE
[Bug] Adaptive Swarm is not beeing able to be tracked with Spell cooldown.

### ISSUE THREAD

**Issue by Betaskill** [ascott18/TellMeWhen#2055]
### WoW Version

Retail

### TellMeWhen Version

10.0.7

### Describe the bug

Hello there, 

I´m back with another Bug, perhaps again made by bliz. 

If I am trying to track the heal druid talent spell "Adaptive Swarm " in the TMW Icon Spell Cooldown and as comparion also in the icon Reactive Ability. 

There is a weird problem. But before I mention that, I am using the german client and trying it with the German spell "Adaptiver Schwarm". 

The TMW icon will not track the spell and here will beginn the weird situation: 

If you are left shift-clicking the spell in the chat it will be printed as "Adaptive Swarm", if I drag and drop the icon from the spell book into a tmw icon it will be printed as "Adaptive Swarm ", buuuut if I am creating an ingame WoW-macro and am left shift-clicking the spell from the spell book in the macro, it will printed "Adaptive Swarm(Shadowlands)" [In German: Adaptiver Schwarm(Schattenlande) ]

Now, if I am using the spelling Adaptive Swarm(Shadowlands) it will be correctly tracked by TMW in Spell Cooldown and also the Reactive Ability icon. Just a side information: TMW can also track the spell "Convoke the Spirits" with the additional spelling (Shadowlands) and without.

The spelling Adaptive Swarm(Shadowlands) will not be suggested by tmw, but tmw can only track this kind of spelling correctly. 

I am not sure if this is only a german client problem, since I have only tested it with the german client and the german spelling. 

Is this a blizzard problem?

Thank you for your hard work. 

### Export Strings

```text
^1^T^SGUID^STMW:group:1ZjZFFZ2mk08 ^SPoint^T ^Sy^F4626746003423233 ^f-44^SrelativePoint ^SBOTTOMLEFT^Sx ^F7591029888778240^f-44 ^t^SLocked^B ^SEnabledSpecs^T ^N65^b ^N66^b ^t^SColumns^N2 ^SIcons^T ^N1^T ^SType^Scooldown ^SName^SAdaptiver~`Schwarm ^SCooldownCheck^B ^SEnabled^B ^t^N2^T ^SType^Scooldown ^SName^SAdaptiver~`Schwarm(Schattenlande) ^SEnabled^B ^SCooldownCheck^B ^t^t^SSettingsPerView^T ^Sicon^T ^SSpacingX^N0.9 ^t^t^t^N100700^S~`~| ^Sgroup^N27 ^^
```

**Comment by ascott18** [comment]
> Is this a blizzard problem?

Yes, #1978
