### ISSUE TITLE
I made an ouchie. 🗡️ 

### ISSUE THREAD

**Issue by 40P3** [ascott18/TellMeWhen#2060]
### WoW Version

Retail

### TellMeWhen Version

10.0.0.7

### Describe the bug

Just watching video guide from the beginning (I'm playing wow since beta but I'm the noobest noob when it comes to tellmewhen :D)
Replicating step by step from video: https://www.youtube.com/watch?v=TvvEdesJnPQ
And when I started Right clicking on the condition icon this happened (I've done the basic rotation to the four basic icons with a tiny bit of difference, and video guide is at/around 14:20) (see attached steps record file attached in zip).
Tried to reload ui and stuff but this is a constant thing...
[tellmewhen rightclick condition icon bars.zip](https://github.com/ascott18/TellMeWhen/files/10419834/tellmewhen.rightclick.condition.icon.bars.zip)

Sooo... what's going on? 👯 

### Export Strings

```text
^1^T^SGroups^T ^N1^T ^SGUID^STMW:group:1ZmwCLVBl1ii ^SScale^F6466042662486016 ^f-51^SPoint ^T^Sy^F8439329416282112 ^f-47^Sx ^F-7177975342668971^f-55 ^Spoint^SBOTTOM ^SrelativePoint^SBOTTOM ^t^SColumns^N1 ^SIcons^T ^N1^T ^SCustomTex^S346547 ^SFakeHidden^B ^SEnabled^B ^t^t^SName^SAnchor ^t^N2^T ^SPoint^T ^Sy^F7574937524238361 ^f-46^Sx ^F-7857659662322275^f-47 ^SrelativeTo^STMW:group:1ZmwCLVBl1ii ^t^SScale^N2.2 ^SRows^N6 ^STextureName^SBantoBar ^SGUID^STMW:group:1Zmy7gJIbv4P ^SColumns^N1 ^SIcons^T ^N1^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SSPELLCD ^SName^SJudgment ^t^N2^T ^SType^SHOLY_POWER ^SOperator^S< ^SLevel^N5 ^t^N3^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1ZmxFMwZ8Jmi ^t^Sn^N3 ^t^SName^SConsecration ^SGUID^STMW:icon:1ZmxFMw2Qymm ^SEvents^T ^N1^T ^SType^SAnimations ^SAnimation^SACTVTNGLOW ^SEvent^SWCSP ^t^Sn^N1 ^t^SCustomTex^SJudgment ^SEnabled^B ^t^N2^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SSPELLCD ^SName^SBlade~`of~`Justice ^t^N2^T ^SType^SHOLY_POWER ^SOperator^S< ^SLevel^N4 ^t^N3^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1ZmxFMw2Qymm ^t^N4^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1ZmxFMwZ8Jmi ^t^Sn^N4 ^t^SGUID^STMW:icon:1ZmxFMwJiKWJ ^SCustomTex^SBlade~`of~`Justice ^SEnabled^B ^t^N3^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SSPELLCD ^SName^SCrusader~`Strike ^t^N2^T ^SType^SHOLY_POWER ^SOperator^S< ^SLevel^N5 ^t^N3^T ^SType^SSPELLCHARGES ^SOperator^S> ^SName^SCrusader~`Strike ^t^N4^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1ZmxFMw2Qymm ^t^N5^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1ZmxFMwJiKWJ ^t^N6^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1ZmxFMwZ8Jmi ^t^Sn^N6 ^t^SCustomTex^SCrusader~`Strike ^SEnabled^B ^t^N5^T ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SMANAUSABLE ^SOperator^S< ^SName^STemplar's~`Verdict ^t^N2^T ^SType^SDEBUFFDUR ^SOperator^S~|= ^SUnit^Starget ^SName^SJudgment ^t^Sn^N2 ^t^SGUID^STMW:icon:1ZmxFMwZ8Jmi ^SCustomTex^STemplar's~`Verdict ^SEnabled^B ^t^t^SSortPriorities^T ^N1^T ^SMethod^Sfakehidden ^t^t^SLayoutDirection^N4 ^SName^SGlobal~`Rotation ^t^t^SNumGroups^N2 ^SVersion^N100700 ^t^N100700^S~`~| ^Sprofile^SPaladin~`-~`New ^^
```

**Comment by ascott18** [comment]
You sorted your group by Always Hidden Last, with no fallback sort order. You have no icons in that group that are set to Always Hide. So, the sort order of your icons will always be nondeterministic.

**Comment by 40P3** [comment]
Not sure what you mean. When I try to right click on an icon in the row they jump around then, not when I'm using the buttons in combat. I'll check it again tonight, importing it to a profile maybe you don't see them jump around in edit mode, then it was just a bug that we can't reproduce weirdly. I'll double check.
