### ISSUE TITLE
Editing Text Displays Loads Blank Dogtag Window

### ISSUE THREAD

**Issue by bren604** [ascott18/TellMeWhen#2069]
### WoW Version

Wrath Classic

### TellMeWhen Version

10.0.8

### Describe the bug

Trying to edit a Text Displays input field (display 1, display 2, etc) loads a blank Dogtag help window. Multiple load if you click the text displays input field again. The Dogtags sidebar that usually shows the tags is also blank.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Upstream fix will be included in the next version of TMW https://github.com/parnic/LibDogTag-3.0/commit/46f9fc8a565f3d641d3586d36a0e7634737dff8c
