### ISSUE TITLE
Lags when combat event icon is triggered

### ISSUE THREAD

**Issue by Rackelhardt** [ascott18/TellMeWhen#2070]
### WoW Version

Retail

### TellMeWhen Version

10.0.8

### Describe the bug

I am not 100% sure but it seems that Combat Event produces mini lags.

Since Patch 10.0.5 i discovered that i have mini lags only in Arena.
Arena is the only place where i use combat events (say-message when our healer is kicked).

Today i made a combat event for outside (when i summon an Elemental) and i had these 1 sec lag again everytime the combat event was triggered. When i deleted the combat event there was no lags anymore. Reloading UI also helped.

I will check in my next arena games if the mini lag comes from the "healer is kicked"-combat event.

But again im not 100% sure if this is because of something else, maybe from Blizzard.

### Export Strings

```text
^1^T^SShowTimer^B ^SType^Scleu ^SConditions^T ^N1^T ^SType^SALIVE ^SUnit^Spet ^t^N2^T ^SType^SUNITISUNIT ^SUnit^Spet ^SName^SUrerdelementar ^t^Sn^N2 ^t^SCLEUDur^N0 ^SName^SErdelementar:~`60 ^SSourceUnit^Splayer ^SCLEUEvents^T ^SSPELL_CAST_SUCCESS^B ^t^SShowTimerText^B ^SEnabled^B ^SInvertTimer^B ^t^N100800^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
Unable to reproduce. 

Try disabling all other addons except TellMeWhen to see if the problem persists. If it goes away, the problem isn't TMW.

**Comment by Rackelhardt** [comment]
Yeah, the problem was from Blizzard. Dont have it anymore

Am Mo., 27. Feb. 2023 um 02:18 Uhr schrieb Andrew Scott <
***@***.***>:
