### ISSUE TITLE
Icon with custom layout not importing or exporting correctly

### ISSUE THREAD

**Issue by Yitaarli** [ascott18/TellMeWhen#2073]
### WoW Version

Retail

### TellMeWhen Version

10.0.8

### Describe the bug

I first reported this on the discord server and was told to post it here by Alweis who confirmed the export string was not working. The string in question is included. 

This icon functions fine on my warrior character but when I tried to send it to my friend who asked me to make it for him, he was unable to import either the icon or the custom icon layout. I also noticed last night when I tried to import it to one of my other characters that I could import the layout only and the layout's name was bugged out (see picture). 

![image](https://user-images.githubusercontent.com/112441138/218315594-2a5a12f6-543f-4008-85c9-feccba962208.png)

Bizzarely, I just tried the exact same icon again on the same character as last night and it now seems to be functioning normally! I suspect this is my error but I thought I'd better just post it here anyway in case it is in fact a bug.

![image](https://user-images.githubusercontent.com/112441138/218315636-1dfc4898-afe6-4f0d-b014-568265c583a8.png)

### Export Strings

```text
String I posted on discord:

^1^T^SShowTimer^B ^SType^Sbuff ^SShowTTText^B ^SShowTimerText^B ^SName^SIgnore~Pain ^SSettingsPerView^T ^Sicon^T ^STextLayout^STMW:textlayout:1Zw1v1VUaU89 ^STexts^T ^N1^S[[Stacks~/~1000]:Round(0)~"k"] ^N2^S[Stacks] ^t^t^t^SCustomTex^S190456 ^SStates^T ^N102^T ^SAlpha^N1 ^t^t^SOnlyMine^B ^SEnabled^B ^t^N100800^S~~| ^Sicon^^

^1 ^T^N1^T ^SAnchors^T ^N1^T ^Sy^N-12 ^Spoint^SBOTTOM ^SrelativePoint^SBOTTOM ^t^t^SJustifyV^SBOTTOM ^SStringName^SIgnore~Pain~amount ^SDefaultText^S[Stacks] ^SSize^N11 ^t^SGUID^STMW:textlayout:1Zw1v1VUaU89 ^SName^SIgnore~Pain~Icon~Layout ^t^N100800^S~`~| ^Stextlayout^STMW:textlayout:1Zw1v1VUaU89 ^^

String I collected today for comparison:

^1^T^SShowTimer^B ^SType^Sbuff ^SShowTTText^B ^SName^SIgnore~`Pain ^SShowTimerText^B ^SSettingsPerView^T ^Sicon^T ^STextLayout^STMW:textlayout:1Zw1v1VUaU89 ^STexts^T ^N1^S[[Stacks~`/~`1000]:Round(1)~`"k"] ^N2^S[Stacks] ^t^t^t^SCustomTex^S190456 ^SStates^T ^N102^T ^SAlpha^N1 ^t^t^SOnlyMine^B ^t^N100800^S~`~| ^Sicon^^^1 ^T^N1^T ^SJustifyV^SBOTTOM ^SAnchors^T ^N1^T ^Sy^N-12 ^Spoint^SBOTTOM ^SrelativePoint^SBOTTOM ^t^t^SStringName^SIgnore~`Pain~`amount ^SDefaultText^S[Stacks] ^SSize^N11 ^t^SGUID^STMW:textlayout:1Zw1v1VUaU89 ^SName^SIgnore~`Pain~`Icon~`Layout ^t^N100800^S~`~| ^Stextlayout^STMW:textlayout:1Zw1v1VUaU89 ^^
```

**Comment by ascott18** [comment]
The string was corrupted, presumably by being pasted on a platform that stripped some of its formatting.
