### ISSUE TITLE
Text on debuff bar not showing

### ISSUE THREAD

**Issue by geckzilla** [ascott18/TellMeWhen#2074]
### WoW Version

Retail

### TellMeWhen Version

10.0.8

### Describe the bug

I've been using this to track the Mark of Lightning/Wind affix in M+. It's a group controller that will plop a stack of bars with all the party member names when the marks go out, just like the WeakAura that most people use. When I test it with a buff it works fine, but when the real debuff gets applied, the bar shows as empty instead of the [AuraSource:Name] showing up. I've decided it's probably a bug that only applies to debuffs.

### Export Strings

```text
^1^T^SGUID^STMW:group:1Ztfny9GR5ec ^SPoint^T ^Sy^N-30 ^SrelativeTo^STMW:group:1ZtfAS2SLw8h ^Spoint^STOPLEFT ^SrelativePoint^STOPLEFT ^Sx^N3 ^t^SScale^N2.3862 ^SRows^N5 ^STextureName^SClean ^SRole^N3 ^SView^Sbar ^SColumns^N1 ^SIcons^T ^N1^T ^SBuffOrDebuff^SHARMFUL ^SUnit^Sgroup~`1-40 ^SDurationMin^N5 ^SType^Sbuff ^SBarDisplay_ClassColor^B ^SName^SMark~`of~`Lightning ^STimerBar_EnableColors^B ^SGUID^STMW:icon:1ZwxInc625G6 ^SSettingsPerView^T ^Sbar^T ^STextLayout^Sbar1 ^STexts^T ^N1^S ^N2^S[AuraSource:Name] ^t^t^t^SEnabled^B ^t^t^SName^SLightning~`Bars ^SSettingsPerView^T ^Sicon^T ^SBorderInset^B ^SSpacingX^N-5 ^SSpacingY^N-5 ^t^Sbar^T ^SSizeY^N12 ^SBorderInset^b ^t^t^SControlled^B ^t^N100800^S~`~| ^Sgroup^N11 ^^
```

**Comment by Alwies** [comment]
"[AuraSource:Name]" Would be Razageth (or environment based on how they coded it).
Use "[Unit:Name]" instead

**Comment by geckzilla** [comment]
Right, dang it, one of these days I'll stop being confused by that and I'll find an actual bug to report.
