### ISSUE TITLE
Text layout -> Groups

### ISSUE THREAD

**Issue by Ermintruder** [ascott18/TellMeWhen#2078]
Hi.
I have used TMW for about 10 to 15 years. And it is awesome. Actually I would say I cant play Wow without it. 
But I have a big issue with it these dayes. Maybe this feature have been removed or it is solved in another way that I am not aware of. But for some time/year's mabye I could change the Text layout for a hole group at the same time. There was a setting for that in the group tab. But now it is not there. So when I have to change all of my icons text layout I have to click on every single icon to do that, and that is very tideous and take so much time. And it is frustrating when I know it has been possible to do it in just a few klick on group level before.
So is this removed or is it done in another way?
And if it is not a feature now, is it possible to put it in again?

WoW Version
Retail

TellMeWhen Version
v10.0.9

**Comment by ascott18** [comment]
Its right here - didn't go anywhere

![image](https://github.com/user-attachments/assets/d5992d98-70c9-4231-aec4-08a9df3d3c4d)
