### ISSUE TITLE
TMW Causing taint, blocking all keyboard actions if entering combat during or shortly after loading UI

### ISSUE THREAD

**Issue by ssateneth** [ascott18/TellMeWhen#2093]
### WoW Version

Wrath Classic

### TellMeWhen Version

10.1.1 r1 (gb7aad41)

### Describe the bug

When entering combat during a UI load or shortly after the UI loads, "Interface Action failed because of an addon" occurs and you cannot use any keyboard binds to control your character (moving with keyboard, casting spells with keyboard) unless you exit combat. Clicking spells and using mouse buttons/movement to move still work. Further, taint log reveals this.

6/30 16:37:34.850  An action was blocked in combat because of taint from TellMeWhen_Options - Frame:SetPropagateKeyboardInput()
6/30 16:37:34.850      Interface/AddOns/TellMeWhen/Components/Core/Suggester/Suggester.lua:437

This is spammed dozens of times in taint log.

This still occurs with no addons loaded EXCEPT tellmewhen. The loss of control ONLY occurs if you have NOT used any keyboard binds BEFORE entering combat. Using keyboard controls BEFORE combat still allows keyboard control after entering combat BUT it still causes the taint to occur.

### Export Strings

```text
N/A - This character uses no TMW icons/bars, either global or character only.
```

**Comment by Alwies** [comment]
With 10.1.5 this bug is now present on retail as well.
