### ISSUE TITLE
Power check not working with spells that cost multiple powers

### ISSUE THREAD

**Issue by asalib** [ascott18/TellMeWhen#2099]
### WoW Version

Retail

### TellMeWhen Version

10.1.5

### Describe the bug

With 10.1.5, several holy paladin spenders were changed from costing holy power to costing holy power AND mana. "Power check" on an icon appears to only be checking for mana, leading to the spell icon appearing as if it is ready to use even when the player doesn't have the required holy power to cast the spell.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Unable to reproduce with Light of Dawn.
