### ISSUE TITLE
Bug: Dynamic Centering doesn't seem to exist if layout is horizontal

### ISSUE THREAD

**Issue by Jalopyy** [ascott18/TellMeWhen#21]
v8.6.0 r7 g9d95ce35

I can get the dynamic centering work vertical, but not horizontal. Been trying random icon sortings and layout directions w/shrink group on. Nothing works.

https://gfycat.com/needybarechimpanzee

Notice how it centers the group in the middle, vertical wise, but won't center it horizontal wise.

**Comment by Jalopyy** [comment]
Update: It works, just not when the row count is >1.

**Comment by ascott18** [comment]
Your anchor points (in the Position settings) are both on the left, so your group will always align to the left.

Change the Group Point to center.

**Comment by Jalopyy** [comment]
Ah shit you're right. I always assumed that that anchor point diagram was for X/Y positioning in regard to the area of the screen...or something...
