### ISSUE TITLE
Glimmer not tracking? no stacks shown?

### ISSUE THREAD

**Issue by WEEZYPEANUT** [ascott18/TellMeWhen#2101]
### WoW Version

Retail

### TellMeWhen Version

v10.1.5

### Describe the bug

Im pretty sure this is a bug? Glimmer of light for holy paladins is not tracking the stacks is just shows nothing on the icon it used to work in shadowlands, all i want to do is be able to track glimmers so i know how many i have on player targets

### Export Strings

```text
^1^T^SOnlyMine^B ^SType^Sbuff ^SName^S287280 ^SSettingsPerView^T ^Sicon^T ^STextLayout^Sicon1 ^t^t^SEnabled^B ^t^N101500^S~`~| ^Sicon^^
```

**Comment by Alwies** [comment]
That sounds more like this dogtag:
https://gyazo.com/f9366b2b4148b7da08bfef3c671755cf

**Comment by ascott18** [comment]
Correct. The icon provided in the issue is not how stack tracking ever worked on buff icons. The `[RaidStacks]` tag on a text display would be the correct way to display this.

**Comment by WEEZYPEANUT** [comment]
Im sorry i cant get this to work, is there any video or explanation on how? am i still making the icon iin buff/debuff? how do ii set up raid stacks?

**Comment by Alwies** [comment]
A buff/debuff icon will work but the icon itself doesn't matter as it's a dogtag, meaning it can be used on any icon. 
Paste this in a text display (icon menu > bottom right):
`[RaidStacks("Glimmer of Light")]`

If you're still having issues after please use the TMW discord.
As every time we post here we send out notifications.
