### ISSUE TITLE
Classic 9.2.2 blows up on Turtle WoW

### ISSUE THREAD

**Issue by JaggedOne** [ascott18/TellMeWhen#2102]
### WoW Version

Classic/Classic SoM

### TellMeWhen Version

9.2.2

### Describe the bug

I play on Turtle WoW. I searched for one of my all-time favorite WoW addons, TellMeWhen, and was delighted to find it on CurseForge.com. I clicked on "WoW Classic", and selected the latest version listed - 9.2.2-classic, which downloaded
as TellMeWhen-922-classic.zip. Unzipping this into my Interface/Addons directory created 2 directories - TellMeWhen and TellMeWhen_Options.

Upon entering the game and checking the Addons, both TellMeWhen and TellMeWhen Options showed as Out of Date. I clicked Load Out of Date Addons. When I loaded my character, my chat box blew up with red error messages from TellMeWhen, far too many to list. The first one was "attempt to index global '_G' (a nil value)".

I am heartbroken - I loved this addon back in the day when I played WoW live.
Am I doing something wrong - is there any way to get this to work ?

Thanks for your work and your (hopeful) response and support !!!

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Private servers use the original client from 2005. WoW Classic uses the modern game client. TMW will never support private servers that use an 18 year old game client.

**Comment by JaggedOne** [comment]
Thanks for your reply !!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
