### ISSUE TITLE
"ItemCooldown" function not working for classic after update

### ISSUE THREAD

**Issue by Navic9** [ascott18/TellMeWhen#2105]
### WoW Version

Classic/Classic SoM

### TellMeWhen Version

9.2.2 classic

### Describe the bug

Whenever you try to use to condition "item cooldown" you get LUA error over and over again so the game becomes unplayeble.

This happend yesterday after the classic UI update. 

### Export Strings

```text
N/A. I cant even re-create this string since useing the function "item cooldown" freezes the whole game.
```

**Comment by ascott18** [comment]
Fixed in 10.1.6
