### ISSUE TITLE
Era version broken after the new patch

### ISSUE THREAD

**Issue by Painstormx** [ascott18/TellMeWhen#2106]
### WoW Version

Classic/Classic SoM

### TellMeWhen Version

10.1.5

### Describe the bug

Blizzard changed Era to use the retail client, so the addon/macro API has changed 😦
Sometimes the Wrath versions of the addons will work, but I can't get that to work with TMW either.
Message: ...nterface/AddOns/TellMeWhen/Components/Core/Utils.lua line 1555:
   attempt to call upvalue 'GetSpecialization' (a nil value)
Debug:
   [string "@Interface/AddOns/TellMeWhen/Components/Core/Utils.lua"]:1555:
      ...nterface/AddOns/TellMeWhen/Components/Core/Utils.lua:1554
   [string "@Interface/AddOns/TellMeWhen/Components/Core/Group.lua"]:352: ShouldUpdateIcons()
   [string "@Interface/AddOns/TellMeWhen/Components/Core/Group.lua"]:393: Setup_Conditions()
   [string "@Interface/AddOns/TellMeWhen/Components/Core/Group.lua"]:477:

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Fixed in 10.1.6
