### ISSUE TITLE
Wotlk Classic - TMW doesn't track when Penance is interrupted like it does for other spell casts/channels.

### ISSUE THREAD

**Issue by BrianShaw23** [ascott18/TellMeWhen#2107]
### WoW Version

Wrath Classic

### TellMeWhen Version

v10.1.5

### Describe the bug

When you use "Combat Event" to track when spells are interrupted with abilities like Mind Freeze, Kick, etc. it works for many spell casts but not Penance. If you interrupt Penance with Mind Freeze TMW will not track it and show that the Priest is interrupted.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
If TMW can't see it then it isn't in the combat log and can't be tracked. I very strongly remember this being how penance worked in original Wrath too.

**Comment by BrianShaw23** [comment]
Thank you Scott, all good!
