### ISSUE TITLE
Era - Herb/Mineral tracking (as missing buff) no longer works

### ISSUE THREAD

**Issue by Painstormx** [ascott18/TellMeWhen#2108]
### WoW Version

Classic/Classic SoM

### TellMeWhen Version

10.1.6 r1

### Describe the bug

Tried the new beta version for Era. Works a lot better than yesterdays version :)
Still some issues with Mineral/Herbs tracking.
I use to track them as "Missing buffs"

### Export Strings

```text
^1^T^SType^Sbuffcheck ^SName^SFind~`Minerals ^SEnabled^B ^SConditions^T ^N1^T ^SType^STRACKING ^SLevel^N1 ^SName^SFind~`Minerals ^t^Sn^N1 ^t^t^N100800^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
These aren't buffs (I'm not sure they ever were, but at the very least they aren't now). Use the Tracking Active condition (which was just fixed in 10.1.6 r2 417ec7a)
