### ISSUE TITLE
error on rogue, lvl 16

### ISSUE THREAD

**Issue by amey1956** [ascott18/TellMeWhen#2110]
### WoW Version

Classic/Classic SoM

### TellMeWhen Version

10.1.6

### Describe the bug

`[string "local sName, sLink, iRarity, iLevel, iMinLe..."]:1: Usage: GetItemInfo(itemID|"name"|"itemlink")
[string "=[C]"]: in function `GetItemInfo'
[string "local sName, sLink, iRarity, iLevel, iMinLevel, sType, sSubType, iStackCount = GetItemInfo(GetInventoryItemID("player", 16));

if sSubType == "Daggers" then
    return true
    
end"]:1: in function `LF_000001CFD0620978'
[string "Condition_LUA"]:3: in function `CheckFunction'
[string "@TellMeWhen/Components/Core/Conditions/ConditionObject.lua"]:266: in function `Check'
[string "@TellMeWhen/Components/Core/Icon.lua"]:770: in function `Update'
[string "Condition_ICON"]:3: in function `CheckFunction'
[string "@TellMeWhen/Components/Core/Conditions/ConditionObject.lua"]:266: in function `Check'
[string "@TellMeWhen/Components/Core/Conditions/UpdateEngine.lua"]:151: in function <...llMeWhen/Components/Core/Conditions/UpdateEngine.lua:146>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[4]"]:9: in function <[string "safecall Dispatcher[4]"]:5>
[string "=(tail call)"]: ?
[string "@TellMeWhen/TellMeWhen.lua"]:836: in function `Fire'
[string "@TellMeWhen/TellMeWhen.lua"]:2616: in function <TellMeWhen/TellMeWhen.lua:2595>

Locals:
`
i am not aware of anything i am doing that could cause this, other than it references lvl 16 & dagger

### Export Strings

```text
n/a
```

**Comment by ascott18** [comment]
This is coming from your own custom code in a Lua condition.
