### ISSUE TITLE
Retributio Paladin,"Custom Texture"display errors

### ISSUE THREAD

**Issue by ymmum1985** [ascott18/TellMeWhen#2114]
### WoW Version

Retail

### TellMeWhen Version

10.1.6

### Describe the bug

"Custom Texture"
Interface/Color/1.tga
But it didn't display the correct image; instead, it showed the icon for 'Avenging Wrath'.
This bug only occurs with the Retributio Paladin.

### Export Strings

```text
N/A
```

**Comment by ymmum1985** [comment]
I created another Retribution Paladin, but didn't encounter this issue. Could it be related to the character's name?
It seems that the custom image isn't displaying successfully. Originally, it would show a green or transparent image, but now it displays the 'Avenging Wrath' icon.
I'm certain that the file path is correct because it displays the custom image correctly when changed to 'Protection' or 'Holy.' The issue only occurs when set to 'Retribution,' where it incorrectly shows the 'Avenging Wrath' image..
The above issue only exists in version 10.2; it wasn't observed in version 10.1.7.

**Comment by ymmum1985** [comment]
![BUG2](https://github.com/ascott18/TellMeWhen/assets/150395889/2252f0a0-59e2-4a80-96b4-7b6b7deff059)

**Comment by ymmum1985** [comment]
I have found the cause of this bug. Although it's a strange thing, it does work. If the 'Avenging Wrath' ability has a glyph, this bug occurs. However, removing the glyph resolves the issue. I hope this solution helps more people.

**Comment by ascott18** [comment]
Thanks for tracking that down. I added a workaround in TellMeWhen and reported to the unofficial addon API bug tracker.

**Comment by ascott18** [comment]
Actually the problem is way worse than just custom textures, so a larger fix may be needed here...
![image](https://github.com/ascott18/TellMeWhen/assets/5017521/b23d6077-b696-450f-8ac0-dd64885f99dd)

**Comment by ascott18** [comment]
Fix 2 now with 100% less avenging wrath 
![image](https://github.com/ascott18/TellMeWhen/assets/5017521/bb9659ca-725d-423d-a9aa-a889a4fc5079)

**Comment by ascott18** [comment]
GetSpellTexture no longer seems to be bugged in this way
