### ISSUE TITLE
Dawn of the Infinite,Error message

### ISSUE THREAD

**Issue by ymmum1985** [ascott18/TellMeWhen#2115]
### WoW Version

Retail

### TellMeWhen Version

10.1.6

### Describe the bug

Message: [string "safecall Dispatcher[1]"]:9: script ran too long
Time: Fri Nov 10 07:00:30 2023
Count: 1
Stack: [string "safecall Dispatcher[1]"]:9: script ran too long
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2721: in function `UpdateNormally'
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2870: in function `Update'
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2878: in function `?'
[string "@Interface/AddOns/Details/Libs/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <...ce/AddOns/Details/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: func = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Group.lua:425
(*temporary) = true
(*temporary) = "script ran too long"
method = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Conditions/ConditionObject.lua:260
arg1 = <table> {
 conditionString = "local ConditionObject = ... 
 return (
     ( not ( UnitExists("mouseover") and not UnitIsDeadOrGhost("mouseover") )) -- 1_ALIVE
    and(( UnitIsPlayer("mouseover") )) -- 2_ISPLAYER
    and((select(2, LibRangeCheck:GetRange("mouseover")) or huge) <= 40) -- 3_LIBRANGECHECK
    and(AuraDur("mouseover", "正在复活", "HARMFUL") == 0) -- 4_DEBUFFDUR
    and(( UnitAffectingCombat("player") )) -- 5_COMBAT
 )"
 NextUpdateTime = Infinite
 UpdateMethod = "OnUpdate"
 RequestedEvents = <table> {
 }
 UpdateNeeded = true
 AutoUpdateRequesters = <table> {
 }
 getsExternallyUpdated = true
 Failed = true
 registeredForUpdating = true
 numArgsForEventString = 1
 CheckFunction = <function> defined Condition_ALIVE_ISPLAYER_LIBRANGECHECK_DEBUFFDUR_COMBAT:0
 funcIdentifier = "_ALIVE_ISPLAYER_LIBRANGECHECK_DEBUFFDUR_COMBAT"
 ExternalUpdaters = <table> {
 }
}
xpcall = <function> defined =[C]:-1
call = <function> defined safecall Dispatcher[1]:3
eh = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:501

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
TMW is already pretty conservative with execution limits per frame. There's not really anything I can do about these kinds of errors.
