### ISSUE TITLE
Efflorescence Icon/Timer not working 

### ISSUE THREAD

**Issue by adhamayoubi** [ascott18/TellMeWhen#2121]
### WoW Version

Retail

### TellMeWhen Version

10.1.6

### Describe the bug

On my resto druid, I use Efflorescence, Lifebloom, Swiftmend, and Flourish timers. Both the built-in Efflorescence or manually created spellcast (I've tried every spell number and version of Efflorescence) doesn't work or reflect any changes in the configuration. I'll cast Efflo and stand in it, not stand in it, etc. and the icon doesn't disappear and the timer doesn't start tracking the spell duration remaining. Lifebloom still works with no issues but the Efflo TMW tracker died once 10.2 dropped and hasn't worked since. Randomly the icon will sometimes disappear, but without any measurable regularity or causation, and even when it does the timer still isn't working.
![Screenshot 2023-11-17 131924](https://github.com/ascott18/TellMeWhen/assets/61243896/d7ca28d8-6f89-48d2-8054-c2a58c6fd594)

### Export Strings

```text
^1^T^SShowTimer^B ^SType^Stotem ^SName^SEfflorescence ^SStates^T ^N1^T ^SAlpha^N0 ^t^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^t^N101600^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
Looks like its no longer treated as a totem by the game - its just a buff, so you can switch to tracking it with a buff/debuff icon.
