### ISSUE TITLE
Timer on Condition - Debuff % Duration not working properly

### ISSUE THREAD

**Issue by Betaskill** [ascott18/TellMeWhen#2126]
### WoW Version

Retail

### TellMeWhen Version

10.2.0

### Describe the bug

Hi there,

there is a "weird" thing going on with the icon condition: Debuff - Duration - Percentage . I guess that it happens because this conditon has an intern timer instead of tracking the actual runtime on the target. 

What is happening: 

The balance druid has a talent "Aetherial Kindling" where starfall extend the duration of moonfire and sunfire. If you are using the Debuff - Duration - Percentage condition set to lets say <= 30% (see icon below) and you are continuously extending the duration the intern timer from the conditions is continuously counting upward and then it can happen that the dots are having a runtime of like 26 seconds (from max 28).  At a time the icon will be visible at a duration above 30% like 20seconds and the intern timer is still counting upwards until it will go completely into synch where the dots are having a runtime of 28seconds and the icon is showing at 28 seconds, and so on. This is possible with the BL buff.  

Btw, I´m using the german client. 

Hope that the explanation was somehow understandable and thank you for your effort :)

### Export Strings

```text
^1^T^SBuffOrDebuff^SHARMFUL ^SUnit^Starget ^SType^Sbuff ^SName^S164812 ^SEnabled^B ^SConditions^T ^N1^T ^SType^SDEBUFFPERC ^SChecked^B ^SOperator^S<= ^SUnit^Starget ^SLevel^N30 ^SName^S164812 ^t^Sn^N1 ^t^t^N102000^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
Unable to reproduce. The "internal timer" being theorized does not exist and has never existed.
