### ISSUE TITLE
Unit Cooldown - Duration Requirements (Minimum) not working properly

### ISSUE THREAD

**Issue by Betaskill** [ascott18/TellMeWhen#2127]
### WoW Version

Retail

### TellMeWhen Version

10.2.0

### Describe the bug

Hi there, 

I am having a werid behavior with the "Minimum" Option in the "Duration Requirements" from the Unit Cooldown-Icon. 

If I set that the Icon should not be visible at a Minimum duration of < 10 sek of the cooldown for the Evoker spell spell "Blessing of the Bronze" the icon is sometimes behaving correctly sometimes not. Sometimes the icon will be hidden if the <10 seconds window has been reached - which is also correct. The problem is, it is only sometimes hidden and not always on hidden. 

I am using the german client and have also created a video to get a better impression of what I mean:

https://youtu.be/MgwDrptn7Dc

This is not only due to the  spell "Blessing of the Bronze"  but with other spells too. 

This is my evoker talent build: 
BEcBsJu/D+01p9npZvkV+nWIkHJlkWEJahkkSCSSSDAAAAACAAkEkoIiECJJAAAAIJJikIkARD

Thank you for taking a look at it. 

### Export Strings

```text
^1^T^SShowTimer^B ^SType^Sunitcooldown ^SName^S364342:~`14 ^SDurationMinEnabled^B ^SOnlySeen^B ^SShowTimerText^B ^SCustomTex^S364342 ^SStates^T ^N1^T ^SAlpha^N0 ^t^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^SDurationMin^N10 ^SDurationMax^N10 ^t^N102000^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
Unable to reproduce
