### ISSUE TITLE
LibRangeCheck-3.0 Needs Updating

### ISSUE THREAD

**Issue by Difjob** [ascott18/TellMeWhen#2134]
### WoW Version

Retail

### TellMeWhen Version

10.2.0

### Describe the bug

The LibRangeCheck-3.0 provided with TellMeWhen doesn't work once combat starts.

I've manually updated the Lib with it's latest version (v1.0.9) and it works in combat now.

Just letting you know it needs updating really.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Such a version was already available - https://legacy.curseforge.com/wow/addons/tellmewhen/files/4977722
