### ISSUE TITLE
WOW Classic SOD Warlock Metamorphosis 

### ISSUE THREAD

**Issue by ahooten3** [ascott18/TellMeWhen#2136]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hello, 

I was hoping you guys could add all the spells for the WOW Classic SOD Warlock rune Metamorphosis (demon charge, shadow cleave, menace, etc.) to your database, so I can use them with your spell cooldown feature. 

I guess there might be a way to manually make spell groups, but I don't know how, and it would just be easier if these new spells were added.

**Comment by ascott18** [comment]
TellMeWhen does not have a spell database. The suggestion list is just a list of suggestions. You're free to type in whatever you like in any input field in the addon.
