### ISSUE TITLE
Claissic Era/SoD: Condition icons broke once again with new version (10.2.1)

### ISSUE THREAD

**Issue by Painstormx** [ascott18/TellMeWhen#2137]
### WoW Version

Classic/Classic SoM

### TellMeWhen Version

10.2.1

### Describe the bug

When you try to add a condition for like "Find Minerals" tracking, there are no spells listed and the icon I had working before, no longer works.
Same error has been there in previous versions, but it was fixed in 10.2.0 I think.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Sorry, blizzard keeps messing with the APIs. I changed it to detect whether the modern tracking API is present or not, but some time shortly after that change blizzard decided to add that API into classic era in a non-functional state.

**Comment by Painstormx** [comment]
Yeah, I can imagine they would just do that.
Thanks for keep fixing it :)
