### ISSUE TITLE
Feature Request: Icon Sorting by Stack Order

### ISSUE THREAD

**Issue by Mosborne90** [ascott18/TellMeWhen#2138]
**Is your feature request related to a problem? Please describe.**
I mostly use the addon in a way that allows me to build a priority system by using the Icon is Shown condition. Using this method, I can have an entire group of icons that only shows 1 at a time and doesn't change position. it's like a rotation helper.

e.g. : Holy Shock is more important than Judgment, so add an icon is shown condition to Judgment that tells it to only show when Holy shock is hidden.

The problem: As a full rotation, let's say with 10 buttons; I have to add the Icon is Shown condition for all icons that are higher priority. This results in a bloated list of conditions that all serve to create a system that only shows the most important icon. So lets say the 10th spell in the rotation is the lowest priority, it needs 9 conditions added from the icons above it to tell it to only show when those icons are hidden.

**Describe the solution you'd like**
A solution I would like is some type of icon sorting that recognizes that icons above that icon are higher priority, or a system that automatically adds all parent icons 'icon is shown condition'.

**Describe alternatives you've considered**
No alternate solution found.

**Additional context**

Here is an image that shows that Holy Light in the rotation requires an icon is shown condition for all above icons.
<img width="529" alt="image" src="https://github.com/ascott18/TellMeWhen/assets/61567207/4543f4e0-9cad-468b-8c17-dfe57cb33471">

**Comment by Alwies** [comment]
You can already do this. 
Create a meta icon and when selecting an icon to display select your priority group instead.
EG: https://gyazo.com/41007251ebafcd71f37e1ddc6e04648f
What it'll do is display the first shown icon in that group, based on icon ID (see title bar in options for the icon ID).

If you or anyone else have any further questions please use the TMW discord.

Disclaimer: I'm not a TMW developer

**Comment by Mosborne90** [comment]
Thanks @Alwies for the solution!
