### ISSUE TITLE
Geeting so many errors of UI and having to reload every 5 minutes.

### ISSUE THREAD

**Issue by Morfogore** [ascott18/TellMeWhen#2141]
### WoW Version

Retail

### TellMeWhen Version

10.2.2

### Describe the bug

im getting this bug everytime. but i dont know what is cauusing it

32x [ADDON_ACTION_BLOCKED] AddOn 'TellMeWhen' tried to call the protected function 'resume()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `resume'
[string "@TellMeWhen/TellMeWhen.lua"]:2680: in function <TellMeWhen/TellMeWhen.lua:2669>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

### Export Strings

```text
32x [ADDON_ACTION_BLOCKED] AddOn 'TellMeWhen' tried to call the protected function 'resume()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `resume'
[string "@TellMeWhen/TellMeWhen.lua"]:2680: in function <TellMeWhen/TellMeWhen.lua:2669>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
```

**Comment by Alwies** [comment]
Wouldn't normally reply here. But as you're having to reload every 5 min.
Simply put the error is due to a blizzard bug that causes false reports. You should be able to press ignore and well completely ignore it without issue.

This is a know issue and has been posted before: #2124

**Comment by Morfogore** [comment]
i cant just click ignore. if i do that i cant play, the message continue popping and i cant use keybinds, im forced to reload.
