### ISSUE TITLE
Feature Request:  Decrease Sensitivity On Scale Slider 

### ISSUE THREAD

**Issue by Necrochrist** [ascott18/TellMeWhen#2146]
**Is your feature request related to a problem? Please describe.**
Scale slider increments are too sensitive.  Trying to achieve a specific scale is nearly impossible and very time-consuming using the slider.

**Describe the solution you'd like**
Either add a numerical input field so a specific number can be typed in, or decrease the sensitivity of the slider.

**Describe alternatives you've considered**

**Additional context**
When trying to stack single group icons and their scale becomes out of adjustment, and when it is impossible to 'Undo', the scale slider is the only way to achieve a scale match.

**Comment by Alwies** [comment]
> Either add a numerical input field so a specific number can be typed in, or decrease the sensitivity of the slider.
To type in a number right click the slider.

Note: works for sliders in conditions, not for some others like the opacity sliders in the icon menu. The ones where it'll work have the tooltip "Right click to switch to manual input"
