### ISSUE TITLE
Item use opacity is now wrong

### ISSUE THREAD

**Issue by AzatoR62** [ascott18/TellMeWhen#2155]
### WoW Version

Retail

### TellMeWhen Version

10.2.3

### Describe the bug

I had 2 icons, one for Fyr'alath and the other for ashes (trinket). I set opacity at 100 when usable and 30 when unusable. Before all worked fine, but since today my icon will always be on 'Unusable' at 30 opacity, even if both my items are usable. Strangely when i set the opacity of 'Unusable' at 100, it change the opacity of my icons. Even if they are usable, it's the opacity of unusable that is used. Have an idea ? :)

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Blizzard changed GetItemCooldown to return booleans in its third return, but didn't change the inventory version of the function to do the same. Awesome.

![image](https://github.com/ascott18/TellMeWhen/assets/5017521/6a42c523-bcb2-4d37-a328-20afb97e00e5)

**Comment by AzatoR62** [comment]
Everything is great again ! Thanks for the reactivity and the good work, keep it rollin' :)
