### ISSUE TITLE
Activation Border isn't round anymore if i use round Icon-skin (via masque)

### ISSUE THREAD

**Issue by Rackelhardt** [ascott18/TellMeWhen#2158]
### WoW Version

Retail

### TellMeWhen Version

10.2.4

### Describe the bug

I didnt play WoW for like 14 months.
When i started the game yesterday i realized that the activation border effect was updated (looks better now).
But unfortunately it isn't round anymore on my round icons (via masque).

![ff](https://github.com/ascott18/TellMeWhen/assets/76191859/e6bf1901-10bb-416c-87d6-574abe2e2322)

I don't know if this problem comes from masque or from TMW.
I tested it with masque: raeli (ring) and with masque: cirque. Neither of them have shown the effect round.
If this problem does not come from TMW, ignore this report.

### Export Strings

```text
N/A
```

**Comment by Rackelhardt** [comment]
Hey.
the Creator of Masque fixed the problem with the round activation border in the newest Beta-Version.
Check this link:
https://github.com/SFX-WoW/Masque/issues/361#issuecomment-2211495636

It already works with other addons (such as Bartender4).
But not yet with TMW.
Could you fix that too? That would be super nice.

![lel](https://github.com/ascott18/TellMeWhen/assets/76191859/1a193502-0d93-4843-9d7a-f3b50f5cddfa)

**Comment by cagricesur** [comment]
this issue is still there and the problem started when Blizzard introduced new proc glow, if that hint helps.
I also am using Masque-Raeli and even though issue does not affect functionality it is kinda frustrating ui wise. Any solution / response will be appreciated

**Comment by Rackelhardt** [comment]
Check this out:

https://github.com/SFX-WoW/Masque/issues/361#issuecomment-2224234620

**Comment by ascott18** [comment]
Added support. Note that confusingly, this doesn't come along with the skin and has to be enabled in separate settings in Masque:

![image](https://github.com/user-attachments/assets/020745e2-bca3-4f07-8e92-3e2ad59f7c10)
