### ISSUE TITLE
Missing Holy Power Resource

### ISSUE THREAD

**Issue by Kathorgan** [ascott18/TellMeWhen#2159]
### WoW Version

Wrath Classic

### TellMeWhen Version

10.2.5

### Describe the bug

Holy Power is missing from resource options. This addon from curseforge claims to be Classic Cataclysm ready. Paladins have up to 3 holy power and we should be able to set conditions depending on how much is available.

### Export Strings

```text
N/A
```

**Comment by Alwies** [comment]
Install the Alpha version.
Either by selecting Alpha in your addon manager or manually from:
 https://www.curseforge.com/wow/addons/tellmewhen/files/5309045
