### ISSUE TITLE
Remix: bug on gear equipping

### ISSUE THREAD

**Issue by solitha** [ascott18/TellMeWhen#2162]
### WoW Version

Retail

### TellMeWhen Version

10.2.6

### Describe the bug

To begin, I understand if you don't want to do work for a temporary mode. I'm just hoping... I do rely a lot on TMW. But in learning or equipping gear in Remix I'm getting this:

`4x ...rocessorHook_Texture_CustomTex/Texture_CustomTex.lua:44: attempt to index field 'CustomTex' (a nil value)
[string "@TellMeWhen/Components/IconDataProcessorHooks/IconDataProcessorHook_Texture_CustomTex/Texture_CustomTex.lua"]:44: in function <...rocessorHook_Texture_CustomTex/Texture_CustomTex.lua:43>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
[string "=(tail call)"]: ?
[string "@TellMeWhen/TellMeWhen.lua"]:844: in function `Fire'
[string "@TellMeWhen/Components/Core/Common/Textures.lua"]:44: in function <...ddOns/TellMeWhen/Components/Core/Common/Textures.lua:30>
[string "@TellMeWhen/Components/Core/Common/Textures.lua"]:50: in function <...ddOns/TellMeWhen/Components/Core/Common/Textures.lua:48>

Locals:
icon = TellMeWhen_GlobalGroup1_Icon1 {
 GUID = ""
 LastUpdate = 0
 ComponentsLookup = <table> {
 }
 Update_Method = "auto"
 EventHandlersSet = <table> {
 }
 attributes = <table> {
 }
 ID = 1
 0 = <userdata>
 position = <table> {
 }
 chargeCooldown = TellMeWhen_GlobalGroup1_Icon1IconModule_CooldownSweepCooldown2 {
 }
 Enabled = false
 Type = "conditionicon"
 NextUpdateTime = 0
 TempGUID = "TMW:icon:1cHcarb2jbWv"
 group = TellMeWhen_GlobalGroup1 {
 }
 Modules = <table> {
 }
 UnitConditions = <table> {
 }
 Name = ""
 lmbButtonData = <table> {
 }
 Conditions = <table> {
 }
 Events = <table> {
 }
 SettingsPerView = <table> {
 }
 viewData = <table> {
 }
 typeData = <table> {
 }
 Components = <table> {
 }
 States = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'CustomTex' (a nil value)"
TMW = TMW {
 0 = <userdata>
 CovenantIcons = <table> {
 }
 SlashCommand = <function> defined @TellMeWhen/TellMeWhen.lua:3024
 modules = <table> {
 }
 CancelTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:147
 DeserializeData = <function> defined @TellMeWhen/Options/TellMeWhen_Options.lua:3907
 InNLengthTable = <function> defined @TellMeWhen/Components/Core/Utils.lua:1060
 InIconSettings = <function> defined @TellMeWhen/TellMeWhen.lua:927
 TryGetNPCName = <function> defined @TellMeWhen/Components/Core/Utils.lua:1631
 DS = <table> {
 }
 ScheduleTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:94
 ConvertContainerToScrollFrame = <function> defined @TellMeWhen/Options/TellMeWhen_Options.lua:118
 GameTooltip_SetDogTag = <function> defined @TellMeWhen/Components/Core/Common/DogTags/config.lua:403
 toSeconds = <function> defined @TellMeWhen/Components/Core/Utils.lua:476
 QueueValidityCheck = <function> defined @TellMeWhen/TellMeWhen.lua:3385
 db = <table> {
 }
 GetDataOwner = <function> defined @TellMeWhen/TellMeWhen.lua:1330
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 CopyWithMetatable = <function> defined @TellMeWhen/Components/Core/Utils.lua:924
 InGroups = <function> defined @TellMeWhen/TellMeWhen.lua:1003
 tDeleteItem = <function> defined @TellMeWhen/Components/Core/Utils.lua:827
 RegisterLuaImportDetector = <function> defined @TellMeWhen/Components/Core/Utils.lua:1667
 operators = <table> {
 }
 isNumber = <table> {
 }
 tRemoveDuplicates = <function> defined @TellMeWhen/Components/Core/Utils.lua:845
 StringToCachedRGBATable = <function> defined @TellMeWhen/Components/Core/Utils.lua:364
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 print = <function> defined @TellMeWhen/TellMeWhen.lua:486
 COMMON = <table> {
 }
 TEXT = <table> {
 }
 binaryInsert = <function> defined @TellMeWhen/Components/Core/Utils.lua:890
 Deserialize = <function> defined @DataStore/libs/AceSerializer-3.0/AceSerializer-3.0.lua:246
 ChangeCounter = <function> defined @TellMeWhen/Components/EventHandlers/Counter/Counter.lua:45
 EquivFullIDLookup = <table> {
 }
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 InitializedDatabase = true
 oneUpString = <function> defined @TellMeWhen/Components/Core/Utils.lua:1291
 name = "TellMeWhen"
 GetSettingsStrings = <function> defined @TellMeWhen/Options/TellMeWhen_Options.lua:3943
 RestoreCase = <function> defined @TellMeWhen/Components/Core/Spells/Spells.lua:493
 Defaults = <table> {
 }
 C = <table> {
 }
 Warn = <function> defined @TellMeWhen/Components/Core/Utils.lua:422
 Print `

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Unable to reproduce
