### ISSUE TITLE
Spell Queued Does Not Appear To Be Working

### ISSUE THREAD

**Issue by artanus3634** [ascott18/TellMeWhen#2163]
### WoW Version

Classic/Classic SoM

### TellMeWhen Version

10.2.6

### Describe the bug

Queuing a spell no longer appears to work with Raptor Strike.  I made a single conditional icon group with a single condition to show when a spell is queued.  Tested with Raptor Strike and Heroic Strike and queuing the spell does not activate the group for Raptor Strike.  Same setup works for Heroic Strike.  Raptor Strike appeared to be registering prior to the last WOW maintenance just fine but not after.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Unable to reproduce.
