### ISSUE TITLE
Spell Casting or Channelling as a "Condition"

### ISSUE THREAD

**Issue by Difjob** [ascott18/TellMeWhen#2164]
**Is your feature request related to a problem? Please describe.**

I am unable to use Spell Casting or Channelling as a Condition. I know you can use those for an Icon Type but there's some situations where it would be useful to be able to set a condition for specific spells.

An example of how I would use it is on Shadow Priest. I'd want to hide certain other Icons using a condition if Void Torrent or Mind Flay: Insanity is channelling so that there's less chance of accidentally interrupting them with weaker abilities.

**Describe the solution you'd like**

If it's possible, add Spell Casting or Channelling as a Condition under the Spells/Items category with options for True/False and a box to enter specific spells, like the Icon Type version.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Alwies** [comment]
Scroll down in the section, it's there.
https://gyazo.com/750948889bfeb4a4483f032ef58f040b

**Comment by Difjob** [comment]
Thanks. I feel a bit stupid lol. Didn't even know some of them were scrollable.
