### ISSUE TITLE
Daybreak buff missing

### ISSUE THREAD

**Issue by mrpusztai** [ascott18/TellMeWhen#2166]
### WoW Version

Wrath Classic

### TellMeWhen Version

10.2.6

### Describe the bug

Hi,
it actually happened in classic Cataclysm - but couldnt select that in the dropdown.

There are 3 matches for Daybreak (holy paladin talent), but all 3 are detailing the talent itself, but not the buff. so when the buff is triggered, the icon is not showing up.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
There's definitely nothing missing. Sometimes, a spell's tooltip and the buff granted by that spell are very different. This is normal. You can see this clearly on Wowhead - https://www.wowhead.com/cata/spell=88819/daybreak

In any case, if you're just wanting to track the ability by name, then just type in the name. There's no "magic" in picking the "correct" suggestion from the suggestion list. Its just a list of suggestions, and what you actually type in is exactly what you get. Just type in "Daybreak" and be done with it. There's no benefit in this scenario to tracking the effect by spellID.
