### ISSUE TITLE
TMW will not load with latest Classic Era update

### ISSUE THREAD

**Issue by kirbuslee** [ascott18/TellMeWhen#2167]
### WoW Version

Classic or SoD

### TellMeWhen Version

10.2.6

### Describe the bug

20x TellMeWhen/Components/Core/Utils.lua:1520: attempt to compare number with string
[string "@TellMeWhen/Components/Core/Utils.lua"]:1520: in function `GetCurrentSpecialization'
[string "@TellMeWhen/Components/Core/Utils.lua"]:1531: in function <TellMeWhen/Components/Core/Utils.lua:1529>
[string "@TellMeWhen/Components/Core/Group.lua"]:352: in function `ShouldUpdateIcons'
[string "@TellMeWhen/Components/Core/Group.lua"]:393: in function `Setup_Conditions'
[string "@TellMeWhen/Components/Core/Group.lua"]:477: in function <TellMeWhen/Components/Core/Group.lua:425>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@TellMeWhen/TellMeWhen.lua"]:2729: in function `UpdateNormally'
[string "@TellMeWhen/TellMeWhen.lua"]:2878: in function `Update'
[string "@TellMeWhen/TellMeWhen.lua"]:3020: in function `LockToggle'
[string "@TellMeWhen/TellMeWhen.lua"]:3138: in function `?'
[string "@AngryEra/libs/AceConsole-3.0-7/AceConsole-3.0.lua"]:90: in function `?'
[string "@Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:5016: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:4674: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:4710: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:120_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:120_OnEnterPressed"]:1>

Locals:
_ = "Warrior"
pclass = "WARRIOR"
specIDs = <table> {
 1 = 71
 2 = 72
 3 = 73
}
biggest = 0
spec = nil
(for index) = 1
(for limit) = 3
(for step) = 1
i = 1
_ = 161
points = ""
(*temporary) = 161
(*temporary) = "Arms"
(*temporary) = ""
(*temporary) = "Arms"
(*temporary) = ""
(*temporary) = "attempt to compare number with string"
classSpecIds = <table> {
 HUNTER = <table> {
 }
 WARRIOR = <table> {
 }
 PALADIN = <table> {
 }
 MAGE = <table> {
 }
 PRIEST = <table> {
 }
 WARLOCK = <table> {
 }
 DEATHKNIGHT = <table> {
 }
 DRUID = <table> {
 }
 SHAMAN = <table> {
 }
 ROGUE = <table> {
 }
}
TMW = TMW {
 0 = <userdata>
 SlashCommand = <function> defined @TellMeWhen/TellMeWhen.lua:3024
 modules = <table> {
 }
 CancelTimer = <function> defined @AngryEra/libs/AceTimer-3.0/AceTimer-3.0.lua:147
 DeserializeData = <function> defined @TellMeWhen/Options/TellMeWhen_Options.lua:3907
 InNLengthTable = <function> defined @TellMeWhen/Components/Core/Utils.lua:1060
 InIconSettings = <function> defined @TellMeWhen/TellMeWhen.lua:927
 TryGetNPCName = <function> defined @TellMeWhen/Components/Core/Utils.lua:1631
 DS = <table> {
 }
 ScheduleTimer = <function> defined @AngryEra/libs/AceTimer-3.0/AceTimer-3.0.lua:94
 ConvertContainerToScrollFrame = <function> defined @TellMeWhen/Options/TellMeWhen_Options.lua:118
 GameTooltip_SetDogTag = <function> defined @TellMeWhen/Components/Core/Common/DogTags/config.lua:403
 toSeconds = <function> defined @TellMeWhen/Components/Core/Utils.lua:476
 QueueValidityCheck = <function> defined @TellMeWhen/TellMeWhen.lua:3385
 db = <table> {
 }
 GetDataOwner = <function> defined @TellMeWhen/TellMeWhen.lua:1330
 SetEnabledState = <function> defined @AngryEra/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 CopyWithMetatable = <function> defined @TellMeWhen/Components/Core/Utils.lua:924
 InGroups = <function> defined @TellMeWhen/TellMeWhen.lua:1003
 tDeleteItem = <function> defined @TellMeWhen/Components/Core/Utils.lua:827
 RegisterLuaImportDetector = <function> defined @TellMeWhen/Components/Core/Utils.lua:1667
 operators = <table> {
 }
 GetCurrentSpecialization = <function> defined @TellMeWhen/Components/Core/Utils.lua:1506
 tRemoveDuplicates = <function> defined @TellMeWhen/Components/Core/Utils.lua:845
 StringToCachedRGBATable = <function> defined @TellMeWhen/Components/Core/Utils.lua:364
 NewModule = <function> defined @AngryEra/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 print = <function> defined @TellMeWhen/TellMeWhen.lua:486
 COMMON = <table> {
 }
 TEXT = <table> {
 }
 binaryInsert = <function> defined @TellMeWhen/Components/Core/Utils.lua:890
 Deserialize = <function> defined @AngryEra/libs/AceSerializer-3.0/AceSerializer-3.0.lua:246
 ChangeCounter = <function> defined @TellMeWhen/Components/EventHandlers/Counter/Counter.lua:45
 EquivFullIDLookup = <table> {
 }
 GetName = <function> defined @AngryEra/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 InitializedDatabase = true
 oneUpString = <function> defined @TellMeWhen/Components/Core/Utils.lua:1291
 name = "TellMeWhen"
 GetSettingsStrings = <function> defined @TellMeWhen/Options/TellMeWhen_Options.lua:3943
 RestoreCase = <function> defined @TellMeWhen/Components/Core/Spells/Spells.lua:493
 Defaults = <table> {
 }
 C = <table> {
 }
 Warn = <function> defined @TellMeWhen/Components/Core/Utils.lua:422
 Print = <function> defined @AngryEra/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 BackupDate = "11:56:14 AM"
 SNIPPETS = <table> {
 }
 UpdateGlobals = <function> defined @TellMeWhen/TellMeWhen.lua:2564
 OrderedTypes = <table> {
 }
 safecall = <functio

### Export Strings

```text
N/A
```

**Comment by Dmeister406** [comment]
Seeing the same.

**Comment by ascott18** [comment]
This was fixed some time ago. ca7eae6fbd68694566d31b2a5d367c7243a2c18c
