### ISSUE TITLE
When TMW enable, addon Gladdy doesnt work. 

### ISSUE THREAD

**Issue by Geryqt** [ascott18/TellMeWhen#2169]
### WoW Version

Cata Classic

### TellMeWhen Version

10. 2. 7

### Describe the bug

From 7/12/2024 when updated TellMeWhen and started play some arenas, my addon Gladdy stop working. When i enable all addons except TellMeWhen, everything works. 

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
That sounds like a Gladdy problem if that's the addon that isn't working. 

Are you seeing any Lua errors? Make sure Lua errors are enabled - [BugGrabber ](https://www.curseforge.com/wow/addons/bug-grabber) and [BugSack](https://www.curseforge.com/wow/addons/bugsack) are a great, non-intrusive way to capture addon errors.

**Comment by SyuSyuGG** [comment]
i have same problem rn, TellMeWhen-10.2.6-11-g7ef844f.zip version is latest version doesnt crash with gladdy.

from 10.2.6-13~ are crash with gladdy addon.

**Comment by ascott18** [comment]
https://github.com/ascott18/TellMeWhen/issues/2171#issuecomment-2226509644
