### ISSUE TITLE
Can't drag and drop spells onto new tell me when bars

### ISSUE THREAD

**Issue by raja-kondaveeti1** [ascott18/TellMeWhen#2172]
### WoW Version

Retail

### TellMeWhen Version

10.27

### Describe the bug

I am unable to drag and drop most of the spells onto tell me when bars. this issue started since last 3-4 days. Very few spells are working - for example i can drag and drop Mage - fire blast spell but rest of mage spells are not working

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Already fixed in 0df8ab0f3878755a173ea74add297079ef26d29a
