### ISSUE TITLE
Crash On Beta Key Start

### ISSUE THREAD

**Issue by Nakor101** [ascott18/TellMeWhen#2173]
### WoW Version

Retail

### TellMeWhen Version

v10.2.8 r4 (g6c0a3de)

### Describe the bug

On Beta when a m+ key is put in and activated, the load screen appears, finishes, and as soon as you load in the game crashes (crash error shown in picture).

This does not happen when I start a key solo, only when a key is started and I am in a group.

I have repeated this 5-10 times with TMW enabled and 5-10 times using WA instead. As soon as TMW is disabled the crashing stops.

Other addons used on beta are the latest alpha versions of plater, grid2, and details.

If you would like me to take any further steps I would be happy to do so, so please let me know.

Thanks
![TMW crash beta](https://github.com/user-attachments/assets/e8a9041c-7fa3-4b8c-8cc0-356a939009fb)

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
These kinds of errors are always Blizzard's problem (or faulty hardware).

If you'd like post the full error info `.txt` file (NOT the `.dmp` file) from here, I can see if there might be something specific in TMW that I can disable as a temporary workaround until blizzard fixes it.
![image](https://github.com/user-attachments/assets/368cb10b-402b-4039-94fc-55c814adc94a)
