### ISSUE TITLE
Spell dragging onto TMW not working

### ISSUE THREAD

**Issue by Alwies** [ascott18/TellMeWhen#2178]
### WoW Version

Retail

### TellMeWhen Version

11.0.1

### Describe the bug

Title basically says it all. 
User in discord mentioned this. 

Accompanying error: `29x bad argument #1 to '?' (Usage: local name = C_Spell.GetSpellName(spellIdentifier))
[string "=[C]"]: ?
[string "@TellMeWhen/Components/IconTypes/IconType_default/default.lua"]:75: in function `DragReceived'
[string "@TellMeWhen/Options/IconConfig.lua"]:446: in function `SpellItemToIcon'
[string "@TellMeWhen/Components/IconModules/IconModule_RecieveSpellDrags/module.lua"]:31: in function <.../IconModules/IconModule_RecieveSpellDrags/module.lua:29>
[string "@TellMeWhen/Components/Core/BaseClasses/ObjectModule.lua"]:42: in function <...lMeWhen/Components/Core/BaseClasses/ObjectModule.lua:39>
[string "=[C]"]: ?

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local name = C_Spell.GetSpellName(spellIdentifier))"
`

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
9c413abbb56348fc6ccb6c42009504ec77df88e2
