### ISSUE TITLE
Can't spy on buffs

### ISSUE THREAD

**Issue by isaaxwind** [ascott18/TellMeWhen#2180]
### WoW Version

Cata Classic

### TellMeWhen Version

11.0.1

### Describe the bug

![QQ_1721893278245](https://github.com/user-attachments/assets/855a8899-b9ca-4a0a-9749-60a1dbc56e56)
WLK 3.4.3
no 增益/减益 (Buffs/Debuffs) option now

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
You'll need to downgrade to TMW 10.2.6 for use on the Chinese WOTLK client
