### ISSUE TITLE
Void Bolt cooldown during Voidform doesn't shown right

### ISSUE THREAD

**Issue by infzp** [ascott18/TellMeWhen#2183]
### WoW Version

Retail

### TellMeWhen Version

11.0.1

### Describe the bug

On Shadow priest Void Bolt cooldown during Voidform shown incorrectly. Void Bolt icon just always shown even when spell on cd. Before new patch was fine.

### Export Strings

```text
N/A
```

**Comment by Alwies** [comment]
For reference in case not familiar with SP. 
The spell void eruption (long CD) Changes into Void bolt (short CD) after use.

Currently in TMW v11.0.2 R5 (alpha) after using void eruption the icon changes to the void bolt icon but still tracks the CD of void eruption. 

Tracking void bolt specifically on a separate icon shows the icon as always ready. This is not the case on TMW 10.2.7 where it tracks the void bolt CD correctly.
As a note the behavior of the void eruption icon is the same on 10.2.7.

Believe the preferred behavior of the icon is to replicate what the spell does on actionbars (track void eruption unless that spell is active than track void bolt). It may have done so by default previously but this I'm not sure about.

**Comment by ascott18** [comment]
Dear Blizzard,

Please stop breaking everything. I'm so tired,
