### ISSUE TITLE
[Aether Attunement] mage's buff tracking bug

### ISSUE THREAD

**Issue by furryfurryfurry** [ascott18/TellMeWhen#2188]
### WoW Version

Retail

### TellMeWhen Version

11.0.3

### Describe the bug

[Aether Attunement] takes 3 buildups to gain [Aether Attunement] buff. however, when TMW tracks the [Aether Attunement] buff, it also tracks the build-up charges. The buff should be monitoring when do I have the actual buff ready to use. the buildup charge will constantly be on the screen 100% of the game time. we should have the buildup charge tracking removed. not to mention the buildup charge and the actual buff share the same tracking slot.

### Export Strings

```text
N/a
```

**Comment by furryfurryfurry** [comment]
[Aether Attunement] is an arcane mage proc

**Comment by Alwies** [comment]
This is not a bug. 
Just a limitation on tracking with name. When buffs/spells share a name but you want a specific one, you've to use spellID instead. 
In your case I believe "453601" is the actual proc and "458388" is the one that stacks.

**Comment by furryfurryfurry** [comment]
wow. problem solved. thank you so much Mister
