### ISSUE TITLE
Echoes of Great Sundering not tracking

### ISSUE THREAD

**Issue by funnelspec** [ascott18/TellMeWhen#2189]
### WoW Version

Retail

### TellMeWhen Version

11.0.4

### Describe the bug

Echoes of great sundering does not track when enabled

### Export Strings

```text
^1^T^SShowTimer^B ^SOnlyMine^B ^SType^Sbuff ^SShowTimerText^B ^SName^SEchoes~`of~`Great~`Sundering ^SEvents^T ^N1^T ^SPassingCndt^B ^SType^SSound ^SValue^N15 ^SSound^STMW~`-~`Ding~`9 ^SEvent^SOnStackIncrease ^SOperator^S> ^t^Sn^N1 ^t^SStates^T ^N1^T ^SAlpha^N0 ^t^t^SEnabled^B ^SHideIfNoUnits^B ^t^N110401^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
You configured your icon to be hidden under all circumstances. 
![image](https://github.com/user-attachments/assets/6eee1d58-14e0-45d2-942f-f823dc2d1203)
