### ISSUE TITLE
Aspect of harmony tracking (beta TWW)

### ISSUE THREAD

**Issue by GuinsooDild0** [ascott18/TellMeWhen#2190]
### WoW Version

Retail

### TellMeWhen Version

11.0.4

### Describe the bug

Not able to track the number store in Aspect of Harmony for MistWeaver in the TWW BETA 
![Capture](https://github.com/user-attachments/assets/a63d758e-a6ac-4e5f-bfe8-3575a2b2884c)

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Please do not ignore the issue template that is provided when you create a new issue. The questions and sections within it provide me with essential information to be able to diagnose and resolve your issue. If you do not include this information, there is little I can do to help you.

Please post the export string(s) of the icons, groups, or profiles you're having trouble with. 

To get an export string, open the icon editor, and click the button labeled "Import/Export/Backup". Select the "To String" option for the appropriate export type (icon, group, or profile), and then press CTRL+C to copy it to your clipboard.

Additionally, if applicable, add screenshots to help explain your problem. You can paste images directly into GitHub issues, or you can upload files as well.

**Comment by Alwies** [comment]
Suggested he post here on disc, but did do some testing myself as well so can elaborate for him. 
WoW version is beta 
TMW is 11.0.4

Aspect of harmony is one of those buffs with a stored value. 
The issue is that changing the aura variable settings in the icon menu never adds any value other than 0 into [stacks].

Confirmed with other addons that this is indeed a tooltip value that can be read.
Also in TMW the condition `Buff - Tooltip Number #1` reads a value higher than 0. 

"Aspect of Harmony" is a new hero talent, 1st option in the master of harmony tree. 
Tested on MW myself just send a few self heals to apply the buff. 

My test group

> ^1^T^SGUID^STMW:group:1cgLS1JWG2On ^SRows^N3 ^SPoint^T ^Sy^F-6755374744993792 ^f-46^Sx ^F7599837256089600^f-46 ^t^SIcons^T ^N1^T ^SShowTimer^B ^SType^Sconditionicon ^SShowTTText^B ^SShowTimerText^B ^SName^SAspect~`of~`Harmony ^SConditions^T ^N1^T ^SType^SBUFFTOOLTIP ^SChecked^B ^SOperator^S> ^SName^SAspect~`of~`Harmony ^t^Sn^N1 ^t^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SCondi~`>~`aura~`variable ^N2^S[Stacks] ^t^t^t^SEnabled^B ^t^N2^T ^SShowTimer^B ^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SBUFFTOOLTIPSCAN1 ^SChecked^B ^SOperator^S> ^SName^SAspect~`of~`Harmony ^t^Sn^N1 ^t^SShowTTText^B ^SName^SAspect~`of~`Harmony ^SShowTimerText^B ^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SCondi~`>~`tooltip~`1 ^N2^S[Stacks] ^t^t^t^t^N3^T ^SShowTimer^B ^SType^Sconditionicon ^SShowTTText^B ^SShowTimerText^B ^SName^SAspect~`of~`Harmony ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SCondi~`>~`tooltip~`2 ^N2^S[Stacks] ^t^t^t^SEnabled^B ^SConditions^T ^N1^T ^SType^SBUFFTOOLTIPSCAN2 ^SChecked^B ^SOperator^S> ^SName^SAspect~`of~`Harmony ^t^Sn^N1 ^t^t^N4^T ^SShowTimer^B ^SType^Sconditionicon ^SShowTTText^B ^SName^SAspect~`of~`Harmony ^SShowTimerText^B ^SConditions^T ^N1^T ^SType^SBUFFTOOLTIPSCAN3 ^SChecked^B ^SOperator^S> ^SName^SAspect~`of~`Harmony ^t^Sn^N1 ^t^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SCondi~`>~`tooltip~`3 ^N2^S[Stacks] ^t^t^t^t^N5^T ^SShowTimer^B ^SType^Sbuff ^SShowTTText^B ^SShowTimerText^B ^SName^S450521 ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SSpellID~`first~`non~`zero ^N2^S[Stacks] ^t^t^t^SEnabled^B ^t^N6^T ^SShowTimer^B ^SType^Sbuff ^SShowTTText^N1 ^SShowTimerText^B ^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SSpellID~`tool1 ^N2^S[Stacks] ^t^t^t^SName^S450521 ^t^N7^T ^SShowTimer^B ^SType^Sbuff ^SShowTTText^N2 ^SShowTimerText^B ^SName^S450521 ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SSpellID~`tool2 ^N2^S[Stacks] ^t^t^t^SEnabled^B ^t^N8^T ^SShowTimer^B ^SType^Sbuff ^SShowTTText^N3 ^SName^S450521 ^SShowTimerText^B ^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SSpellID~`tool3 ^N2^S[Stacks] ^t^t^t^t^N9^T ^SShowTimer^B ^SType^Sbuff ^SShowTTText^B ^SShowTimerText^B ^SName^SAspect~`of~`Harmony ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SName~`first~`non~`zero ^N2^S[Stacks] ^t^t^t^SEnabled^B ^t^N10^T ^SShowTimer^B ^SType^Sbuff ^SShowTTText^N1 ^SShowTimerText^B ^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SName~`tool1 ^N2^S[Stacks] ^t^t^t^SName^SAspect~`of~`Harmony ^t^N11^T ^SShowTimer^B ^SType^Sbuff ^SShowTTText^N2 ^SShowTimerText^B ^SName^SAspect~`of~`Harmony ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SName~`tool1 ^N2^S[Stacks] ^t^t^t^SEnabled^B ^t^N12^T ^SShowTimer^B ^SType^Sbuff ^SShowTTText^N3 ^SName^SAspect~`of~`Harmony ^SShowTimerText^B ^SEnabled^B ^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^SName~`tool3 ^N2^S[Stacks] ^t^t^t^t^t^t^N110401^S~`~| ^Sgroup^N1 ^^

**Comment by Alwies** [comment]
Not sure if related but got this error on Beta just now (on MW with the test group still active).

1x TellMeWhen/TellMeWhen.lua:2715: ...mponents/Core/Conditions/Categories/BuffsDebuffs.lua:319: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@TellMeWhen/TellMeWhen.lua"]:2715: in function <TellMeWhen/TellMeWhen.lua:2704>

Locals:
(*temporary) = false
(*temporary) = "...mponents/Core/Conditions/Categories/BuffsDebuffs.lua:319: attempt to index field '?' (a nil value)"

**Comment by ascott18** [comment]
Added options to pull the number from the tooltip
