### ISSUE TITLE
Notification counter not working correctly

### ISSUE THREAD

**Issue by Betaskill** [ascott18/TellMeWhen#2191]
### WoW Version

Retail

### TellMeWhen Version

11.0.4

### Describe the bug

Hello, 

I am currently experiencing the problem that the notification counter does not count/work properly if an "Icon is Shown" check is made for an "on" or "while" condition settings. 

If an icon, in my case icon 2 called "control" is enabled or disabled either via the button in the main menu or a lua script, then the set counter is not adjusted. If "control" is enabled(so shown) = counter set to 1, if disabled (so hidden) = counter set to 0.

Somehow the notification can no longer work with Icon is Shown, although the condition can handle it. 

### Export Strings

```text
^1^T^SType^Sconditionicon ^SConditions^T ^N1^T ^SType^SCOUNTER ^SName^Sshow ^t^Sn^N1 ^t^SEvents^T ^N1^T ^SType^SCounter ^SCounter^Sshow ^SCounterAmt^N0 ^SCounterOperation^S= ^SEvent^SOnCondition ^SOnConditionConditions^T ^N1^T ^SType^SICON ^SLevel^N1 ^SName^Stj ^SIcon^STMW:icon:1cjhTpI2wOKH ^t^Sn^N1 ^t^SFrequency^N0.5 ^t^Sn^N1 ^t^SSettingsPerView^T ^Sicon^T ^STexts^T ^N1^Scat ^N2^S0 ^t^t^t^SEnabled^B ^t^N110401^S~`~| ^Sicon^^
```

**Comment by Alwies** [comment]
Enabling/disabling icons is probably not an envisioned use case for the icon is shown condition. 
However that's for Cybeloras.

Just came here to suggest that if a condition icon can detect it you can just set the counter based on that condition icon. 
So:
Icon 1: the icon you enable/disable
Icon 2: a, (always hide) Condition icon checking if icon 1 is shown (as you said the condition works fine)
Icon 3: An icon to change your counter based on icon 2
Disabling icon 1 will hide icon 2 triggering icon 3. 

If you need help exploring this idea please use the TMW discord instead so we don't spam pings here.

As I said the notification event condition with icon is shown not detecting the enabling/disabling of an icon is for Cybeloras to decide.
