### ISSUE TITLE
NumAura DogTag broken in 11.0.2

### ISSUE THREAD

**Issue by Effeh** [ascott18/TellMeWhen#2194]
### WoW Version

Retail

### TellMeWhen Version

11.0.4

### Describe the bug

I guess this might be a https://github.com/parnic/LibDogTag-3.0/ thing so I possibly shouldn't raise it here? It generates hundreds of errors and doesn't display the aura count anymore

![image](https://github.com/user-attachments/assets/868ef67b-79e1-4ff3-9ead-5fec5c9c5d5e)

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
https://github.com/parnic/LibDogTag-Unit-3.0/ would be the place to report this

**Comment by Effeh** [comment]
parnic updated the lib
