### ISSUE TITLE
Fusion of Elements

### ISSUE THREAD

**Issue by tlw3908** [ascott18/TellMeWhen#2196]
**Is your feature request related to a problem? Please describe.**
The problem is that "Fusion of Elements" is a passive for elemental shamans that does now show when it is procced, unlike other passives for elemental shamans like "Power of the Maelstrom" or "Master of the Elements."
**Describe the solution you'd like**
I would like to have a combat display tell me I have one "stack" AFTER pressing Icefury (which grants the Fusion of Elements passive proc). THEN I would like to have Flame Shock, Elemental Blast, or Primordial Wave set the stack back to zero and/or make the TellMeWhen icon to disappear (so I know that an Elemental Blast has been casted at 60% effectiveness; thus consuming the proc.)
**Describe alternatives you've considered**
I have considered putting "Fusion of Elements" as a buff and track it that way, but the buff does not show in the top right buffs panel after casting an Icefury. The passive proc does not show up in the TellMeWhen spell book either. I have tested it this way; I have not found that this way works like the other passives with elemental shamans.
**Additional context**
I understand that the passive proc "Fusion of Elements" is activated AFTER casting an Icefury, and it is procced after casting both a fire and a nature spell in ONE cast - Flame shock is Volcanic Damage - Volcanic Spell Damage is BOTH fire and nature damage, while Primordial Wave and Elemental Blast is Elemental Damage - Elemental Spell Damage is ALL three of fire, nature, and frost damage (which procs an additional Elemental Blast cast at 60% effectiveness.)

**Comment by ascott18** [comment]
You'll have to petition Blizzard to make this an actual buff. I won't be adding some special handling for this one specific class mechanic that is poorly exposed by Blizzard. Sorry.
