### ISSUE TITLE
LUA ERROR

### ISSUE THREAD

**Issue by jmarts123** [ascott18/TellMeWhen#2197]
### WoW Version

Cata Classic

### TellMeWhen Version

11.0.4

### Describe the bug

Message: ...akAuras/Libs/LibSpellRange-1.0/LibSpellRange-1.0.lua:273: IsSpellInRange(): Invalid spell slot
Time: Sat Aug 17 06:56:32 2024
Count: 85
Stack: ...akAuras/Libs/LibSpellRange-1.0/LibSpellRange-1.0.lua:273: IsSpellInRange(): Invalid spell slot
[string "=[C]"]: ?
[string "@Interface/AddOns/WeakAuras/Libs/LibSpellRange-1.0/LibSpellRange-1.0.lua"]:273: in function <...akAuras/Libs/LibSpellRange-1.0/LibSpellRange-1.0.lua:249>
[string "@Interface/AddOns/TellMeWhen/Components/IconTypes/IconType_cooldown/cooldown.lua"]:214: in function `UpdateFunction'
[string "@Interface/AddOns/TellMeWhen/Components/Core/Icon.lua"]:784: in function `Update'
[string "@Interface/AddOns/TellMeWhen/Components/IconTypes/IconType_meta/meta.lua"]:235: in function `UpdateFunction'
[string "@Interface/AddOns/TellMeWhen/Components/Core/Icon.lua"]:784: in function <Interface/AddOns/TellMeWhen/Components/Core/Icon.lua:741>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2675: in function <Interface/AddOns/TellMeWhen/TellMeWhen.lua:2637>

Locals: (*temporary) = nil
(*temporary) = "target"
------------------------------------
Message: TellMeWhen: ...akAuras/Libs/LibSpellRange-1.0/LibSpellRange-1.0.lua:273: IsSpellInRange(): Invalid spell slot
Time: Sat Aug 17 06:56:06 2024
Count: 1
Stack: TellMeWhen: ...akAuras/Libs/LibSpellRange-1.0/LibSpellRange-1.0.lua:273: IsSpellInRange(): Invalid spell slot
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2855: in function <Interface/AddOns/TellMeWhen/TellMeWhen.lua:2812>

Locals: self = TMW {
 0 = <userdata>
 SlashCommand = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:3058
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/WeakAuras/Libs/AceTimer-3.0/AceTimer-3.0.lua:147
 DeserializeData = <function> defined @Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.lua:3906
 InNLengthTable = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:1063
 InIconSettings = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:961
 TryGetNPCName = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:1681
 DS = <table> {
 }
 ScheduleTimer = <function> defined @Interface/AddOns/WeakAuras/Libs/AceTimer-3.0/AceTimer-3.0.lua:94
 ConvertContainerToScrollFrame = <function> defined @Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.lua:116
 GameTooltip_SetDogTag = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Common/DogTags/config.lua:403
 toSeconds = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:479
 QueueValidityCheck = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:3419
 db = <table> {
 }
 GetDataOwner = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:1364
 SetEnabledState = <function> defined @Interface/AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 CopyWithMetatable = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:927
 ALLOW_LOCKDOWN_CONFIG = true
 InGroups = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:1037
 GetSpellCooldown = <function> defined =[C]:-1
 tDeleteItem = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:830
 RegisterLuaImportDetector = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:1717
 operators = <table> {
 }
 GetCurrentSpecialization = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:1554
 tRemoveDuplicates = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:848
 StringToCachedRGBATable = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:367
 NewModule = <function> defined @Interface/AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 print = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:520
 COMMON = <table> {
 }
 TEXT = <table> {
 }
 binaryInsert = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:893
 Deserialize = <function> defined @Interface/AddOns/WeakAuras/Libs/AceSerializer-3.0/AceSerializer-3.0.lua:246
 ChangeCounter = <function> defined @Interface/AddOns/TellMeWhen/Components/EventHandlers/Counter/Counter.lua:45
 EquivFullIDLookup = <table> {
 }
 GetName = <function> defined @Interface/AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 InitializedDatabase = true
 oneUpString = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:1294
 name = "TellMeWhen"
 GetSettingsStrings = <function> defined @Interface/AddOns/TellMeWhen/Options/TellMeWhen_Options.lua:3942
 RestoreCase = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Spells/Spells.lua:455
 Defaults = <table> {
 }
 C = <table> {
 }
 Warn = <function> defined @Interface/AddOns/TellMeWhen/Components/Core/Utils.lua:425
 Print = <function> defined @Interface/AddOns/Bartender4/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 BackupDate = "06:56:06 AM"
 SNIPPETS = <table> {
 }
 UpdateGlobals = <function> defined @Interface/AddOns/TellMeWhen/TellMeWhen.lua:2598
 OrderedTypes = <table> {
 }
 safecall = <funct

---------------------------------------------
Message: Interface/AddOns/TellMeWhen/TellMeWhen.lua:2715: ...akAuras/Libs/LibSpellRange-1.0/LibSpellRange-1.0.lua:273: IsSpellInRange(): Invalid spell slot
Time: Sat Aug 17 06:56:06 2024
Count: 1
Stack: Interface/AddOns/TellMeWhen/TellMeWhen.lua:2715: ...akAuras/Libs/LibSpellRange-1.0/LibSpellRange-1.0.lua:273: IsSpellInRange(): Invalid spell slot
[string "=[C]"]: ?
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2715: in function <Interface/AddOns/TellMeWhen/TellMeWhen.lua:2704>

Locals: (*temporary) = false
(*temporary) = "...akAuras/Libs/LibSpellRange-1.0/LibSpellRange-1.0.lua:273: IsSpellInRange(): Invalid spell slot"

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Fixed in 71292cc21190145eef1d3e560f939ae73ccfb476
