### ISSUE TITLE
Error in UpdateActionSlots

### ISSUE THREAD

**Issue by canofbutter** [ascott18/TellMeWhen#2198]
### WoW Version

Retail

### TellMeWhen Version

11.0.5 r6 (g5ec41a8)

### Describe the bug

A LUA error occurs on load and when changing the action bars.  

```
Message: bad argument #1 to '?' (Usage: local name = C_Spell.GetSpellName(spellIdentifier))
Time: Sun Aug 18 16:18:51 2024
Count: 1
Stack: bad argument #1 to '?' (Usage: local name = C_Spell.GetSpellName(spellIdentifier))
[string "=[C]"]: ?
[string "@Interface/AddOns/TellMeWhen/Components/Core/Common/Actions.lua"]:67: in function <...AddOns/TellMeWhen/Components/Core/Common/Actions.lua:49>
[string "@Interface/AddOns/TellMeWhen/Components/Core/Common/Actions.lua"]:99: in function <...AddOns/TellMeWhen/Components/Core/Common/Actions.lua:97>
[string "=[C]"]: in function `PickupAction'
[string "@Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua"]:1449: in function <.../AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:1445>

Locals: (*temporary) = "bad argument #1 to '?' (Usage: local name = C_Spell.GetSpellName(spellIdentifier))"

```

This was a weird one:  It seems to be getting stuck on a spell that I have on action slot 79, with ID 152173 (this is Serenity's old ID, a spell now removed from the game), but slot 79 is a stance bar, which I can't access as a monk anymore (stances removed in 7.0, so it's from long before the spell was removed and I can't fix it easily).

"baseId" from the FindBaseSpellByID in UpdateActionSlots in Components/Core/Common/Actions.lua:64 returns nil for this spell even though the actionType is still "spell" and the id itself is not nil.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
How odd. Fixed!
