### ISSUE TITLE
Unable to track Thunderstrike Ward shield imbue

### ISSUE THREAD

**Issue by SJPadbury** [ascott18/TellMeWhen#2200]
**Is your feature request related to a problem? Please describe.**
I'm attempting to track the Thunderstrike Ward shield imbue, and there isn't a category for that, nor does it appear under weapon imbues.

**Describe the solution you'd like**
Either add a shield imbue category, or add this and any other temporary enhancements to shield to weapon imbues

**Comment by ascott18** [comment]
Works just fine.

![image](https://github.com/user-attachments/assets/7575148a-38b3-4f72-8163-dc791a1eddbc)
