### ISSUE TITLE
Add condition for hero talents

### ISSUE THREAD

**Issue by furinkazanzibar** [ascott18/TellMeWhen#2203]
**Is your feature request related to a problem? Please describe.**
Currently "Points in Talent" = 1 is always true once the Hero talent nodes are unlocked. Regardless of which hero spec you are currently using. This makes any kind of conditions based on active hero tree unusable.

For example, I am trying to set a condition based on if I have Elemental Reverb in the Farseer tree and Echo of the Elements in the Elemental/Restoration tree so that I know if I have either a max of 2 or 3 charges of Lava Burst/Riptide. So if I am in Farseer spec, I should include Elemental Reverb, if not, then I technically do not have the talent active.

**Describe the solution you'd like**
Include new condition similar to Unit Specialization with your specs 2 hero talents as options.

**Describe alternatives you've considered**
Or set the "Points in Talent" filter to recognize the active hero talents = 1 and set all the other Hero tree talents = 0

**Additional context**

**Comment by furinkazanzibar** [comment]
Actually the behavior seems inconsistent. It looks like if I am elemental and switch to a different build with the specific hero talent, it works. But not for resto. And it seems to not work if you change hero talents within the same build. I am guessing that once you activate the other Hero talent, all those talents get flipped to 1, otherwise they are 0 until you choose it?

**Comment by ascott18** [comment]
This was already fixed bc385cb57d0cc739ebcd6c4cca907035c8ad2fb3
