### ISSUE TITLE
LibDogTag3.0 related bug

### ISSUE THREAD

**Issue by godfingerbtx** [ascott18/TellMeWhen#2204]
### WoW Version

Retail

### TellMeWhen Version

11.0.4

### Describe the bug

The error message will pop up when I mount or start move for certain distance and then will pop up non-stop with the local:start value keep increasing even if I disable all the active tmw groups. The error message is pasted below:

Message: ...rface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Events.lua:719: ...llMeWhen/Lib/LibDogTag-Unit-3.0/Categories/Auras.lua:119: attempt to call upvalue 'UnitAura' (a nil value)
Time: Mon Aug 26 00:13:18 2024
Count: 2
Stack: ...rface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Events.lua:719: ...llMeWhen/Lib/LibDogTag-Unit-3.0/Categories/Auras.lua:119: attempt to call upvalue 'UnitAura' (a nil value)
[string "@Interface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Events.lua"]:719: in function <...rface/AddOns/TellMeWhen/Lib/LibDogTag-3.0/Events.lua:710>

Locals: start = 316501536.286900
Coroutine = <no value>

### Export Strings

```text
This is not related to a specific icon or group.
```

**Comment by ascott18** [comment]
Already fixed 7cf02c9037fa9b42d6aaeeac3c66d81be12f9511
