### ISSUE TITLE
Update credit for original author

### ISSUE THREAD

**Issue by NephMakes** [ascott18/TellMeWhen#2206]
Heya! I noticed you still have an email for me listed in the file headers. I was wondering if instead you could just credit me as "Originally by NephMakes". You should be able to see that's how I'm listed on Curse. And that I've been maintaining NeedToKnow (TellMeWhen's parent addon).

**Comment by ascott18** [comment]
Done!

**Comment by NephMakes** [comment]
Awesome, thanks! \m/
