### ISSUE TITLE
Spells where using the spell turns it into another spell (e.g. "Sacred Weapon" turning into "Holy Bulwark") are not tracked correctly

### ISSUE THREAD

**Issue by RealHawkBat** [ascott18/TellMeWhen#2207]
### WoW Version

Retail

### TellMeWhen Version

11.0.5

### Describe the bug

**Background:**
As a Prot Paladin, when "Holy Armaments" is talented, when the spell "Sacred Weapon" is used, it is replaced by the spell "Holy Bulwark". When "Holy Bulwark" is used, it becomes the "Sacred Weapon" again etc.
While this example calls out specific spells, I believe this bug would be present for any spell where using it replaces the spell with another. 

**Steps to reproduce:**
1. Log in as a Prot Paladin with "Holy Armaments" talented
2. Create Icon A for Spell Cooldown that tracks "Sacred Weapon" (spellid: 432472)
3. Create Icon B for Spell Cooldown that tracks "Holy Bulwark" (spellid: 432459)
4. Ensure "Sacred Weapon" spell is off cooldown

**Expected Result**
1. Icon A IS visible, Icon B is NOT visible

**Actual Result**
1. Both Icon A AND Icon B are visible

Notes:
It appears that TellMeWhen tracks both spells as if they are the same.

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Working as intended.

**Comment by RealHawkBat** [comment]
Hi, as part of my rotation, different conditions need to be met to use one spell or the other. There is no way to manage this is TellMeWhen treats them as the same spell.
