### ISSUE TITLE
Sound notifications playing for ALL icons even ones that don't have a sound notification

### ISSUE THREAD

**Issue by eatticks** [ascott18/TellMeWhen#2210]
### WoW Version

Retail

### TellMeWhen Version

11.0.5

### Describe the bug

All of my sound notifications are playing for all of my icons instead of just the one sound picked for the icons that have sounds. This has never happened before this last patch. 

When I load the last release patch (11.0.4), it does not happen and everything works fine so it is something that was just changed since 11.0.4.  I tried to attach my profile but the site won't let me submit it - says file is too many characters.  I have some customsound files that I use (e.g., Interface/Customsounds/shotgun.mp3) so not sure if it could be related specifically to those? But they've always worked fine before.

My full profile is too big to send but I am sending one of the icons that is having its sound triggered for everything.  This uses a custom sounds file though so you would need to replace the sound with a working sound file or one of the defaults for it to actually make a sound.

### Export Strings

```
^1^T^SShowTimer^B ^SType^Scooldown ^SShowTimerText^B ^SName^SCapacitor~`Totem ^SGUID^STMW:icon:1Z8J75OueHOj ^SConditions^T ^N1^T ^SType^SPTSINTAL ^SLevel^N1 ^SName^SCapacitor~`Totem ^t^Sn^N1 ^t^SEvents^T ^N1^T ^SAnimColor^Sbfff0000 ^SType^SAnimations ^SThickness^N3 ^SOnlyShown^B ^SAnimation^SICONFLASH ^SEvent^SWCSP ^SOnConditionConditions^T ^N1^T ^SType^SICON ^SIcon^STMW:icon:1Z8p1IfwMpGi ^t^N2^T ^SType^SICON ^SAndOr^SOR ^SIcon^STMW:icon:1ZCiqm79lN8Z ^t^Sn^N2 ^t^t^N2^T ^SType^SAnimations ^SOnlyShown^B ^SAnimation^SACTVTNGLOW ^SEvent^SWCSP ^SOnConditionConditions^T ^N1^T ^SType^SSPELLCD ^SName^SCapacitor~`Totem ^t^Sn^N1 ^t^t^N3^T ^SType^SSound ^SSound^SInterface/Customsounds/shotgun.mp3 ^SEvent^SOnCondition ^SOnConditionConditions^T ^N1^T ^SType^SSPELLCD ^SOperator^S> ^SName^SCapacitor~`Totem ^t^Sn^N1 ^t^t^N4^T ^SAnimColor^Sbfff0000 ^SType^SSound ^SSound^SInterface/Customsounds/shotgun.mp3 ^SEvent^SOnCondition ^SOnConditionConditions^T ^N1^T ^SType^SSPELLCD ^SName^SCapacitor~`Totem ^t^Sn^N1 ^t^t^N5^T ^SType^SAnimations ^SOnlyShown^B ^SMagnitude^N2 ^SEvent^SWCSP ^SOnConditionConditions^T ^N1^T ^SType^SSPELLCD ^SName^SCapacitor~`Totem ^t^N2^T ^SType^SCOMBAT ^t^N3^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1Z8p1IfwMpGi ^t^N4^T ^SType^SICON ^SLevel^N1 ^SIcon^STMW:icon:1ZCiqm79lN8Z ^t^Sn^N4 ^t^t^Sn^N5 ^t^SStates^T ^N2^T ^SAlpha^N0.5 ^t^t^SEnabled^B ^t^N110401^S~`~| ^Sicon^^
```

**Comment by eatticks** [comment]
The linked resolution - 6743bd - seems to have been in regard to a GCD
issue.

My issue was with sound notifications playing inappropriately all the time.
Was the sound issue also addressed?  Thanks.

**Comment by ascott18** [comment]
Sounds are the symptom here, not the disease. The cause was that for a brief moment every time a GCD starts, cooldown checks that should have been ignoring the GCD were not ignoring the GCD.

FYI, your icons could be simpler if you trigger your sounds with the On Start / On Finish events on the cooldown icon instead of using condition triggers.

**Comment by eatticks** [comment]
Ok great!

Thanks for the explanation - and the tip!
