### ISSUE TITLE
Fire Breath CD no working AUG

### ISSUE THREAD

**Issue by Licketyspliit** [ascott18/TellMeWhen#2212]
### WoW Version

Retail

### TellMeWhen Version

11.0.5

### Describe the bug

creating a CD tracker for Fire Breath on Evoker 
Fire Breath Cooldown, works for Devo , but on switching to AUG does not,   the spell does not show its on CD and no Timer  

Work around for now is using the Spell ID itself

**DEVO talents**
CsbBWYnbRY1EREkP8a0IbB+ZHAAAAAAAAAAAAzMzgZGmBDYgxMTzYmJz2MbzwMjZMzyMgZMz2YmZZMDmBGDWglxoxyAyMBYD

**AUG talents**
CEcBWYnbRY1EREkP8a0IbB+ZHwMLjlZmZGLDmZWmBzYmNAAAAAwAAgZGYwYYqhZmBAAAAzMzsNmZWGzMwYbGYMbWYBGYGGaELYG

### Export Strings

```text
NA
```

**Comment by ascott18** [comment]
Getting really tired of Blizzard and their incorrect spell data. :(

![image](https://github.com/user-attachments/assets/b190fcc2-e44e-42f9-8908-ff151fdaf7f4)
