### ISSUE TITLE
Arms Warrior Spec LUA issue

### ISSUE THREAD

**Issue by JohnEH827** [ascott18/TellMeWhen#2213]
### WoW Version

Retail

### TellMeWhen Version

11.0.5

### Describe the bug

When Speced as Arms as Warrior, LUA issue "TellMeWhen/Components/Core/Common/Actions.lua:43: table index is nil"

Attached is the LUA from Bugsack
[Bugsack LUA.txt](https://github.com/user-attachments/files/16841235/Bugsack.LUA.txt)

### Export Strings

```text
N/A
```

**Comment by Alwies** [comment]
This looks a lot like #2208 
Try updating to the latest **Alpha version** I'd bet that fixes it.

Small chance I'm wrong and this is a (slightly) different issue. We've only seen this on monks before now.

**Comment by ascott18** [comment]
Definitely the same issue. The original monk issue mentioned it as an issue with the stance bar, so happening in Warrior would make sense too
