### ISSUE TITLE
Spell in range of unit defaults to range-to-player which is always zero

### ISSUE THREAD

**Issue by bionicles** [ascott18/TellMeWhen#2223]
### WoW Version

Retail

### TellMeWhen Version

11.0.4

### Describe the bug

When adding "Spell in range of unit" conditions, the default is range to player, which is always zero, so we always need to erase the word "player" and write "target" -- a minor annoyance repeated many times. 

Solution: "Spell in range of unit" can default to "target" because we only really care about range to target or perhaps targettarget in rare cases

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
Unable to reproduce.

https://github.com/user-attachments/assets/8eb070b3-fea3-44fc-9756-2db53cf19ccf
