### ISSUE TITLE
GLOBAL COOLDOWN SHOWING WHEN GROUP VISIBILITY IS TURNED OFF

### ISSUE THREAD

**Issue by IINogueiraII** [ascott18/TellMeWhen#2228]
### WoW Version

Retail

### TellMeWhen Version

11.0.9

### Describe the bug

GLOBAL COOLDOWN SHOWING WHEN GROUP VISIBILITY IS TURNED OFF. 

![GCD IS SHOWING](https://github.com/user-attachments/assets/e6c5f6f0-2148-48e7-9a2c-c57c91195b15)
![GROUP IS HIDDEN](https://github.com/user-attachments/assets/c3a87793-b8a7-4c60-b91c-e2323b16078c)

### Export Strings

```text
N/A
```

**Comment by ascott18** [comment]
THANK YOU FOR TYPING LOUDLY SO I CAN HEAR YOU CLEARLY.

I FORGOT TO ACCOUNT FOR GROUP OPACITY WHEN I ADJUSTED THIS BEHAVIOR RECENTLY FOR OTHER SITUATIONS. WILL GET THIS FIXED SOON.

**Comment by IINogueiraII** [comment]
Thank you
