### ISSUE TITLE
LUA code in conditions does not work on newer versions

### ISSUE THREAD

**Issue by Jokich7** [ascott18/TellMeWhen#2233]
### WoW Version

Retail

### TellMeWhen Version

11.0.2

### Describe the bug

LUA code in conditions on version does not work 
TMW-11.0.9 while in the old version TMW-11.0.5 everything works as it should.

local now = GetTime()
local math1 = 0
local math2 = 0
local startTime, duration, enabled = GetSpellCooldown(61304)
if startTime > 0 then
    math1 = now - startTime 
end
if duration > 0 then
    math2 = duration - math1
end

if math2 <= 0.3 then
    return true
end

In addition, some groups are disabled when the character enters the dungeon, on the old version all works fine.

Translated with www.DeepL.com/Translator (free version)

### Export Strings

```text
N/A
```

**Comment by Alwies** [comment]
That wouldn't work correctly on any TMW version. 
Blizzard removed `GetSpellCooldown` and replaced it with `C_Spell.GetSpellCooldown` , see: [https://warcraft.wiki.gg/wiki/API_C_Spell.GetSpellCooldown](https://warcraft.wiki.gg/wiki/API_C_Spell.GetSpellCooldown)
