### ISSUE TITLE
TMW Bug 

### ISSUE THREAD

**Issue by Jaska555** [ascott18/TellMeWhen#2234]
### WoW Version

Retail

### TellMeWhen Version

11.0.9

### Describe the bug

This is from BugGrabber, i have no clue what this means.

34416x TooltipID/Core.lua:45: attempt to call field 'SurfaceArgs' (a nil value)
[string "@TooltipID/Core.lua"]:45: in function <TooltipID/Core.lua:41>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `resume'
[string "@TellMeWhen/TellMeWhen.lua"]:2817: in function <TellMeWhen/TellMeWhen.lua:2778

### Export Strings

```text
-
```

**Comment by ascott18** [comment]
This is a problem with TooltipID, not TellMeWhen.
