### ISSUE TITLE
Sound notifications are ignoring Icon's Conditions

### ISSUE THREAD

**Issue by osy999** [ascott18/TellMeWhen#2236]
### WoW Version

Retail

### TellMeWhen Version

11.0.10

### Describe the bug

Im under the impression that an Icon have to be displayed in order to run its notifications
So for this icon, as long as Im not targetting anything, the notifications should not be played
But its playing Sound notification even the icon has failed its conditions(when Im not targetting anything)

### Export Strings

```text
^1^T^SType^Scooldown ^SConditions^T ^N1^T ^SType^SEXISTS ^SUnit^Starget ^t^Sn^N1 ^t^SName^SAgony ^SEvents^T ^N1^T ^SType^SSound ^SSound^STMW~`-~`Pling~`6 ^SEvent^SWCSP ^SOnConditionConditions^T ^N1^T ^SType^SHEALTH ^SOperator^S~|= ^t^Sn^N1 ^t^t^Sn^N1 ^t^SEnabled^B ^t^N11001001^S~`~| ^Sicon^^
```

**Comment by Alwies** [comment]
Check the "Only trigger if icon is shown" Checkbox: 
![tmwgit](https://github.com/user-attachments/assets/e7d93a45-e047-40b2-a9fa-03ab26d76127)
