### ISSUE TITLE
Warlock's Corruption is very buggy

### ISSUE THREAD

**Issue by osy999** [ascott18/TellMeWhen#2237]
### WoW Version

Retail

### TellMeWhen Version

11.0.10

### Describe the bug

I dont know how to describe it, its like giving false positive results but in a very inconsistent pattern
It can sometimes show the debuff is absent, and sometimes when its absent, its shown as its not absent

I have 2 notifications
Color Flash Red: Corruption on target is absent
Activation Border: Corruption on target is not absent

![image](https://github.com/user-attachments/assets/811fa766-13cf-4b63-9d52-80a6a1aa86a2)
^Target has Corruption debuff, but is running both notifications
Expectation: its supposed to trigger Activation Border notification only

![image](https://github.com/user-attachments/assets/c2602299-5097-4519-970d-a4131d678536)
^Target doesnt have Corruption debuff, but is not running any of the notifications
Expectation: its supposed to trigger Color Flash Red notification only

I guess it has something to do with Corruption and Wither's infinite duration timers

### Export Strings

```text
^1^T^SShowTimer^B ^SBuffOrDebuff^SHARMFUL ^SUnit^Starget ^SOnlyMine^B ^SType^Sbuff ^SName^SCorruption ^SShowTimerText^B ^SEvents^T ^N1^T ^SType^SAnimations ^SPeriod^N0 ^SAnimation^SICONFLASH ^SEvent^SWCSP ^SOnConditionConditions^T ^N1^T ^SType^SDEBUFFDUR ^SChecked^B ^SOperator^S~|= ^SUnit^Starget ^SName^SCorruption ^t^Sn^N1 ^t^t^N2^T ^SType^SAnimations ^SAnimation^SACTVTNGLOW ^SEvent^SWCSP ^SOnConditionConditions^T ^N1^T ^SType^SDEBUFFDUR ^SChecked^B ^SOperator^S~|= ^SUnit^Starget ^SName^SCorruption ^t^Sn^N1 ^t^t^Sn^N2 ^t^SSettingsPerView^T ^Sicon^T ^STexts^T ^N2^S ^t^t^t^SStates^T ^N2^T ^SAlpha^N1 ^t^t^SEnabled^B ^SConditions^T ^N1^T ^SType^SEXISTS ^SUnit^Starget ^t^Sn^N1 ^t^t^N11001001^S~`~| ^Sicon^^
```

**Comment by Alwies** [comment]
Your notification triggers are identical for both animations. At least on the export you send. 
Both are set to corruption ~= 0 (aka is present).

**Comment by osy999** [comment]
> Your notification triggers are identical for both animations. At least on the export you send. Both are set to corruption ~= 0 (aka is present).
My bad.. guess I have the wrong conditions since beginning
