### ISSUE TITLE
Multiple script ran too long errors

### ISSUE THREAD

**Issue by Betaskill** [ascott18/TellMeWhen#2238]
### WoW Version

Retail

### TellMeWhen Version

10.0.10

### Describe the bug

Hi,

I am standing in my WOD garrison and opening TMW with a /TMW ingame macro. If I am in the config mode and leaving for some minutes, I am getting different script ran to long-errors. 

**First one was this, even if the bar is completely empty:**
18x [string "safecall Dispatcher[1]"]:9: script ran too long
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@TellMeWhen/TellMeWhen.lua"]:2735: in function `UpdateNormally'
[string "@TellMeWhen/TellMeWhen.lua"]:2884: in function `Update'
[string "@TellMeWhen/TellMeWhen.lua"]:2892: in function `?'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
(*temporary) = true
(*temporary) = "script ran too long"
arg1 = TellMeWhen_Group31_Icon20 {
 group = TellMeWhen_Group31 {
 }
 ComponentsLookup = <table> {
 }
 Update_Method = "auto"
 EventHandlersSet = <table> {
 }
 attributes = <table> {
 }
 ID = 20
 Name = ""
 GUID = ""
 Enabled = false
 Type = ""
 NextUpdateTime = 0
 TempGUID = "TMW:icon:1ctQPCWuG4WR"
 typeData = <table> {
 }
 Modules = <table> {
 }
 position = <table> {
 }
 Components = <table> {
 }
 lmbButtonData = <table> {
 }
 Events = <table> {
 }
 SettingsPerView = <table> {
 }
 viewData = <table> {
 }
 Conditions = <table> {
 }
 UnitConditions = <table> {
 }
 States = <table> {
 }
}

**After I have deactivated the whole Group, I am receving multiple different ones like:**

1x TellMeWhen/Components/Core/Group.lua:341: script ran too long
[string "@TellMeWhen/Components/Core/Group.lua"]:341: in function <TellMeWhen/Components/Core/Group.lua:340>
[string "=(tail call)"]: ?
[string "@TellMeWhen/Components/Core/Icon.lua"]:561: in function `IsValid'
[string "@TellMeWhen/TellMeWhen.lua"]:3448: in function `DoValidityCheck'
[string "@TellMeWhen/TellMeWhen.lua"]:2744: in function `UpdateNormally'
[string "@TellMeWhen/TellMeWhen.lua"]:2874: in function `Update'
[string "@TellMeWhen/TellMeWhen.lua"]:3016: in function `LockToggle'
[string "@TellMeWhen/TellMeWhen.lua"]:3134: in function `?'
[string "@Ace3/AceConsole-3.0-7/AceConsole-3.0.lua"]:90: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5479: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5131: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:3308: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:3302>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseAction'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:342: in function `handler'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:667: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:649>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:681: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:674>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:723: in function `SecureActionButton_OnClick'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:1438: in function <Blizzard_ActionBar/Mainline/ActionButton.lua:1408>
[string "=[C]"]: ?

Locals:
group = TellMeWhen_Group20 {
 Strata = "MEDIUM"
 Point = <table> {
 }
 3 = TellMeWhen_Group20_Icon3 {
 }
 Scale = 2
 Rows = 1
 5 = TellMeWhen_Group20_Icon5 {
 }
 TextureName = ""
 7 = TellMeWhen_Group20_Icon7 {
 }
 8 = TellMeWhen_Group20_Icon8 {
 }
 10 = TellMeWhen_Group20_Icon10 {
 }
 12 = TellMeWhen_Group20_Icon12 {
 }
 14 = TellMeWhen_Group20_Icon14 {
 }
 resizeButton = Button {
 }
 TimerBar_EnableColors = false
 OnlyInCombat = false
 Columns = 20
 Locked = true
 20 = TellMeWhen_Group20_Icon20 {
 }
 Domain = "profile"
 SortPriorities = <table> {
 }
 19 = TellMeWhen_Group20_Icon19 {
 }
 EnabledProfiles = <table> {
 }
 18 = TellMeWhen_Group20_Icon18 {
 }
 SettingsPerView = <table> {
 }
 viewData = <table> {
 }
 Conditions = <table> {
 }
 Components = <table> {
 }
 17 = TellMeWhen_Group20_Icon17 {
 }
 16 = TellMeWhen_Group20_Icon16 {
 }
 15 = TellMeWhen_Group20_Icon15 {
 }
 TimerBar_MiddleColor = "ffffff00"
 13 = TellMeWhen_Group20_Icon13 {
 }
 6 = TellMeWhen_Group20_Icon6 {
 }
 ComponentsLookup = <table> {
 }
 TimerBar_CompleteColor = "ff00ff00"
 9 = TellMeWhen_Group20_Icon9 {
 }
 Modules = <table> {
 }
 Role = 7
 11 = TellMeWhen_Group20_Icon11 {
 }
 TimerBar_StartColor = "ffff0000"
 ID = 20
 Level = 10
 EnabledSpecs = <table> {
 }
 Controlled = false
 Enabled = true
 4 = TellMeWhen_Group20_Icon4 {
 }
 2 = TellMeWhen_Group20_Icon2 {
 }
 View = "icon"
 numIcons = 20
 BackdropColor_Enable = false
 Icons = <table> {
 }
 LayoutDirection = 1
 GUID = "TMW:group:1X44T0GigDiH"
 Name = "Spec Frost"
 ShrinkGroup = false
 1 = TellMeWhen_Group20_Icon1 {
 }
 __shown = true
 Alpha = 1
 BackdropColor = "7f333333"
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "script ran too long"
TMW = TMW {
 CovenantIcons = <table> {
 }
 modules = <table> {
 }
 DS = <table> {
 }
 db = <table> {
 }
 operators = <table> {
 }
 isNumber = <table> {
 }
 COMMON = <table> {
 }
 TEXT = <table> {
 }
 EquivFullIDLookup = <table> {
 }
 InitializedDatabase = true
 name = "TellMeWhen"
 Defaults = <table> {
 }
 C = <table> {
 }
 BackupDate = "10:46:09 PM"
 SNIPPETS = <table> {
 }
 OrderedTypes = <table> {
 }
 justifyVPoints = <table> {
 }
 Views = <table> {
 }
 CHANGELOG = "## v11.0.10
* Fix: #2228 - Cooldown bling appearing on groups with 0% opacity.
* Fix: #2230 - Raised max value of Maelstrom condition.
* Fix: #2231 - Some abilities not reflecting out-of-power state correctly.
* Fix: #2232 - Spell Queued condition not working on retail WoW.

## v11.0.9
* Fix various Lua errors.

## v11.0.8
* #1857 - Added LibCustomGlow animations.
* #2144 - Cooldowns and auras now accounts for time dilation. For example, timer freezes caused by talents, or boss mechanics like Jailer phase transitions or Chronomatic Anomaly fast/slow effects.
* #2214 - New condition: Spell Overridden. For all those pesky new Paladin talents with no way to figure out which spell is active.
* Fix: #2089 - Track swings with Crusading Strikes talent in swing timers
* Fix: #2125 - "script ran too long" when zoning into instances.
* Fix: #2191 - Icon Shown condition ignoring Shown/Hidden checkboxes for disabled icons/groups.
* Fix: #2193 - Icon overlay and border animations starting in the wrong state defaultModuleState = true
 CHANGELOG_LASTVER = "10.0.0"
 HELP = <table> {
 }
 UPD_INTV = 0.001000
 Locked = false
 NAMES = <table> {
 }
 justifyPoints = <table> {
 }
 EventList = <table> {
 }
 EVENTS = <table> {
 }
 EquivOriginalLookup = <table> {
 }
 CONST = <table> {
 }
 indentLib = <table> {
 }
 GroupsToUpdate = <table> {
 }
 GCDSpell = 53
 Classes = <table> {
 }
 isRetail = true
 Group_Defaults = <table> {
 }
 SpellTexturesMetaIndex = <table> {
 }
 Warned = true
 performedEvent = "TMW_UPGRADE_PERFORMED"
 UNITS = <table> {
 }
 isWrath = false
 profile = <table> {
 }
 DOGTAG = <table> {
 }
 IconStateArbitrator = <table> {
 }
 time = 56484.783000
 isCata = false
 baseName = "TellMeWhen"
 TIMERS = <table> {
 }
 Backupdb = <table> {
 }
 OrderedViews = <table> {
 }
 SUG = <table> {
 }
 strlowerCache = <table> {
 }
 DD = <table> {
 }
 DROPDOWNMENU = <table> {

**Is it an Ace problem or what do these errors mean?** 

### Export Strings

```text
"N/A"
```

**Comment by ascott18** [comment]
Unable to reproduce
