### ISSUE TITLE
Updated-ish CC groups

### ISSUE THREAD

**Issue by Jalopyy** [ascott18/TellMeWhen#3]
I can add spellIDs for all of these later if I get the time. Dunno if I'll get around to doing snares which the CCs I track on my healer, snares aren't relevant information to me.

For updating reference, I'd probably just filter what I listed here and cross check what you already have added with what I didn't list, and check if those specific spells still exist/still do what they used to when you first added them. IE Winter is Coming isn't a stun anymore, it's a root.

```
stuns

asphyxiate (108194; 221562)
axe toss (89766)
between the eyes (199804)
bull rush (255723)
chaos nova (179057)
cheap shot (1833)
demonic trample (205629)
double barrel (202346)
earthfury (204399)
earthquake (77505)
fel eruption (211881)
gnaw (91800)
hammer of justice (853)
holy word: chastise (200200)
Illidan's grasp (205630; 208618) <- first ID is the channel, second is the stun after you get tossed
infernal awakening (22703)
intimidation (24394)
kidney shot (408)
leg sweep (119381)
lightning lasso (204437)
maim (203123)
rake (163505)
mighty bash (5211)
Monstrous Blow (91797)
overrun (202244)
psychic horror (64044)
pulverize (118345)
shadowfury (30283)
shockwave (132168)
Static Charge (118905)
storm bolt (132169)
war stomp (20549)
warpath (199085)
```

```
fear/disorient 

blind (2094)
blinding light (105421)
blinding sleet (207167)
cyclone (33786)
dragon's breath (31661)
Fear (118699)
intimidating shout (5246)
mind bomb (205369)
psychic scream (8122)
seduction (6358)
sigil of misery (207685)
sin and punishment (87204)
song of chi-ji (198909)
```

```
incap/poly

freezing trap (3355; 203337)
hibernate (2637)
hex (51514; 211015; 211010; 211004; 210873; 196942; 269352; 277778; 277784)
holy word: chastise (200196)
imprison (217832; 221527)
incapacitating roar (99)
incendiary brew (202274)
mortal coil (6789)
paralysis (115078)
polymorph (61721; 61305; 28272; 28271; 126819; 161354; 161353; 61780; 161355; 161372; 277787; 277792; 118) 
quaking palm (107079)
repentence (20066)
ring of frost (82691)
sap (6770)
scatter shot (213691)
sundering (197214)
wyvern sting (19386)
```

```
silence

avenger's shield (31935)
garrote - silence (1330)
shield of virtue (217824)
sigil of silence (204490)
silence (15487)
solar beam (81261)
spider sting (202933)
strangulate (47476)
unstable affliction (31117) <- I haven't confirmed this, might have changed his this was the spellID
```

```
root

binding shot (109248) <- might be wrong? double check this. could be that or 117526
charge (105771)
deathchill (204085)
disable (116706)
earthgrab (64695)
Entangling Roots (339; 235963)
Entrenched in Flames (233582)
freeze (33395)
frostbite (198121)
frozen center (233395)
glacial spike (228600)
harpoon (190927)
ice nova (157997)
frost nova (122)
immobilized (45334)
ranger's net (200108)
mass entanglement (102359)
Shambling Rush (91807)
Steel Trap (162480)
thunderstruck (199042)
tracker's net (212638)
winter is coming (207171)
```

A new nice group to add might be a way to track interrupts all in a single 'group'. Not sure if that's beyond TMW's capability since it'd track combat events within itself, though.

**Comment by ascott18** [comment]
SpellIDs would be great - its a huge effort trying to correlate the names with the spellID since it has to be done spell-by-spell (and for 100% correctness, it has to be done in-game because the buff/debuff often doesn't have the same spellID as the spell that applies it)

**Comment by Jalopyy** [comment]
All updated. Pretty sure that's everything. I'd make a PR but...I don't know how to.

**Comment by Jalopyy** [comment]
fixed imprison's two versions both being poly DR

**Comment by Jalopyy** [comment]
Added UA backlash silence

**Comment by Jalopyy** [comment]
Added Sin and Punishment (VT dispel backlash).

Is there anything you needed me to do for this? I'd make a pull req, but I don't know how to.

**Comment by ascott18** [comment]
I just forgot about it. I'd love if you did make PR - check https://help.github.com/articles/editing-files-in-another-user-s-repository/ for the easiest way to go about it. 

https://github.com/ascott18/TellMeWhen/blob/master/Components/Core/Spells/Equivalencies.lua is the file where the data goes. The spellIDs in that file prefixed with a `-` are ones that should be checked by name rather than by ID. This should only be used for things like "Polymorph", "Hex", "Sap", etc. - buffs/debuffs that are going to always have the same kind of effect whenever a buff/debuff with that name is found. Generally, I'd advise that you not add any that check by name rather than by ID (i.e. don't prefix any of the IDs that you add with a `-`.

Try and keep all the indentation consistent as you see it now - all the IDs should be right-aligned with one another.

**Comment by Jalopyy** [comment]
I'll do this later tonight when I'm not busy then, and hopefully not fuck it up.

**Comment by Jalopyy** [comment]
Can I mix tabs and spaces to keep things aligned or is that gonna fuck things up?

**Comment by ascott18** [comment]
Yes, tabs for indentation, then spaces for alignment. Use the same number of tabs that each line already has.

**Comment by ascott18** [comment]
Closed in https://github.com/ascott18/TellMeWhen/pull/7/
